### ISSUE TITLE
Fix DockerHub deployment

### ISSUE THREAD

**Issue by DanNixon** [scipp/scipp#1005]
Conda seems to take a long time to resolve dependencies.

See https://github.com/scipp/scipp/commit/9a9c7eaa0639632cddd1c22f7a117b77ba57ebbd

**Comment by SimonHeybrock** [comment]
The question is whether we should continue providing a docker image at this point? Provided that we will fix the Mantid conda package, is there any relevant use case right now? People who are fine with running docker, but not conda?

**Comment by DanNixon** [comment]
The only case this really benefits is having a "ready to go" example with real neutron data. Also for meetings where network connectivity is limited.

I think most (if not all) other cases would be handled by Conda.

**Comment by DanNixon** [comment]
I actually think this highlights a more serious problem though, the reason this is failing is a dependency resolution issue that is causing Conda to fall back to the slow, almost brute force method, which is why the CI job is timing out.

I'd rather see why this is happening to try and address the package incompatibility rather than just throwing more CPU time at the solver.
