### ISSUE TITLE
conda package on Windows does not work

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1007]
Steps to reproduce:
- Install fresh Anaconda with Python3 as per instructions https://docs.anaconda.com/anaconda/install/windows/
- `conda create -n scipp -c conda-forge -c scipp/label/dev scipp`
- `import scipp` fails with `ImportError: DLL load failed: The specified module could not be found.` at https://github.com/scipp/scipp/blob/90f6eb1e96f81979151fe06222f67c2b91f0022e/python/src/scipp/__init__.py#L13.

Things we tried:
- It works for Piotr with an existing Anaconda install. We failed to determine the difference.
- Does not work with the release channel either.
- Does not work without `conda-forge` either(related issue: apparently without `conda-forge` and extremely old version of scipp is installed?).

**Comment by DanNixon** [comment]
> related issue: apparently without conda-forge and extremely old version of scipp is installed?

Yes, this is due to the addition of dependencies that are available via conda-forge. This is how the package solver is designed and it has in fact done exactly what it was asked, just that is not always what you want.

The only ways around this are either removing all our old packages so the resolution fails or pin the version of scipp you want so bad dependencies cause resolution to fail.

I'll at least update the docs since they don't actually mention the need for conda-forge.

**Comment by rozyczko** [comment]
Installed successfully on another Win10/64 machine.
`conda 4.7.12`
using `conda install -c scipp/label/dev scipp`
caveats:
- need to have `conda-forge` channel
- does not install `matplotlib` and `ipywidgets` automatically, I had to manually install them later

**Comment by SimonHeybrock** [comment]
@DanNixon Do you know which packages are only available on conda-forge?

**Comment by DanNixon** [comment]
> @DanNixon Do you know which packages are only available on conda-forge?

- appdirs
- python-configuration
- pyyaml
- tbb

**Comment by DanNixon** [comment]
>     * does not install `matplotlib` and `ipywidgets` automatically, I had to manually install them later

Also intended, I'll reflect this in the docs. This was done to avoid installing plotting specific dependencies in cases when you may not want to do any plotting, e.g. in HPC jobs.

**Comment by rozyczko** [comment]
>  in HPC jobs

Yes, but I should be at least able to `import scipp` then, without needing `matplotlib`, I guess?

**Comment by SimonHeybrock** [comment]
@nvaytet I thought this was fixed. Did it creep back in?

**Comment by DanNixon** [comment]
> > in HPC jobs
> 
> Yes, but I should be at least able to `import scipp` then, without needing `matplotlib`, I guess?

Yes, if you can't actually import scipp without plotting dependencies that is an issue. I thought this was taken care of now, could you provide a stack trace?

**Comment by rozyczko** [comment]
` scipp              scipp/label/dev/win-64::scipp-0.2-py37_889`

`
Python 3.7.6 | packaged by conda-forge | (default, Mar  5 2020, 14:47:50) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipp as sc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\envs\scipp2\lib\scipp\__init__.py", line 16, in <module>
    from . import neutron
  File "C:\Anaconda3\envs\scipp2\lib\scipp\neutron\__init__.py", line 10, in <module>
    from .instrument_view import instrument_view
  File "C:\Anaconda3\envs\scipp2\lib\scipp\neutron\instrument_view.py", line 10, in <module>
    from ..plot.tools import parse_params
  File "C:\Anaconda3\envs\scipp2\lib\scipp\plot\tools.py", line 10, in <module>
    from matplotlib.colors import Normalize, LogNorm, LinearSegmentedColormap
ModuleNotFoundError: No module named 'matplotlib'
>>>
`

**Comment by rozyczko** [comment]
`IPywidgets` dependence is now gone in build 889, I've seen it with earlier builds yesterday, when installing scipp without `conda-forge` channel specified.

**Comment by nvaytet** [comment]
ok I can see that `matplotlib` is still a dependency, i missed that one. I'm fixing in #1010

**Comment by rozyczko** [comment]
One of the VMs we have exhibits this behaviour.
It has conda with python 3.8 installed as local user (to c:\users\).

Identical setup on two other machines runs scipp successfully.

Compared:
- conda version: 4.8.2
- python version: 3.8.2
- %PATH% for relevant sections
- %PYTHONPATH%
- conda list: identical entries after running the same command:
  `conda create -n scipp -c conda-forge -c scipp python=3.8 scipp`

**Comment by rozyczko** [comment]
We now have access to Foreman for provisioning VMs on request so this might be useful for testing stubborn bugs like this.
Will create a Danish language clean VM and redo the test.

**Comment by rozyczko** [comment]
Found the issue. scipp is compiled/linked with VS2019 but the target machine has an old VC runtime installed (2017, ver. 14.14.26405).
After installing the most recent universal redistributable `14.26.28720`, the import succeeds.
Redist can be downloaded from https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by rozyczko** [comment]
We should probably either modify the conda recipe to include the VC redist or include a note in the installation docs.

**Comment by SimonHeybrock** [comment]
What would you recommend? Is the redist availabe on conda?

**Comment by rozyczko** [comment]
Added a note to the Installation section of the docs.

**Comment by SimonHeybrock** [comment]
Fixed (or rather: documented) in #1159.
