### ISSUE TITLE
Missing comparison operator in Mantid's Run and Sample

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1039]
See skipped test `compat/test_mantid.py::TestMantidConversion::test_comparison`.

**Comment by OwenArnold** [comment]
Mantid side of this issue fixed via https://github.com/mantidproject/mantid/pull/28466

**Comment by SimonHeybrock** [comment]
@OwenArnold I think you just have to reenable the test to be able to close this, since the Mantid issue has been fixed?

**Comment by OwenArnold** [comment]
@SimonHeybrock Indeed. Will do.
