### ISSUE TITLE
Convention-breaking pulse-time and other labels

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1042]
Mantid converters should use `'pulse-time'` and not `'pulse_times'`. The latter breaks two conventions (underscore instead of hyphen, plural where other labels are singular). The same issues exists for others such `source-position` and `sample-position`.

- Fix converters.
- Fix `neutron::convert` or rather the things in `neutron/beamline.cpp`
- Fix documentation, if applicable.
- Check if there are others I did not mention above.

**Comment by pptaszni** [comment]
Hi Simon, I would like to contribute to this project and I started looking for some "good first issues". That one doesn't look complicated, can you explain in which context exactly `pulse_times` violates the convention? I have seen it used only once as a dict key in `compat/mantid.py`

```
coords_labs_data["coords"]["pulse_times"] = labs
```

Otherwise, it is used as variable name or argument (e.g. `load_pulse_times=False`), which seems correct.

**Comment by SimonHeybrock** [comment]
Welcome Pawel, thanks for writing! Yes, this is just about the dict key in `mantid.py`. There may be some Jupyter notebook in `docs/` that uses it, but I am not sure.

As you say, the variable names should be kept.

**Comment by SimonHeybrock** [comment]
@pptaszni If you would really like to contribute, we can probably find a more interesting task, let me know if so, and what you would be particularly interested in.

**Comment by pptaszni** [comment]
Sure, sounds good. I usually prefer to write C++ code (Python is OK, but quite annoying with its dynamic typing). I might help to implement some new tool, algorithm, write some tests for existing code, analyze code architecture, look for some improvements. Depends what has high priority right now. For that mantid converter I first need to compile and install mantid itself :) Apart from this module, all c++ tests and all python tests (apart from skipped ones) seem to be passing, so my env is probably ready for development.

**Comment by SimonHeybrock** [comment]
@pptaszni We are just entering a cleanup and consolidation phase (see also #1047), so it is not clear what can be done independently right now. A good starting point, giving an glimpse of some of the internal mechanics of scipp may be some refactoring for improved unit tested we have started: See #964 for a good example. We have since done the same for other functions, but this is not complete yet. You should be able to find more uses of `transform` and `transform_in_place` which are just defining the lambdas inline, and could instead be moved to the `scipp::core::element` namespace for independent testing.

If you are looking for a challenge (and I don't know if there is a solution): We'd be interested in finding a way to reduce compile times for uses of `transform` and `transform_in_place`, e.g., as found in https://github.com/scipp/scipp/blob/master/core/variable_binary_arithmetic.cpp. It has to instantiate a lot a different cases (and that cannot really be changed), but it is not clear why compilation is taking quite so long. Splitting up `cpp` files even more than we already did can help, but it is just shifting the problem, rather than solving it.

I can give some more info after the Easter holidays.

Cheers,
Simon

**Comment by pptaszni** [comment]
Yes, it looks OK to start with, I see it also discussed in #513 . In e.g. `variable_operations.cpp` I see a lot of places for this kind of improvement. I will take a look.

**Comment by pptaszni** [comment]
I see that all appropriate operations are already moved to `element` namespace and there are no hardcoded lambdas. I needed to make some space on my PC for the additional libs anyway (had only small 100GB ssd). Maybe you want the `using namespace scipp` directives in tests to be changed to `using scipp::PARTICULAR_CLASS`? Or it will not pose any problems? For the long compilations times, it looks like the result of many template impls in the headers. There are some places where not all of the headers are necessary, but that I can confirm later, after tiding up my workspace a bit :) Let me know if there is  some unassigned work to do.

**Comment by SimonHeybrock** [comment]
> I see that all appropriate operations are already moved to element namespace and there are no hardcoded lambdas

There should still be many that are not. Examles can be found, e.g., in https://github.com/scipp/scipp/blob/split-variable-from-core/variable/variable_operations.cpp and https://github.com/scipp/scipp/blob/split-variable-from-core/variable/variable_binary_arithmetic.cpp. In some cases, lambdas are in fact defined outside the `transform` or `transform_in_place` call already, but not tested according to the pattern linked earlier. Note that I linked to branch `split-variable-from-core`, which splits one of our core modules into two pieces. It is likely to be merged tomorrow, and I would recommend doing any changes based on that, too avoid too many merge conflicts.

> Maybe you want the using namespace scipp directives in tests to be changed to using scipp::PARTICULAR_CLASS? Or it will not pose any problems?

`using namespace ...` in header would case problems and is avoided, in tests (which are just cpp files that are compiled individually there should be no issue.

> For the long compilations times, it looks like the result of many template impls in the headers.

In some cases probably (and there are small gains to be had), but I think it is mostly in `cpp` files where `transform` and `transform_in_place` is used.

**Comment by SimonHeybrock** [comment]
To be more concrete, you could for example try working on `reciprocal`, see https://github.com/scipp/scipp/blob/split-variable-from-core/variable/variable_operations.cpp#L128.

Before you start, you can look at the diff in https://github.com/scipp/scipp/pull/964, which was a similar refactor for `sqrt`, i.e., also a function with a single argument (note that this pull request we split `scipp-core` into `scipp-core` and `scipp-variable`, i.e., the involved files are now found in two different submodules). By now you can also find more similar examples if more guidance is needed.

The individual steps would be:
- Move functor to `scipp::core::element`.
- Add units tests for the functor in `scipp/core/test`.
- Use functor in `scipp:variable::reciprocal`.
- Cleanup tests of this in `scipp/variable/test`, avoiding retesting of things that are now tested for the functor. This may allow for removing some of the tests (with care).
