### ISSUE TITLE
On-the-fly histogramming for realigned data

### ISSUE THREAD

**Issue by nvaytet** [scipp/scipp#1065]
Currently, realigned data (event data as well as normal data) needs to be manually histogrammed manually before being sent to the plotting function.

Since realigned data contains all required coordinates, histogramming can happen automatically.

- Call `sc.histogram` inside `plot` if data is realigned. Something like `x = x if x.data is not None else sc.histogram(x)` should do.
- For plots that perform slicing, i.e., the slice viewer, ensure to call `sc.histgoram` *after* slicing, to avoid creation of huge multi-dimensional volumes that may be larger than the available memory.
- Histogramming should *not* be automatic for event data that is *not* realigned. No change here.

**Comment by SimonHeybrock** [comment]
@nvaytet I have included more details in de description, and moved to of the items you listed to #1070 since they are not a priority and not needed in 0.4.
