### ISSUE TITLE
import scipp fails on Linux clang builds with undefined symbol

### ISSUE THREAD

**Issue by DavidFair** [scipp/scipp#1083]
Was running into this locally, since I by default build with clang and switch to GCC on failure. We don't get errors from `ld` even with LTO on it can be a bit misleading to diagnose.

To reproduce:

- Build with clang (10 used here)
- `DDYNAMIC_LIB=ON` must be passed to CMake, else you will get a segmentation fault instead of DLLOpen reporting the missing symbol
- Install and attempt to `import scipp`

This results in the following error:
 `../lib/libscipp-core.so: undefined symbol: _ZNK5scipp5units9Unit_implINS0_7neutron4UnitEE14isCountDensityEv`

Which the de-mangler points to
`scipp::units::Unit_impl<scipp::units::neutron::Unit>::isCountDensity() const`

**Comment by SimonHeybrock** [comment]
I think I fixed this with recent work on using dynamic linking by default.
