### ISSUE TITLE
cross product

### ISSUE THREAD

**Issue by OwenArnold** [scipp/scipp#1101]
scipp has `dot` product but no `cross`. See not too problematic workaround [here](https://github.com/scipp/scipp/blob/master/python/src/scipp/compat/mantid.py#L212) for example.

Maybe this is tied to a larger question of linear algebra support in scipp. It's a big orthogonal direction for scipp at present, so maybe best avoided for now?

**Comment by SimonHeybrock** [comment]
I agree. We should (not now) look into removing the `Eigen` things and just implement this based on "internal" dimensions.

**Comment by SimonHeybrock** [comment]
Implement `cross` if required (should be simple), closing issue since there seems to be nothing to discuss specifically to this (apart from the wider `Eigen` discussion).
