### ISSUE TITLE
Binary arithmetic between float and int types

### ISSUE THREAD

**Issue by DavidFair** [scipp/scipp#1114]
Here is a trivial case which should "just work" from a user perspective. 

```
foo = sc.Dataset()
foo.coords[Dim.Tof] = sc.Variable([Dim.Tof],
                   values=np.arange(1, 10, 1, dtype=np.float64))

foo.coords[Dim.Tof] += 5
```

Instead we get the following message:
`Cannot apply operation to item dtypes float64 int32 `
(Note this message should be improved to say something like `between a float64 and int32`, `dtype` is a C++ idiom)

In my opinion this is an API bug for the following reasons:
- We are adding to a int to a float so precision can't be lost (the same isn't true to other way)
- Python supports this operation normally
- It violates principle of least astonishment 

I can see users starting to take the path of least resistance leading to casts like this before every operation out of habit:
`foo.coord[Dim.Tof] += float(5)` 

In `transform.h` and `apply.h` we should use something like
```
if constexpr (!std::is_same_v(a, b)){
    if constexpr (!std::is_convertible<a, b>::value || std::is_floating_point<a>::value){
         throw ...;
    }
    // Trivially convert b -> a then use b for the rest
    decltype(a) b_converted(a);
```

This allows us to convert `int` -> `float` but prevents us losing precision if we try to convert a `float` -> `any`

**Comment by SimonHeybrock** [comment]
> Here is a trivial case which should "just work" from a user perspective.
> 
> ```
> foo = sc.Dataset()
> foo.coords[Dim.Tof] = sc.Variable([Dim.Tof],
>                    values=np.arange(1, 10, 1, dtype=np.float64))
> 
> foo.coords[Dim.Tof] += 5
> ```
> 
> Instead we get the following message:
> `Cannot apply operation to item dtypes float64 int32 `
> (Note this message should be improved to say something like `between a float64 and int32`, `dtype` is a C++ idiom)

I am using `dtype` since this is a `numpy` ideom, C++ would by `type`?

> In my opinion this is an API bug for the following reasons:
> 
>     * We are adding to a int to a float so precision can't be lost (the same isn't true to other way)
> 
>     * Python supports this operation normally
> 
>     * It violates principle of least astonishment
> 
> 
> I can see users starting to take the path of least resistance leading to casts like this before every operation out of habit:
> `foo.coord[Dim.Tof] += float(5)`
> 
> In `transform.h` and `apply.h` we should use something like
> 
> ```
> if constexpr (!std::is_same_v(a, b)){
>     if constexpr (!std::is_convertible<a, b>::value || std::is_floating_point<a>::value){
>          throw ...;
>     }
>     // Trivially convert b -> a then use b for the rest
>     decltype(a) b_converted(a);
> ```
> 
> This allows us to convert `int` -> `float` but prevents us losing precision if we try to convert a `float` -> `any`

I don't think enabling conversion globally in `transform` is a good approach, since this would affect *all* operations. I do agree however that this case should probably be added then *calling* transform for arithmetic operations such as `+=`. We do however have to have a discussion about which conversions exactly we want to allow.
