### ISSUE TITLE
Missing free functions

### ISSUE THREAD

**Issue by nvaytet** [scipp/scipp#1132]
A list of functions that are still missing.
The list was compiled from looking at the python bindings. I have not checked whether the function is implemented in C++ and the binding in missing, or that the function is simply missing altogether.

The functions marked with a `?` are a possible suggestions/additions.

**Comparison:**

- [ ] `less(Variable x, VariableView out)`
- [ ] `less(DataArray x)`, `less(DataArray x, DataArrayView out)`
- [ ] `less(Dataset x)`, `less(Dataset x, DatasetView out)`
---
- [ ] `greater(Variable x, VariableView out)`
- [ ] `greater(DataArray x)`, `greater(DataArray x, DataArrayView out)`
- [ ] `greater(Dataset x)`, `greater(Dataset x, DatasetView out)`
---
- [ ] `less_equal(Variable x, VariableView out)`
- [ ] `less_equal(DataArray x)`, `less_equal(DataArray x, DataArrayView out)`
- [ ] `less_equal(Dataset x)`, `less_equal(Dataset x, DatasetView out)`
---
- [ ] `greater_equal(Variable x, VariableView out)`
- [ ] `greater_equal(DataArray x)`, `greater_equal(DataArray x, DataArrayView out)`
- [ ] `greater_equal(Dataset x)`, `greater_equal(Dataset x, DatasetView out)`
---
- [ ] `equal(Variable x, VariableView out)`
- [ ] `equal(DataArray x)`, `equal(DataArray x, DataArrayView out)`
- [ ] `equal(Dataset x)`, `equal(Dataset x, DatasetView out)`
---
- [ ] `not_equal(Variable x, VariableView out)`
- [ ] `not_equal(DataArray x)`, `not_equal(DataArray x, DataArrayView out)`
- [ ] `not_equal(Dataset x)`, `not_equal(Dataset x, DatasetView out)`
---
**Reduction:**
- [ ] `mean(DataArray x, Dim dim, DataArrayView out)`
- [ ] `mean(Dataset x, Dim dim, DatasetView out)`
- [ ] `mean(Variable x)`, `mean(Variable x, VariableView out)`
- [ ] `mean(DataArray x)`, `mean(DataArray x, DataArrayView out)`
- [ ] `mean(Dataset x)`, `mean(Dataset x, DatasetView out)`
---
- [ ] `sum(DataArray x, Dim dim, DataArrayView out)`
- [ ] `sum(Dataset x, Dim dim, DatasetView out)`
- [ ] `sum(Variable x)`, `sum(Variable x, VariableView out)`
- [ ] `sum(DataArray x)`, `sum(DataArray x, DataArrayView out)`
- [ ] `sum(Dataset x)`, `sum(Dataset x, DatasetView out)`
---
- [ ] `min(Variable x, Dim dim, VariableView out)`, `min(Variable x, VariableView out)`
- [ ] `min(DataArray x, Dim dim)`, `min(DataArray x)`
- [ ] `min(DataArray x, Dim dim, DataArrayView out)`, `min(DataArray x, DataArrayView out)`
- [ ] `min(Dataset x, Dim dim)`, `min(Dataset x)`
- [ ] `min(Dataset x, Dim dim, DatasetView out)`, `min(Dataset x, DatasetView out)`
---
- [ ] `max(Variable x, Dim dim, VariableView out)`, `max(Variable x, VariableView out)`
- [ ] `max(DataArray x, Dim dim)`, `max(DataArray x)`
- [ ] `max(DataArray x, Dim dim, DataArrayView out)`, `max(DataArray x, DataArrayView out)`
- [ ] `max(Dataset x, Dim dim)`, `max(Dataset x)`
- [ ] `max(Dataset x, Dim dim, DatasetView out)`, `max(Dataset x, DatasetView out)`
---
- [ ] `all(Variable x, Dim dim, VariableView out)`, `all(Variable x, VariableView out)`
- [ ] `all(DataArray x, Dim dim)`, `all(DataArray x)`
- [ ] `all(DataArray x, Dim dim, DataArrayView out)`, `all(DataArray x, DataArrayView out)`
- [ ] `all(Dataset x, Dim dim)`, `all(Dataset x)`
- [ ] `all(Dataset x, Dim dim, DatasetView out)`, `all(Dataset x, DatasetView out)`
---
- [ ] `any(Variable x, Dim dim, VariableView out)`, `any(Variable x, VariableView out)`
- [ ] `any(DataArray x, Dim dim)`, `any(DataArray x)`
- [ ] `any(DataArray x, Dim dim, DataArrayView out)`, `any(DataArray x, DataArrayView out)`
- [ ] `any(Dataset x, Dim dim)`, `any(Dataset x)`
- [ ] `any(Dataset x, Dim dim, DatasetView out)`, `any(Dataset x, DatasetView out)`
---
**Trigonometry:**
- [ ] `sin(DataArray x)`, `sin(DataArray x, DataArrayView out)`
- [ ] `sin(Dataset x)`, `sin(Dataset x, DatasetView out)`
---
- [ ] `asin(DataArray x)`, `asin(DataArray x, DataArrayView out)`
- [ ] `asin(Dataset x)`, `asin(Dataset x, DatasetView out)`
---
- [ ] `cos(DataArray x)`, `cos(DataArray x, DataArrayView out)`
- [ ] `cos(Dataset x)`, `cos(Dataset x, DatasetView out)`
---
- [ ] `acos(DataArray x)`, `acos(DataArray x, DataArrayView out)`
- [ ] `acos(Dataset x)`, `acos(Dataset x, DatasetView out)`
---
- [ ] `tan(DataArray x)`, `tan(DataArray x, DataArrayView out)`
- [ ] `tan(Dataset x)`, `tan(Dataset x, DatasetView out)`
---
- [ ] `atan(DataArray x)`, `atan(DataArray x, DataArrayView out)`
- [ ] `atan(Dataset x)`, `atan(Dataset x, DatasetView out)`
---
- [ ] `atan2(DataArray x)`, `atan2(DataArray x, DataArrayView out)`
- [ ] `atan2(Dataset x)`, `atan2(Dataset x, DatasetView out)`
---
**Operations:**

(Maybe `flatten` and `concatenate` should be moved to reduction?)

- [ ] `flatten(Variable x, Dim dim, VariableView out)`
- [ ] `flatten(DataArray x, Dim dim, DataArrayView out)`
- [ ] `flatten(Dataset x, Dim dim, DatasetView out)`
- [ ] `flatten(Variable x)` ?
- [ ] `flatten(DataArray x)` ?
- [ ] `flatten(Dataset x)` ?
- [ ] `flatten(Variable x, VariableView out)` ?
- [ ] `flatten(DataArray x, DataArrayView out)` ?
- [ ] `flatten(Dataset x, DatasetView out)` ?
---
- [ ] `concatenate(Variable x, Dim dim, VariableView out)`
- [ ] `concatenate(DataArray x, Dim dim, DataArrayView out)`
- [ ] `concatenate(Dataset x, Dim dim, DatasetView out)`
- [ ] `concatenate(Variable x)` ?
- [ ] `concatenate(DataArray x)` ?
- [ ] `concatenate(Dataset x)` ?
- [ ] `concatenate(Variable x, VariableView out)` ?
- [ ] `concatenate(DataArray x, DataArrayView out)` ?
- [ ] `concatenate(Dataset x, DatasetView out)` ?
---
- [ ] `dot(Variable x, Variable y, VariableView out)`
- [ ] `dot(DataArray x, DataArray y)`, `dot(DataArray x, DataArray y, DataArrayView out)`
- [ ] `dot(Dataset x, Dataset y)`, `dot(Dataset x, Dataset y, DatasetView out)`
---
- [ ] `sort(Variable x, Variable key, VariableView out)`
- [ ] `sort(DataArray x, Variable key, DataArrayView out)`
- [ ] `sort(Dataset x, Variable key, DatasetView out)`
- [ ] `sort(DataArray x, Dim dim, DataArrayView out)`
- [ ] `sort(Dataset x, Dim dim, DatasetView out)`
---
- [ ] `contains_events(Dataset x)` ?
---
**Unary:**
- [ ] `abs(DataArray x)`, `abs(DataArray x, DataArrayView out)`
- [ ] `abs(Dataset x)`, `abs(Dataset x, DatasetView out)`
---
- [ ] `sqrt(DataArray x)`, `sqrt(DataArray x, DataArrayView out)`
- [ ] `sqrt(Dataset x)`, `sqrt(Dataset x, DatasetView out)`
---
- [ ] `norm(Variable x, VariableView out)`
- [ ] `norm(DataArray x)`, `norm(DataArray x, DataArrayView out)`
- [ ] `norm(Dataset x)`, `norm(Dataset x, DatasetView out)`
---
- [ ] `reciprocal(DataArray x, DataArrayView out)`
- [ ] `reciprocal(Dataset x)`
- [ ] `reciprocal(Dataset x, DatasetView out)`
---
- [ ] `nan_to_num(DataArray x)`, `nan_to_num(DataArray x, DataArrayView out)`
- [ ] `nan_to_num(Dataset x)`, `nan_to_num(Dataset x, DatasetView out)`
---
**Geometry:**
- [ ] `geometry.x(Variable pos, VariableView out)`
- [ ] `geometry.x(DataArray pos)`, `geometry.x(DataArray pos, DataArrayView out)`
- [ ] `geometry.x(Dataset pos)`, `geometry.x(Dataset pos, DatasetView out)`
---
- [ ] `geometry.y(Variable pos, VariableView out)`
- [ ] `geometry.y(DataArray pos)`, `geometry.y(DataArray pos, DataArrayView out)`
- [ ] `geometry.y(Dataset pos)`, `geometry.y(Dataset pos, DatasetView out)`
---
- [ ] `geometry.z(Variable pos, VariableView out)`
- [ ] `geometry.z(DataArray pos)`, `geometry.z(DataArray pos, DataArrayView out)`
- [ ] `geometry.z(Dataset pos)`, `geometry.z(Dataset pos, DatasetView out)`
---
Not sure if these below make sense?

- [ ] `geometry.position(Variable x, Variable y, Variable z, VariableView out)`
- [ ] `geometry.position(DataArray x, DataArray y, DataArray z)`
- [ ] `geometry.position(DataArray x, DataArray y, DataArray z, DataArrayView out)`
- [ ] `geometry.position(Dataset x, Dataset y, Dataset z)`
- [ ] `geometry.position(Dataset x, Dataset y, Dataset z, DatasetView out)`
---
- [ ] `geometry.rotate(DataArray pos, Variable rot)`
- [ ] `geometry.rotate(DataArray pos, Variable rot, DataArrayView out)`
- [ ] `geometry.rotate(Dataset pos, Variable rot)`
- [ ] `geometry.rotate(Dataset pos, Variable rot, DatasetView out)`

**Comment by SimonHeybrock** [comment]
Replaced by #1221, omitting existing and unnecessary operations.
