### ISSUE TITLE
Value-based indexing and slicing

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1133]
See also http://xarray.pydata.org/en/stable/indexing.html, in particular `sel`.

In contrast to xarray, scipp has units (and most coordinates do), so value-based indexing should include the unit.

- Use scalar variables to provide value, e.g., `1.5 * sc.units.m`.
- Performance from using variable for this should not be an issue, since finding value is slow anyway.
- How should bin-edge coords be handled? Return bins that contain the value? Maybe this case is actually simpler than the non-edge case, where a decision has to be made on what is included.
- What should the syntax be?
  - `xarray` uses `sel` and `loc`, but I consider those hard to remember. Is there a better name?
  - How should arguments be passed?
  - For single slice? `data.slice('tof', 1.5*sc.units.us)`?
  - For range? `data.slice('tof', 1.5*sc.units.us, 12.3*sc.units.us)`?

**Comment by OwenArnold** [comment]
- Yes I prefer `slice` to `sel` and `loc`. What you suggest for the syntax looks good for the point slice and range.
- Yes I would return whole bin containing value
- Would we ever have a case where specifying a value range would not yield a single coord slice?

**Comment by SimonHeybrock** [comment]
> Would we ever have a case where specifying a value range would not yield a single coord slice?

I think there can be many issues, such as constant coords, coords with the same value in multiple places, coords in decreasing order, ...

**Comment by OwenArnold** [comment]
I think the naive value slicing approach maybe doesn't matter? We just return anything that sits in the interval range.

**Comment by SimonHeybrock** [comment]
> I think the naive value slicing approach maybe doesn't matter? We just return anything that sits in the interval range.

Except that there may be no such an interval (there may be multiple), or the interval may be empty if the range is decreasing, unless start and end are also specified in reverse order.

**Comment by OwenArnold** [comment]
One option for an initial implementation is to use `is_linspaced` we may want this as an optimisation anyway (throw not implemented otherwise). Other than that we could maybe list out the possibilities and what we think should be done under all cases.

**Comment by SimonHeybrock** [comment]
linspace is too restrictive, but supporting only monotonically increasing coords would be a good start.

**Comment by SimonHeybrock** [comment]
Note that for performance reasons xarray creates hash-tables of indices, which are *stored in the data array / dataset*. We will have to consider this carefully.

**Comment by SimonHeybrock** [comment]
Note https://github.com/scipp/scipp/blob/15abba378035ea45956ee6e677d05a62a449124c/dataset/groupby.cpp#L426-L434, which is doing this in a crude way.

**Comment by OwenArnold** [comment]
> Note
> 
> https://github.com/scipp/scipp/blob/15abba378035ea45956ee6e677d05a62a449124c/dataset/groupby.cpp#L426-L434
> 
> , which is doing this in a crude way.

Yes I did notice that when I reviewed it. What do you consider crude about it, isn't this exactly the way it would need to be done?

**Comment by SimonHeybrock** [comment]
> Yes I did notice that when I reviewed it. What do you consider crude about it, isn't this exactly the way it would need to be done?

- Handling of duplicate values.
- Handling of bin edges (even if it would just fail for now).
- Handling of ranges (both with and without bin edges), even if for now just fail.
- Maybe faster way to do the find by not comparing variable every time (but this may be an improvement for the future).

**Comment by OwenArnold** [comment]
for the first point, I would have thought we just do something with `adjacent_find` or similar. Yes I hadn't considered your second and third points.

**Comment by SimonHeybrock** [comment]
`std::adjecent_find`works only for ordered coords, but coords values may appear in any order, so we need to do something like "find, continue searching, throw if second match, else return first".

**Comment by SimonHeybrock** [comment]
Also note another way of implementing this is based on array comparisons:
```python
def select_bins(array, dim, start, end):
    coord = array.coords[dim]
    bins = coord.shape[0]
    # scipp treats bins as closed on left and open on right: [left, right)
    first = sc.sum(sc.less_equal(coord, start), dim).value - 1
    last = bins - sc.sum(sc.greater(coord, end), dim).value
    assert first >= 0
    assert last < bins
    return array[dim, first:last+1]
```
Can be translated to C++.
