### ISSUE TITLE
Missing reverse division with scalar (__rtruediv__)

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1141]
This is a missing Python binding.

- We can do `1.0 * variable`.
- `1.0 / variable` does not work
- Other operators are implemented here https://github.com/scipp/scipp/blob/79804c9033bd0470904df6a40c5c5eba84ccb04b/python/variable.cpp#L184-L193.

I suppose we just need to add `__rtruediv__`?

**Comment by rozyczko** [comment]
Indeed `__rtruediv__` seems to the be right overload since `Variable` is not a subclass of `float` and `__rtruediv__` overload will get priority here (`__truediv__` will return error)
