### ISSUE TITLE
Coordinates, slicing, and binary operations

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1155]
## 1 Status quo

In the past months we have repeatedly come across issues with handling coordinates and attributes.  Examples include:

- We wanted to support things such as normalization to monitors after unit conversion to wavelength.  To solve this we adapted `neutron.convert` to switch position-related coords to attrs when converting away from time-of-flight.  This created some follow-up issues:
  - Issues with "intermediate" units such as `wavelength`, where positions may still be required for conversion to `Q`.  With the position-related coords stored as attributes these may not be found when required.
  - Confusion for users.  Several cases where copying attributes back to coords, or removing coords was required have been observed in the wild.
  - Duplication of attributes for datasets.
  - Can create datasets in `wavelength` with positions stored as attributes, which are then impossible to convert to `tof`, since positions may mismatch.
  - Overall brittle mechanism.
- Unit conversion of a single "spectrum" extracted by slicing such as `data['spectrum', 17]` is not possible, because scipp drops the coords that depend on the sliced dimension.  This can be bypassed with a range slice such as `data['spectrum', 17:18]`, but this is inconvenient and user unfriendly, increasing teaching/documentation needs.
- Masks get lost when slicing without range.
- Valuable information is just discarded during slicing.

These issues boil down to the handling of coordinates in slicing operations, and handling of coordinates in operations with 2 or more operands.  Before reading on, make sure to study the [xarray terminology](https://xarray.pydata.org/en/stable/terminology.html) and [how their computation handles coordinates](http://xarray.pydata.org/en/stable/computation.html#coordinates).  Scipp has adopted the same terminology.

However, scipp takes a different approach in operations: **All coords are compared, not just dimension-coords.**

The **original reasoning** for this was as follows:
1. Coords are important and should be compared, if not then use attributes.
2. We need to support things such as `data -= data['x', 0]`, therefore we need to drop coord depending on `'x'`.
3. If coords should be preserved, use a range-slice `data -= data['x', 0:1]`.
4. Requirement to have bin-edges: `histogram['x', 0]` does not depend on `'x'`, so we cannot preserve the edge coord in non-range slice (which would still have two edges in it).

Please go through the issues listed on to and consider how they relate to some of these items.

With the number of issues seen *in practice* (these are not edge cases, there typically appear to be *multiple* points in even a simple data-reduction script where we have to work around this) we have to take a step back and reconsider the mechanism.

## 2 xarray's mechanism

First, let us look in detail at xarray's mechanism.  Consider data arrays with a non-dimension coordinate:

```python
import numpy as np
import xarray as xrdata = np.random.rand(4)
a = xr.DataArray(data, coords=[np.arange(4)], dims=['x'])
b = xr.DataArray(data, coords=[np.arange(4)], dims=['x'])
a.coords['aux'] = a.coords['x']
b.coords['aux'] = b.coords['x'] + 3
print(a)
print(b)
```

The `aux` coord is incompatible.  Therefore, a binary operation *drops* the coord:

```python
print(a-b)
```

This operation *would fail with scipp*.  An in-place operations *preserves* the coord:

```python
a-=b 
print(a)
```

Adding the arrays to a dataset behaves in the same way, *ignoring* non-dimension coords of arrays added after first:

```python
d = xr.Dataset()
d['a'] = a
d['b'] = b
print(d)
```

This makes `d` *depend on the insertion order*.

Based on these, we can also look at the behavior in relation to slicing:

```python
a[0] - a[1] # works because `x` coord is non-dimension coord after slicing
a -= a[1] # `x` of slice ignored as above
```

The results after the subtraction are the *same as with scipp*.  Scipp's mechanism achieves the same effect by different means.

So where do the differences show up?  From the perspective of what we are used to with scipp the behavior in binary arithmetic and dataset creation appears like a substantial downside and source of bugs in scripts using the library.  Paradoxically, scipp's approach of having the additional safety need of enforcing compatible non-dimension coords, e.g., in binary arithmetic operations, *reduces* safety in other cases, by dropping information *earlier* than necessary, in a slicing operation.  In the case of dropped masking information this is not just reduced safety but an actual correctness problem (which could be fixed by special handling of masks in slicing, with the downside of more special case handling).

### 3.1 xarray's approach

xarray's approach appears to handle non-dimension coordinates mostly like scipp handles attributes.  There is a natural transition between coordinates and non-dimension coordinates by means of slicing or concatenation operations, but there is not for coordinates and attributes (see manual switching to attrs in unit conversion above).

1. Switching to xarray's concept of slicing and handling of non-dimension coordinates appears to solve all the issues listed at the beginning of this discussion.
2. New down-sides are introduced, in particular less safety:
   1. Binary arithmetic drop *not-matching* non-dimension coords. This is ok, because the mismatch is obvious from the lack of the coord in the output.
   2. In-place  binary arithmetic ignores non-dimension coord of right-hand side. This has some risk for bugs, but is often the desired behavior (in the majority of cases?).
   3. Insertion into dataset uses non-dimension coords of arrays inserted first, silently ignoring those of others. This appears like a significant bug source since the outcome will depend on the insertion order and inserting (`d['b'] = b`) and extracting (`b_with_different_aux = d['b']`) an from a dataset will magically override its non-dimension coords.
3. Need to understand how to handle bin-edges in non-range slices.

### 3.2 Our options

1. Stick with our mechanism.  Solution to issues listed on top would be required.  So far I have *failed* to come up with anything reasonable.
2. Switch to xarray's mechanism.
3. Switch to xarray's mechanism with some tweaks, such as ignoring non-dimension coords in operations, but *not* in dataset insertion.
4. Find a completely new mechanism.  A new mechanism might be something that realises that there are *three* as opposed to *two* cases, (a) dimension coords, (b) scipp-style non-dimension coords (compared in operations), and (c) xarray-style non-dimension coords (not compared in operations).  (c) is essentially what attributes are in scipp.  The riddle to solve is whether this can be modified in some way so there are *natural* transitions between the cases, such as the transition between dimension coord and non-dimension coord when slicing, but supporting the additional transition required for the third case.  So far I have *failed* to come up with anything reasonable.
   
### 3.3 Discussion

I am beginning to see 3.2.2 or 3.2.3 as the only options, since the issues with 3.2.1 do not seem to disappear or reduce.

One more argument for this approach is: Slicing should make sense on its own (preserving all coords).  What we have done is *compromise* the slicing concept to fulfil a *requirement of something else* (being able to do binary arithmetic with slices).

To move forward, we need to take a closer look at the items in 3.1:

1. Ensure this is really solving the current issues.
2. Try if 3.1.3 works, by keeping coord with extent two (containing left and right edge), but having data without this dimension.  The coord would then not be a dimension coord (its name matches its dimension, but not the dimension of the data).
3. Analyse concrete cases where 3.1.2.2 is relevant.  How many cases with risk for bugs are there (and how severe are they?), contrasted with how many cases that require workarounds in the implementation?
4. Figure out which way to go with 3.1.2.3.

Please discuss!

**Comment by nvaytet** [comment]
This really feels like we should get in the same room and talk about this on a white board.... Maybe we can try that online white board thing?
I think that having the order of insertion matter is strange, so achieving something like 3.2.3 might work.

Could you clarify a little (maybe with an example) what you mean by
> Slicing should make sense on its own (preserving all coords). What we have done is compromise the slicing concept to fulfil a requirement of something else (being able to do binary arithmetic with slices).

Are you refering to the case where we drop the `x` coord when we do `a['x', 0]`?

**Comment by SimonHeybrock** [comment]
> Could you clarify a little (maybe with an example) what you mean by
> 
> > Slicing should make sense on its own (preserving all coords). What we have done is compromise the slicing concept to fulfil a requirement of something else (being able to do binary arithmetic with slices).
> 
> Are you refering to the case where we drop the `x` coord when we do `a['x', 0]`?

Yes. 0D coords are preserved, but the 1D coord disappears. If you consider a monitor as a 1D data array, it would usually have 0D position coord. But if a spectrum (or a monitor) is extracted as a slice from a 2D data array the position coord would not be there!

**Comment by SimonHeybrock** [comment]
During discussion with @OwenArnold and @nvaytet more issues with the curret solution were ucovered. Consider neutron data reduction with normalization to monitor (to be done in wavelength), and a background subtraction:

```python
# convert switches positions to attributes, so normalization is not prevented
data = sc.neutron.convert(data, 'tof', 'wavelength') # dims = ('spectrum', 'tof')
back = sc.neutron.convert(back, 'tof', 'wavelength') # dims = ('spectrum', 'tof')
```

### Problem 1: Monitor normalization

Problem: normalized does not contain positions, since mismatching attributes are dropped

```python
normalized = data / monitor # works, but cannot convert again, e.g., back to TOF
```
Current solution: Normalize in place

```python
data /= monitor
```

This has 2 downsides:

- Extra documentation and training "need to use in-place operations", confusion since the solution is not obvious and not "searchable" (the conversion operation will fail, but the issue lies elsewhere, when the arithmetic operation is applied).
- Harder for developing workflows, where we want to avoid in-place ops

### Problem 2: Preventing bad operation

If unit conversion changes coords to attrs, they will not be checked. The following will work:

```python
data -= back
```

The problem here is that `back` may have different detector positions, so we would like the subtraction in wavelength to be prevented (should, e.g., subtract in `Q`, when positions are not relevant any more).

The xarray-style approach would keep positions as a coord, and, provided that position is a dimension of `data` and `back`, would fail the operation because of a mismatching dimension coord. Note that this is still not 100% fool proof since, e.g., a mismatching source-position (which is typically not an explicit dimension) would not be caught.

**Comment by SimonHeybrock** [comment]
Note thatxarrays approach leads to problematic outcomes for multiple additions:
<img width="586" alt="image" src="https://user-images.githubusercontent.com/12912489/83617140-f3a47c80-a588-11ea-85c2-524c07461e1f.png">

**Comment by SimonHeybrock** [comment]
Inspired by https://github.com/pydata/xarray/issues/1603, but taking a different approach/solution, I propose the following (incomplete) solution:

Summary:
- Combine the concepts of coord and attrs into "aligned coords" and "unaligned coords".
- Slicing converts aligned coord to unaligned coord (similar to xarray transition from dim coord to non-dim coord), if dim associated with coord is sliced.
- Explicit control over which coords are aligned and which are not. "Dimension coords" are aligned by default.
- Aligned coords are preserved in binary operations (fail on mismatch).
- Unaligned coords are preserved if they match (missing unaligned coord in one op counts as mismatch to ensure that `a + (b + c) == (a + b) + c`).
- Dataset aligns only aligned coords, unaligned coords are stored in items (just like item attrs now).

Open questions:
- Do we need aligned and unaligned masks?
- How exactly do we handle point-slice of histogram? Would require 2 bin edges but data does not have the dimension.

Concrete solutions:
- Issues with unit conversions should be solved. Only change required is to switch position to "unaligned" when converting to wavelength with `scatter=False`, or when converting to Q or d-spacing (`scatter=True`)?

**Comment by nvaytet** [comment]
Some more on masks: I definitely feel that dropped masks when slicing is counter-intuitive.
e.g.
![Screenshot_2020-06-11_15-11-08](https://user-images.githubusercontent.com/39047984/84389518-6f8c6d80-abf6-11ea-9e51-998477aeaac5.png)

**Comment by SimonHeybrock** [comment]
I think this is something that #1186 does not address yet, but I fully agree!

**Comment by nvaytet** [comment]
Yes, i added this comment while I was playing with #1186 (as you can see, the screenshot was actually made using that branch)

**Comment by SimonHeybrock** [comment]
Here is a case that works neither now nor with the proposed new mechanism:

```python
# compare straws in tubes 0 and 1
straw_ratio = data['layer', 0:7] / data['layer', 7:14]
```
Instead we have to:
```python
tmp = data.copy()
del tmp.coords['layer']
straw_ratio = tmp['layer', 0:7] / tmp['layer', 7:14]
```
This is maybe just an indication that the original dimensions could be chosen better, or that we should use reshape:

```python
tmp = sc.reshape(data, dims=['tube', 'straw'], shape=[4, 7])
straw_ratio = tmp['tube', 0] / tmp['tube', 1]
```
Note that `reshape` for `DataArray` does not exist yet, and would need to be implemented in a way to map aligned coords that are reshaped (`layer` in this case) to an unaligned coord.

**Comment by SimonHeybrock** [comment]
Intermediate results and notes from long discussion with @nvaytet. This also realted to #1211:

```python
data.coords['x'] = x # dimension-coord => align by default
data.coords['xx'] = x # non-dimension-coord => unaligned by default
# No! Align by default, as for dataset. This is in-line with current way of how
# scipp coords work, i.e., all coords are compared by default
ds.align('x') # make unaligned items coord aligned coord of ds, fail on mismatch
ds.unalign('x') # make x coord unaligned coord of all items
data.coords['x'] = sc.unaligned(x) # Variable -> UnalignedCoord

# Natural default for dataset
ds.coords['xx'] = x # dataset cannot have unaligned, aligned by default (conflicts above)
ds['a'].coords['xx'] = x # unaligned because set via item

# What is difference between attributes and non-dimension coords?
# - Attrs behave just like Python dict, i.e., could be dataset or data array or string,
#   (not variable of dataset/data-array/string)


# realigned data vs aligned/unaligned coords?
# realign             unaligned
# x                   x(position) # shadowing, data.unaligned.coords['x']
# y                   y(position) # shadowing
# tof                 tof
# dims=[y,x,tof]      [position,tof]
# Connection between existing realign concept and new concept of aligned/unaligned coords?
a = sc.realign(data, {'x':x_bins_a})
a.coords['x'].align = False
b = sc.realign(data, {'x':x_bins_b}) # same shape but different values than x_bins_a
b.coords['x'].align = False
ds = sc.Dataset({'a':a, 'b':b})
# What is the relation between unaligned dims (concept used by realign)
# and aligned/unaligned coords?

# Dataset definition:
# - set of data arrays with aligned coords (implying same shape/dims)
# New definition:
# - set of data arrays with same dims/shape => sane definition of slicing
# - and matching aligned coords
#   => sane definition of value-based slicing?
#   => use as table
# - unaligned coords may mismatch

# realign definition:
# - puts new dims and shape around data array
a = sc.realign(data, ['x','y']) # no bins specified
a = sc.realign(data, {'x':x_bins,'y':y_bins, 'tof':None})
# three cases (we have this now, but third is automatic):
# - realigned (map x(position) into x bins)
# - keep (tof)
# - hide (automatic for position, because coord for realigned dim depends on it)
#   => may need to change to do this explicitly if required
# Examples:
# realign position to x,y:  mapping 1 dim to 2 new dims
# realign event tof to tof: mapping event-index to 1 new dim
# realign event tof and pulse time to tof and temperature: mapping event-index to 2 new dims
# realign x-pixel,y-pixel to scattering angle: mapping 2 dims to 1 dim
# realign x-pixel to nothing (ignore off-specular): mapping 1 dim to 0 dims

data.attrs['monitor'] = (monitor, dims) # dims=[tof]
# implementation of attrs
def __setitem__(name, attr, dims=[]): # default: ignore dims, equivalent to 0-D attr
    self[name].value = sc.realign(attr, dims=dims)
    
# internally data.attrs['monitor'].value.unaligned
data.attrs['monitor'] # DataArray dims=[tof]
    
data = sc.concatenate(data1, data2, 'spectrum') # shape=(2, data1.shape)
# could concatenate on attrs['monitor'].value # realigned DataArray
data.attrs['monitor'] # DataArray dims=[spectrum,tof]
data['spectrum',0].attrs['monitor'] # DataArray dims=[tof]
    
    
# Question: Is this the same as saying that coords should be
# DataArray (with no coords in normal case)?
# Do we need align and unaligned coords as well as attrs?
# Can we get away without attrs?

# Question: What contract does an object need to fulfil to be usable as a coord?
# - must have dims, shape
# - comparable
# - sliceable
# => could support Variable, DataArray, Dataset
class VariableConcept {
    auto dims() = 0;
    auto shape() = 0;
    bool operator==() = 0;
    auto slice() = 0;
    auto concatenate() = 0; // throw if PyObject?
};
class Variable : public VariableConcept {};
class DataArray : public VariableConcept {
private:
    // example: monitor
    // point to realigned DataArray (hiding, e.g., different TOF shape)
    std::map<std::string, deep_ptr<VariableConcept>> m_coords;
};
class Dataset : public VariableConcept {};
class PyObject : public VariableConcept {};
    
data.attrs['monitor'].value # now
data.coords['monitor'].unaligned # then

# but would still like to
data.coords['name'] = 'abc' # could add this without trouble? => Variable(dims=[], value='abc')
# and
name = data.coords['name'] # name is 0-D variable, can we make it behave more like a string?

table = data.attrs['table']
table['column1'] # instead of "table.value['column1']"
col = data.attrs['table']['col']

data.coords['x'] # 1D Variable
data.coords['monitor'] # 0D DataArray
data.coords['name'] # PyObject (str)
```
