### ISSUE TITLE
Use of bitmask comparitors instead of logical

### ISSUE THREAD

**Issue by DavidFair** [scipp/scipp#1156]
As part of the work in #1154 we noticed that MSVC warns in Rebin for comparison between `bool` and `int`

It turns out that `bool &` is compared as a pointer (e.g. bool / ptr) comparison, rather than the underlying type. This also effects the ops in `logical.cpp`

We should:
- Enable the GCC bitmask comparison warning (not included by default in Wall)
- Replace with logical comparison in Rebin (already done)
- Replace the operator in `logical`, this is a bit more nuanced since we have to deal with both `bool` and `variable` types, the latter could be a null pointer

**Comment by DavidFair** [comment]
For future documentation we are seeing warnings on MSVC as follows:

1>C:\Users\\repos\scipp\variable\logical.cpp(22,51): warning C4805: '|': unsafe mix of type 'bool' and type 'int' in operation
1>C:\Users\\repos\scipp\variable\include\scipp/variable/transform.h(483): message : see reference to function template instantiation 'auto scipp::variable::<lambda_504655a0a9e53788b505d9f7575cc961>::operator ()<bool,bool>(bool &,const bool &) const' being compiled
1>C:\Users\\repos\scipp\variable\include\scipp/variable/transform.h(208): message : see reference to function template instantiation 'auto scipp::variable::detail::overloaded_events<Op,scipp::variable::in_place<false>::TransformEventsInPlace>::operator ()<bool&,const bool&>(bool &,const bool &) const' being compiled
1>        with
1>        [
1>            Op=scipp::overloaded<scipp::variable::<lambda_504655a0a9e53788b505d9f7575cc961>,scipp::core::<lambda_ef0fa1bafb4f2c535f3cf79f47d4a8bd>>
1>        ]
1>C:\Users\\repos\scipp\variable\include\scipp/variable/transform.h(218): message : see reference to function template instantiation 'void scipp::variable::detail::call_in_place_impl<Op&,Indices,bool&,scipp::span<const T,18446744073709551615>&,0>(scipp::variable::detail::overloaded_events<scipp::overloaded<scipp::variable::<lambda_504655a0a9e53788b505d9f7575cc961>,scipp::core::<lambda_ef0fa1bafb4f2c535f3cf79f47d4a8bd>>,scipp::variable::in_place<false>::TransformEventsInPlace>&,const Indices &,std::integer_sequence<unsigned __int64,0>,Arg,scipp::span<const T,18446744073709551615> &)' being compiled
1>        with
1>        [
1>            Op=scipp::variable::detail::overloaded_events<scipp::overloaded<scipp::variable::<lambda_504655a0a9e53788b505d9f7575cc961>,scipp::core::<lambda_ef0fa1bafb4f2c535f3cf79f47d4a8bd>>,scipp::variable::in_place<false>::TransformEventsInPlace>,
1>            Indices=std::tuple<scipp::index,scipp::index>,
1>            T=bool,
1>            Arg=bool &
1>        ]

**Comment by DavidFair** [comment]
Copying @SimonHeybrock comment from that PR:

> 
> Interestingly:
> 
> import numpy as np
> 
> a = np.array([True, False])
> ~a # array([False,  True])
> 
> That is, numpy behavior does not match Python behavior, so the operators we provide appear to be consistent with numpy (we may just need to implement them differently to avoid the warnings)?
>

**Comment by DavidFair** [comment]
Looking at the source code this shouldn't affect Python since the operators are bound to their own implementation in `bind_operators.h:122`

So it looks like we have separate behaviours on the C++ and Python side? If so these changes should not change anything in the Python layer (and are unobservable from the C++ layer)

**Comment by SimonHeybrock** [comment]
> their own implementation 
Not sure what you mean here? It should be binding to our C++ version of the operators.
