### ISSUE TITLE
Support for variances in comparison functions?

### ISSUE THREAD

**Issue by DavidFair** [scipp/scipp#1178]
Assuming a user wants to mask anything above / below a certain value the naive implementation would be:

``` python
import scipp as sc

data = [1., 0.4, 0.6]
d = sc.Variable(["counts"], values=data, variances=data)

threshold = sc.Variable(0.8)
masks = sc.greater(d, threshold)  # or sc.less(...)
```

This throws `RuntimeError: This data type cannot have variances.` at Variable.tcc:274 since we rightly have no variances associated with `threshold`

However, this check should not fire, as we are returning a comparison without manipulating data so the RHS being scalar should not be a problem

**Comment by SimonHeybrock** [comment]
Started looking into this: I think all is fine, with one exception: `ValueAndVariance::operator==` would be used for `element::equal`. However, the former is already implemented and also compares the variances. So there are two options:

1. Change `operator==` to ignore variances, as the newly added `operator<`, `operator<=`, ... would. This would require using a *different* operator when comparison including variance is required. The main use of comparison are currently coordinate comparisons. However, this is based on comparing the underlying value and variance arrays (not copying to `ValueAndVariance`) so this is unaffected.
2. Handle `ValueAndVariance` using an overload in `element::equal`. This is mode code and an maybe less consistent.
