### ISSUE TITLE
Bad error messages

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1183]
Improve error messages to include where, what, and why.

List of unclear error messages:

- [x] `transform` supported dtypes.
- [x] `Dataset` constructor from `DataArrays`: mismatch of coords
- [x] #1499
- [ ] Indexing / slicing: claims to need a tuple: `arg0: Tuple[scipp._scipp.core.Dim, int]` but `var['x', 0]` is allowed.
- [x] label based indexing with units mismatch or index with wrong dtype.
- [x] Coord length in creation of `DataArray`. Error doesn't mention possibility of bin-edge coords.
- [x] Constructors with invalid dtypes, e.g. `sc.Variable(dims=['x'], dtype=dict())`

**Comment by jl-wynen** [comment]
>  Indexing / slicing: claims to need a tuple: `arg0: Tuple[scipp._scipp.core.Dim, int]` but `var['x', 0]` is allowed.

I don't think it is possible to change that message unless we wrap `__getitem__` with a function that checks the arguments or parses pybind11's error message/

**Comment by jl-wynen** [comment]
@SimonHeybrock What about the last item? Do you think it is worth trying to find a workaround?

**Comment by SimonHeybrock** [comment]
Regarding the remaining item:
> Indexing / slicing: claims to need a tuple: arg0: Tuple[scipp._scipp.core.Dim, int] but var['x', 0] is allowed.

I don't see the issue? Isn't the error correct? The request for `Tuple` comes from the fact that `obj[<something>] only takes a single argument, so if we pass `'x', 0` it is always turned into a tuple. I think this is just Python, and we can do nothing about this.

**Comment by jl-wynen** [comment]
I think it is confusing because it looks like the args should be `obj[('x', 2)]` and not `obj['x', 2]`.

> I think this is just Python, and we can do nothing about this.

In principle we could by parsing the arguments ourselves. But I don't think it is worth it. This is why I didn't do it in my PR from November.

**Comment by SimonHeybrock** [comment]
Note that `obj['x', 2]` is just a shorthand for passing a tuple. This works: `sc.arange(dim='x', start=0, stop=4)[('x', 1)]`
