### ISSUE TITLE
Drop "scipp" from target names

### ISSUE THREAD

**Issue by DavidFair** [scipp/scipp#1189]
Currently we have names like

`scipp-core`
`scipp-dataset`

and for unit tests:
`scipp-dataset-test`
`scipp-core-test`

...etc.

This means that developers can't tab complete by just typing `data`, they first need to do `scipp-data`. It's a trivial thing but over time it just feels awkward to develop with using make/ninja.

`core`
`dataset`
`core-test`
`dataset-test`
...etc.

What are people's thoughts?

**Comment by SimonHeybrock** [comment]
No one appears to have an opinion about this. Current target names match, e.g., the library names (`libscipp-core.so`). Closing for now.
