### ISSUE TITLE
Incorrect error msg constructing DataArray in C++

### ISSUE THREAD

**Issue by DavidFair** [scipp/scipp#1190]
The following code
```c++
auto tofCoords = makeVariable<double>(Dims{Dim::X}, Shape{4}, units::us,
                                        Values{1, 2, 3, 4});

  auto data = makeVariable<double>(Dims{Dim::X}, Shape{3}, Values{10, 20, 30},
                                   Variances{0, 0, 0});

  DataArray array(data, {{Dim::Tof, tofCoords}});
```

Produces the following error:
`C++ exception with description "Length mismatch on insertion. Expected size: 4 Requested size: 4" thrown in the test body.`

Because `Dim::X` in line 1 does not match the dim (`Tof`) for DataArray, not because of a length mismatch

**Comment by SimonHeybrock** [comment]
The dim label mismatch is not the issue. I believe there is a restriction such that only dimension-coords can be bin edges. If you reduce the length of the coord to 3 the error should go away.

The real question is: Should we support non-dimension coords that are bin edges?
