### ISSUE TITLE
Cannot reshape into 1d

### ISSUE THREAD

**Issue by DavidFair** [scipp/scipp#1192]
Reshape expects a tuple type for shape, this means that it's not possible to reshape to a 1d array:

```
import scipp as sc
import numpy as np

values = np.array([[1., 2.], [3., 4.]])

v = sc.Variable(["x", "y"], values=values)
sc.reshape(v, ["spectrum"], shape=4)
```

It looks like we just need an overload adding to fix this up

**Comment by SimonHeybrock** [comment]
```python
sc.reshape(v, ["spectrum"], shape=(4,))
```
Note the comma for creating the size-1 tuple.

https://stackoverflow.com/questions/7992559/what-is-the-syntax-rule-for-having-trailing-commas-in-tuple-definitions
