### ISSUE TITLE
OSX packaging with Mantid via Workbench

### ISSUE THREAD

**Issue by OwenArnold** [scipp/scipp#1196]
A place to collect and record TODOs and short comings to be solved with the experimental prototype [branch](https://github.com/mantidproject/mantid/tree/scipp_with_mantid)

* Might do better with cmake `install` command
* Always builds Release mode (probably what we want) and build is done at cmake time, which I think is also acceptable given we are ONLY trying to produce a compatible python package.
* Better check for presence of scipp in `make_package.rb`. Currently just seeing if it's in bin directory
* Other cleanup in `make_package.rb`, some dependencies added to not need to be considered for MantidPlot. 
* Check working on Windows. Configuration (Release/Debug...) paths different.
* Solution on Linux might have to be slightly different again. Uses system python so would maybe just need to make scipp known to `mantidpython`? maybe easy.
* Doesn't work for MantidPlot, but maybe that would be beneficial for the Mantid team anyway?

Further future ideas.
* We currently build `origin/master` which is probably right for time being. but maybe Mantid would consider pinning stable `scipp` versions only in future. i.e. `1.0.x`.
* Template in mantid does `import numpy as np` maybe we could add/replace with `import scipp as sc`
* Maybe better confluence of plotting options in scipp with the wrapping windows of MantidWorkbench

**Comment by SimonHeybrock** [comment]
- Document OSX packing info, or make a build script?
- Info will be lost if in branch. Should be on `master` (but not necessary to include in dev docs).
- Issues with plotting with current package.
- Mantid OSX conda package would resolve most of the problems, but difficult?

**Comment by OwenArnold** [comment]
> Will become urgent within the coming 6 months.

Another further reason to need this  is for conda support in dependent packages. (scipp-neutron, ess, ess-notebooks) will all need an upstream scipp conda package and that requires a mantid-framework package.

**Comment by OwenArnold** [comment]
This is made obsolete as far as current use-cases are concerned by #1465 However, this approach may be of interest to the Mantid team.
