### ISSUE TITLE
Instrument view for 1D data and integers

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1203]
Two issues:
- If data is integer instead of float, we get an exception.
- Data is expected to be 2D, e.g., have an inner dim `tof`. We can change this dim using the `dim` argument, but `dim=None` does not work. Adding a dummy dim using `reshape` is also not sufficient: We *also* have to add a *coord* for the dummy dim, or else it still fails.

**Comment by nvaytet** [comment]
MWE:
```Py
# geometry = load() # some instrument
with sc.compat.mantid.run_mantid_alg('LoadEmptyInstrument', Filename=f'{path}/{instrument}') as ws:
    geometry = sc.neutron.from_mantid(ws, advanced_geometry=True)
var = sc.Variable(['spectrum'], values=np.ones(geometry.values.size))
a = sc.DataArray(sc.reshape(var, dims=['spectrum',"empty"], shape=(var.values.size,1)).astype(sc.dtype.float64) )
for coord in ['position','sample-position','source-position','empty']:
    a.coords[coord] = geometry.coords[coord]
for attr in ['rotation','shape','instrument-name']:
    a.attrs[attr] = geometry.attrs[attr]
```

when trying to show layer indices on the instrument view, given by a variable containing ints.

The two problems where the need for `reshape` and `astype`.

And the need to copy the empty coord (or `tof` in other cases).

**Comment by nvaytet** [comment]
The instrument view will go through a major re-write (see #1230 ) and we defer this fix to be part of that refactor/cleanup.
