### ISSUE TITLE
Bugs when plotting realigned data

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1210]
- `plot` ignores `log=True` in a 2D plot of realigned data with automatic histogramming?
- Unit not showing on the color bar, compare, e.g., cells [8] and [9] in https://scipp.github.io/user-guide/unaligned-data.html.

**Comment by nvaytet** [comment]
The second item appears to be a bug in `matplotlib`: https://github.com/matplotlib/matplotlib/issues/17804

**Comment by nvaytet** [comment]
This is now fixed after the plotting refactor.

e.g. from the `binned_data` notebook
![Screenshot at 2020-12-11 12-51-41](https://user-images.githubusercontent.com/39047984/101900383-ac3e1f00-3baf-11eb-87b1-a70662ea89a3.png)
