### ISSUE TITLE
Overplotting data from multiple objects or slices

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1217]
As discussed in #802, users would like to plot data from multiple data arrays or dataset in the same figure. The problem is more general: Even if axes are shared, data may be in multiple objects. The solution proposed there is to use matplotlib:

```python
import matplotlib.pyplot as plt
fig, ax = plt.subplots(1, 1, figsize=(9, 6))
plot(d1["Sample1"], mpl_axes=ax)
plot(d2["Sample2"], mpl_axes=ax, color=1)
ax.set_ylim([0, 10])
fig
```

However, in practice it required a fair bit more work, non obvious to a user:

```python
import matplotlib.pyplot as plt
fig, ax = plt.subplots(1, 1, figsize=(7, 5))

plot(db, logy=True, collapse='Q', mpl_axes=ax)

plot(db_full, color=9, mpl_axes=ax)
ax.lines[-1].set_linestyle('dotted') # because `linestyle` option is ignored for histogram
ax.lines[-1].set_label('full range') # because there is no `label` option to `plot`

plot(db_fit, mpl_axes=ax)
ax.lines[-1].set_linestyle('dashed') # see above
ax.lines[-1].set_label('fit') # see above

ax.set_ylim([0.1, 100])
ax.legend() # because setting labels by hand apparently does not update legend
fig.show()
```

See inline comments for required changes. A more convenient wrapper for this "overplotting" application is likely a requirement. Fixing some of the inconveniences (non-working linestyle and label options) may get us part of the way, but "native" overplotting support should still be considered.

A second, related but different, application is plotting selected indices from an object. Scientists would like to plot, e.g., slices `0,3,9,17` from an object. This is not supported by our slicing syntax. We might use a loop to plot this to the same axes:
```python
import matplotlib.pyplot as plt
fig, ax = plt.subplots(1, 1, figsize=(7, 5))
for i, straw in enumerate([1,3,4]):
    plot(straw_counts['straw',straw], color=i, marker=i, mpl_axes=ax)
```
This is actually relatively convenient already, except for the need to `enumerate` to manually set the color and marker (otherwise everything has identical colors and markers). However, this is still missing the legend, so we have to do this by hand again, which brings us to the more complex:
```python
import matplotlib.pyplot as plt
fig, ax = plt.subplots(1, 1, figsize=(7, 5))
i = 0
for tube, straw in (1,3),(3,5),(4,0),(11,3):
    plot(pixel_counts['tube', tube]['straw', straw],
         color=i, marker='.',
         mpl_axes=ax)
    ax.lines[-1].set_label(f'tube-{tube}-straw{straw}')
    i += 1
ax.legend() # last label does not show without this
```

**Comment by nvaytet** [comment]
Note that you can supply the plot function a `dict` of `DataArrays`. E.g.:
```Py
d1 = sc.Dataset()
N = 50
d1.coords['tof'] = sc.Variable(['tof'],
                                 values=np.arange(N).astype(np.float64) + 20.0,
                                 unit=sc.units.us)
d1['Sample1'] = sc.Variable(['tof'], values=10.0*np.random.rand(N),
                           unit=sc.units.counts)
d2 = sc.Dataset()
M = 100
d2.coords['tof'] = sc.Variable(['tof'], values=np.arange(M).astype(np.float64),
                                 unit=sc.units.us)
d2['Sample2'] = sc.Variable(['tof'], values=2.0*np.random.rand(M),
                            unit=sc.units.counts)
plot({"Sample1": d1["Sample1"], "Sample2": d2["Sample2"]})
```
Maybe this helps?

**Comment by nvaytet** [comment]
And you can customize further by doing something like:
```Py
plot({"Sample1": d1["Sample1"], "Sample2": d2["Sample2"]},
     linestyle={"Sample1": "solid", "Sample2": "dashed"},
     color={"Sample1": "red", "Sample2": "black"})
```
![Screenshot_2020-06-23_13-22-06](https://user-images.githubusercontent.com/39047984/85397828-8d41c700-b554-11ea-98d3-3f80dd77ca12.png)

**Comment by nvaytet** [comment]
And for your last example, this could be:
```Py
N = 50
M = 10
L = 100
d = sc.Dataset()
d.coords['tof'] = sc.Variable(['tof'], values=np.arange(L))
d.coords['tube'] = sc.Variable(['tube'], values=np.arange(N))
d.coords['straw'] = sc.Variable(['straw'], values=np.arange(M))
d['Sample1'] = sc.Variable(['tube', 'straw', 'tof'],
                           values=np.arange(N*M*L).reshape([N, M, L]),
                           unit=sc.units.counts)
to_plot = {}
for tube, straw in (1,3),(3,5),(4,0),(11,3):
    to_plot[f'tube-{tube}-straw{straw}'] = d['Sample1']['tube', tube]['straw', straw]
plot(to_plot)
```
![Screenshot_2020-06-23_13-35-58](https://user-images.githubusercontent.com/39047984/85399077-7bf9ba00-b556-11ea-8f43-3103904e40ee.png)

**Comment by nvaytet** [comment]
These examples should probably be in the documentation pages. Just realised it's not listed anywhere that you can do this....

**Comment by SimonHeybrock** [comment]
I don't believe this is general enough: Consider in particular my first example: We have 2D data we want to plot as 1D with the `collapse` option, and 1D data to overplot. This is one particular example where we want to overplot things, but use different options for each added line or set of lines. The approach with `mpl_axes` is maybe the right one, if we can wrap it up more conveniently?

**Comment by nvaytet** [comment]
yes, i still think that something like `mpl_axes` is required for full customization, but i think you can achieve a lot with a dict of dataarrays. For combining collapsed data with others, maybe `collapse` could be a free function that returns a dict of data arrays, and then we could send that to the plot?
e.g.
```Py
plot(sc.collapse(d, keep="Q"))
```

Maybe it is useful to have that functionality outside of the `plot` anyway? Also, `collapse` was always a bit of an odd ball in the plotting code, an outsider. And the syntax was a little counter-intuitive. You think it reads "I want to collapse Q" but instead it actually means "collapse everything else than Q".

I addition, what do people think about changing the keyword argument from `mpl_axes` to `ax` (more in line with `matplotlib` naming), and `cax` for the colorbar axes?

**Comment by SimonHeybrock** [comment]
> For combining collapsed data with others, maybe `collapse` could be a free function that returns a dict of data arrays, and then we could send that to the plot?
> e.g.
> 
> ```python
> plot(sc.collapse(d, keep="Q"))
> ```
> 
> Maybe it is useful to have that functionality outside of the `plot` anyway?

Yes, in fact I needed this more than once besides plotting, essentially to map a dimension of a data arryy to dataset entries, I would like to to:

```python
dataset = sc.Dataset(sc.slices(array, dim='wavelength'))
``` 
I feel it is definitely the right approach to attempt to extract this from the plotting code to avoid overcomplication. The question is which helpers we need, or if we should/can just say "use dict-comprehension":

```python
plot({f'wavelength-{i}':data['wavelength', i] for i in 1,2,3,6,7 })
```

**Comment by SimonHeybrock** [comment]
This example actually works licely with dict-comprehension:
```python
plot({f'tube-{tube}-straw{straw}':pixel_counts['tube', tube]['straw', straw]
      for tube, straw in [(1,3),(3,5),(4,0),(11,3)]})
```

**Comment by nvaytet** [comment]
i think we start with `dict` comprehension and then add helper later if many users are fed up with having to type this long line too many times.

**Comment by nvaytet** [comment]
then the plotting code could always take a dict of dataarrays or even dict of dicts, when we make a `to_dict` from a `dataset`, and then it will be easier to separate it from the rest of scipp.

**Comment by SimonHeybrock** [comment]
Ok, so it looks like the decision here is:
- Simplify plotting code by dropping `collapse` option.
- Recommend and document use of dicts (and dict-comprehension).
- Probably provide helpers such as `sc.collapse` or `sc.slices` so we do not lose functionality compared to what `plot` can do now. This would return a dict and could, e.g., be used to convert a dimension to a dataset. The reverse would also be useful.
