### ISSUE TITLE
Should rebin apply masks?

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1218]
Reduction operations such as `sum` or `mean` apply masks that depend on the reduced dimension. In `rebin` we chose to rebin the mask instead, growing the mask where masked and unmasked bins contribute to the same output bin.

Is this the correct approach? Essentially the output value for every bin is the sum over potentially multiple input bins, i.e., from this point of view we should just apply the mask. This would be logically more consistent. The question is whether it would cause issues in practice?

**Comment by nvaytet** [comment]
One small thing where this would cause problems is plotting 2D data where masks are present, as `rebin` is used there.
But I guess one could always work around that.

**Comment by SimonHeybrock** [comment]
I suppose one could rebin the variable and mask separately in that case, instead of rebinning the data array?

**Comment by nvaytet** [comment]
Yes, that would be the way to work around it in this case

**Comment by SimonHeybrock** [comment]
From a slightly different point of view, `rebin` should *not* apply masks: While in principle there is a `sum` applied, we are not removing a dimension. Applying (and thus dropping) the mask will thus lead to very misleading outputs, since it will be impossible to tell whether a region is actually zero or has simply been masked before the rebin. Keeping *and* applying the mask does not make sense, so I conclude that the current mechanism is correct.
