### ISSUE TITLE
Additional operations

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1221]
# General remarks

- `out` args are nice to have, but in practice mostly relevant for certain performance-critical actions. Given that we may also change how this is handled on the Python binding side (see #1184) I propose to **NOT add support for `out` args at this point** across the board.

# Operations for variables

- [x] `exp`, `log`, `log10`
- [x] `nanmin` and `nanmax`: min and max of a Variable ignoring NaNs (as in `numpy`)
- [x] `nansum` sum of a Variable ignoring NaNs (as in `numpy`) including overloads applying to all dimensions
- [x] `nanmean` including an overload applying to all dimensions @OwenArnold (in progress see #1381) -> use `isnan`:
     ```
     DataArray nanmean(const DataArrayConstView &a) {
       return nansum(a) / sum(!isnan(a));
     }
     ```
- [x] `isinf` `isnan`, `isfinite`, `isneginf`, `isposinf`
- [ ] "Shape" operations such as stack, concatenate multiple, broadcast/reshape? Which do we want to support at this point?
- [x] `//` and `//=` (floordiv), for integer dtype
- [ ] Negation for Variable (possibly the wider set of [logical operators](https://en.cppreference.com/w/cpp/language/operator_logical)) and proxies allowing us to for example `!isnan(x)`

When added, these should also be added for data arrays.

# Operations for data arrays

In principle any operation that is available for variables should be supported also for data arrays. Missing right now:

- [x] Comparisons (`less`, `less_equal`, `equal`, ...).
     - These should operate like binary arithmetic operations, i.e.,  `less` for data array should compare aligned coords, OR masks and then return a new data array where values are given by `less()` for the data() of the arrays.
     - Make sure to add Python bindings for `__lt__`, `__eq__`, ..., as done for variables.
- [ ] Reductions (`min`, `max`) (`sum` and `mean` are available already)
- [x] Trigonometry (`sin`, ...)
- [x] `abs`
- [x] `sqrt`
- [ ] `nan_to_num`
- [ ] `reshape`

## *Not* required:

- `norm`, `dot` (these are for positions, which do not have coords, usually).
- `all`, `any`, ... (maybe later, but boolean arrays are usually masks, i.e., variables, and do not have coordinates)

# Operations for dataset

I suggest to ignore those for now since rarely neeed. Let us focus on variable and data array functions for now.

**Comment by OwenArnold** [comment]
Maybe good things for new developer to work on.

**Comment by jl-wynen** [comment]
Should functions operating on `NaN` and `inf` check if those are supported by the platform?
- **Compilation error**: seems too strong because most of scipp would still work. 
- **assert** / **terminate**: cannot be recovered from / worked around
- **Exceptions** 
   - *pro*: would only trigger if the corresponding function gets used and can be recovered from.
   - *con*: changes `noexcept` depending on the system and adds extra header to fundamental operations.
- **do nothing**: just breaks in some unpredictable way. But does anyone actually have a non IEEE 754 compliant machine?

Example:
```.cpp

constexpr auto isnan = overloaded{
    arg_list<double, float>,
    [](const auto x) -> bool {
      if constexpr (std::numeric_limits<decltype(x)>::has_quiet_NaN &&
                    !std::numeric_limits<decltype(x)>::has_signaling_NaN) {
        return std::isnan(x);
      } else {
        throw std::runtime_error(
            "This platform does not support not-a-number.");
      }
    },
    [](const units::Unit &) { return units::dimensionless; }};
```

**Comment by SimonHeybrock** [comment]
I don't think anyone has such a machine? If so, we would probably have quite a few other things that are broken, so I would so we should not worry about this at this point?

**Comment by jl-wynen** [comment]
If the users are disciplined and run the units tests, then those might catch it. I could just add a test for IEEE 754 compliance to be on the safe side?

**Comment by SimonHeybrock** [comment]
I don't think that should be handled on a per-operation basis then? Rather, it should be checked when loading the library, i.e., is unrelated to the additions in this thread?

**Comment by jl-wynen** [comment]
What would you do if it fails? Not load the module or just print an error? In the former case, we can also abort compilation and get the diagnostic earlier.

**Comment by SimonHeybrock** [comment]
Our CI runs the tests before making a package so that should catch this. If someone builds on their own, on a special platform that is a different question. I don't think this is a priority right now, but if it is as simple as adding a line in the CMake config, why not.

**Comment by jl-wynen** [comment]
`static_assert(std::numeric_limits<double>::is_iec559);` at file scope?

**Comment by SimonHeybrock** [comment]
Sounds ok, but which file? Every file using NANs?

**Comment by jl-wynen** [comment]
Doesn't matter. If it is a file that is always compiled, it will trigger.
`core/element/special_values.h` seems natural because it contains the core NaN/inf handling.
