### ISSUE TITLE
__eq__, __le__, __lt__, ...?

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1235]
### Proposal

Scipp's `==` returns `true` or `false`. This is used frequently on the C++ side, e.g., to implement coordinate comparisons and unit tests. This is different from a comparison of, e.g., numpy arrays, which returns and array of booleans.

This would be very much non-standard in C++: Consider comparison of variables, which have a unit, so comparison operators would throw. Therefore, scipp supports `equal`, less_equal`, `less`, ...

However, users of the Python API rarely make use of full comparisons, but rather require element-wise comparisons in many cases. We could therefore:

- Leave everything on the C++-side as it is.
- Bind `__eq__` to `equal` instead of `operator==`, `__lt__` to `less`, ... Note that these would throw, e.g., on unit mismatch.
- Add named binding for the rarer cases when `operator==` is what is needed.

This would bring scipp more in-line with what people are used to from numpy.

### Real life example:
Now:
```python
sample.masks['electronics-error'] = sc.less(sc.abs(x), 0.2 * sc.units.m) \
                                  & sc.less(sc.abs(y), 0.03 * sc.units.m) \
                                  & sc.equal(counts, 0.0 * sc.units.counts)
```
If proposal is implemented:
```python
sample.masks['electronics-error'] = sc.abs(x) < 0.2 * sc.units.m \
                                  & sc.abs(y) < 0.03 * sc.units.m \
                                  & counts == 0.0 * sc.units.counts
```

**Comment by OwenArnold** [comment]
so you would no longer directly be able to do `if a == b` where `a` and `b` are scipp variables (this is major proposed change), would have to go via named binding? Did you have a name in mind for the additional binding for `operator==`?

**Comment by SimonHeybrock** [comment]
> so you would no longer directly be able to do `if a == b` where `a` and `b` are scipp variables (this is major proposed change), would have to go via named binding? Did you have a name in mind for the additional binding for `operator==`?

Correct. Maybe `if sc.same(a, b)`?

**Comment by OwenArnold** [comment]
> > so you would no longer directly be able to do `if a == b` where `a` and `b` are scipp variables (this is major proposed change), would have to go via named binding? Did you have a name in mind for the additional binding for `operator==`?
> 
> Correct. Maybe `if sc.same(a, b)`?

I consider that this is something that would frequently be used, you proposed name sounds reasonable. should also name `is_approx` to `approx` in that case.

**Comment by SimonHeybrock** [comment]
> I consider that this is something that would frequently be used, you proposed name sounds reasonable. should also name `is_approx` to `approx` in that case.

Where would it be used frequently? Can you give examples?

**Comment by SimonHeybrock** [comment]
Maybe `is_equal` and `is_approx` are better names (`equal` would return an array).

**Comment by OwenArnold** [comment]
> > I consider that this is something that would frequently be used, you proposed name sounds reasonable. should also name `is_approx` to `approx` in that case.
> 
> Where would it be used frequently? Can you give examples?

I should have said more frequently. Primarily based on analogy of wanting to compare numpy arrays `np.all(a==b)` rather than element-wise i.e. Writing/developing function and asserting result.

**Comment by SimonHeybrock** [comment]
As a counter-point, I cannot think of examples in the notebooks we have written so far. It is used in our unit tests, but apart from that?

**Comment by OwenArnold** [comment]
> As a counter-point, I cannot think of examples in the notebooks we have written so far. It is used in our unit tests, but apart from that?

Indeed. Haven't needed it to complete an operation outside development/testing.

**Comment by SimonHeybrock** [comment]
So then maybe we should go ahead with the proposal, designing the API for users rather than dev/testing?
