### ISSUE TITLE
Use boost from conda instead of downloading the source?

### ISSUE THREAD

**Issue by nvaytet** [scipp/scipp#1241]
Since we are relying on `tbb` from conda for development purposes, we could also rely on conda for `boost` instead of downloading a fixed version during the CMake step?

**Comment by DanNixon** [comment]
If we do this I vote we do this with all dependencies. It would be preferable to have a single dependency manager.

**Comment by nvaytet** [comment]
I think we are trying to move away from Eigen anyway.
What other dependencies do we have? Were you thinking of `gtest` for instance?

**Comment by rozyczko** [comment]
`pybind11` can also be pulled from conda-forge

**Comment by DanNixon** [comment]
Also Google benchmark.

**Comment by SimonHeybrock** [comment]
I feel this would significantly heighten the entry barrier for building scipp as a developer. Right now `cmake` just deals with everything (except TBB, which is not relevant to all developers at all times). Forcing everyone to use conda and build inside a conda environment does not feel like an advantage to me?

**Comment by SimonHeybrock** [comment]
@rozyczko mentions another problem with switching to conda here: https://github.com/scipp/scipp/issues/1097#issuecomment-660696132.

**Comment by DanNixon** [comment]
> I feel this would significantly heighten the entry barrier for building scipp as a developer. Right now `cmake` just deals with everything (except TBB, which is not relevant to all developers at all times). Forcing everyone to use conda and build inside a conda environment does not feel like an advantage to me?

I disagree, currently to use the Python API you need to deal with Conda and this is well documented in the developer getting started guide so installing build time dependencies via Conda does not really change much in this regard.

In fact, the steps in the documentation would not even need to change (https://scipp.github.io/developer/getting-started.html#getting-the-code-building-and-installing).

**Comment by SimonHeybrock** [comment]
I don't think you need conda. My default build is not in a conda env, and I am using `pip` when running, e.g., Python tests, for the extra dependencies.

I honestly do not see why forcing the use of an additional, optional tool just to build scipp would be an advantage?

**Comment by DanNixon** [comment]
You don't *need* it, but it is the far easier path for a new developer.
There is not a simple way to obtain a command you can give to `pip` to install everything you need whereas there is with Conda and this is our documented means of doing so (hence why I say there is no change for a new developer).

> I honestly do not see why forcing the use of an additional, optional tool just to build scipp would be an advantage?

- We do not actually say it is optional: https://scipp.github.io/developer/tooling.html#misc
- It is easier
	- Less places to hunt around for dependencies
	- Documented
	- Builds something closer to what is released

**Comment by SimonHeybrock** [comment]
> but it is the far easier path for a new developer.

They can do that now as well. No reason for changing how we install header-only libs.

> but it is the far easier path for a new developer.

On the contrary. As it is now, if someone just wants to build and run the C++ tests all they need is `cmake`. If we change the C++ dependencies to conda, they need `cmake` *and* `conda`. So this would be a change to a more difficult path.

> Documented

You mean conda documentation is better than cmake documentation? Not sure what you are referring to?

> Builds something closer to what is released

In what sense? The releases also use `cmake` to install the header-only C++ dependencies.

**Comment by DanNixon** [comment]
> As it is now, if someone just wants to build and run the C++ tests all they need is cmake

I'd bet a lot on no Scipp developer ever doing this or ever doing so in the future. I can't see how you can completely ignore the Python bindings and documentation.

> You mean conda documentation is better than cmake documentation? Not sure what you are referring to?

Our documentation. Conda is mentioned as a requirement here.

> In what sense? The releases also use cmake to install the header-only C++ dependencies.

This referred to your method of using `pip`, which does not guarantee installing the same versions (or indeed packages) as Conda.

**Comment by SimonHeybrock** [comment]
> > As it is now, if someone just wants to build and run the C++ tests all they need is cmake
> 
> I'd bet a lot on no Scipp developer ever doing this or ever doing so in the future. I can't see how you can completely ignore the Python bindings and documentation.

Surely not for someone really working with it on a daily basis. But I do disagree that no one will ever to this in the future: Have you never found a bug in a project, forked it, fixed it, ran the tests, and submitted a PR upstream? *Requiring* use of `conda` (I am *not* against *recommending* use of `conda`, on the contrary) does significantly raise the barrier of entry for such contributions. For example, we had such a one-time contributor to scipp just 2 months ago with a C++-only change (not sure whether they used conda or not, but just to give a concrete example).


> > You mean conda documentation is better than cmake documentation? Not sure what you are referring to?
> 
> Our documentation. Conda is mentioned as a requirement here.

Odd argument. When documentation is incomplete/wrong we don't usually suggest to change the code to match the documentation.


> > In what sense? The releases also use cmake to install the header-only C++ dependencies.
> 
> This referred to your method of using `pip`, which does not guarantee installing the same versions (or indeed packages) as Conda.

I don't understand. `pip` is for runtime dependencies, so it has nothing to do with library versions used for building the C++ parts.

**Comment by DanNixon** [comment]
I can see I am getting nowhere and this is never really going to be considered.
