### ISSUE TITLE
The save figure feature sometimes opens a new with a blank screen with nothing to save.

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1247]
No more information available.

**Comment by nvaytet** [comment]
I'm guessing this is a matplotlib bug and not a scipp bug?

You can always save a figure using the `filename` keyword argument: see https://scipp.github.io/visualization/plotting-1d-data.html#Saving-figures

**Comment by SimonHeybrock** [comment]
Found it: https://github.com/matplotlib/matplotlib/issues/9117. Apparently this is in issue in Chrome, i.e., it should work in Firefox?

**Comment by nvaytet** [comment]
I'd like to also add that it seems using the `ipympl` backend for matplotlib figures in Jupyter (https://github.com/matplotlib/ipympl) is better at saving figures.
Install with `conda install -c conda-forge ipympl`
