### ISSUE TITLE
Modification of dataset coords via item coords should be prevented

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1256]
This has been long known, but for the record:
```python
import scipp as sc

d = sc.Dataset()
d['a'] = 1.0 * sc.units.m
d.coords['x'] = 1.0 * sc.units.one
d['a'].coords['x'] += 1.0 # this should not be possible
```
With the coord handling refactor, is there a way to prevent this?

**Comment by OwenArnold** [comment]
@SimonHeybrock so what you are proposing is something along the lines of `CoordsView` subscriptable access providing a VariableConstView rather than a VariableView?

**Comment by SimonHeybrock** [comment]
Yes, probably. This would require wider support for const views on the Python side though. May be worth investigating what would need to change first, without starting the implementation, so we can then consider out options/priorities.

**Comment by OwenArnold** [comment]
> Yes, probably. This would require wider support for const views on the Python side though. May be worth investigating what would need to change first, without starting the implementation, so we can then consider out options/priorities.

I've only taken a cursory look thus far. But implementing may be tricky. Inplace for masks would often make sense for example and I think that's all implemented through `MutableView`

**Comment by SimonHeybrock** [comment]
Dataset does not have masks any more (after changes this summer). All masks are stored on the items, so this should not be relevant.

**Comment by OwenArnold** [comment]
> Dataset does not have masks any more (after changes this summer). All masks are stored on the items, so this should not be relevant.

Indeed. I meant more in terms of being careful around changes for `MaskView` which is also templated  `MutableView` instance, and returned from the dataset for the relevant item `d['a'].masks['mask']`

**Comment by SimonHeybrock** [comment]
Would be irrelevant if shared ownership was introduced, see #1617.
