### ISSUE TITLE
Cleaner Python API for adding unaligned coords?

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1264]
#1261 changed `attrs` to `unaligned_coords`. Python API is now:

```python
a = DataArray(data=var, coords={'x':x}, unaligned_coords={'attr':x})
a.coords
a.aligned_coords
a.unaligned_coords
```

It would be more intuitive to have:

```python
a = DataArray(data=var, coords={'x':x}) # should still work if no unaligned
a = DataArray(data=var, coords={'aligned':{'x':x}, 'unaligned':{'attr':x}})
a.coords
a.coords.aligned
a.coords.unaligned
```

The suggestion would be to keep changes on the C++ side minimal, i.e., keep `DataArray::unaligned_coords()` (etc.). Changes would be done in the Python bindings only. Potentiall not trivial (requiring *some* internal C++ changes), since right now there is no way of getting back to the parent data array of a coord view, i.e., we cannot create the aligned or unaligned subview.

**Comment by OwenArnold** [comment]
Do not develop this until we know it really needed.

See #1346 for attempted solution and notes on future direction of solution if required.

**Comment by SimonHeybrock** [comment]
- Should we rename `unaligned_coords` back to `attrs`?
  - Note that xarray attrs would then behave differently.

Confusing?
```python
data.attrs['attr'] = var
data.coords['attr'] # exists now
```

Would this work, or is there an issue with datasets? Re-read #1155.
```python
data.meta # coords and attrs?
data.coords # only aligned
data.attrs # only unaligned
```

**Comment by SimonHeybrock** [comment]
See also #1253.

**Comment by SimonHeybrock** [comment]
Reassigned, since I am trying the renaming approach, which would make this API addition obsolete.
