### ISSUE TITLE
Strange behaviour with `sc.sum` on multi-item datasets with global masks

### ISSUE THREAD

**Issue by OwenArnold** [scipp/scipp#1278]
Found while evaluating imaging notebook for #1261 

Background.

* Following example is based on weighted sum implementation in the notebook
* Original implementation used dataset level masking to mask zero elements prior to division. This has to be reimplemented as part of the new approach as use of global masks are not possible.
* The reimplementation exposed what looks like a bug in the original though sum on a dataset DOES respect global masks when it applies the sum to each held item.

```python
def with_data_array(da, dim):
    variances = sc.variances(da.data)
    norm = sc.DataArray(data=sc.reciprocal(variances))
    return sc.sum(norm, dim)

def with_dataset(da : sc.DataArrayView, dim):
    variances = sc.variances(da.data)
    d = sc.Dataset()
    d["norm"] = sc.reciprocal(da.data)
    d["data"] = da.copy() # Do nothing, but THIS affects return output. Removing it yields correct result!
    d = sc.sum(d, dim=dim)
    return d['norm']
    
da = sc.DataArray(data=sc.Variable(['spectrum'], values=np.arange(1.0, 10.0), variances=np.arange(1.0,10.0)),masks={'mask':sc.Variable(['spectrum'], values=np.array([True]*9))})

correct = with_data_array(da, "spectrum")
strange = with_dataset(da, "spectrum")
print(correct)
print(strange)
```

**Comment by SimonHeybrock** [comment]
Yes, this was a known (or even intended and useful) behavior prior to #1261. Simpler example:

```python
import scipp as sc
import numpy as np

d = sc.Dataset()
d['a'] = sc.DataArray(data=1.0*sc.units.one)
d['b'] = sc.DataArray(data=1.0*sc.units.one, masks={'mask':sc.Variable(value=True)})
d['a']
```
`d['a']` now lists the mask added via `b`. This is fixed with the removal of dataset masks.

**Comment by OwenArnold** [comment]
Closing this issue after discussion. This behaviour will disappear anyway with #1261.
