### ISSUE TITLE
Better documentation for plotting

### ISSUE THREAD

**Issue by nvaytet** [scipp/scipp#1283]
Right now, the documentation for plotting shows a few examples, but there is no list of all the keyword arguments, explaining what they are and what they do.
This should probably be a long table in a section called `Plotting reference` or something like that.

**Comment by SimonHeybrock** [comment]
Having a proper Shpinx docstring for `plot()` would get us half-way, and should be added anyway?

**Comment by nvaytet** [comment]
> Having a proper Shpinx docstring for `plot()` would get us half-way, and should be added anyway?

yes, that's part of it :-)

**Comment by nvaytet** [comment]
see #1323
