### ISSUE TITLE
Reenable Windows CI

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1299]
- [x] Revert #1298 (commit bab86e7) once compiler issues solved.
- [x] Revert fb8d8df
- [x] Mark Windows Job as "Required" in GitHub branch protection settings.

**Comment by Matthew-Andrew** [comment]
Seems to be as a result of this issue https://developercommunity.visualstudio.com/content/problem/1141651/regression-c-internal-compiler-error-in-1670-with.html

**Comment by Matthew-Andrew** [comment]
This seems to be the result of the later versions of visual studio not being able to cope with code like in https://godbolt.org/z/Wh896M (the currently selected version of MSVC here works switching to a later one will break things). As this pattern is used throughout the code base I don't think updating it looks feasible.

As in the error report linked above this problem goes away if scipp is compiled against `/std:c++latest` this leads to other problems in the code-base however.

This problem also persists when compiling scipp with the current visual studio preview build.
