### ISSUE TITLE
Improve Python bindings

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1302]
- [x] ~Partially broken auto complete (works in Notebooks, but not in PyCharm?)?~ ~edit (@matthew-d-jones): turns out it works in PyCharm, just not in the PyCharm embedded in CLion. Hopefully I'll discover some misconfiguration that can be fixed to solve it...~
- [x] Auto-complete includes irrelevant types, e.g., `VariableConstView` instead of just `Variable`.
- [x] `scipp` Python module is polluted with imports and functions that should be private.
- [x] Complicated error messages in particular form constructors for `Variable`, `DataArray`, and `Dataset`, try, e.g., `sc.Variable(dim='x')`. Can this be fixed by wrapping with Python and using type hinting?
- [x] Type hinting in Python bindings.
- [x] Enforce keyword args in complex cases such as `Variable` or `DataArray` constructors.
- [x] Bind C++ exceptions
- [x] Add methods for things such as `sin()` or `sum()`, similar to numpy.

**Comment by jl-wynen** [comment]
I think this is done after #2012 is merged.
Does anyone see additional points to do?
