### ISSUE TITLE
Instrument view takes long time to determine min and max for auto-histogramming

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1304]
This is noticable especially with slightly larger instruments such as WISH (200k pixels):

```python
sc.neutron.instrument_view(sample, bins=1, pixel_size=0.02)
```

Much faster:
```python
tof_range = sc.Variable(dims=['tof'], unit=sc.units.us, values=[0.0, 100000.0])
sc.neutron.instrument_view(sc.histogram(sample, tof_range), pixel_size=0.02)
```

Why is the min/max finding so slow? It should not take longer than histogramming data?

## Solution?
This may be solved automatically with the new event mechanism discussed in #1281. Data boundaries would be stored as coords, even if there is just a singe (TOF) bucket. *Do not attempt to fix this issue at this point, since it may just disappear*.

**Comment by nvaytet** [comment]
So i am now seeing that
```Py
%%time
tof_range = sc.Variable(dims=['tof'], unit=sc.units.us, values=[0.0, 210000.0])
sn.instrument_view(sc.histogram(sample.bins, tof_range), pixel_size=0.01)
1.33 s
```
is about 2x faster than
```Py
sn.instrument_view(sample, pixel_size=0.01)
2.59 s
```
(which is equivalent to running the instrument view on `sample.bins.sum()`).

@SimonHeybrock is this because `.bins.sum()` uses a non-optimized branch of the histogramming?

Do you remember how long it was taking when you opened the issue?

**Comment by SimonHeybrock** [comment]
`.bins.sum()` does not histogram, it is just calling `sum`. Since it is a reduciton operation it is not multi-threaded that this point (this is an open TODO), which may explain the difference.

**Comment by nvaytet** [comment]
In any case, if the current run time is much lower than before (i have a vague memory that it was taking more than 10s to render for WISH), I would say we can close this?

**Comment by SimonHeybrock** [comment]
I think I agree. I cannot notice a slowdown now (apart from the difference between histogramming and summing, we may consider using histogramming to 1 bin instead of calling `bins.sum()`, but this is unrelated to this issue).
