### ISSUE TITLE
Silently fails to add coords when creating DataArray

### ISSUE THREAD

**Issue by matthew-d-jones** [scipp/scipp#1307]
When constructing a `DataArray`, if you try to add coords with a dimension label that does not match a dimension label of the data, then the `DataArray` is created but the coords are missing. I suggest this should raise an exception.

Example:
```python
data_array = sc.DataArray(
    data=sc.Variable(["time"], values=np.linspace(1.,100.,246)),
    coords={"times": sc.Variable(["times"], values=np.linspace(1.,100.,246))})
```
`data_array` is created but adding the coords silently fails.

**Comment by SimonHeybrock** [comment]
Note that it does not actually fail to add the coords: The are added, but are "filtered out" when *retrieving* them. The reason for this behavior is that `DataArray` is implemented as a single-element `Dataset`. In a dataset we *can* have coords that are not for all items, so `dataset.coords` may contain coords that are not in `dataset['a'].coords`.
