### ISSUE TITLE
Slow plot_image for large datasets

### ISSUE THREAD

**Issue by nvaytet** [scipp/scipp#131]
Currently the `plotly` `Heatmap` plot is very slow for large (e.g. 1000 * 2000) datasets.
It would be ideal to limit the resolution for an image, and have it keep the resolution constant every time we zoom in.
It's currently unclear how to achieve this with `plotly`

**Comment by nvaytet** [comment]
I posted a question on the plotly forum and got an answer which might be a good solution. See https://community.plot.ly/t/heatmap-is-slow-for-large-data-arrays/21007

**Comment by SimonHeybrock** [comment]
Fixed by #193, I think.
