### ISSUE TITLE
Use new "bucket" variables to load event-Nexus files without sorting by detector

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1315]
The introduction of bucket-variables gives us the opportunity to have a respresentation of event data very close to how it is stored in Nexus files. While this is *not* useful for most steps of data reduction (such as unit conversions), it may turn out relevant and convenient, e.g., for handling soft-vetoing, i.e., filtering out pulses based in chopper logs.

```python
# Variables loaded from file
event_time_offset # dims=('event')
event_id # dims=('event')
event_index # dims=('pulse')
event_time_zero # dims=('pulse')
weights # often not in file, just 1s?
# events
data = sc.DataArray(
  data=weights,
  coords={'tof':event_time_offset, 'detector-id':event_id})
events = sc.DataArray(
  data=sc.to_buckets(begin=event_index, end=<compute from event_index>, dim='event', data=data),
  coords={'pulse-time':event_time_zero})
```
We can then, e.g., select a pulse:
```python
events['pulse', 17]
```
or get the table of events for the pulse:
```python
events['pulse', 17].value
```

**Comment by SimonHeybrock** [comment]
Existing examples on how to use `to_buckets`: https://github.com/scipp/scipp/blob/master/python/tests/test_buckets.py.

**Comment by matthew-d-jones** [comment]
This can wait until Tuesday, but I'm getting `IndexError: Overlapping bucket indices are not allowed.`. I suspect this is due to pulses where no events were recorded, such that the start and end index are the same.
I could remove all zero length pulses, or perhaps we could allow this case of overlapping indices.

**Comment by SimonHeybrock** [comment]
Can you double check the parameters? Empty buckets should work: https://github.com/scipp/scipp/pull/1317.

**Comment by matthew-d-jones** [comment]
@SimonHeybrock You're right, I made a mistake with the end indices.
