### ISSUE TITLE
scipp sort is slow

### ISSUE THREAD

**Issue by OwenArnold** [scipp/scipp#1350]
Sort hangs on large datasets. On my laptop this does it.

```python
from scipp.io import open_hdf5
import scipp as sc
data = open_hdf5('to-sort2.hdf5')
mask = open_hdf5('sort-by.hdf5')
sc.sort(data, dim='t') # Hangs
sc.sort(data, mask) # Also Hangs
```

`SortData.zip` on owncloud

Shrinking the data size by a dimension sum etc is enough to get things working again.

**Comment by OwenArnold** [comment]
Update: Seems to just get slower with the example above.  size of Indexsliceview > 1000. concatenate used to join every slice.

**Comment by SimonHeybrock** [comment]
This was mainly intended for being able to sort small tables. Is there a current application where you require this for larger data?

**Comment by OwenArnold** [comment]
> This was mainly intended for being able to sort small tables. Is there a current application where you require this for larger data?

As it happens the problem I had I solved with masking, but also groupby would also have worked.

**Comment by OwenArnold** [comment]
@SimonHeybrock mentioned having a better sort implementation. Other than that it would be useful if `sort` could inform/throw if the processing was predicted to take a non-trivial amount amount of time. In example above, sort is taking minutes. Maybe the changes to predict the size of scipp objects could (compare against available memory maybe, though fraught), or just set a maximum object size.

**Comment by SimonHeybrock** [comment]
Note potentially faster `sortby`, removed in #1402. Maybe worth trying that approach again, replacing the existing mechanis,
