### ISSUE TITLE
Add scipp.widgets as a module containing generic widgets for Jupyter notebooks

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1351]
Related: https://github.com/scipp/ess/pull/30

Proposal for discussion:
- Add a new package (separate from scipp) as part of the scipp organization, `scipp/scipp_ipywidgets`.
  - `pip install scipp_ipywidgets`
  - `import scipp_ipywidgets as widgets`
- The module should contain fully generic helpers for setting up widgets, i.e., nothing neutron-scattering related.
- In the linked PR, the two main components that are generic and could become part of `scipp.widgets` are:
  - One or multiple types of base widgets. Essentially anything that can link widget inputs to a function.
  - Generic validators/pre-processors, e.g., to allow only data arrays or dataset as inputs, or only numbers, a list of allowed options for a dropdown menu, ...
- For the time being, avoid unnecessary complexities such as linking widgets for updates, etc. (unlike in the PR).
- Documentation with concrete usage examples should become part of our scipp doc pages.

Overall guideline: Keep it really simple. If in doubt whether a particular feature should be supported, leave it out (for now).

**Comment by OwenArnold** [comment]
Relates to #1220

**Comment by SimonHeybrock** [comment]
> Relates to #1220

Note that the case here is considerably simpler: The proposed module should not contain ESS- or neutron-specific code.

**Comment by SimonHeybrock** [comment]
Esseentially done, see https://scipp.github.io/scipp-widgets/
