### ISSUE TITLE
Do not show legend in 1d plots when data name is empty

### ISSUE THREAD

**Issue by nvaytet** [scipp/scipp#1393]
![Screenshot at 2020-11-12 23-01-10](https://user-images.githubusercontent.com/39047984/99001333-f72a2f80-253a-11eb-9af6-7e2a6e97d989.png)

**Comment by SimonHeybrock** [comment]
Wondering whether in general the data array name should be shown as the title, rather than legend?

**Comment by nvaytet** [comment]
That's the case for 2d images, but since in 1d line plot you can have more than one line on the same axes (e.g. https://scipp.github.io/visualization/plotting-1d-data.html#Plotting-a-Dataset-with-multiple-entries), i think you have to have it as a legend.

**Comment by SimonHeybrock** [comment]
True, unless we would want to distinguish plotting a data array from plotting a dataset.

**Comment by nvaytet** [comment]
You could say that it should be as the title if there is only one line, and then as a legend if there are more, but then it gets inconsistent when you are using `projection=1d` and you start saving profiles with the buttons, as they should appear as entries in the legend.

**Comment by nvaytet** [comment]
> True, unless we would want to distinguish plotting a data array from plotting a dataset.

But i don't know how you would then distinguish between a Dataset and a dict of DataArrays as an input (with `collapse` or dict comprehension)
