### ISSUE TITLE
More flexibility around component_info

### ISSUE THREAD

**Issue by OwenArnold** [scipp/scipp#1396]
Several requirements here
* [ ] We need an `assign_coords` for Dataset and DataArray @SimonHeybrock pointed out xarrays `assign_coord` which would be very useful in general. See examples below
```python
import xarray as xr
import numpy as np
var = xr.Variable(['x'], data=np.arange(10))
da = xr.DataArray(var, coords={'x':var})
ds = xr.Dataset()
combined = ds.assign_coords(da.coords) # like this
coords_from_value = ds.assign_coords({'m':da.data})  # or this
donor = xr.Dataset({'a':da, 'b':da})
coords_from_datase = ds.assign_coords(donor) # or this
```
* [ ] With the above we can rewrite load_component_info to return a dataset with the `sample-position`, `positions`, `rotations` etc as data rather than coords. That gives the ability to (a) save/reload via `to_hdf5` (scipp.io.hdf5) and also the ability to operate easily on the data itself, `+/-...`. In other words we can use the same functionality far more generally.
* [x] As a further step to above. `to_hdf5` does not support 3D vector types, which we would need. Fixed by (#1409)

As a follow on to this, we could consider bypassing Mantid entirely for instrument loading. We would simply need to create the geometry one, save to a hdf5 file and use that.

**Comment by SimonHeybrock** [comment]
I believe some of this functionality (in scippneutron) has been moved or removed. Unclear what (if anything) is needed here.
