### ISSUE TITLE
Investigate SANS code crash with event data

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1410]
Previously that code in `sans.py` (now in https://github.com/scipp/ess-legacy/tree/master/sans) worked with event data. However, with a current scipp version and event data files from SANS2D the Jupyter kernel crashes. Errors indicate it might be an unsupported dtype.

- Why does unsupported dtype lead to a crash, instead of an exception?
- Fix if confirmed, it may have been due to a change of event data handling in recent refactor.

**Comment by SimonHeybrock** [comment]
Problem appears to be the monitor access. Changing in `sans.py`:

```python
def subtract_background_mean(data, dim, begin, end):
    coord = data.coords[dim]
    assert (coord.unit == begin.unit) and (coord.unit == end.unit)
    i = np.searchsorted(coord, begin.value)
    j = np.searchsorted(coord, end.value) + 1
    return data - sc.mean(data[dim, i:j], dim)

def transmission_fraction(sample, direct, wavelength_bins):
    # Approximation based on equations in CalculateTransmission documentation
    # p = \frac{S_T}{D_T}\frac{D_I}{S_I}
    # This is equivalent to mantid.CalculateTransmission without fitting
    def setup(data, begin, end):
        background = subtract_background_mean(data, 'tof', begin, end)
        background = sc.neutron.convert(background, 'tof', 'wavelength')
        background = sc.rebin(background, 'wavelength', wavelength_bins)
        return background

    us = sc.units.us
    #sample_incident = setup(sample['spectrum', 0], 40000.0 * us, 99000.0 * us)
    #sample_trans = setup(sample['spectrum', 3], 88000.0 * us, 98000.0 * us)
    #direct_incident = setup(direct['spectrum', 0], 40000.0 * us, 99000.0 * us)
    #direct_trans = setup(direct['spectrum', 3], 88000.0 * us, 98000.0 * us)
    sample_incident = setup(sample.attrs['monitor1'].value, 40000.0 * us, 99000.0 * us)
    sample_trans = setup(sample.attrs['monitor4'].value, 88000.0 * us, 98000.0 * us)
    direct_incident = setup(direct.attrs['monitor1'].value, 40000.0 * us, 99000.0 * us)
    direct_trans = setup(direct.attrs['monitor4'].value, 88000.0 * us, 98000.0 * us)
    return (sample_trans / direct_trans) * (direct_incident / sample_incident)
```

The "problem" is this line:
https://github.com/scipp/scipp/blob/c3787ac3290bb6459b6b537197b3ace2d0b6dd96/python/src/scipp/compat/mantid.py#L778

This was a "hack" to deal with the odd handling of monitors when *histogrammed* data was loaded, working around an issue of a monitor-only workspace.

The solution should be to setup monitors correctly as `attrs`. That is, we want to access monitors as `sample.attrs['monitor1']` in *all* cases. We should *not* add hacks in `sans.py` to support both cases.

**Comment by OwenArnold** [comment]
I've been through the `direct-beam.ipynb` from here https://github.com/scipp/ess-legacy/blob/master/sans/direct-beam.ipynb modernising as I go. I don't seem to be able to get anything relating to the `sans.py` script to crash on my mac. I'll push updates to `sans.py` and `loki.py` scripts.
