### ISSUE TITLE
Improve is_approx

### ISSUE THREAD

**Issue by OwenArnold** [scipp/scipp#1412]
- [ ] Provide improved tolerance options for `is_approx`, currently only absolute is supported, but the range should include those of `numpy.isclose`, rtol etc.

- [ ] We might also get this working for DataArrays. We should check coords and data, presumably we can simply `&&` the results of all variables under consideration though this might require more thought (what to do with unaligned etc).

**Comment by SimonHeybrock** [comment]
> We should check coords and data, presumably we can simply && the results of all variables under consideration though this might require more thought (what to do with unaligned etc).

Not sure, since this would break with the behavior of essentially all other scipp methods? Probably should just compare all meta data exactly (just like `equal` does), and call `is_approx` on data?

I also noticed an inconsistency with `is_equal`, which returns `bool`, but `is_approx` returns a variable, like `equal`?

**Comment by OwenArnold** [comment]
> I also noticed an inconsistency with is_equal, which returns bool, but is_approx returns a variable, like equal?

I think it is more generally useful to have it like this. You can still use in combination with `sc.all` or `sc.any` and it gives similar behaviour to `sc.isclose`. Though maybe we should have two functions for this to better match `is_equal` and `equal`.

**Comment by SimonHeybrock** [comment]
Not saying it is not useful, but should then probably be renamed for consistency with other array comparisons.

**Comment by OwenArnold** [comment]
> Not saying it is not useful, but should then probably be renamed for consistency with other array comparisons.

Indeed, the naming needs fixing. Maybe just `close` or `approx` as a rename for existing behaviour? That would allow us to use `is_approx` or `is_close` more like `is_equal` as a future reduction operation?

**Comment by SimonHeybrock** [comment]
This should be mirroring https://numpy.org/doc/stable/reference/generated/numpy.isclose.html
- [ ] rename
- [ ] support `rtol` as well as `atol`.
- [ ] consider also adding https://numpy.org/doc/stable/reference/generated/numpy.allclose.html#numpy.allclose
