### ISSUE TITLE
Docs problems

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1420]
- The _Building Documentation_ section under _Getting Started_ is not correct or not specific enough. The instructions make it look as though you had to run `sphinx-build` in your chosen build directory. But in truth it needs to be run in `docs`. See  https://github.com/scipp/scipp/blob/e79f3f9685e2b7922d67c80dc67b4857ecb23333/.azure-pipelines/templates/documentation_build.yml#L42
- Sphinx places a lot of generated files in `docs/generated` which is not git-ignored. We should either add that to `.gitignore` or allow builds in a different location. Don't know how difficult that would be to set up, though.
- Why is it necessary to download 700 MB of data for the documentation? (Also not git-ignored)

_Originally posted by @jl-wynen in https://github.com/scipp/scipp/issues/1418#issuecomment-734804412_

My take on this:

- Maybe we should add a CMake target for the docs (and update the docs on building docs). I *can* run sphinx in the build folder by the way, no need to be in `docs/`.
- The second issue could be solved if the CMake target does this correctly, but it may not be so easy since `generated` is created by a plugin (`nbsphinx`), not Sphinx. Maybe there is an option?
- The third issue may be resolved once we move `scipp-neutron` to its own package/module. Note that the that is not needed by changing a config flag.

**Comment by jl-wynen** [comment]
>     * The third issue may be resolved once we move `scipp-neutron` to its own package/module. Note that the that is not needed by changing a config flag.

The one that ignores errors? Or is there an undocumented flag?

**Comment by SimonHeybrock** [comment]
> > ```
> > * The third issue may be resolved once we move `scipp-neutron` to its own package/module. Note that the that is not needed by changing a config flag.
> > ```
> 
> The one that ignores errors? Or is there an undocumented flag?

The one that ignores errors (admittedly not a good solution).

**Comment by nvaytet** [comment]
Another issue with the docs is that by default, visitors land on the doc pages that are relevant to the current `master` branch, and not the latest release (see #1504 )

We should have a more obvious way for users to switch between releases, and by default, visitors should land on the latest release pages.

On RTD, there is a dropdown menu at the bottom of the page that takes you to stable or latest doc build. Something similar would be nice.

**Comment by SimonHeybrock** [comment]
@jl-wynen 
> Sphinx places a lot of generated files in docs/generated which is not git-ignored. We should either add that to .gitignore or allow builds in a different location. Don't know how difficult that would be to set up, though

https://github.com/scipp/scipp.github.io/tree/master/generated only seems to contain the necessary html files? Which files are you referring to?

**Comment by jl-wynen** [comment]
It contains no HTML files on my machine, only rst files. Everything else is in the build directory. Maybe this changed when the `docs` build target was added. But those files are not required for the final documentation, right? So why would they end up in the source tree?

**Comment by SimonHeybrock** [comment]
The html files? They are required.

**Comment by jl-wynen** [comment]
I mean, there are not HTML files in `generated`, only rst files. And those latter files are not required for the final documentation. The HTML files are in the build directory.

**Comment by SimonHeybrock** [comment]
There is a lot of outdated info in this thread, and no ongoing work. Closing (fix outstanding issues directly, or open new issue where relevant).
