### ISSUE TITLE
Improvements to Label Based Slicing

### ISSUE THREAD

**Issue by OwenArnold** [scipp/scipp#1423]
Current possibilities are listed [here](https://scipp.github.io/user-guide/slicing.html#Label-based-indexing) and caveats [here](https://scipp.github.io/user-guide/slicing.html#Label-based-indexing-caveats)

**1. Slicing is only supported on a dimension coordinate.** 

```python
da = sc.DataArray(data = sc.Variable(dims=['x', 'y'], values=np.arange(8.0).reshape(2, 4)),
    coords={
        'y': sc.Variable(['y'], values=np.arange(8, step=2), unit=sc.units.m),
        'y-other': sc.Variable(['y'], values=np.arange(8, step=2), unit=sc.units.m)})

da['y', 2 * sc.units.m] # Fine (dimension coordinate)
da['y-other', 2 * sc.units.m] # Expected dimension to be in {{y, 4}}, got y-other Error
```
The problem here is that label-based indexing is passing directly through position indexing. Should we allow this slicing for any coordinate (possibly any attribute too).

**2. Slicing coordinate must be monotonic at present**

This simplifies the current implementation as it ensure that just a single positional index (or index range) needs to be generated from the value(s). Operations such as groupby would need to solve a similar problem, so it might be worth looking there for an implementation solution.

**Comment by SimonHeybrock** [comment]
> The problem here is that label-based indexing is passing directly through position indexing. Should we allow this slicing for any coordinate (possibly any attribute too).

I don't think this is a/the problem. We can lookup `dim` -> `coord` (and find the index range, as done now) and then define `slicing_dim = coord.dims().inner()` and forward that to positional indexing?

**Comment by SimonHeybrock** [comment]
> 2. Slicing coordinate must be monotonic at present

> This simplifies the current implementation as it ensure that just a single positional index (or index range) needs to be generated from the value(s). 

I think it is true that this is difficult to do in general. I think I would recommend to only support this for non-range non-bin case, such that we can:

- `data['month', sc.Variable(value='october)']
- Raise if there are multiple matching keys found.

**Comment by SimonHeybrock** [comment]
Note that 1.) is working already?

**Comment by SimonHeybrock** [comment]
Main issue is fixed already. Non-monotonic indices are an advanced feature, we can handle in a new issue once required.
