### ISSUE TITLE
Output style with dark mode

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#1452]
The output of of Scipp objects as well as the output of `scipp.show` seem to have some hard coded colour values that only work with light mode. In Jupyter Lab dark mode, the output is not completely readable:
![dark_mode](https://user-images.githubusercontent.com/11393224/101639193-49257e80-3a2f-11eb-801f-a951c2c85079.png)

**Comment by nvaytet** [comment]
What happens with axes ticks and labels for 1d and 2d plots? are they also invisible?

**Comment by jl-wynen** [comment]
Plotting and `sc.table` are broken again, they only output text with `VBox ...`
Maybe this is a fault on my side but I can't remember any changes I made to my setup since last time. But it shouldn't be related to this issue.

**Comment by nvaytet** [comment]
If you are on JupyterLab, you need to install/activate an extension for the widgets: https://github.com/matplotlib/ipympl#install-the-jupyterlab-extension

**Comment by jl-wynen** [comment]
Seems like my Conda env got reset. It's working now.

The plot looks fine. I's not nice that it uses a white background but that is normal Matplotlib behaviour and I wouldn't change that. But somehow the `logx` and `logy` buttons are different from the rest. Are they custom made and the others part of the default Matplotlib widget?
![plot](https://user-images.githubusercontent.com/11393224/101737323-fdbdaf80-3ac4-11eb-88e5-0043d631e77f.png)

Tables are kind of funny. The contents start out looking ok. But when I hover over them with the mouse, they turn light blue with white text (in the middle of the picture). And then they keep a white background afterwards.
The table headers (both ('Coords, 'Data') and ('Values', 'Values', Values', 'Values', 'Variances') in this case) have light backgrounds with light text from the start.
And the background under '1D Variables' was white from the beginning.
![table](https://user-images.githubusercontent.com/11393224/101737505-42e1e180-3ac5-11eb-85d5-6e4d5f9ac07b.png)
