### ISSUE TITLE
HTML repr should mark bin-edge attrs

### ISSUE THREAD

**Issue by nvaytet** [scipp/scipp#1454]
Currently, the following code
```Py
sc.DataArray(
    coords={'x': sc.Variable(['x'], values=np.arange(10), unit=sc.units.m),
            'lab': sc.Variable(['x'], values=np.arange(11), unit=sc.units.m)},
    attrs={'attr': sc.Variable(['x'], values=1.1*np.arange(11), unit=sc.units.m)},
    data=sc.Variable(['x'], values=np.random.random(10), unit=sc.units.counts))
```
produces
![Screenshot at 2020-12-09 19-33-30](https://user-images.githubusercontent.com/39047984/101671900-7127d880-3a55-11eb-9380-8be982a482de.png)
`attr` should be marked as a bin-edge attr in the `repr`

**Comment by jl-wynen** [comment]
I think this is not completely fixed:
```.py
da = sc.DataArray(
    data = sc.array(dims=['x'], values=np.random.random(7)),
    coords={
        'x': sc.array(dims=['x'], values=np.linspace(1.0, 2.0, num=8), unit=sc.units.m)})
da['x', 1.5*sc.units.m]
```
![HTML-repr-slice](https://user-images.githubusercontent.com/11393224/103913754-31faaf00-5109-11eb-8f05-78fdaabc7124.png)

Works for a slice, e.g. `da['x', 1.5*sc.units.m:2.5*sc.units.m]`

**Comment by jl-wynen** [comment]
The cases that were missed by the first PR are all scalars.  In the above example, the only reason why I expected attribute `x` to be marked as bin-edge is that it originally comes from an (aligned) coord. So in other words, it depends on what the DataArrayView views. It does not make much sense to display different things based on the underlying container instead of the actually observable properties of the view.
With scalars, it is maybe meaningless to talk about 'bin-edges' in the first place.

I'm suggesting to not change anything and close this issue. Do you agree?

**Comment by jl-wynen** [comment]
@SimonHeybrock @nvaytet @OwenArnold Any oppinions?

**Comment by SimonHeybrock** [comment]
I think the common case where this shows up is when we select a single bin from some data, e.g.:

```python
bin = data['spectrum',17]['tof',40]
```

Not marking `tof` (originally a coord, but converted to attr by slicing) as bin edges would be confusing.

I don't think it is meaningless at all. For a scalar bin edges are telling use "this measured value is valid between here and there". You are right tht we do not have a 100% consistent way of knowing which coords are edges, but in practice I feel we have 10x more cases where scalars have edges, as opposed to cases where something may get wrongly marked as edges.

**Comment by jl-wynen** [comment]
Does that mean you would mark _all_ attributes with 2 elements as bin-edges (in scalars)? Otherwise I see no way of selecting which ones to mark because then we would need to follow the internal pointer to the underlying DataArray. (Is this even possible in Python?)

**Comment by SimonHeybrock** [comment]
Yes, I would. I think in general coords with more dimensions that data *only* show up when we have bin edges. Everything else seems like weird edge case.
