### ISSUE TITLE
Plotting using attrs as axes dimension

### ISSUE THREAD

**Issue by nvaytet** [scipp/scipp#1455]
Currently, using attrs as the variable to use for coordinate axes for plotting fails, as the plotting function only looks inside the `coords`:
```Py
d = sc.DataArray(
    coords={'x': sc.Variable(['x'], values=np.arange(10), unit=sc.units.m)},
    attrs={'attr': sc.Variable(['x'], values=1.1*np.arange(11), unit=sc.units.m)},
    data=sc.Variable(['x'], values=np.random.random(10), unit=sc.units.counts))
plot(d, axes={'x': 'attr'})
```
yields
`RuntimeError: Requested dimension was not found in input data: attr`

This is probably the place to make the change: https://github.com/scipp/scipp/blob/master/python/src/scipp/plot/sciplot.py `_process_axes_dimensions()`

**Comment by SimonHeybrock** [comment]
This should be simple to fix, using `array.meta` instead `array.coords` to access axis labels?

**Comment by nvaytet** [comment]
Yes, that should do it
