### ISSUE TITLE
conda build and distribution for mantid-framework on OSX.

### ISSUE THREAD

**Issue by OwenArnold** [scipp/scipp#1465]
Current temporary osx distribution solution is to build scipp into the mantid workbench and release that. Some outstanding issues around that approach are discussed here #1196

This issue is for generating a full conda `mantid-framework` package for OSX that solves a number of problems we currently have:

* Mantid distribution uses bundled python with is very problematic on the mac. Scipp has to work with that bundled python.
* Related to above - need for "patching" of MantidWorkbench after installation (install_jupyter and run scripts required) to work around Issues with plotting with current package.
* The mantid project has not agreed in any way to adopt or distribute scipp, so the whole current process is unofficial. 
Conda on the other hand is a target distribution mechanism for Mantid so we should get help with this.
* Gives scipp as single mostly combined distribution mechanism for linux and osx (and a future pathway for windows)

Will become urgent within the coming 6 months.

**Foreseen TODO**

1. ~~FrameworkManager -> cannot locate instrument directory. Seems to carry build paths not install paths.~~ 
1. ~~Simple API has no Algorithms, could be located to instrument issue described above.~~
1. ~~Fix rpath problem for api to geometry.~~
1. ~~Fix CMAKE hacks in Framework for Workbench variables. Should be set in Darwin setup.~~
1. ~~Clean up new Framework Only flag usage in Mantid.~~
1. ~~Run all Mantid python tests on package?~~
1. ~~Check new recipe still works with linux~~
1. ~~Port recipe changes to https://github.com/scipp/mantid_framework_conda_recipe~~
1.  ~~Put test package on anaconda cloud and make dependency in scipp (osx) - start by updating the scipp-developer yaml file (or just use mantid specific one). Build Then run all unit tests and notebooks on osx.~~
1. ~~Create azure setup for the above mantid_framework_conda_recipe to be manually run.~~

**Comment by nvaytet** [comment]
Fixed via https://github.com/scipp/mantid_framework_conda_recipe/pull/1
