### ISSUE TITLE
Problematic coord -> edge-coord conversion in plot model

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1469]
`model.py` converts non-edge coord to edges. This is problematic for some implementations of `ResamplingModel`. Can we move this to a better place?

**Comment by nvaytet** [comment]
Maybe this can be pushed back to 0.6?

**Comment by SimonHeybrock** [comment]
Possibly, since now the "hack" was generalized. But it may be that we find it causes issues. I'll leave it for now, but will be happy to push it back if we don't encounter instances where things don't work.
