### ISSUE TITLE
Customisable printing

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#1472]
It would be nice if we could customise how Variables are printed. Sometimes it is not enough to see just four elements and iterating through them manually is a lot of work, especially for arbitrary shapes.
In Python there are ways to print all data in a Variable: using `sc.table` or grabbing the underlying array and use Numpy to print it. The latter doesn't include the meta data in the Variable and the former only works in Jupyter. In C++ there is no way of doing this without either hacking `array_to_string` or writing a custom loop.

I propose adding a mechanism similar to `numpy.set_printoptions` which allows a user to set, e.g. how many elements are printed, the precision, and potentially more options. It wouldn't be pretty because it needs a global Variable. But at least for debugging it would be a great help.

(Alternatively, one could move all formatting functions into use a formatter object and avoid the global variable this way. But it would require bigger changes to the existing code.)

**Comment by SimonHeybrock** [comment]
There is a singleton dealing with some of the formatting anyway, so we may use that or similar to configure this.

**Comment by SimonHeybrock** [comment]
Related: #2556.

**Comment by SimonHeybrock** [comment]
Partially related: We have to trim down the length of exceptions. Frequently exceptions result in whole data arrays being printed, including dozens of attributes, which is very unreadable. Should be exclude or abbreviate this?

**Comment by jl-wynen** [comment]
Do exceptions use `repr` or `str`? One of them is supposed to be brief and the other 'complete'.

**Comment by SimonHeybrock** [comment]
- We should distinguish between `__str__` and `__repr__`.
- Extend `__format__`, continuing work from #2556.

**Comment by jl-wynen** [comment]
How about we use the following in `__format__` (sorry for the format grammar notation). See also
https://docs.python.org/3/library/string.html#format-string-syntax
https://docs.python.org/3/library/string.html#format-specification-mini-language

```
format_spec ::= [scipp_spec][:python_spec]
```
`python_spec` would be applied to the elements and `scipp_spec` affects the variable, etc., overall.
For example:
```python
f'{var}'  # normal, calls str
f'{var:c}'  # like now, uses compact formatting for the variable
f'{var::.2f}'  # formats the outer variable in the default way (like str) but each element is formatted using f'{elem:.2f}', i.e. as a float with precision=2
f'{var:a: +5.3e}'  # hypothetical a for 'array only' and each element is formatted as f'{elem: +5.3e}'
```

This would be very flexible and would separate our own format spec from the standard one for int, float, etc. (In particular our `c` clashes with `c` for int).
Implementing this in Python should be quite simple because it can forward to the standard formatter for the elements. But This would also mean rewriting the whole string formatting in Python.
On the other hand, doing this in C++ would be a lot of complicated work because we would have to re-implement Python's formatting for int, float, etc.

How can we avoid duplicating code to support `__format__` in Python and also `to_string` in C++ (needed at least for exceptions)?

**Comment by SimonHeybrock** [comment]
I like the nested-spec idea!

I would not worry much about the C++ duplication for now. The task here is mainly for `Variable`, so there is relatively little duplication, I believe?

**Comment by jl-wynen** [comment]
Ok. I can make a prototype and see how much I need to reimplement.

**Comment by jl-wynen** [comment]
Also, I came up with a refined spec:
```
format_spec ::= [scipp_spec] [":" python_spec]
python_spec ::= (https://docs.python.org/3/library/string.html#format-specification-mini-language)
scipp_spec  ::= [selection][#length][type]
slice       ::= "<" | ">" | "^"
length      ::= digit+
type        ::= "v" | "e" | "c" | "s"

selection: select which elements to show
    <: :length
    >: -length:
    ^: :length//2 , -length//2:

length: number of elements to show

type:
    v: array of values
    e: array of variances
    c: compact  (Variable only)
    s: summary (dtype+unit+sizes but not values)
```

This is just a suggestion for now. But I think it covers the most relevant use cases.

**Comment by g5t** [comment]
:+1: For the nested format specification idea

@jl-wynen You said `c: compact  (Variable only)` but did you mean `c: compact [Variable(Error) notation]`?
That is, will the `c` format specification stay the same?

**Comment by jl-wynen** [comment]
> @jl-wynen You said c: compact  (Variable only) but did you mean c: compact [Variable(Error) notation]?
That is, will the c format specification stay the same?

I meant that it can only be used with variables, not with data arrays, etc. I don't intend to change the spec for it, In fact, I think I won't even support nested specs for it unless there is a need.

**Comment by jl-wynen** [comment]
Closing for now because the most relevant parts have been implemented.
