### ISSUE TITLE
Use log bins for log scales on 2d images

### ISSUE THREAD

**Issue by nvaytet** [scipp/scipp#1473]
When using log scale on a 2d image axis, the plot current resamples on linear bins, and then lets matplotlib apply the log scaling on the image. This makes some very large pixels to the left and very small pixels to the right.

We should resample on log bins, and use `pcolormesh` instead of `imshow` to we can display evenly sized pixels on an axis which has log-scale ticks and ticklabels.

**Comment by SimonHeybrock** [comment]
Done in plopp.
