### ISSUE TITLE
Clang fails to link tests with dynamic libraries

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#1501]
When building the tests with clang and linking scipp components as dynamic libraries, I get lots of `undefined reference to X` errors. Compilation works without errors. The main dynamic library can be linked as well.

I configured the build with
```
cmake .. \
  -DCMAKE_CXX_COMPILER=clang++ \
  -DCMAKE_C_COMPILER=clang \
  -DCMAKE_BUILD_TYPE=Debug \
  -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=OFF \
  -DDYNAMIC_LIB=ON
```
and have
```
$ clang++ --version
clang version 11.0.0
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

LTO has no impact.

Everything works when `-DDYNAMIC_LIB=OFF`.

**Comment by SimonHeybrock** [comment]
Should be fixed with recent move to dyn libs by default.
