### ISSUE TITLE
conda-build and distribution for mantid-framework on windows

### ISSUE THREAD

**Issue by OwenArnold** [scipp/scipp#1515]
This seems less critical than #1465 given the widespread use of macs amongst our users, however it is worth highlighting that with this in place, we can move fully to a conda solution for all dependent packages `neutron`, `ess`, `ess-notebooks` etc. Possibility the most appealing aspect of this is that at facilities where windows is more common, users would be able to make use of scipp for neutron scattering.

This is something the mantid team might eventually solve, but timescales for work on dependency management are quite signifiant at present for Mantid given the desire to completely redesign the deployment/development architecture.

**Comment by SimonHeybrock** [comment]
Closing, as a `mantid-framework` conda package should be available from upstream in the near future.
