### ISSUE TITLE
Minor issues with cut surfaces in Instrument View

### ISSUE THREAD

**Issue by OwenArnold** [scipp/scipp#1524]
1. Should get units reported with slice position. Good example here. `position` has units `m` but not reported no slice viewer. https://scipp.github.io/tutorials/neutron-diffraction.html Note in the image below the `position` is 0.5 with no units.
![image](https://user-images.githubusercontent.com/1109536/104192206-6971a000-5416-11eb-9231-962b557be2b2.png)
2. `Position` is the name of control whether you are working with `cartesian`, `spherical` or `cylindrical` controls. In the case of `spherical` it useful to know that this is say `radius` and not `diameter`

**Comment by nvaytet** [comment]
@OwenArnold 
Regarding point 1:
If you are plotting in the instrument view, and the positions vector as a unit, then it makes sense to show a unit next to the cut slider. If you are showing a value isosurface, then it also makes sense to have the unit of the data.

However, if you are plotting dense data in 3d, and you make a spherical or cylindrical cut, and the 3 coordinate axes don't have the same units, then the unit of the radius is ill-defined.
Should we just hide the unit in this specific case, and show the unit in all the other cases?

**Comment by OwenArnold** [comment]
> then the unit of the radius is ill-defined.

Yes interesting. I'm not sure our unit system will handle sqrt(a^2 + b^2 + c^2) or equivalent for the cylindrical case where a, b and c could all potentially be different.

> Should we just hide the unit in this specific case, and show the unit in all the other cases?

I think that would be better than what we have so I would say yes.

**Comment by OwenArnold** [comment]
I should also have said for point 2: That we should handle the `value` case just in case that gets forgotten, but you mention it above, so I think it's still on your radar.
