### ISSUE TITLE
Plots not show in docs

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#1526]
~~The plots in User Guide > Binned Data > Filtering (https://scipp.github.io/user-guide/binned-data/filtering.html) are missing. They show up when running the notebook manually.~~

Actually, they seem to be missing everywhere in the docs.

**Comment by SimonHeybrock** [comment]
I can see the plots.

**Comment by nvaytet** [comment]
Have you tried re-loading the page in your browser?

**Comment by jl-wynen** [comment]
I had blocked scripts from unpkg.com Apparently they are needed to insert the plots.
I can see them now.

**Comment by nvaytet** [comment]
All plots are now widgets, so that's possibly why...
