### ISSUE TITLE
Freeze when zooming 2D plot of binned data

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#1527]
In the plot generated by this: (taken from https://scipp.github.io/user-guide/binned-data/filtering.html)
```.py
import numpy as np
import scipp as sc
from scipp.plot import plot

np.random.seed(1)
tof_max = 10
width = tof_max/20
sizes = 4*np.array([7, 3, 3, 5])
size = np.sum(sizes)

table = sc.DataArray(data=sc.Variable(dims=['event'],
                     values=np.random.normal(0, 1, size)),
                     coords={'tof': sc.Variable(dims=['event'],
                                                values=np.arange(0., size))})
end = sc.Variable(dims=['x'], values=np.cumsum(sizes))
begin = end.copy()
begin.values -= sizes
events = sc.DataArray(
    data=sc.bins(begin=begin, end=end, dim='event', data=table),
    coords={'x': sc.Variable(dims=['x'], values=np.linspace(0, 1, num=4))})

tof_bins = sc.Variable(dims=['tof'], values=np.linspace(0, tof_max, num=100))
binned_events = sc.bin(events.bins, [tof_bins])
plot(binned_events)
```
When I zoom in, the plot freezes and I can't execute any cells.
The zoom rectangle stays on screen:
![frozen_plot](https://user-images.githubusercontent.com/11393224/104206929-70a5a780-5430-11eb-978e-b579b2c61bc6.png)

There are no messages printed to terminal. The kernel seems be be busy, it uses 100% of a CPU core.

This does not always happen immediately, it depends on where I zoom in. But when zooming sufficiently deep, it always seems to happen.

I suspect that this is an issue with `transform` and/or `MultiIndex` but I haven't dug into this, so this is just an intuition. Could be related to having empty bins and  #1479

**Comment by SimonHeybrock** [comment]
Also files with a loaded event data file:
```python
data = sc.neutron.load(filename='PG3_4844_event.nxs')
data.plot()
```
