### ISSUE TITLE
Functions should be agnostic about tuple or list

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#1541]
Some function arguments are required to be either a tuple or a list. But both should be accepted. For example, `sc.reshape`:
```.py
var = sc.Variable(dims=['x'], values=np.arange(10.0))
sc.reshape(var, dims=['x', 'y'], shape=[5, 2])
```
This code raises a `TypeError` because `shape` must be a tuple.

Please add other cases here if you know any:
- ~~[ ] `reshape`~~
- [] constructors: `sc.Variable(dims=('x',), values=(0,))`, `dims` work but `values` and `variances` don't

Note that `dims` in both the Variable constructor and `reshape` accept both list and tuple.

**Comment by SimonHeybrock** [comment]
`reshape` does not exist any more, can you please check if there are other broken examples? If not, please close.

**Comment by jl-wynen** [comment]
Only found a minor case. This might might not be worth fixing because it is not very relevant in practice and could make the bindings even more messy.
