### ISSUE TITLE
Integration tests with compat layer in CI

### ISSUE THREAD

**Issue by OwenArnold** [scipp/scipp#1563]
For neturon scattering, the ability to use mantid under-the-hood is critical at present, this interface must not break.

As a result of the memory utilisation improvements in `test_mantid.py` and `mantid.py` introduced here https://github.com/scipp/scipp/pull/1556, we can now run the compat tests with < 13 GB of ram. 

1. Run these tests as part of the test section in the `mantid-framework` conda recipe. i.e gives us the ability to see if there is a fault in the interface between mantid-scipp
1. Template the azure pipeline we use for conda building `mantid-framework` and refactor the manual (release.yaml) to use it.
2. Using the above template create a new pipeline `master` which does not publish (probably just archive). Set this to be automated (maybe nightly). Gives us the ability to quickly determine when things break!

**Comment by SimonHeybrock** [comment]
I believe these tests *are* running (and have been for a while now).
