### ISSUE TITLE
Binned operation comparison for scipp-mantid docs

### ISSUE THREAD

**Issue by OwenArnold** [scipp/scipp#1578]
#1573 is introducing dense - bin operation comparisons

We should do a similar thing for scipp - mantid comparisons in `from_mantid_to_scipp.ipynb`

**Comment by SimonHeybrock** [comment]
We got few questions about this recently. I think we should focus efforts on documenting scipp, not documenting differences to another software package, since our main focus is not the userbase of Mantid (any more)?
