### ISSUE TITLE
reshape for DataArray

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1588]
Currently we only support this for variables.

Note that there is a rough implementation at https://github.com/scipp/ess-legacy/blob/d9b3b4f543204805baf808244ddd1c88d4fdc93e/sans/loki.py#L47-L71, but this makes a copy. In principle it should be possible to do this without making copies, if implemented on the C++ side.

**Comment by nvaytet** [comment]
Question: when you reshape a Dataset item, do you then reshape all the other items that depend on the same dimensions?

**Comment by SimonHeybrock** [comment]
> @SimonHeybrock When you reshape a Dataset item, do you then reshape all the other items that depend on the same dimensions?

Yes, see linked code.

**Comment by nvaytet** [comment]
Yes but that code is for a DataArray, not a Dataset. I meant all the other items in the Dataset that have the same dimensions?
Doing
```Py
da = sc.DataArray(...)
sc.reshape(da)
```
in unambiguous, and so is
```Py
ds = sc.Dataset(...)
sc.reshape(ds)
```
(you just reshape all the items).
But what do you do when
```Py
ds = sc.Dataset()
ds["a"] = sc.array(dims=['x'], values=some1darray)
ds["b"] = sc.array(dims=['x', 'y'], values=some2darray)
sc.reshape(ds["a"], ['tof', 'z'], [ntof, nz])
```
do you also reshape `ds["b"]`? And what about
```Py
sc.reshape(ds["a"], ['y', 'z'], [ny, nz])
```
when `ds["b"]` already contains `"y"`?

**Comment by nvaytet** [comment]
You just don't support reshaping via an item i guess

**Comment by SimonHeybrock** [comment]
We do not support in-place reshape for now, I think? And yes, reshaping via an iptem should not be supported.

**Comment by nvaytet** [comment]
I'm not sure it's as easy to implement as in the snippet you link to, as I believe it is only valid when you are reshaping a single dimension into multiple ones.

If you use the same syntax as the one for a Variable `reshape`, where you can reshape all dims in one go, e.g.
```Py
var = sc.array(dims=['x', 'y'], values=np.random.random([20, 6]))
sc.reshape(a, dims=['i', 'j', 'k'], shape=(10, 4, 3))
```
which is a very valid thing to do.

Now, if you want to do this kind of operation on a DataArray, in the case where you have a coordinate with dimensions `['x', 'y']`, it's also easy to know what to do. However, in the case where
```Py
da = sc.DataArray(data=sc.array(dims=['x', 'y'], values=np.random.random([20, 6])),
    coords={'x': sc.array(dims=['x'], values=np.arange(20)),
            'y': sc.array(dims=['y'], values=np.arange(6))})
sc.reshape(da, dims=['i', 'j', 'k'], shape=(10, 4, 3))
```
then what do you do with the coordinates?
The same applies the other way round, if you want to do
```Py
sc.reshape(da, dims=['z'], shape=(120,))
```

I'm starting to think that to do a reshape, you have to specify which dim(s) you want to reshape.
Something like
```Py
sc.reshape(da, old_dims=['x'], new_dims=['i', 'j'], shape=(10, 2))
```
would give you something with dims `['i', 'j', 'y']` and shape `(10, 2, 6)`.
Coordinate `x` would now be 2D (`['i', 'j']`), but then it's not even clear what its name should be?
`'i'` or `'j'`? Or a combination of the 2?

Aside from that, to get the reshape example for the Variable, one would now have to do it in 2 steps, but maybe that is acceptable?

On the other hand, if you try to do
```Py
da = sc.DataArray(data=sc.array(dims=['x', 'y'], values=np.random.random([20, 6])),
    coords={'x': sc.array(dims=['x'], values=np.arange(20)),
            'y': sc.array(dims=['y'], values=np.arange(6))})
sc.reshape(da, old_dims=['x', 'y'], new_dims=['z'], shape=(120,))
```
again, what happens to the coords?

Maybe conceptually, it makes little sense to keep the coords at all?
Should we just discard any coord that contains one of the dims that is being reshaped?

Note that the same goes for masks which can also be 1d for multi-d data.
