### ISSUE TITLE
Binned Data Representation

### ISSUE THREAD

**Issue by OwenArnold** [scipp/scipp#1594]
We have discussed overhauling the html (and string representations) for binned data. This will not happen until before release 0.5. However looking again at the docs, for example https://scipp.github.io/user-guide/binned-data/binned-data.html, I am concerned that the representation offers little information to the casual user to indicate they are working with binned data. The user might take hints that the data is itself a `DataArrayView` but this seems too abstract, - I propose we insert an additional `(binned data)` message  alongside the data, in a similar way that we are able to mark `bin edges`.

**Comment by SimonHeybrock** [comment]
You mean in the short data representation, replacing the useless truncated part of the summary?

<img width="756" alt="image" src="https://user-images.githubusercontent.com/12912489/105668065-e1db6500-5edc-11eb-90af-3e59a640c9fb.png">

**Comment by SimonHeybrock** [comment]
Reactivating some old code from the previous event-data formatting, I can to this:
<img width="837" alt="image" src="https://user-images.githubusercontent.com/12912489/105671261-b491b580-5ee2-11eb-9715-9cf8e6722fa1.png">

Any better ideas on what to print instead of the length?

**Comment by OwenArnold** [comment]
> Reactivating some old code from the previous event-data formatting, I can to this:
> <img alt="image" width="837" src="https://user-images.githubusercontent.com/12912489/105671261-b491b580-5ee2-11eb-9715-9cf8e6722fa1.png">
> 
> Any better ideas on what to print instead of the length?

I'm not sure what other information we have that would be more suitable. Length seems like a good option given what we have to me.

**Comment by SimonHeybrock** [comment]
Other options may include the "columns" of the binned data, e.g., stating it contains `tof`, `pulse-time`, and data.
