### ISSUE TITLE
Difference between documented an actual behaviour for bins

### ISSUE THREAD

**Issue by OwenArnold** [scipp/scipp#1595]
This works as expected.
```python
buffer = sc.Variable(['x'], values=[1,1,1,2,1,1])
begin = sc.Variable(['x'], values=[0, 3])
sc.bins(begin=begin, end=(begin + 1 * sc.units.one), dim='x', data=buffer)
```

The docs for `end` param  of  `bins` says:
```
:param end: Optional end indices of bins, used for slicing `data`. If not
                provided this is assumed to be begin + 1.
```

So removing the end argument in the above, I would expect to get the same result, however, I get an error instead.
```
ValueError: __sizeof__() should return >= 0
```

**Comment by SimonHeybrock** [comment]
`bins` works fine, `to_html()` raises when getting the object size.

There is however a slight difference in the behavior: Not providing end sets `end` to `-1`, which on the C++ API (unlike Python) means a non-range-slice is made. So the items of the variable above a 0-D variable views, not 1-D views.

**Comment by SimonHeybrock** [comment]
Looking at this a bit closer, I think I have supported this in the data structure, but mostly ignored the option to have non-range-slice based bins when implementing operations. Unless we can think of an important applicatio for this, I would suggest:

- Remove support for non-range bin indices from `BinModelBase`. Fixing and testing all operations would probably be a larger effort now.
- Consider changing `sc.bins` without `end` to make bins that are contiguous, i.e., `end` is a shifted version of `begin` (concatenated the final size). This would require `begin` to be sorted, but it seem like a saner behavior.

**Comment by OwenArnold** [comment]
> Consider changing sc.bins without end to make bins that are contiguous, i.e., end is a shifted version of begin (concatenated the final size). This would require begin to be sorted, but it seem like a saner behavior.

You are suggesting the shift would result in no gaps?

**Comment by SimonHeybrock** [comment]
> > Consider changing sc.bins without end to make bins that are contiguous, i.e., end is a shifted version of begin (concatenated the final size). This would require begin to be sorted, but it seem like a saner behavior.
> 
> You are suggesting the shift would result in no gaps?

Yes, end of first bin would be given be begin of second bin, etc.
