### ISSUE TITLE
Slicing inconsistent with numpy

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#1602]
In slices, `end` < `begin` is not allowed:
```.py
sc.Variable(['x'], values=[1, 2, 3])['x', 2:1]
```
```
IndexError: end must be >= begin. Given begin 2 end 1
```

but in numpy this produces an empty array:
```.py
np.array([1,2,3])[2:1]
```
```
array([], dtype=int64)
```

**Comment by OwenArnold** [comment]
This doesn't seem like a huge problem - is there a practical place where this is needed at present?

**Comment by jl-wynen** [comment]
I'm the wrong person to ask about applications. But it is not unreasonable to have code that computes slices where `end` comes out less than `begin`. This would allow users to do this without manually testing.
Also, this is how slicing in basic Python and numpy works, so I think we should be consistent.
