### ISSUE TITLE
Plot empty data

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#1604]
Trying to plot empty variables produces a strange error:
```.py
plot(sc.Variable(['x'], values=[]))
```
```
ValueError: Axis limits cannot be NaN or Inf
```

Should either be more clear about the error or produce an empty plot like matplotlib.

The same happens with `DataArray`.

**Comment by nvaytet** [comment]
I would say it should raise a sensible error message. An empty plot is just useless

**Comment by nvaytet** [comment]
Maybe such a Variable should simply not exist?
It makes a variable with dims `['x']` and size 0.
You can't really do anything with it after that. You can't set `value` or `values`.

@SimonHeybrock what do you think?

**Comment by SimonHeybrock** [comment]
No, this is perfectly valid. You might not use it in practice, but if you have some code that dynamically computes slice thickness it can definitely occur. I think label-based indexing may be one example:
```python
range = var['x', 1.2 * sc.units.m, 1.3 * sc.units.m] # size 0 if there are no pointsin the range
```

**Comment by SimonHeybrock** [comment]
> You can't really do anything with it after that. You can't set `value` or `values`.

I just checked, setting values works fine for me, how did you try @nvaytet ?

```python
import scipp as sc
var = sc.array(dims=['x'], values=[1,2,3])
var['x', 1:1].values = []
```
