### ISSUE TITLE
Ownership model?

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1617]
- Current behavior is a bit like `std::vector`, where `push_back` invalidates iterators. Scipp views become invalidated when adding or removing items.
- Making things similar to Python is an advantage, e.g., teaching shared ownership, instead of different scipp behavior.
- If `Variable` and `Variable(Const)View` were unified, would we lose `const` handling in C++ (doing everything at runtime instead)?
- Would remove brittle `keep_alive` mechanisms in Python bindings?

Related issues:
- #1256
- #1176
- #1307 (potentially, depending on implementation choice in DataArray rewrite)
- #860 slicing with strides could be implemented by the rewrite.
- #847 transpose for data arrays should be much simpler to do

**Comment by jl-wynen** [comment]
Maybe it is possible to avoid surprises of accidentally modifying arrays if we had something similar to Rust's mechanism for mutable / immutable refs.
```.py
v = sc.Variable(['x'], values=np.array([1, 2, 3]))

r = v['x', 0:1]
r['x', :] = 0  # allowed
v['x', :] = 0  # not allowed, r currently has write access
print(v)  # in Rust: also not allowed because r has write access. Maybe too strict for us.
del r
v['x', :] = 0  # allowed, write permissions are back with v

cr = v['x', 0:1].const()  # syntax??
cr['x', :] = 0  # not allowed, as no write access
v['x', :] = 0  # in Rust: also not allowed because there is another ref. Maybe too strict for us.
```

Problems:
- These checks would have to be done at runtime which would be confusing / inefficient in C++.
- Unusual for Python.
- Potentially hard to track who references what and who can write / read.

**Comment by SimonHeybrock** [comment]
## Aspects to consider (in random order):

1. For binned data, non-owning binned data would become redundant/equivalent, which will make certain things easier.
2. Can we or should we avoid having `values` and `variances` (of the same `Variable`) pointing to the same buffer?
3. We may need non-owning variables (or slices), or need a new mechanism for implementing `groupby`. For number of slicing approach 1 million the current implementation (based on cheap `VariableConstView`) gets limited performance aready now. May have to find a mechanism to slice without taking buffer ownership.
4. Should we (optionally) support taking ownership of `numpy` buffers so copies can be avoided? This would require GIL handling which may severaly limit performance? If we keep this optional though it may be worth it? Is it as simple as making `element_array` and abstract base class, which can be implemented internally, or with an alternate implementation wrapping a Python buffer?


## How do we handle const-ness?

This is the key (open) question for me (on the C++ side). Consider:

```cpp
auto myfunc(const Variable &var) {
  // var.value<double>() += 1; // should not compile since `const`?
  auto shallow_copy(var); // shallow copies would be default
  shallow_copy.value<double>() += 1; // not `const` what should this do?
}
```

I see two options here:
- Allow modification. This would also happen on the Python side (since we don't have `const` there), so maybe not too much is gained by preventing this on the C++ side.
- When making a shallow copy of a `const Variable`, set a runtime flag which prevents modification (throws of attempted). This could get cumbersome though since `shallow_copy.value<double>()` would call the non-const overload above, even if we were only using this for a read. We might need a lot of const casts to add const in many places?

**Comment by SimonHeybrock** [comment]
As discussed on Friday, we need some sort of cheap slicing in particular for the implementation of `groupby`. My consludion then was that the mechanism taking ownership was too expensive and we need to keep the existing non-owning slicing mechanism, in parallel to the new one desribed in the prototype #1785. This would actually be a major complication of the design.

I believe I now found I much better and simpler solution for this:

- Provide a mechanism on the `Variable` API that allows for shifting/panning a view, e.g., by changing the offset or shape along a dimensions.
- This would simply change a handful of integer parameters in the variable rather than inflicting expensive `std:shared_ptr` copies.
- In `groupby` (each thread) would initially create a slice, but the iteration over all slices would be done by simply reconfiguring the variable returned by the intial slicing, rather than creating a new one.

There may be one or two other places where this mechanism would be used, potentially the `sort` implementation (which is slow anyway in many applications and may need rewriting, but this is a different story).

**Comment by SimonHeybrock** [comment]
The current implementation of `VariableConstView` is based on storing *two* `Dimension` objects (which store dim labels and shape), one for the "data dimensions" (the dimensioneso f the full underlying buffer), one for the view/slice dimensions.

In combination these to `Dimension` objects allow for defining slicing. In principle they could also be used for defining strides (see my comment in #860).

However, with the unification of `Variable` and `VariableView` it feels simpler to just store a *single* copy of dimension *labels*, *shape*, and *strides*. Whether the latter should be part of `class Dimensions` is unclear to me at this point.

Right now, I am trying to understand whether there is any scenario we can currently support using the two dimension classes, which would not be possible with having just strides? @jl-wynen you are the only one aside from me familiar with the internals of the relevant part if `transform` and `MultiIndex`. Can you think of anything that would cause trouble?
