### ISSUE TITLE
Find a better way to handle units

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1620]
# What?

- `boost::units` may be too inflexible.
- Need unit scales.
- Need more than hard-coded set of supported unit combinations.

# Requirements

- Support units with different scales, e.g., `m` and `km`.
  - Note that powers of 10 are *not* sufficient, e.g., since we may have `s` and `h`.
  - A single scale for a given unit is also not sufficient, e.g., for `uAh` (microampere hours).
- Need support for adding custom units, e.g., for "counts".
- Need some way of interoperability with `boost::units` so we can keep making use of their physical constants, unless we want to replace that as well.
- Playing nicely with common Python packages for units would be an advantage.
- Do we want to support `unit = None`, rather than using `dimensionless` for, e.g., `dtype=string`?

# Considerations

- There appears to be very few C++ runtime unit libraries (but many compile-time libs):
  - https://github.com/LLNL/units seems most mature?
  - https://github.com/martinmoene/PhysUnits-RT 
- Python options may include `pint` and `astropy`
  - Would make a C++ library depend on a Python library?
  - Would introduce GIL into *all* of our operations!?
- Writting something from scratch is most likely far from trivial, contrary to what one might think at first glance.
- Is there a better way to make a runtime wrapper of `boost::units` that is less restrictive than what we have currently? JIT?
- Is it useful to limit what units a dtype can have? For example, as mask (bools) does not make sense with anything but `dimensionless`. Maybe more trouble than what is gained from being restrictive?

**Comment by jl-wynen** [comment]
https://github.com/LLNL/units always converts to a common unit as far as I can tell.
```
std::cout << to_string(m*nm) << '\n';
// -> 9.99999971718068537e-10m^2
```
The regular units have only ~6 digits of precision. There are also 'precise units' with ~13 digits of precision. I tried to find a case where this breaks down and produces wrong units as a result of operations. But I could not find any. Still, we should be careful.

**Comment by SimonHeybrock** [comment]
Does it do the same for non-SI base, e.g., `J` and `meV` or `m` and `Angstrom`?

**Comment by jl-wynen** [comment]
Yes `eV` tends to be converted to `J` and `Angstrom` to `m` when combined with other units of the same dimension.

**Comment by SimonHeybrock** [comment]
What about mixed cases such as `uAh`? Does it cancel the `u` and `3600` from `h`?

**Comment by jl-wynen** [comment]
It creates `0.0036C`. So it creates the derived unit.

**Comment by jl-wynen** [comment]
This
```.cpp
auto b = micro*A*units::unit_from_string("h");
auto c = b * energy::eV / (micro*A);
```
gives `c = eV * h`. So it looks like it retains the 'hour' somehow. Maybe it doesn't actually covert after all.
