### ISSUE TITLE
Extract Ei and Ef from Mantid if possible

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1625]
For #1413 we require incident energy and final energy stored as coords. Unofrtunately extracting this information is non-trivial, since it is inconsistently stored:

See:
- `ws.getEMode()`
- `ws.getEFixed()`
- module `IndirectCommon` provides `getEfixed()`
- Related algorithms `GetEi` and `GetAllEi`.

**Comment by OwenArnold** [comment]
This does not sound like an easy problem - however, it seems like potential solutions to this should be made in Mantid rather than the scipp codebase. Alongside some automated testing, that would also better help ensuring that updates in Mantid don't break things.

**Comment by SimonHeybrock** [comment]
I don't think changing this in Mantid is feasible or a good use of our time since it would likely have little benefit, or make things worse, but adding changing from N to N+1 mechanisms for storing this info.

The structure of how this is stored in Mantid is given by files, and apparently there are instruments where it is not stored directly but computed from other logs and monitor information, see https://docs.mantidproject.org/nightly/algorithms/GetAllEi-v1.html and https://docs.mantidproject.org/nightly/algorithms/GetEi-v2.html.

I think we just need to make sure to extract the info that *is* there. I think we are already covering what is in experiment logs. What is missing is the parameters on the instrument, which are used for `Ef` (which depends on the detector or analyzer).

**Comment by OwenArnold** [comment]
I'm not suggesting making any change on the Mantid side to how this is stored, only the mechanism for reading the information. One might imagine a single python function that tries various ways to get the the Ei. As this feels like a Mantid internal, my suggestion is that the fetching code lives there, that way the logic/testing of the extraction does not unnecessarily live on the scipp side.

**Comment by SimonHeybrock** [comment]
There are already *two* Python functions (could find) that try to do this.
