### ISSUE TITLE
Extract data extents for a given dimension in python

### ISSUE THREAD

**Issue by OwenArnold** [scipp/scipp#1634]
A bit annoying to have to do this, but not having a method/property to provide it.
```python
va = sc.Variable(['x', 'y'], values=np.arange(100).reshape(20, 5))
dict(zip(va.dims, va.shape))['x']
```
@nvaytet

**Comment by nvaytet** [comment]
Actually, `xarray` calls this `sizes`: http://xarray.pydata.org/en/stable/generated/xarray.DataArray.sizes.html#xarray.DataArray.sizes

**Comment by OwenArnold** [comment]
Ok, so should enough to add this function on the python side and monkey patch it as a property onto our key scipp objects. That is how I think we should proceed with this at least. Other suggestions welcome.

**Comment by nvaytet** [comment]
I think i would just add it in here: https://github.com/scipp/scipp/blob/master/python/bind_data_access.h#L366

**Comment by nvaytet** [comment]
you can probably just return `self.dimensions()`?
