### ISSUE TITLE
Precompiled Headers

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#1640]
We can accelerate the build using precompiled headers. (This came up in https://github.com/scipp/scipp/pull/1638#issuecomment-770598230)

It is pretty simple to use them with CMake and get a big speedup. I added this to `units/CMakeLists.txt`:
```.cmake
target_precompile_headers(${TARGET_NAME} PUBLIC
  "include/scipp/units/unit.h"
  "include/scipp/units/dim.h")
```
With gcc 10.2 in a fresh build, this produced a speedup of 12s (8%) with 12 threads and 14min (25%) in a sequential build.
When modifying `variable/transform.h` and rebuilding, the speedup was 9s (10%) in the parallel build and 85s (20%) in a sequential build.

Unfortunately, this feature was only added in CMake 3.16 and we are using 3.13. However, we could enable it conditionally, if the user has a recent enough version.

**Comment by SimonHeybrock** [comment]
I have previously played with using https://github.com/sakra/cotire in Mantid. Was simple to setup and worked well, I think.

**Comment by jl-wynen** [comment]
In their README:
> The functionality provided by cotire has been superseded by features added to CMake 3.16. Support for pre-compiling and unity builds is now built into CMake. Thus, there will not be any further updates or support for this project.

**Comment by SimonHeybrock** [comment]
> In their README:
> 
> > The functionality provided by cotire has been superseded by features added to CMake 3.16. Support for pre-compiling and unity builds is now built into CMake. Thus, there will not be any further updates or support for this project.

👍 nice! I think we may be able to push our cmake version.
