### ISSUE TITLE
Naming convention for neutron-specific coords

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1642]
We have previously switched to the convention:
- use `_` for subscripts, e.g. `E_i` or `Q_x`.
- use `-` (hyphen) the separate words.

However:
- This conflics with same conventions from Nexus.
- Variable names do not match coord names, e.g., `pulse_time = data.coords['pulse-time']`
- Would not be compatible if keyword args for `__getitem__` where supported in the future, e.g., `data[pulse_time=4]`.
- Would not allow defining properties from dict entries, e.g., `data.pulse_time` to access `data.coords['pulse-time']`.

Dicussion:
- Should we use `_` instead?

**Comment by matthew-d-jones** [comment]
Are there reasons for sticking with hyphens other than these?
- no changes required
- nice to reserve _ for subscript

**Comment by nvaytet** [comment]
Yes I would say just go with underscore. The simple fact that the variable names can then be the same as the string is enough for me ;-)

**Comment by nvaytet** [comment]
and the consistency with Nexus is also important I would say

**Comment by SimonHeybrock** [comment]
> Are there reasons for sticking with hyphens other than these?
> 
>     * no changes required
> 
>     * nice to reserve `_` for subscript

No requiring so many SHIFT presses while typing? Not a strong argument I suppose. :)

**Comment by matthew-d-jones** [comment]
The names aren't consistent with NeXus anyway though: there's is no "pulse_time", "tof", etc in NeXus. But it sounds to me like the argument for switching to underscore is stronger anyway.

**Comment by SimonHeybrock** [comment]
> ~The names aren't consistent with NeXus anyway though: there is no "pulse_time", "tof", etc in NeXus. But it sounds to me like the argument for switching to underscore is stronger anyway.~
> Actually scrap that, it makes life easier for log names.

Do Nexus log names have naming conventions, or is this up to the facility? When converting files that were opened by Mantid Is see many camel-case run logs, are those non-standard, or did Mantid convert the names?

**Comment by matthew-d-jones** [comment]
There is no name field in NXlog and the group itself can be called anything. What is worse from our perspective is that NXlogs may exist in many different places in the file, for example ones related to sample environment may be in the sample group, log of chopper timestamps in the corresponding chopper group, etc. Finding them is no problem, but it means they may not have unique names.
In ISIS files pretty much all the NXlog groups are called "value", it is the parent group or maybe a dataset in the parent group that has a unique name. Mantid is probably converting the names, and probably getting the name to convert from a different place depending on the facility.

**Comment by SimonHeybrock** [comment]
> What is worse from our perspective is that NXlogs may exist in many different places in the file, for example ones related to sample environment may be in the sample group, log of chopper timestamps in the corresponding chopper group, etc.

I suppose this may be the reason why `xarray` supports attributes (different from what we call attributes) on all objects, including variables, so this things can be stored in the same location is the file?

**Comment by matthew-d-jones** [comment]
hmm, I hadn't considered the possibility of retaining the hierarchy of the NeXus file in the scipp data structure.

**Comment by SimonHeybrock** [comment]
> hmm, I hadn't considered the possibility of retaining the hierarchy of the NeXus file in the scipp data structure.

In fact, it is not really. I think a second problem is that scipp requires aligned coords and dimension extents for everything in a (scipp) dataset (which would correspond to a group in HDF5/Nexus I suppose).

**Comment by matthew-d-jones** [comment]
I thought attributes get around that?

**Comment by SimonHeybrock** [comment]
Not really. Attributes still have to have the same *shape* (dimension length), unless you want to store them as a Variable/DataArray nested in a 0-d (scalar) variable (which is what we commonly do).

**Comment by matthew-d-jones** [comment]
Ah yes.

For now in the loading code I'm using the NXlog group name. If they are not unique then I append a suffix and display a warning .
