### ISSUE TITLE
Use lengths for unit conversion

### ISSUE THREAD

**Issue by OwenArnold** [scipp/scipp#1672]
At present the unit conversion in scipp-neutron requires the positions of source, sample and detectors to perform the conversion. From this the primary and secondary flight path are calculated. 

We should allow the conversion to work off a total flight path "length" coordinate (dim spectrum or x, y etc).

* Imaging beamlines (for example) often back-calculate the flight path based on a known bragg reflection. This is the currently more urgent case.
* There can be differences between the physical and neuronic layout that are not accounted for easily by specifying the exact flight path.

Caveat: Taking this approach one would not be able to perform stop-flow experiments. This is a future consideration.

**Comment by OwenArnold** [comment]
Thinking about this some more - using scipp to store lengths potentially solves a major problem found in Mantid while evaluating Instrument 2.0. The L1 L2 paths are wavelength dependent for certain techniques. Presumably we can simply solve this with an additional dimension for wavelength on the L1, L2 coords (maybe makes sense as a nested dataset) and the use of `groupby` to do the lookup.

**Comment by OwenArnold** [comment]
I have queried the state of the Mantid path length plans.

* Primary problem relates to REFL (more details needed)
* Unhappy with separate neutron/physical setup
* Cannot properly carry the corrected L1/L2. You can apply at point of use via ConvertUnitsUsingDetectorTable (since deprecated) so does not form a good solution.
* There has been no full requirements gathering for this yet, but they plan to do this.

**Comment by SimonHeybrock** [comment]
If you simply stored the wavelength-dependence with the same binning as the data you don't need nesting or `groupby`. Not sure if that is too much overhead though.

**Comment by OwenArnold** [comment]
> If you simply stored the wavelength-dependence with the same binning as the data you don't need nesting or groupby. Not sure if that is too much overhead though.
We should ask Stuart Campbell around this as he first raised the problem about wavelength dependence in path length and I believe he has some experience of the problems for Direct Inelastic.

**Comment by SimonHeybrock** [comment]
> I have queried the state of the Mantid path length plans.
> 
>     * Primary problem relates to REFL (more details needed)

Should be solved by mechanism I am working on. It will be possible to specify incident beam direction and L1 directly, instead of deducing it from `source_position` and `sample_position`.

>     * Unhappy with separate neutron/physical setup

I recenty had a discussion on this with Gregory Tucker. I think our conclusion was that we should indeed store the physical positions (including analyzer positions). However `scippneutron.convert` would probably make no attempt at deducing `scattering_angle` and `L2` from this since it may be very complicated. Instead, `convert` will provide a mechanism to use those directly, either as extra coords or via args passed to `convert`.

>     * Cannot properly carry the corrected L1/L2. You can apply at point of use via ConvertUnitsUsingDetectorTable (since deprecated) so does not form a good solution.

Should hopefully be solved by new mechanism.

**Comment by OwenArnold** [comment]
> Should be solved by mechanism I am working on. It will be possible to specify incident beam direction and L1 directly, instead of deducing it from source_position and sample_position.

I'm not sure how relevant this is for this (maybe more of a down-stream instrument/techinque thing), but for reflectometers at isis, they typically might not trust the readings from EPICS relating to motor positions etc. They therefore use Snell's law in some combination with the spectral/transmission lines from the detector to calibrate the setup and determine exact incident and final scattering angles.

**Comment by SimonHeybrock** [comment]
The plan is that parameters can be overridden at any stage, so this should also be covered.
