### ISSUE TITLE
Formatting with unicoded units is off

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#1675]
It looks like when printing Variables, the width of unicode characters is based on the number of bytes, not characters:
```
  <scipp.Variable>          datetime64  [s]              ()  [1970-01-01T00:02:03]

  <scipp.Variable>          datetime64  [µs]            ()  [1970-01-01T00:00:00.000123]

  <scipp.Variable>          datetime64  [ns]             ()  [1970-01-01T00:00:00.000000123]
```
Fixing this would require a proper unicode library if done in C++. So maybe not feasible / worth the effort.

**Comment by SimonHeybrock** [comment]
Seems complicated indeed (https://stackoverflow.com/questions/4063146/getting-the-actual-length-of-a-utf-8-encoded-stdstring). For keeping our backlog manageable I'll close this, feel free to reopen if you think it is important and consider it likely that it would get fixed.
