### ISSUE TITLE
clang warnings

### ISSUE THREAD

**Issue by nvaytet** [scipp/scipp#168]
At the moment there are several warning that are generated at compile time when using `clang`:
```
/home/travis/build/mantidproject/dataset/src/variable.cpp:1187:10: warning: 
      redundant move in return statement [-Wredundant-move]
  return std::move(b);
```
```
/home/travis/build/mantidproject/dataset/test/dataset_test.cpp:693:5: warning: 
      explicitly assigning value of variable of type 'Dataset' to itself
      [-Wself-assign-overloaded]
  a /= a;
  ~ ^  ~
```
```
/home/travis/build/mantidproject/dataset/exports/dataset.cpp:734:21: warning: 
      explicitly assigning value of variable of type 'const
      pybind11::detail::self_t' to itself [-Wself-assign-overloaded]
      .def(py::self -= py::self, py::call_guard<py::gil_scoped_release>())
           ~~~~~~~~ ^  ~~~~~~~~
```

We should try to remove them.

**Comment by dtasev** [comment]
Note about: `py::self -= py::self` and `a /= a`. There is an issue, for the first case, in the pybind repo: https://github.com/pybind/pybind11/issues/1893. They ended up filing a LLVM bug report https://bugs.llvm.org/show_bug.cgi?id=43124. I would say this also applies in our case. It can be suppressed, [but it doesn't look pretty](https://github.com/mosra/magnum-bindings/blob/1ec72697322715ce1d79cdd2eb22f11c1a6fc0af/src/python/magnum/math.vector.h#L99-L106).

**Comment by DanNixon** [comment]
Another one I've noticed recently:
```
In file included from /home/dan/git/scipp/scipp/core/histogram.cpp:9:
/home/dan/git/scipp/scipp/core/include/scipp/core/transform_subspan.h:30:10: warning: moving a local object in a return statement prevents copy elision [-Wpessimizing-move]
  return std::move(ret);
         ^
/home/dan/git/scipp/scipp/core/include/scipp/core/transform_subspan.h:30:10: note: remove std::move call here
  return std::move(ret);
         ^~~~~~~~~~   ~
1 warning generated.
```

I didn't just fix this as the commit that introduced it apparently fixed MSVC issues that I have no way to test.

cc @dtasev

**Comment by dtasev** [comment]
Might be just the `unique_ptr` that is important. I'll run the tests without the `std::move` and if they pass it should be OK to remove it

**Comment by SimonHeybrock** [comment]
I believe these have been fixed in https://github.com/scipp/scipp/pull/844.
