### ISSUE TITLE
Plotting eigen types

### ISSUE THREAD

**Issue by OwenArnold** [scipp/scipp#1688]
`plot` fails to plot (as expected), but error message is not incredibly useful. Could we check, report on types that cannot be plotted earlier with a more useful message:

examples
```python
x = sc.Variable(dims=['x'], dtype=sc.dtype.vector_3_float64, values=np.arange(30).reshape(10, 3))
plot(x)
```

```python
x = sc.Variable(dims=['x'], dtype=sc.dtype.matrix_3_float64, values=np.arange(90).reshape(10, 3, 3))
plot(x)
```

**Comment by nvaytet** [comment]
When you have vectors in a coordinate, the plot works (it uses a tickformatter on the axis ticks to replace the normal numbers with the 3 component tuple).
e.g.
```Py
d = sc.Dataset()
N = 10
d.coords['x'] = sc.Variable(['x'],
                            values=np.arange(30).reshape(10, 3),
                            unit=sc.units.m,
                            dtype=sc.dtype.vector_3_float64)
d["Sample"] = sc.Variable(['x'],
                          values=np.random.random(N),
                          unit=sc.units.counts)
sc.plot(d)
```

The simplest is probably, as you suggest, to fail cleanly on these types, but if we want to get this to work it should be possible, along the same lines (apply a tick formatter also to the y axis).
