### ISSUE TITLE
Scipp forces numpy version 1.15?

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1700]
From Torben:
> It seems that scipp_dev dictates that numpy remains on version 1.15.something. While scipp can work with numpy 1.19 or even 1.20. So if I in the scipp_dev yml file set numpy=1.19 -  conda still picks a lower version (the 1.15).

Our `yml` says `numpy>=1.15.3`, why is not it allowing use of a later version?

**Comment by nvaytet** [comment]
No idea, I thought you had set that rule.

**Comment by nvaytet** [comment]
Could it be a formatting issue in the `yml`? In the `scipp-developer.yml` there is a space between `numpy` and `>=`.
I don't know if that is allowed?

**Comment by nvaytet** [comment]
Maybe it comes from the `mantid-framework` instead of `scipp`?
https://github.com/scipp/mantid_framework_conda_recipe/blob/master/conda_build_config.yaml#L5

**Comment by matthew-d-jones** [comment]
1.15 is a result of pinning numpy version in the mantid_framework recipe. Attempting to use a more recent version in the recipe results in failure to find libboost library at runtime during the conda build process for mantid_framework. It looks like a different package for the same boost version may be being picked up when the numpy version is changed, perhaps one of the packages is broken?
