### ISSUE TITLE
Strange result in arithmetic between Variable and numpy array

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#1740]
```.py
v = sc.Variable(['x'], values=np.arange(4))
a = np.arange(-2, 0)
print(v + a)
```
prints
```
[  <scipp.Variable>          int64      [dimensionless]  (x)  [-2, -1, 0, 1]
   <scipp.Variable>          int64      [dimensionless]  (x)  [-1, 0, 1, 2]
]
```

Is this intentional or desirable? Seems pretty surprising to me.

Something similar happens with the other operators.

**Comment by SimonHeybrock** [comment]
I have no clue how this could happen? Some odd casting/implicit conversions in our Python bindings, maybe?

**Comment by SimonHeybrock** [comment]
Ok, I figure out what is happening. Numpy arrays can be constructed from variable (this is a 0-D array):
<img width="513" alt="image" src="https://user-images.githubusercontent.com/12912489/110080160-63e76500-7d8a-11eb-8926-2dc9070b06a5.png">

When adding to another array this then broadcasts, i.e., it adds the scalar numpy array (containing a variable) to the first element of `a` and to the second element of `a`:

<img width="578" alt="image" src="https://user-images.githubusercontent.com/12912489/110080293-88dbd800-7d8a-11eb-9233-5e311fdb6b23.png">
