### ISSUE TITLE
Remove operator bool from Variable and Dataset

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#1741]
`operator bool` Variable and Dataset checks if those contain any data or if the internal pointer is `nullptr`. That is not very useful for a user (is it even possible to reach that state and why?)
But the operator is dangerous, for instance
```.cpp
static_cast<bool>(is_approx(a, b, tol))
```
_always_ evaluates to `true`.

**Comment by OwenArnold** [comment]
Some way of being able to use scipp types as default (non initialised) arguments is useful, which requires a corresponding way to query. That could be done with a named method, it does not need to happen through `operator bool()`.

**Comment by SimonHeybrock** [comment]
This is used quite a bit on the cpp side. Furthermore, after you `std::move` from a `Variable` it wil contain a `nullptr`.

**Comment by SimonHeybrock** [comment]
Please reopen if you think this is relevant.

**Comment by jl-wynen** [comment]
It did cost me >10min because I thought that something was broken with `bin` and not with the unit test I had just written.

In Python, containers can be converted to bool which checks if they are empty. This is not exactly the same as the operator here because a variable with `Shape{0}` still evaluates to `true`; the operator queries something about the internal representation. But it is a similar kind of idea.
However, in my eyes, Variable is not a simple container. It defines a lot of operations that are mapped over its elements. In that sense, it behaves a bit like the things it stores (can do arithmetic for instance). So it is natural to expect it to behave like a bool when it contains bools. But with a scalar variable containing a bool, `operator bool` does not relate the the stored boolean value but to the container itself.
Furthermore, in numpy conversion to bool looks at the elements, `array([False])` does actually evaluate to `False`.

Long explanation for a small operator, but I am strongly in favour of turning it into a regular member function.

**Comment by SimonHeybrock** [comment]
I think the Python argument is irrelevant, but I did previously fall into the trap with something like `if (all(var1 == var2))`, which is not given what is expected, so I see the point. 👍

**Comment by jl-wynen** [comment]
I think the comparison with numpy is relevant because, at least I myself, approach Variables with a similar mindset as numpy arrays. (The Python builtin container thing not so much, but that is part of my point)
