### ISSUE TITLE
Avoid overallocating memory

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#1746]
My system crashed because scipp used too much memory in a notebook.
I don't know how this happened, when running the same code as a script, Python just gets killed without any side ffects that I can see.

Maybe we should not rely on the allocator to fail in a meaningful way.
- We could check if an allocation is possible before actually doing it. If there is still a bunch of memory left, we can throw an exception or print a message and terminate to let the user know. If there is hardly any space left, just terminate instead of risking the print or throw to fail as well. (Would be tricky to get to work though...)
- Or we set it up such that C++ terminates when an allocation fails instead of throwing an exception.

**Comment by jl-wynen** [comment]
I tried to trigger the crash but simply allocating a large variable does not do it. E.g. `sc.empty(sizes={'x': 10**10})` raises `MemoryError: std::bad_alloc`. And strangely, `[sc.empty(sizes={'x': 10**9}) for _ in range(10)]` works without complaints and seems to not allocate any large memory. Only filling it, e.g. via `for i in range(10): l[i].values[...] = 0` allocates and eventually crashes.
A faster way to trigger a crash is via `sc.zeros(sizes={'x': 10**10})`.

This tells me that the allocation (calling `new`) alone does not cause a crash but something further down the line. No idea, what is going on, though.

**Comment by SimonHeybrock** [comment]
When you call `new`, Linux (and I presume other OSes) does not hand out pages, so creating an `sc.empty` is fast (and that is why it exists in the first place --- if it was slow, doing init of all pages, everyone would just use `sc.zeros`). Then, as you begin the access addresses in your `sc.empty`, the kernel gives you new pages as you go. I don't think you need to *fill* (write), simply accessing 1 address (per page) should cause this.

**Comment by SimonHeybrock** [comment]
We are not aware of a feasible solution, closing for now.
