### ISSUE TITLE
Sanitizer CMake module is outdated

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#1773]
The CMake sanitizer project that we use as a Git submodule has not been updated since 2018. Its CMake minimum required version is deprecated.

Should  we update it ourselves or write our own implementation?

**Comment by SimonHeybrock** [comment]
Still outdated, but no other option. As it will not break builds there is no pressing need to address this. The module is quite small, so in the worst case we may be able to make fixes ourselves.
