### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by anderskaestner** [scipp/scipp#1774]
I tried to build scipp from the latest sources and got the cmake error that Boost is missing.
Maybe you can add boost as a required dependency on https://scipp.github.io/developer/tooling.html?
cmake ran without errors after installing Boost.

(I'm using macos)

**Comment by SimonHeybrock** [comment]
Yes, good point, I will do that. Boost was previously downloaded by cmake, but we switched away from that. We recommend using the `scipp-developer.yml` to create a `conda` environment for building scipp, see https://scipp.github.io/developer/getting-started.html#getting-the-code-building-and-installing.
