### ISSUE TITLE
Create a toolkit for bin edges and histograms

### ISSUE THREAD

**Issue by nvaytet** [scipp/scipp#1802]
It would be good to have all our python helpers to manipulate variables in one place, under a well-thought API.

1. What should the module be called?

2. List all the helpers we have and would like to add:
  - `to_bin_edges`, `to_bin_centers` (exists in `plotting/tools.py`)
  - `bin_widths` (missing)
  - `collapse`, `slices` (exists in `_utils`)

**Comment by SimonHeybrock** [comment]
Edited title, we should focus on bin edges / histograms here.

**Comment by SimonHeybrock** [comment]
See also scipp/scippneutron#238
