### ISSUE TITLE
Use / implement logging framework

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#1807]
There are several places where we print (or should print) info for the user:
- scippneutron prints some info on unit conversions.
- scipp itself could benefit from printing warnings in some situations, e.g. division by zero, see numpy.
- Possibly more info in certain operations, or at least in a debug build to help us and maybe users analyse out code. (Ownership?)

There needs to be a way to configure these things as scipp should be mostly silent by default. And it also makes sense to centralise it in scipp itself such that scippneutron and potentially other packages can all be controlled consistently. 

Since we mainly target Python, it makes sense to use the `logging` package of the standard library. It is quite easy to expose that to C++: https://github.com/evanberkowitz/isle/blob/a3efd361940fe958815abec1c57860c836bf81cb/src/isle/cpp/logging/logging.cpp (We might want to implement it differently, maybe use a singleton so that not every user has to re-import the Python module.)
However, this would add Python as a dependency to the C++ part of scipp. In particular, a C++ user would have to launch the Python interpreter: https://github.com/evanberkowitz/isle/blob/a3efd361940fe958815abec1c57860c836bf81cb/tests/cpp/test_main.cpp
This could be avoided by providing a logging framework in C++. It could be configured to just print by default and reconfigured to forward to Python's `logging` when importing scipp in Python.

We could either implement our own mechanism or use one of the open source logging frameworks. The former would likely result in a very basic API compared to what 3rd party implementations can provide. The latter would mean that we have two separate formatting mechanisms in C++ and Python. We cannot use the one implemented by `logging` in C++ because that would mean binding every type that we want to print to Python and again would make all of scipp depend on Python.

Personally, I prefer [spdlog](https://github.com/gabime/spdlog) because it uses the new string formating via libfmt. However, if we want to wait for C++20's implementation of `format`, then we would have to wait with implementing logging in this way.
Other frameworks would also work but if, in the long run, we want to move away from `operator<<`, then we should avoid those.

**Comment by OwenArnold** [comment]
A slight aside from logging - would it also be worth considering introspection tools that could be used with scipp? One might like to answer questions - For example given two DataArrays `a`, `b` do they share coords, attrs, masks? i.e. if I change masks on `a` am I going to affect `b`.

**Comment by jl-wynen** [comment]
If we follow through with what we discuss here in #2067 would it be enough to just use Pythons `logging` package or would we need logging support in C++?

**Comment by OwenArnold** [comment]
Logging came up with the SANS group on 31st August 2021. Good logging control and useful output for debugging are things they want to see. This isn't enough to form a specification, but maybe we could with the help of the relevant instrument data scientists.
