### ISSUE TITLE
Errors/warnings in cppcheck seem to be ignored

### ISSUE THREAD

**Issue by nvaytet** [scipp/scipp#1820]
The `ccpcheck` step in the CI reports several warnings and errors, but they currently seem to just be ignored, since the builds still pass.
e.g. https://dev.azure.com/scipp/scipp/_build/results?buildId=4328&view=logs&j=bed8431f-6f63-524c-44b8-61876ac065c4&t=3e06b184-52ff-5881-87c0-6015aee42633

We should probably change this so that builds fail on `cppcheck` errors.

**Comment by SimonHeybrock** [comment]
See work done in #2245. I believe the CI setup is probably a very incomplete run of cppcheck. Should use the new mechanism via cmake instead.
