### ISSUE TITLE
Transforms on Variables with NDIM_MAX dimensions segfault

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#1835]
`NDIM_MAX = 6` by default, performing a transform on such a Variable causes a segfault.
The shallow-copy branch implements `copy` using `transform`, so now 
```.cpp
BENCHMARK_TEMPLATE(BM_Variable_copy, Generate6D<float>)
    ->Apply(Args_Variable_copy);
```
in variable_benchmark.cpp triggers the segfault.

I think this is due to how `MultiIndex` uses the last element of its `m_coord` array.

Suggested fixes:
- Make transforms work with `ndim <= NDIM_MAX` or rename `NDIM_MAX` to indicate an exclusive upper bound.
- Detect too large ndim and signal to user.

**Comment by SimonHeybrock** [comment]
Would this be fixed by simply changing `m_coord` (and related) in `MultiIndex` to be of size `NDIM_MAX+1`?

**Comment by jl-wynen** [comment]
I think so. But I did not do an in depth analysis.
