### ISSUE TITLE
Rewrite `class Sizes` to avoid `std::unordered_map`

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1839]
Just like `class Dimensions`, we should probably avoid the memory allocations and overhead from using a data structure that allocates memory. We can use, e.g., a `std::array`, similar to how it is done in `class Dimensions`.

- Can `Sizes` be a base class of `Dimensions`? This would avoid overhead from the quite frequent need for conversion between the two.
- Unit tests
- Consider removing constructor `Dimensions(Sizes)`? Are the use-cases coverable by methods of `Sizes`?

**Comment by jl-wynen** [comment]
We might want a generic small-size map container since we need it in at least two places. In addition, a small-size _optimized_ container might be useful for `Dict` because you will often not have a lot of coordinates and masks.

Concerning whether `Sizes` can be a base class of `Dimensions`, is the only difference the insertion behaviour?  If so, could `Dimensions` just use a `Sizes` object internally? Or would there be a lot of functions that just forward to the underlying object?

**Comment by SimonHeybrock** [comment]
> Concerning whether Sizes can be a base class of Dimensions, is the only difference the insertion behaviour? If so, could Dimensions just use a Sizes object internally? Or would there be a lot of functions that just forward to the underlying object?

I think there are quite a few cases where we do things like `if (a.contains(b))`. If `b` is `Dimensions` and `a` is sizes, with a base-class approach we could call `Sizes::contains(Sizes)`. But you are right that it is not entirely clear whether the benefits outweigh the disadvantages of inheritance.

**Comment by SimonHeybrock** [comment]
> We might want a generic small-size map container since we need it in at least two places. In addition, a small-size _optimized_ container might be useful for `Dict` because you will often not have a lot of coordinates and masks.

I agree, some considerations:

- Historically we wanted `Dimensions` to be really small and never allocate since it was created/copied frequently as part of `VariableConstView`.
- I think this is still somewhat true, since `Dimensions` is part of `Variable`, which is created when making a slice. It now has more overhead than before due to the `std::shared_ptr` copy, so maybe slightly less relevant. Note that every time we slice a data array we slice ALL coords, masks, and attrs. That is small overhead may quickly add up.
- Previously we had an implementation that used `boost::small_vector` to implement the meta-data maps. Not the nicest thing to do, maybe there are nicer implementations out there?

**Comment by jl-wynen** [comment]
According to this https://tylerayoung.com/2019/01/29/benchmarks-of-cache-friendly-data-structures-in-c/
`llvm::DenseMap` is super fast. But it doesn't look at copying, though that should be fast, too. But we cannot really use anything from llvm.

**Comment by SimonHeybrock** [comment]
Is this similar to `boost::flat_map`?

**Comment by jl-wynen** [comment]
Haven't looked at it

**Comment by jl-wynen** [comment]
Actually, it looks like it does not use small-size optimisation but stores everything on the heap.
