### ISSUE TITLE
Explain used/supported computing languages on homepage

### ISSUE THREAD

**Issue by jwuttke** [scipp/scipp#1842]
From https://scipp.github.io it is unclear to me in which language this library is implemented, and which are the target languages.

**Comment by SimonHeybrock** [comment]
Hi Joachim,
Scipp is essentially a Python library (targeting Python users) and provides additional features for interactive use in Jupyter notebooks. Its internals are implemented in C++ and in principle it could also be used as a C++ library, but at this point we do not recommend the latter.

This is mentioned in the first paragraphs [here](https://scipp.github.io/#scipp-multi-dimensional-data-arrays-with-labeled-dimensions), but you are right that it may not be entirely clear, I will reformulate.
