### ISSUE TITLE
Shared ownership refactor: Run benchmarks and compare to old performance

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1850]
- Where did we lose performance?
- Pay particular attention to BM_groupby_large_table

**Comment by SimonHeybrock** [comment]
`groupby` benchmarks done in #1854, should also look at variable and dataset benchmarks.

**Comment by jl-wynen** [comment]
Benchmarks for binning. Looks like nothing changed.

![bin_table](https://user-images.githubusercontent.com/11393224/117413917-d43f6d80-af16-11eb-8d96-ddfc18872e87.png)
![rebin_outer](https://user-images.githubusercontent.com/11393224/117413918-d4d80400-af16-11eb-9ea6-c9403a5a9bfe.png)
