### ISSUE TITLE
binned data coord issue

### ISSUE THREAD

**Issue by OwenArnold** [scipp/scipp#1894]
Originally observed as part of the upgrades for `scippneutron` specifically [this](https://github.com/scipp/scippneutron/pull/73#discussion_r627424984)

To emulate what's happening in the convert procedure - this can be independently simplified with the following example.

```
a = sc.DataArray(data=sc.bins(data=da, dim='tof', begin=sc.array(dims=['tof'], values=[0,1,2])))
b = a.copy(deep=True)
a.bins.coords['tof'].values[0].values = np.array([6]) # sharing still continues with b
sc.identical(a, b) # True 
```

**Comment by SimonHeybrock** [comment]
Cannot reproduce. I get `False`.

Here is a minimally working example:
```python
import scipp as sc
import numpy as np
var = sc.array(dims=['tof'], values=np.random.rand(3))
da = sc.DataArray(data=var,
                  coords={'tof':var})
a = sc.DataArray(data=sc.bins(data=da, dim='tof', begin=sc.array(dims=['tof'], values=[0,1,2])))
b = a.copy(deep=True)
a.bins.coords['tof'].values[0].values = np.array([6]) # sharing still continues with b
sc.identical(a, b) # True 
```

**Comment by OwenArnold** [comment]
Having re-tested I believe that I falsely came to the conclusion this was an issue because I had already modified the data (`da`) prior to running this snipped. The first coordinate value was already `6` which yielded the false positive. Closing issue.
