### ISSUE TITLE
Support transform kernels defined in Python

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#1897]
Users might want to add custom kernels to `transform` to
- add new functionality
- fuse existing kernels to improve performance

We could add support for regular Python functions. But those would be rather slow and and would make transform serial because of the GIL. An alternative are JIT compiled functions. Numba supports this through CFunc and it seems to be pretty simple to use in principle:
In C++ (compiled into `nbcpp`):
```.cpp
#include <iostream>
#include <pybind11/pybind11.h>

namespace py = pybind11;

PYBIND11_MODULE(nbcpp, m) {
    m.def("trans", [](py::object const &kernel){
        auto fptr_address = kernel.attr("address").cast<intptr_t>();
        auto fptr = reinterpret_cast<int64_t(*)(int64_t)>(fptr_address);
        return fptr(2);  // works -> calls C function
        // return fptr("asd");  // compile error
        // return kernel("asd");  // works -> calls Python funtion
    });
}
```
In Python:
```.py
from numba import cfunc
import nbcpp

@cfunc("int64(int64)")
def kernel(a):
    return 2*a

print(nbcpp.trans(kernel))
```

In practice there are of course complications: We have to make sure that the signature of the kernel is correct, otherwise the `reinterpret_cast` followed by a function call would break in nasty ways.
We could inspect the function on the C++ side, which would not be terribly simple.
Alternatively, we can provide a wrapper in Python which encapsulates the compilation. This has a number of advantages:
- hides the compilation including the argument type list from the user
- can enforce correct types and provide overloads
- can wrap the compiled function to simplify the type checks in C++

It is not clear to me at this point how relevant this actually is or how performant it would be. We would have to try it out to find out.

Alternative:
Make numba compile the entire call to `transform`. This can inline the kernel and potentially produce faster binaries. But it would require access to scipp's source code and compilation would be rather slow. Also, I am not aware of a way to do this in numba.
EDIT it looks like it works in Awkward Array: https://awkward-array.org/what-is-awkward.html#performance

**Comment by SimonHeybrock** [comment]
Performance looks ok if compared to memory allocation: 
<img width="417" alt="image" src="https://user-images.githubusercontent.com/12912489/117609536-7ef69c80-b160-11eb-8726-f1f80721dd02.png">

**Comment by OwenArnold** [comment]
FYI this requirement has already come up around imaging where users may want to provide custom smoothing kernels to their data.
