### ISSUE TITLE
Convolutions

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#1901]
`transform` only applies element-wise kernels. But some applications need to perform convolutions. See for instance  https://github.com/scipp/scipp/issues/1897#issuecomment-836746280

Another use case would be kernel density estimations for people who find histograms too boring.

I came across this in a notebook for diffraction and thought about how it could work in scipp. In principle, this would not be hard to implement on dense Variables. But it becomes very complicated with binned data or DataArrays.

With binned Variables, a convolution over an outer dimension would combine bins with different numbers of elements which would not work easily. In the inner dims it would be dominated by the boundaries for all small bins. In addition, convolutions tend to make data more dense which makes the result less suitable for binning and potentially use more memory.

With DataArrays (Datasets) it makes no sense to identify neighbours based on memory layout, one would have to use coordinates instead. So finding all elements that need to be passed to any one kernel invocation would be `O(N)` unless the data is sorted cleverly.

**Comment by SimonHeybrock** [comment]
> With DataArrays (Datasets) it makes no sense to identify neighbours based on memory layout, one would have to use coordinates instead. So finding all elements that need to be passed to any one kernel invocation would be `O(N)` unless the data is sorted cleverly.

I suppose we would do the same as in value-based indexing: Support only ordered coordinates.

**Comment by SimonHeybrock** [comment]
As far as I can tell the original requirement here was a median filter? I will close this since we now have `scipp.ndimage.median_filter`. `generic_filter` can deal with even more cases. We can consider this again once new requirements arise.
