### ISSUE TITLE
Review tests of `class DataArray`

### ISSUE THREAD

**Issue by OwenArnold** [scipp/scipp#1908]
- Are there redundant duplicates now, from previous tests of `class DataArrayConstView` or `class DataArrayView`?
- Fix holes in test coverage related to sharing mechanism.
- Tests for slices are missing

**Comment by SimonHeybrock** [comment]
Note I have done parts of (but definitely not all of) this in https://github.com/scipp/scipp/pull/1899, make sure to have a look.
