### ISSUE TITLE
Unify DataArray and Variable into a flexible object on the Python side?

### ISSUE THREAD

**Issue by nvaytet** [scipp/scipp#1909]
I has been pointed out by several users that having `sc.array(...)` create a Variable, and `sc.DataArray(...)` create something quite different, is confusing.

We like `sc.array(...)` as it is like a numpy array.

We could maybe create a new object, on the python side, that would basically be a Variable that you can attach coords (and attrs and masks) to?
Myabe it is a bit similar to numpy's `masked_array`? It behaves like an array when it needs to?

But then wouldn't that just be a `DataArray`? Do we really need a new class?
We probably do, so that it can be passed to functions that only accept Variables as arguments?

**Comment by SimonHeybrock** [comment]
Since no one of our users is screaming, and we have little other reason to do something about this right now, I think I'll close this for now, in particular since unifying variables with data arrays may add extra confusion. Happy to discuss more if our requirements/opinions change later, as usual.
