### ISSUE TITLE
DataArrays with multi-dimensional bin-edge coordinates in 'first' through 'last minus one' dimensions

### ISSUE THREAD

**Issue by g5t** [scipp/scipp#1948]
Creating a `DataArray` with a mixed binned and non-binned multi-dimensional coordinate is only possible if the binned dimension of the coordinate is last.

```python
import scipp as sc
import numpy as np
from itertools import permutations

n_x, n_y, n_z = 10, 20, 50

xy = sc.array(dims=['x', 'y'], unit='dimensionless', values=np.random.rand(n_x, n_y + 1))
z = sc.array(dims=['z'], unit='dimensionless', values=np.random.rand(n_z))
xyz = xy - z
values = sc.array(dims=['x','y','z'], values=np.random.rand(n_x, n_y, n_z))

succeeds = []
failures = []

for p in permutations(('x', 'y', 'z')):
    p_xy = [q for q in p if q in ['x', 'y']]
    try:
        da = sc.DataArray(data=sc.transpose(values, p), coords={'xy': sc.transpose(xy, p_xy), 'z': z, 'mixed':sc.transpose(xyz, p)})
        succeeds.append(p)
    except sc.DimensionError as er:
        failures.append(p)
        
print('Success for {}\nFailures for {}'.format(succeeds, failures))
```

Produces the output
```
Success for [('x', 'z', 'y'), ('z', 'x', 'y')]
Failures for [('x', 'y', 'z'), ('y', 'x', 'z'), ('y', 'z', 'x'), ('z', 'y', 'x')]
```

Are binned coordinates only supported in their last dimension?

**Comment by SimonHeybrock** [comment]
> Are binned coordinates only supported in their last dimension?

Yes and no. Scipp does not store or require specification of the dimension a coordinate corresponds to:
- For 1-D coordinates the correspondence is obvious.
- For 2-D (or higher) coordinates the documentation states:
  [*In the special case of non-dimension coords that have more than 1 dimension, they are considered to be labels for their inner dimension.*](https://scipp.github.io/user-guide/data-structures.html#Distinction-between-dimension-coords-and-non-dimension-coords,-and-coords-and-attrs)

One could argue that for bin-edge coordinates, as in your example, scipp could deduce the dimension the coord corresponds to by finding the dimension that exceeds the data shape by 1. At this point scipp is not, and I do not see a stong argument for this additional complication (this may change). That being said, note:

1. Dimension-coordinates *can* have the bin-edge dimension anywhere:
   ```python
   import scipp as sc
   da = sc.DataArray(data=sc.zeros(dims=['x','y'], shape=(4,4)))
   da.coords['x'] = sc.zeros(dims=['x','y'], shape=(5,4))   # name matches dim => ok
   da.coords['x2'] = sc.zeros(dims=['x','y'], shape=(5,4))  # fails
   ```
2. If performance from transposed memory access is a concern, the upcoming scipp release (0.7) supports transposition without copying, see we can satisfy scipp's requirement of having the bin-edge dimension as inner dimension, while at the same time having the memory layout of your choice:
   ```python
   da.coords['x2'] = sc.transpose(sc.zeros(dims=['x','y'], shape=(5,4)), dims=['y','x'])
   da.coords['x2'].values.strides   # (8, 32)
   ```

**Comment by SimonHeybrock** [comment]
Tagged as `Question` so it is searchable. If this comes up more often we should add an FAQ item, or reconsider supporting this.

Closing for now, since Greg indicated he can live with this answer.
