### ISSUE TITLE
Misleading limit handling in 2d plot with log axis?

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1980]
<img width="563" alt="image" src="https://user-images.githubusercontent.com/12912489/121996210-74a37000-cda8-11eb-8fcd-b2ba8e0695ab.png">

This is with a coord `da.coords['xx'] = sc.linspace(dim='xx', unit='mm', start=1.1, stop=5.2, num=4)`

The current configuration of limits passed to the (resampling) model rounds to full orders and yields zeros in regions with no data. Can and should it be NAN (yielding white display) instead?

**Comment by SimonHeybrock** [comment]
Maybe this is actually not an issue, but standard behavior? I believe we experience the same with ragged coord or for event data?

**Comment by SimonHeybrock** [comment]
Is the answer to not use axis limits extended to cover full magnitudes? This was desired behavior, but maybe makes sense only for the *values*, i.e., vertical axis in 1d plots?

**Comment by jl-wynen** [comment]
> Is the answer to not use axis limits extended to cover full magnitudes?

What is the use of this? Why show regions with no data at all?

**Comment by SimonHeybrock** [comment]
Depending on the range of data plots become hard to read otherwise. But as I say in that comment: Maybe this is important for the value axis (y in 1d plot), but not for coord axes.

**Comment by SimonHeybrock** [comment]
> > Is the answer to not use axis limits extended to cover full magnitudes?
> 
> What is the use of this? Why show regions with no data at all?

Example of potential readability issues: 
<img width="591" alt="image" src="https://user-images.githubusercontent.com/12912489/122027239-3e2b1c80-cdcb-11eb-9780-12d2df95c572.png">

**Comment by jl-wynen** [comment]
I think this is more readable. Yes, one has to count ticks but at least one does not have to know where there is and isn't data. When I see a 2d plot like in the original post, I assume that there could be data outside the coloured region.

And concerning your question about NaN, setting the values to zero is confusing because it is visually indistinguishable from very small z-values.

**Comment by SimonHeybrock** [comment]
Cannot reproduce this anymore, neither with scipp nor with plopp.
