### ISSUE TITLE
Return Variables in isxxx functions

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#1985]
Unrelated, but this should actually be changed: It was added a long time ago, but not I think this [`issorted`] should return `Variable`. If required we can add `allsorted` to return `bool`, similar to `isclose` and `allclose`.

_Originally posted by @SimonHeybrock in https://github.com/scipp/scipp/pull/1983#discussion_r654157484_

**Comment by SimonHeybrock** [comment]
Fixed in #2094
