### ISSUE TITLE
Setup CI with sanitizer builds

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#202]
Previous attempt to enable sanitizers in Travis: https://github.com/scipp/scipp/pull/201.

- Fails on gcc with `/usr/bin/ld: unrecognized option '--push-state--no-as-needed'`. See here: https://stackoverflow.com/questions/50024731/ld-unrecognized-option-push-state-no-as-needed, is the gcc available on Travis too old?

- Fails on clang with `ERROR: LeakSanitizer: detected memory leaks`, most likely due to an `#pragma omp parallel for`. Google gives a number of hits to similar problem with OpenMP, also Valgrind giving false-positive warnings. I have not found information on how to fix this (or disable the warning/error). Note that I cannot reproduce this warning on my local clang (Ubuntu 18.04), maybe another case of outdated compilers on Travis?

**Comment by SimonHeybrock** [comment]
We are not building iwith OpenMP any more => try again with clang

**Comment by SimonHeybrock** [comment]
#455 takes steps to setup a local build environment with Jenkins. I suggest the sanitizers should be run in a similar setup.

- [ ] Setup things in new repo `scipp/scipp-ci-sanitizers`?
- [ ] Configure local Jenkins to run this, e.g., once per day.

**Comment by DanNixon** [comment]
Superseded by #952.
