### ISSUE TITLE
Add `pow` for variables and data arrays

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#2027]
```python
sc.linspace('qz', 0, 10, 10) ** sc.arange('qz', 0, 1, 0.1)
>>> TypeError: unsupported operand type(s) for ** or pow(): 'scipp._scipp.core.Variable' and 'scipp._scipp.core.Variable'
```

Works for numpy:
```python
import numpy as np
a = np.arange(5)
a ** a
```

- Base should support data arrays and variables.
- Exponent should support variables, and probably float/int (just like `+`)?

**Comment by jl-wynen** [comment]
It does not even support variables as base.

**Comment by SimonHeybrock** [comment]
Oh, right, I mixed it up with `Unit`, which does.

**Comment by jl-wynen** [comment]
So, change this to 'Implement pow for variables'?
