### ISSUE TITLE
`table` rows spinbox default to a smaller value than 50?

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#2034]
Is it possible to have the number of rows spinbox default to a smaller value than 50? Something like 

`sc.table(data['event', :], nrows=10)`

_Originally posted by @arm61 in https://github.com/scipp/ess-notebooks/pull/39#discussion_r665928209_

**Comment by nvaytet** [comment]
Note that as a workaround, you can currently set the `table_max_size` value in the runtime config.
But having a function argument would also be useful.

**Comment by SimonHeybrock** [comment]
Can we set that flag in the docs builds?

**Comment by SimonHeybrock** [comment]
I think it would be valuable to have the option to have an HTML table representation. The widget representation right now should be an alternative option. The former would then likely only work for "true" 1d objects, without the handling of multiple different 1d items, or 0d items.

**Comment by SimonHeybrock** [comment]
See also #2403.
