### ISSUE TITLE
`pip` package for scipp?

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#2035]
We should consider this again. Possible solutions or puzzle pieces for solutions:

- https://github.com/pypa/manylinux
- https://setuptools-cpp.davidmontague.xyz/
- https://thomastrapp.com/blog/building-a-pypi-package-for-a-modern-cpp-project/

**Comment by jl-wynen** [comment]
On top of conda or instead of it? Is there a way to make one from the other?

**Comment by SimonHeybrock** [comment]
In addition to conda, I think? The links I provided would also only work for Linux.

**Comment by arm61** [comment]
I would like to add my support for this functionality. 

I am interested in using `scipp` internally in `easyReflectometry` to store my experimental data (initially to make use of scipp plotting of the data and the fitting model). However, as you are aware, easyReflectometry is built on pip/poetry so this is non-trivial.

**Comment by arm61** [comment]
`easyReflectometry` is currently being built of macOS, windows and linux with a single python version.

**Comment by SimonHeybrock** [comment]
See also https://discuss.python.org/t/notes-on-binary-wheel-packaging-for-c-library-wrappers/2609

**Comment by g5t** [comment]
@SimonHeybrock, I mentioned to @jl-wynen that I have recently refactored the GitHub Actions workflows for `brille` to create and distribute wheels for PyPI on Windows, macOS, and linux. He suggested that I provide some details here.

I put together a simple C++ project built with CMake and exposed to Python via [pybind11](https://github.com/pybind/pybind11/) to test [workflow(s)](https://github.com/g5t/workflows) for `brille`. The [main workflow](https://github.com/g5t/workflows/blob/master/.github/workflows/build_deploy.yml) builds the Python modules with CMake and tests it with CTest, before rebuilding and 'repairing' the wheels using `delvewheel`, `delocate-wheel`, or `auditwheel` depending on the system (and via an action ['manywin'](https://github.com/g5t/manywin-action), ['manymac'](https://github.com/g5t/manymac-action) or [manylinux](https://github.com/RalfG/python-wheels-manylinux-build)).

The 'repairing' step is what should make the modules in each wheel distributable, as they bundle-in any non-standard/non-system libraries, e.g., `libomp` or `libhdf5`. I've put the Windows and macOS workflows in their own Actions to try and make the main workflow a bit easier to follow, but they could easily be incorporated into a repository's `.github/actions/` or directly into a workflow if you wanted to avoid external dependencies.

**Comment by SimonHeybrock** [comment]
I found an easy way: `scikit-build` + `cibuildwheel`.
