### ISSUE TITLE
Changing axis scale adjusts limits incorrectly

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#2038]
Setting the y-scale to 'log' via the button in the following sets the lower ylim to 0 which makes the plot unreadable.
```.py
x = np.arange(2.0, 50.0)
d = sc.DataArray(sc.Variable(dims=['x'], values=x),
                coords={'x': sc.Variable(dims=['x'], values=x)})
sc.plot(d)
```
It works when specifying `norm='log'` in `sc.plot`. But then, using the button to go to linear scale produces an unoptimal range.

This is unaffected by #2018. See in particular https://github.com/scipp/scipp/pull/2018#issuecomment-876378076

**Comment by nvaytet** [comment]
Strangely enough, it seems that this doesn't happen in the profile 1d plots?
![Screenshot at 2021-07-09 10-35-28](https://user-images.githubusercontent.com/39047984/125049635-78719c00-e0a1-11eb-99c9-c11e77ce5f43.png)

**Comment by SimonHeybrock** [comment]
@nvaytet Did your PR fix this?

**Comment by nvaytet** [comment]
Yes it did: #2426
