### ISSUE TITLE
Incorrect plots in docs because of interactivity

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#2041]
The plots in 'Customizing Figures' do not show the modifications made to them, e.g. setting the line colour to red has no effect in the docs.

Maybe the solution to this would also handle the sliders, etc. which are shown but do nothing.

**Comment by SimonHeybrock** [comment]
We are already fixing this as part of #2018.

**Comment by SimonHeybrock** [comment]
Note that it didn't work in notebooks for me either, not just docs.

**Comment by jl-wynen** [comment]
Checked locally and it is fixed
