### ISSUE TITLE
Remove builtin support for 3-D scatterplots of N-D data

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#2046]
Scipp currently support 3-D scatterplots of N-D data (see first figure in https://scipp.github.io/visualization/plotting/plotting-nd-data.html#3D-visualization). This works by, among other things, computing a regular grid of positions, and dealing with scaling differences of the axis.

We feel that:
1. This is of very limited use, i.e., the number of users who would regularely use this feature is extremely small compared to users of regular plots.
2. Development effort and maintenance overhead is not insignificant.
3. It is relatively simple to manually create fake position and such a plot. We can provide a recipe for this in the docs. Only advanced features such as switching the dims which are mapped to positions or not possible. Example:
   ```python
   xx = da.coords['xx'].copy()
   yy = da.coords['yy'].copy()
   zz = da.coords['zz'].copy()
   yy.unit = ''  # deal with potential different units
   xx *= 3.0  # deal with potential differences in axis scales
   da.coords['dummy-pos'] = sc.geometry.position(xx, yy, zz)
   da.plot(projection='3d', positions='dummy-pos')
   ```

Therefore the plan is to remove this feature.

**Comment by jl-wynen** [comment]
Sounds reasonable to me. If there is enough demand for this, we could provide a simple wrapper that does something along the lines of what you posted above (minus modifying the input).

But I have one problem with this solution. The default opacity is even worse for me than with the builtin solution:
![alpha](https://user-images.githubusercontent.com/11393224/125245629-16a77100-e2f1-11eb-9520-cf1a47172cc1.png)
