### ISSUE TITLE
Orthographic projection

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#2048]
For 3D plots it can be useful to use an orthographic projection instead of a perspective one in order to inspect the geometry of an object. I don't know how hard this is to set up in pythreejs. If it is easy enough we should support it.

**Comment by nvaytet** [comment]
Should be pretty easy: https://threejs.org/docs/#api/en/cameras/OrthographicCamera

**Comment by SimonHeybrock** [comment]
Will do if requested.
