### ISSUE TITLE
Conceptually wrong association of N-D coords with dimensions

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#2057]
From [docs](https://scipp.github.io/user-guide/data-structures.html#Distinction-between-dimension-coords-and-non-dimension-coords,-and-coords-and-attrs): "*In the special case of non-dimension coords that have more than 1 dimension, they are considered to be labels for their inner dimension.*"

Now consider this data array, where `radius` and `phi` coords have been computed from `x` and `y`:

<img width="747" alt="image" src="https://user-images.githubusercontent.com/12912489/125899709-00aaa6dc-151f-4603-83cc-cc4669e5c309.png">

Slice the array along one of its dimensions:

<img width="737" alt="image" src="https://user-images.githubusercontent.com/12912489/125899903-c8e05773-758b-4c5f-b3c9-c87dacdc31fc.png">

Here `phi` is converted to an attribute because it is considered are coordinate of `x`. However, for such a coord it is just conincidence what its inner dimension is --- it isn't labelling *either* of the dims (or both, after slicing).

The conclusion seems to be that the current definition is wrong. In the above example the expected outcome would be that `radius` and `phi` behave in the same manner, and that slicing along `x` or `y` is that same: In all 4 cases either both or neither of `radius` and `phi` should turn into attributes.

Whether both or neither requires closer consideration.

**Comment by jl-wynen** [comment]
There is another, related problem in the context of `transform_coords`, namely the limitation that bin-edges must be the innermost dimension. For example, 
```.py
da = sc.DataArray(sc.ones(dims=['x', 'y'], shape=[2, 3]),
                          coords={'x': sc.arange('x', 2), 'y': sc.arange('y', 4)})
def combine(x, y):
    return x + y
da.transform_coords('s', {'s': combine})
```
works as intended. But switching the order of dimensions in, e.g., `combine`:
```.py
def combine(x, y):
    return y + x
```
makes it fail with `DimensionError: Cannot add coord exceeding DataArray dims`.
In practice, the author of a conversion function does not know the order of dimensions in the input data, nor is it even accessible.

It would be possible to check the dimension order before inserting a new coord in `transform_coords` and transpose when needed. But this does not seem like a clean solution to me. It would be better if bin-edge coords would be allowed to be a different order than the data just like non bin-edge coords.
