### ISSUE TITLE
Emit warning from `transform_coords` if requested output was not computed but found as existing coord/attr?

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#2068]
See title. Right now this will just work, e.g., when converting back to original coords (if inputs have been kept in initial transform). This may be surprising, since it ignores potentially modified coords.

**Comment by SimonHeybrock** [comment]
@jl-wynen Is this address by #2266? Should we emit a warning if no computation happens at all?

**Comment by jl-wynen** [comment]
With #2266 the log message reads
```
Transforming coords (x) -> (x)
  Steps:
```
which is not very informative.

I am not sure if a warning is the right solution. But the info log should definitely be clearer.
Are there use cases where you expect to get request a coord that already exists? 
A wrapper function might produce all sorts of coords some of which might have been precomputed. Would it be the wrapper author's responsibility to not request existing coords?

**Comment by SimonHeybrock** [comment]
> Are there use cases where you expect to get request a coord that already exists?

Maybe this is not relevant any more, since we decided to *not* support conversion back to `tof` in scippneutron?
