### ISSUE TITLE
Builtin type promotion in operators

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#2082]
Currently, operators with builtin Python types `int` and `float` pick an overload based on the _value_ of the number, e.g.
```.py
sc.scalar(3, dtype='int64') + 2      # calls (int64, int32) -> int64
sc.scalar(3, dtype='int64') + 2**32  # calls (int64, int64) -> int64
sc.scalar(3, dtype='int32') + 2      # calls (int32, int32) -> int32
sc.scalar(3, dtype='int32') + 2**32  # calls (int32, int64) -> int64
```
This is a bit strange since Python natively always uses 64bit precision (except for on Windows and except for when an int becomes too large). I would even say that the third case above results in an unintentional loss of precision. Additionally, the only way to control the precision in this case is by wrapping the RHS in a Variable manually.

In numpy, it looks like all of the above operations convert to int64 first and also return int64. We could achieve the same by removing the 32bit overloads in https://github.com/scipp/scipp/blob/52244515a7f5f43c6f1c6467f0b66b3c0b87d063/python/bind_operators.h#L212-L226

I think this would be the better solution. Please comment!

**Comment by SimonHeybrock** [comment]
Basically, what you are asking is: Should we treat all Python integers as 64 bit?

**Comment by SimonHeybrock** [comment]
It gets worse:
```python
import scipp as sc
var = sc.scalar(1.23456789)
print((var / math.pi).value)
print((var / sc.scalar(math.pi)).value)
```
Gives
```
0.3929751536165327
0.3929751645520626
```
Apparently it always picks the `float` overload?
