### ISSUE TITLE
 Show bin boundaries when plotting binned data

### ISSUE THREAD

**Issue by g5t** [scipp/scipp#2084]
When plotting binned data there is no indication of bin boundaries, which can be a useful tool to identify features in the displayed data.
I think adding the ability to display bin boundaries in a plot will benefit users of `scipp`, but I do not know how best to achieve this. Two options are detailed in a jupyter notebook, reproduced below in Markdown and available outside of GitHub.

In summary the two options are:
1. Use the minor tick grid lines to show the bin boundaries, but this is very fragile
2. Draw the bin boundaries after the data as a `matplotlib.lines.Line2D` object, which seems more robust.

Assuming everyone agrees that this is a good idea, would someone else be able to implement this or point me in the right direction for where such a feature could or should go in scipp?

<hr>

```python
import numpy as np
import scipp as sc
```

Construct a DataArray, [from the scipp documentation](https://scipp.github.io/user-guide/binned-data/binned-data.html#From-scattered-to-binned-data)

```python
N = 5000
values = 10*np.random.rand(N)
data = sc.DataArray(
    data=sc.Variable(dims=['position'], unit=sc.units.counts, values=values, variances=values),
    coords={
        'position':sc.Variable(dims=['position'], values=['site-{}'.format(i) for i in range(N)]),
        'x':sc.Variable(dims=['position'], unit=sc.units.m, values=np.random.rand(N)),
        'y':sc.Variable(dims=['position'], unit=sc.units.m, values=np.random.rand(N))})
```

We can plot the scattered data as is, but we want to bin it first instead:

```python
xbins = sc.Variable(dims=['x'], unit=sc.units.m, values=np.linspace(0,1,num=11))
ybins = sc.Variable(dims=['y'], unit=sc.units.m, values=np.linspace(0,1,num=6))
binned = sc.bin(data, edges=[ybins, xbins])
```

We can plot this but will not see the structure of the binning.

If the plot command supported a `edgecolors` keyword like `matplotlib.pyplot.pcolormesh` then the structure would be immediately apparant. (Using `pcolormesh` or `pcolor` directly would force us to lose-out on `scipp`'s automatic resampling, which does not seem like a good thing).

Instead, we can draw the bin edges outselves -- either as a `Line2D` object or by abusing the minor ticks (and reverting `matplotlib.axis.Axis` [behaviour](https://github.com/tacaswell/matplotlib/commit/d3b948400500c4adbc9c88903913b1ec054358be))

```python
# make sure that any overlapping major and minor ticks do not remove the minor tick entirely
import matplotlib
matplotlib.axis.Axis.remove_overlapping_locs = False
```

```python
h = sc.plot(binned, aspect='equal')
h.ax.set_xticks(binned.coords['x'].values, minor=True)
h.ax.set_yticks(binned.coords['y'].values, minor=True)
h.ax.tick_params(which='minor', length=0)
h.ax.grid(which='minor')
h
```

The potential downsides to utilising the minor grid to draw bin boundaries are
1. Updating the draw grid(s) interactively by hovering over the plot and pressing 'g' will remove the minor grid lines
2. Semilog or log plots may use the minor ticks to display partial decades, which would interfere with this method

An alternative approach is to directly draw the grid lines after the data, which is accomplished by the following two functions

```python
def edges_to_line(xedges, yedges, **kwds):
    from matplotlib.lines import Line2D
    xmin, xmax = min(xedges), max(xedges)
    ymin, ymax = min(yedges), max(yedges)
    x, y = [], []
    for ye in yedges:
        x[:0] = [xmin, xmax, None]
        y[:0] = [ye, ye, None]
    for xe in xedges:
        x[:0] = [xe, xe, None]
        y[:0] = [ymin, ymax, None]
    return Line2D(x, y, **kwds)

def draw_bins(obj, **kwds):
    axes_values = [obj.model.data_arrays[obj.name].coords[obj.axes[xy]].values for xy in 'xy']
    obj.ax.add_artist(edges_to_line(*axes_values, **kwds))
    return obj
```

The following image should show the bin boundaries, but anything which clears the axes as part of a redraw will remove the boundary markers as well.
A widget button which controls the drawing of bin boundaries would be very nice to have, but is beyond my abilities at present.

```python
draw_bins(sc.plot(binned, aspect='equal'), color=[0.6,0.6,0.6], linewidth=0.5)
```

## Bin edges are drawn slightly out of place
When a binned `DataArray` contains 'dense' data each bin is coloured by a single colormap value.
Are these drawn as a `PolyCollection`, as in `matplotlib.pcolor`, as a `QuadMesh`, as in `matplotlib.pcolormesh`, or as an image via `matplotlib.imshow`?
If `imshow` is used, perhaps there is an aliasing problem between the image resolution and the binned array?

```python
draw_bins(sc.plot(binned.bins.sum()), color='red', linewidth=0.5)
```

**Comment by nvaytet** [comment]
I'm just pasting here the image of what you would like to achieve, to make the discussion easier
![Screenshot at 2021-08-09 10-35-31](https://user-images.githubusercontent.com/39047984/128679409-7a741308-947d-4bb5-95be-51ac331ed3a6.png)

**Comment by nvaytet** [comment]
> Bin edges are drawn slightly out of place

I think this has to do with the way the resampling of the plot is done. It is trying to match the resolution on screen so that the effects at the bin boundaries are not visible, but i agree that you can still see them on some edges.
This becomes more apparent, if you lower the resolution
```Py
draw_bins(sc.plot(binned.bins.sum(), resolution=64), color='red', linewidth=0.5)
```
The `rebin` function is basically doing a `mean` operation for these pixels that are covering both sides of a bin edge, making the boundaries between the edges 'fuzzy'.

To answer the question, we are indeed using `imshow` but using `pcolormesh` wouldn't help here because we are always using `rebin` to resample the data to the requested image resolution (`64` here).

**Comment by SimonHeybrock** [comment]
This suggestion will not be applicable with the future plotting code since it will require explicit binning/histogramming (automatic resampling removed). Unless someone is planning to build an advanced plotting tool (using the upcoming pipeline mechanism) with automatic resampling I suggest we close this.

**Comment by g5t** [comment]
The last point that I raised previously will be ameliorated by the removal of automatic resampling, but the bigger issue of being able to show bin boundaries _might_ remain. The ease with which a user can show bin boundaries certainly will depend on which plotting engine is used to display histogrammed 2D data. 
Should this issue remain open as a reminder that the ability to _show_ bin-boundaries is a weak(?) requirement on the new plotting implementation? Or could that be recorded some place else?

**Comment by nvaytet** [comment]
To clarify a little, say you have event data with 3x3 bins. With the old plotting implementation, where automatic resampling was happening, you would get a 2D image with 700x500 pixels (or something like that), and there it would have been useful to overlay the boundaries of the large 3x3 bins.
In the new plotting, you will just get an image with 3x3 pixels, that correspond to the bins.

**Comment by g5t** [comment]
> If there is no resampling, bin boundaries would be "pixel" (not display pixel) boundaries, i.e., obvious.

> In the new plotting, you will just get an image with 3x3 pixels, that correspond to the bins.

Even in the case where the image pixels (or patches) match the underlying bin boundaries it may still be desirable to display the bin boundaries. Doing so can help communicate to others what bin size has been used, even if the binned data varies smoothly between neighbouring bins.

As an example that this _may_ be useful, the original MATLAB version of MSlice allowed users to select 'faceted' 2-D plotting where the bin edges are displayed. 

If, e.g., [`matplotlib.pyplot.pcolormesh`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.pcolormesh.html) is used to display the binned data providing access to its keyword `edgecolor` would be sufficient to allow a user to turn on the desired behaviour.

**Comment by SimonHeybrock** [comment]
Plotting binned data is no longer possible with Plopp, so this does not apply any more as the user always needs to histogram manually.
