### ISSUE TITLE
Cleanup API for in-place operations with variables and datasets

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#212]
Need an intuitive way of distinguishing in-place operations and non-in-place operations.

- The best solution may be different between Python and C++.
- Should all operations have both options, or do we want things like, e.g., `sort` that always operate in-place?
- If we use a method it will not be possible to add them in another module, i.e., we would have both styles?

Example:
```cpp
auto sorted = sort(dataset, Dim::Tof);
// in-place
dataset.sort(Dim::Tof);
// or use move for in-place op?
dataset = sort(std::move(dataset), Dim::Tof);
sort_in_place(dataset, Dim::Tof);
sort(dataset, Dim::Tof, scipp::InPlace);
auto other = sort(dataset, Dim::Tof, scipp::StealBuffer);
```

Python:
```python
dataset.sort(Dim.Tof)
# "move"
dataset = sort(dataset, Dim.Tof, steal=True)
```

**Comment by OwenArnold** [comment]
I would prefer not to have separate named functions for `in_place` not in place, I think the method signatures and mandatory options should be able to make this clear enough.

On the c++ side, these could all be supported without contradition or abiguity
```
dataset.sort(Dim::Tof); // void return 

dataset = sort(std::move(dataset), Dim::Tof);

auto other = sort(dataset, Dim::Tof, scipp::StealBuffer); // no default for third arg
```
Only the `move` variant would not have an analogue in python.

**Comment by SimonHeybrock** [comment]
I think we will have to go with free functions, otherwise we could, e.g., not support an in-place `convert`, since it is in another module and thus cannot add methods.

**Comment by SimonHeybrock** [comment]
Maybe out-parameters as in numpy are the right way?

**Comment by SimonHeybrock** [comment]
I realize now that out-args have a crucial edge over most if not all other options: They support output into a *slice*, that is, even if only a subset of elements is processed we can avoid copies.

**Comment by SimonHeybrock** [comment]
Examples have been implemented, but support across the board will be pushed to a future milestone.

The main difficulty comes with operations for `DataArray` or `Dataset`, where defining and checking the correct configuration (content, dimensions, ...) of the `out` argument is complex.

**Comment by DanNixon** [comment]
I'll look at supporting out argument the remaining unary operations or `Variable`.

**Comment by SimonHeybrock** [comment]
Closing since we are on the way of adding support for "out" args, the discussion here should be done.
