### ISSUE TITLE
Checked `value` and `values`

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#2131]
When getting the value(s) from a Variable, it can make sense to check if the Variable is dimensionless, e.g. (name up for debate)
```.py
(a / b).dimless_value
```
would raise if the quotient is not dimensionless. This would provide a safety check if the units are not what you thought they are.

**Comment by SimonHeybrock** [comment]
How about `sc.to_unit(a/b, 'dimensionless).value`.

**Comment by jl-wynen** [comment]
> How about `sc.to_unit(a/b, 'dimensionless).value`.

The shortest form this can take is `sc.to_unit(a/b, 'one', copy=False).value` which is a mouthful. I am not proposing something that cannot be done already, just something that makes life more convenient.

**Comment by SimonHeybrock** [comment]
Sure, but we always have to find the balance between making frequently/infrequently used things convenient and bloating our interface with too many function/methods/properties that will become hard to maintain and hard to remember.

Until we know if this is something that gets used all over the place I would suggest to add this to the FAQ or Howto instead.

**Comment by jl-wynen** [comment]
Fair. The one use case that I had disappeared anyway once the whole function was rewritten in scipp instead of using numpy for part of it.
