### ISSUE TITLE
Linker warnings on MacOS

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#2138]
Linking `scipp-variable` causes the following warnings on MacOS
https://dev.azure.com/scipp/scipp/_build/results?buildId=7161&view=logs&j=63453d53-15fd-5495-e319-bb80e05c85cc&t=4e695665-cffc-5d60-d406-781be98817a9&l=761

**Comment by OwenArnold** [comment]
Could find no satisfactory way of dealing with this. No change to the linker setting seemed to have any effect. Lots of other projects are reporting issues with this, but could not find a resolution.
