### ISSUE TITLE
CI thoughts and worries

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#2163]
Recent trouble with the packaging highlighted a number of shortcomings of the current setup:

- The manual coping of files in `build_conda.py` was very hard to debug and led to many slow iterations while attempting to fix the packaging. If I remember correctly the reason for this was to avoid rebuilds when calling `conda --build`?
- A sub-problem of the former was the mix of platform-specifics in this script, which meant fixing one platform broke the other platform's packages (more than once).
- We build `install` and `all-tests` before running *any* of the tests. One reason for splitting the scipp codebase into sublibraries was to be able to abort early, e.g., to run `scipp-core-test` before compiling `scipp-variable`. This advantage was lost at some point. While this may sometimes be irrelevant, during the past week or so I *did* observe that we had jobs waiting for free builders at times when we were merging/pushing in multiple projects (scipp, scippneutron, ess) at the same time.
  - Would maybe require fixing the unresolved MSVC issue of full recompilation of all object files and libraries for every target.
- Could consider building without IPO for PRs?
- Having to maintain a series of different env files is becoming a nightmare. We have:
  - dev envs (multiple platforms), used also for parts of CI
  - conda build `meta.yml`
  - User-facing envs (linked to from docs)
- Do we actually want to publish a package for every push to `main`?
- We have multiple times broken the ability to make patch releases by updating `pipelines`. Should probably use tags in pipelines repo, and refer to concrete tags from downstream CI? -> fixed in #2207.

**Comment by nvaytet** [comment]
- I agree with running the core tests before building the variable.

- "The manual coping of files in build_conda.py was very hard to debug". Yes I came across that multiple times when setting up pipelines and common build tools. This is a remnant of what Dan set up initially, and I don't really remember the original reason for doing it this way. What is the alternate way of doing it? (i don't know enough about conda build)

**Comment by SimonHeybrock** [comment]
Notes from inspecting our current setup (work in progress):
- Why is `CONDA_PREFIX` used in our build scripts, rather than `PREFIX`?

**Comment by SimonHeybrock** [comment]
# Proposal

This is an attempt to outline a possibly simpler solution. For now this is incomplete and probably has some holes:

- Improve `meta.yml` as described in https://github.com/scipp/scipp/issues/2085#issuecomment-897741399.
- Disable IPO in non-package builds to speedup CI.
- Use `conda debug` to create env from `meta.yml`. Use this instead of `scipp-developer.yml` for local builds and non-package CI builds.
- Get rid of `tools/build_conda.py` and manual file copying. Rely on files installed by cmake from `install` target.
- Do not use `conda build` in PRs.
  - How to handle docs builds?
- Figure out if we actually want to run `conda build` for every merge/push to `main`.
  - Should CI for `main` be independent of packaging?
  - Should we use a cron job instead?
  - Are the `scipp/label/dev` packages actually useful?
  - How would docs build/publish work? Part of `conda build`.

**Comment by jl-wynen** [comment]
> How to handle docs builds?

`cmake --build . --target docs` should work. But need to make sure it is run in the same directory where `_scipp` was built to prevent recompilation.

> Are the scipp/label/dev packages actually useful?

Yes, for updating scippneutron to a new scipp version, see past weeks. But we could enable building those packages only when needed.

This sounds like we potentially miss bugs in the day-to-day CI since we would not build the final package. Can we ensure that all dependencies are set up correctly without calling `conda build`?

**Comment by OwenArnold** [comment]
> Do not use conda build in PRs

This is the way we originally had things, but @nvaytet changed this at some effort for consistency. I believe the driver for this was to eliminate potential bugs that would  get through between PR pipelines `main`/`release` and our PR pipelines. However I prefer the idea of getting back to a state were we could use ccache without having to do the cpp builds outside of `conda build`.

**Comment by SimonHeybrock** [comment]
> > Do not use conda build in PRs
> 
> This is the way we originally had things, but @nvaytet changed this at some effort for consistency. I believe the driver for this was to eliminate potential bugs that would get through between PR pipelines but only be realised at`main`/`release` pipelines. However I prefer the idea of getting back to a state were we could use ccache without having to do the cpp builds outside of `conda build`.

I feel that this may have been an instance of fixing the symptoms, rather than the underlying issues? With the above suggestion we would (hopefully) have a consistent way of creating envs (which would eliminate once source of bugs).

**Comment by SimonHeybrock** [comment]
> > How to handle docs builds?
> 
> `cmake --build . --target docs` should work. But need to make sure it is run in the same directory where `_scipp` was built to prevent recompilation.

Well, but there is also the question of publishing, and avoiding publishing unless packages were built/published.

> > Are the scipp/label/dev packages actually useful?
> 
> Yes, for updating scippneutron to a new scipp version, see past weeks. But we could enable building those packages only when needed.
> 
> This sounds like we potentially miss bugs in the day-to-day CI since we would not build the final package.

Why would we miss bugs? I am not suggesting to not run CI, just to not build/publish packages. The only bugs this would miss are bugs in the packaging env and build scripts, which is unrelated.

>  Can we ensure that all dependencies are set up correctly without calling `conda build`?

You mean dependencies specified in `meta.yml`? If the suggestion to use `conda debug` for creating dev/CI envs is viable, I think this would be ensured?

**Comment by OwenArnold** [comment]
> > > Do not use conda build in PRs
> > 
> > 
> > This is the way we originally had things, but @nvaytet changed this at some effort for consistency. I believe the driver for this was to eliminate potential bugs that would get through between PR pipelines but only be realised at`main`/`release` pipelines. However I prefer the idea of getting back to a state were we could use ccache without having to do the cpp builds outside of `conda build`.
> 
> I feel that this may have been an instance of fixing the symptoms, rather than the underlying issues? With the above suggestion we would (hopefully) have a consistent way of creating envs (which would eliminate once source of bugs).

Yes environment is one source of bugs. cmake settings and flags is another, and possibly the bigger issue if I recall.

**Comment by SimonHeybrock** [comment]
> > > > Do not use conda build in PRs
> > > 
> > > 
> > > This is the way we originally had things, but @nvaytet changed this at some effort for consistency. I believe the driver for this was to eliminate potential bugs that would get through between PR pipelines but only be realised at`main`/`release` pipelines. However I prefer the idea of getting back to a state were we could use ccache without having to do the cpp builds outside of `conda build`.
> > 
> > 
> > I feel that this may have been an instance of fixing the symptoms, rather than the underlying issues? With the above suggestion we would (hopefully) have a consistent way of creating envs (which would eliminate once source of bugs).
> 
> Yes environment is one source of bugs. cmake settings and flags is another, and possibly the bigger issue if I recall.

Shouldn't this be solved by the recent introduction of `build_cpp.py`?

**Comment by OwenArnold** [comment]
> Shouldn't this be solved by the recent introduction of build_cpp.py?

Yes that would work. Though I think we would want to adapt it to support a more `conda build` like approach. This needs more thought.

**Comment by SimonHeybrock** [comment]
> > Shouldn't this be solved by the recent introduction of build_cpp.py?
> 
> Yes that would work. Though I think we would want to adapt it to support a more `conda build` like approach. This needs more thought.

Can you elaborate? I thought `conda build` would call this script? It is basically a unified version of `build.sh` and `build.bat`.

**Comment by OwenArnold** [comment]
> Can you elaborate? I thought conda build would call this script? It is basically a unified version of build.sh and build.bat.

I had thought that `build_cpp.py` was internally activating environments, but after checking,  that's not where it's done, so indeed this wouldn't need to change.

**Comment by nvaytet** [comment]
Using `conda build` for PR builds was to make sure the same was done when building the PRs, and when building the conda packages. In the past, we had separate scripts and several times we modified the PR script, and not the conda build scripts, and we ended up with inconsistencies (or `main` builds failing when the PR build passed).
So I would vote against dropping `conda build` for PRs.

**Comment by nvaytet** [comment]
I don't think using conda build was actually related to the docs, I misremembered during the daily call.

**Comment by nvaytet** [comment]
I also think it is important to check that the conda package still builds on PRs. I think we would spend a lot of time debugging if we suddently notice the Main builds have been failing for 2 days before someone realises.

**Comment by SimonHeybrock** [comment]
> Using `conda build` for PR builds was to make sure the same was done when building the PRs, and when building the conda packages. In the past, we had separate scripts and several times we modified the PR script, and not the conda build scripts, and we ended up with inconsistencies (or `main` builds failing when the PR build passed).
> So I would vote against dropping `conda build` for PRs.

But this is one of the key points here: In my opinion we should not treat symptoms any more (because it complicates the whole setup), but fix the root causes! Because in the end treating the symptoms has led to **even more** problems:
- Complicated 2-stage build with 2 different env files.
- Complicated `build_conda.py`, which feels unnecessary (if I understand correctly).
- Slow builds, where jobs an Azure begin queuing up on some days.
- Slow builds mean I won't always merge `main` when I want to merge two "unrelated" PRs, since I'd have to wait an hour for it to complete. Essentially this means we either
  - Limit ourselves to merging 8 PRs per day (assuming 8 working hours)
  - Breaking `main` since builds have not run.

**Comment by nvaytet** [comment]
> Complicated 2-stage build with 2 different env files.

This is indeed annoying. You first solve an env from the `scipp-developer.yml` to build the cpp (so you can use `ccache`), and then solve a second (hopefully) identical one, from the `conda/meta.yaml` file, during the `conda build` step.

A while ago, we were simply doing `conda build` for everything, but we changed back to 2 stages so we could start using `ccache` again.

> Slow builds, where jobs an Azure begin queuing up on some days.

I guess this is one of the most important issues we have: the (mainly Scipp) builds are slow.
But you do have an incompressible 25 mins of building the C++ library.
And once many people start hogging builders with many PRs on the `ess` repository, we might find that even 30mins is too slow?
Would it be a bad idea to turn even more optimizations off on PR builds? e.g. use `-O0`?

**Comment by SimonHeybrock** [comment]
> But you do have an incompressible 25 mins of building the C++ library.

This may be a reason why we may sooner or latter consider splitting off the C++ core of scipp (everything excluding the Python bindings) into a separate library. There would be fewer iterations on that, such that building scipp itself (only Python bindings and Python code) would be faster.

**Comment by SimonHeybrock** [comment]
First step for solution:
- Do not use `build_conda.py` on PRs and Main builds, just run script calling `build_cpp.py` and Python tests and Docs build.
  - Note: Cannot use `conda build` since ccache does not work
  - Disable IPO
  - Have single script for test stage, used by both `conda build` and PR/Main builds.
- Run nightly conda package builds.
  - Change `build_conda.py` to simply call `build_cpp.py` (or directly if we can pass params from `meta.yml`)
    - Don't build docs here (unlike PR and Main CI)... or put into test section of `meta.yml`?
    - Add `cmake` `find_package(scipp)` in `meta.yml` `test` section to ensure the conda package provides a working cmake module.
    - Can we use ` [linux64]` to test/build docs only on linux?
