### ISSUE TITLE
`plot` with automatic resampling revisited

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#2167]
# Current situation

- `plot` automatically resamples data on zoom in.
- This includes event data, which can be infinitely resampled.

# Issues

- Infinite zoom with event data is not useful and led to considerations on a different (more complicated) mechanism, #1728.
- Log-scale plots should use log bins to be truly useful, but is appears to be non-trivial to implement, #1473.
- Picking values for the profile view has unpredictable and misleading values depending on zoom level. This has been improved in the recent refactor by growing the bounds of the selection to the underlying data bins, but the solution is incomplete since it does not resolve the problem when multiple data bins contribute to a display pixel.
- Complex code related to resampling throughout the plotting code. While the actual resampling bit is encapsulated in `ResamplingModel` there is a significant number of complications ranging from custom handling of bounds on zoom event to handling of coord/axis tic labels.
- Misleading display of data values on zoom, displaying values on display pixel rather than data pixel.
- Complicated handling of datetimes that also affects resampling. Plotting with binned datetime dimension currently fails.

# Discussion

Consider why we introduced resampling in the first place:

1. Plotting of data with "long" dimensions, in particular a "pixel" dimension.
2. Plotting with multi-dimensional coordinates, i.e., not plain "images".
3. Plotting of event data.

It is unfortunate that these aspects become so pervasive in the plotting code, which should ideally just take data and coords and hand them to a plotting library. 
Can we make this approach more modular, ideally making the plotting code completely oblivious to the presence of resampling?

# Potential solutions

## 1. Use data updates to display resampled data?

Assume we have a plotting code that simply takes a data array and plots its data with given coordinates.
For "normal" data (not in the one of the 3 special cases listed in the discussion section above) this would simply plot and work as expected, resolving a number of the listed issues for this case.

How could we handle plotting for the 3 special cases? We could resample by hand, e.g.,
```python
sc.resample(da, resolution=500).plot()  # hypothetical `resample` function
```

This would resample `da` to a resolution of `500` and plot it. The problem is obviously that this would be static, i.e., when we zoom in we would *not* resample.

Consider instead creation of a resampling model on top of our data, e.g.,
```python
# for illustration, ignore discussion on user-facing interface now, there can be wrappers that do this automatically
sc.dynamic_resample(da, resolution=500).plot()
```

Here `dynamic_resample` could:
- Resample `da` to a resolution of `500` and plot it.
- Connect to the `zoom` event of the plot view.
- Use the recently added data update mechanism to update the plotted data (and coords).

There is a large question-mark attached to the final item.
- Would this really be simpler than the current mechanism?
  Essentially it would have to bypass the zoom mechanism of whichever plotting library is used.
- Maybe zooming and resampling should be two entirely distinct mechanisms? We may zoom in, and then a manual user intervention could trigger a resample? How would we update the plotted data and coords (given that the resolution will change)?

**Comment by nvaytet** [comment]
> We may zoom in, and then a manual user intervention could trigger a resample?
i like this idea

**Comment by nvaytet** [comment]
Some plotting libraries (like `bokeh` and `plotly`) have mouse wheel zoom, which I find really nice to work with.
Automatic resampling when using a mouse wheel zoom seems difficult (it will be laggy).
It's probably better to zoom in as the library does it, and just ask for a resample when we've zoomed in too much (there could also be a keyboard shortcut?)

**Comment by nvaytet** [comment]
How does this work if you zoomed in quite far, and then you hit "resample" and then you want to use the panning tool.
The areas around the resampled view don't exist anymore?

What happens if you zoom out after resampling? Do you need to then automatically trigger a resample?

**Comment by nvaytet** [comment]
I guess this doesn't help with the issue we have that `counts` data gets diluted when image pixels are much smaller than the displayed bins.

**Comment by SimonHeybrock** [comment]
Maybe the resampling should not affect the original figure, but produce a new one (similar to how the profile is shown in a new figure).

**Comment by nvaytet** [comment]
This still doesn't solve the issue with panning after having resampled..

**Comment by SimonHeybrock** [comment]
> Some plotting libraries (like `bokeh` and `plotly`) have mouse wheel zoom, which I find really nice to work with.
> Automatic resampling when using a mouse wheel zoom seems difficult (it will be laggy).

You can drag with the middle mouse button in matplotlib to zoom.

**Comment by SimonHeybrock** [comment]
Stride support (added in #2423) may provide another option for plotting without actual resampling.

**Comment by SimonHeybrock** [comment]
Here is a concrete example of issues from resampling:
<img width="789" alt="image" src="https://user-images.githubusercontent.com/12912489/167416655-27c204b0-5b62-475d-8a3c-7f482e76dae6.png">

- Very low `vmin` makes actual data hard to see.
- "Glitches", i.e., dark blue pixels, from very small overlap of data pixels with display pixels
