### ISSUE TITLE
Bin utilities in Python

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#2170]
We have some helper functions in C++ to handle binned and non-binned variables transparently, e.g. (members of VariableFactory)
- `is_bins`
- `elem_unit`
- `elem_dtype`

Those are completely lacking in Python but providing them would simplify code; ideally as properties / methods of `Variable` and `DataArray`.

One could argue that `var.bins is not None` serves the purpose of `is_bins`. But I find `var.is_bins()` more expressive.

**Comment by SimonHeybrock** [comment]
I consider `var.bins is not None` more Pythonic. It also avoids having to remember yet another function name. It is also in line with `var.variances is not None` and thus easy to remember.

Apart from some internal code I have not seen much use if `elem_unit` and `elem_dtype`. Until that changes, I think it would be ok to add these as internal helper function, but not as methods or top-level functions of the scipp package.

**Comment by SimonHeybrock** [comment]
I'll close this, but feel free to implement `elem_unit` and `elem_dtype` as non-top-level helpers if needed.
