### ISSUE TITLE
Handle `del` in `meta` dicts properly

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#2174]
Using `del` on the `meta` dict of a DataArray returns without exception but does not affect the DataArray. It should either
- delete the element from `coord` or `attrs` of the parent (would likely require pointer-to-parent, so probably not an option.)
- raise an exception

**Comment by SimonHeybrock** [comment]
Item 1.) is indeed not an option (we had considered that at length during the design process). Item 2.) would require subclassing (possibly only on the Python side?).

**Comment by jl-wynen** [comment]
Is it not enough to modify the binding of `__delitem__`, potentialy by using a read-only flag?

**Comment by SimonHeybrock** [comment]
The problem is that `coords` and `meta` return and instance of the same type. That is why I say subclassing would need needed.

**Comment by SimonHeybrock** [comment]
Actually my logic on this is outdated. We have since added readonly flags, I believe we can use those. Working on a fix.
