### ISSUE TITLE
Further unify reduction operations code

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#2224]
We have several places with code for reduction operations:
- `dataset/groupby.cpp`
- `dataset/reduction.cpp` providing operations that require knowledge about masks
- `variable/reduction.cpp`
- `dataset/bins.cpp` for, e.g., `bins_sum`.

While a fair amount of code is already unified and relies on common methods, there is more to do, e.g., for initialization and mask handling. #2223 added another thing to unify, namely handling of event masks.

**Comment by jl-wynen** [comment]
Part of this is done in #2608 But there is still room for improvements.

**Comment by SimonHeybrock** [comment]
We are unlikely to make major further changes to the reduction code at this point. I'll close this since it has little use for now.
