### ISSUE TITLE
Faster converters from Mantid workspaces

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#223]
We have some basic Python converters, but they are slow for event data. When moving to larger data volumes we need something more performant.

Should this be part of `scipp-neutron`, or should we have, e.g., `scipp-compat-mantid`? We do not want a Mantid dependency on `scipp-neutron`, so probably the latter?

The main problem to solve is the dependency: Should Mantid depend on `scipp`... or `scipp` (or rather a special module) on Mantid, or is there a way to avoid this? Maybe we can define some lightweight "library" with a buffer used for exchange, Mantid could fill the buffer, and `scipp` could read from it. This could provide a more stable interface and would avoid issues with binary compatibility issues.

Probably this should be two tasks:
- [x] Solve slow pulse-time conversion (see comment below).
- [ ] Consider C++ converter?

**Comment by DanNixon** [comment]
The buffered approach is possible.

Mantid could create a named pipe which it informs the user of and starts filling it. scipp could have a function that takes the name of the pipe and starts consuming the data.

Data format would be handled by some shared code between Mantid and scipp.

**Comment by SimonHeybrock** [comment]
Got some pointers from Pete regarding at least solving the issue with expensive pulse-time conversion: https://docs.mantidproject.org/nightly/api/python/mantid/kernel/DateAndTime.html

> Pete Peterson:  https://github.com/mantidproject/mantid/blob/master/Framework/PythonInterface/mantid/kernel/src/Exports/TimeSeriesProperty.cpp#L93 connects through a registered convertor to https://github.com/mantidproject/mantid/blob/master/Framework/PythonInterface/core/src/Converters/DateAndTime.cpp
