### ISSUE TITLE
Think about more than 6 dimensions for Dataset

### ISSUE THREAD

**Issue by nvaytet** [scipp/scipp#225]
Currently, a `Dataset` is limited to 6 dimensions, just like the `Dimensions` class.
If we have 3 spatial (`Dim.x, Dim.Y, Dim.Z`) and say `Qx, Qy, Qz` then we have already reached the limit.
Limiting to 6 dimensions in the `Dimensions` class prevents expensive memory allocations by always having a fixed size array, but we should think about allowing for more in a `Dataset`.

**Comment by SimonHeybrock** [comment]
See also first bullet in item 7 of #58. `Dataset` should simply not use `Dimensions`. One option would be to create it (or rather a replacement that does not imply on order) on the fly, but that would imply a performance penalty. Should create an understanding of whether this is required in performance critical parts of the code.

**Comment by SimonHeybrock** [comment]
Not relevant any more since `Dataset` does not use `class Dimensions` now.
