### ISSUE TITLE
Requirements for eigen transform types

### ISSUE THREAD

**Issue by Tom-Willemsen** [scipp/scipp#2252]
We would like to support eigen transforms in scipp, for example to support the workflows in https://github.com/scipp/scippneutron/issues/34 . Document requirements and investigate similar libraries (e.g. can we be compatible with scipy apis).

**Comment by Tom-Willemsen** [comment]
After looking at the transform code available in eigen as well as comparable APIs in scipy, I'm suggesting the following API for 3d transformations, which I think would be sufficient for our current use-cases (for example https://github.com/scipp/scippneutron/issues/34), and is general enough to be useful for other use cases.

I have assumed for the moment that we don't need or want to support variances on transform types (similar to vectors and matrices currently).

Comments and suggestions welcome.

### Dtypes that need to be supported:

- `dtype=transform3d` 
  * internally Eigen's Transform type, which is a utility wrapper over a 4x4 matrix
  * when accessed using `.values` gives a numpy 4x4 matrix.

### Constructor/creation functions:

- `scipp.spatial.transform.from_affine_matrix(np.array) -> transform3d` (Make a transformation directly from the provided matrix coefficients
  * Error if last row of matrix is not `0 0 0 1` as it is then not an affine matrix
  * Error if the input is not a 4x4 array
- `scipp.spatial.transform.identity() -> transform3d` (no-op transformation, i.e. identity matrix)
  * Following function naming convention from [numpy](https://numpy.org/doc/stable/reference/generated/numpy.identity.html)
  * Do we want to move this function up to a higher level and be able to generate 3x3 identity matrices as well?
  * An alternative would be to overload `sc.ones` to give the identity transformation, but that seems like a potentially ambiguous/confusing API to me?

**Rotations**
Function names and the module structure here reflects [a similar API in scipy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.html).
- `scipp.spatial.transform.rotation.from_matrix(sc.matrix | np.array) -> transform3d`
- `scipp.spatial.transform.rotation.from_rotvec(sc.vector | np.array, sc.scalar | float) -> transform3d`
  * Can be implemented either as a wrapper around the similarly named function in scipy, or in c++ using Eigen.
- `scipp.spatial.transform.rotation.from_quat(sc.Variable | np.array) -> transform3d`
  * Replacing our current function `scipp.geometry.rotation_matrix_from_quaternion_coeffs`, unless there's a good reason to keep that function separately?
  * Can be implemented either as a wrapper around the similarly named function in scipy, or in c++ using Eigen.
- Further rotation constructors could be provided by thin wrappers over scipy's Rotation methods, this minimises implementation complexity.
  * `from_mrp`, `from_euler`
  * Currently I don't think we have a use-case for these - do we need/want to implement them immediately anyway?

**Translations**
There is no analogous API for these in scipy.
- `scipp.spatial.transform.translation.from_vec(sc.vector | np.array) -> transform3d`

**Scaling**
As far as I know we don't have a use-case for scaling yet, but it would make our transformation API more complete, and helper methods are available in Eigen. There is not an analogous API for this in scipy. We could leave this out, at least initially, if we think it adds too much complexity.
- `scipp.spatial.transform.scaling.from_const(sc.scalar | float) -> transform3d` (apply the given scaling factor to all axes)
- `scipp.spatial.transform.scaling.from_vec(sc.vector | np.array) -> transform3d` (apply different scaling factors to each axis)

We will also need plural versions of all the above creation functions (to keep consistent with `sc.matrix`/`sc.matrices`, `sc.vector`/`sc.vectors`, etc.).

### Operations

- `transform3d * vector -> vector` (apply transform to vector)
- `transform3d * transform3d -> transform3d` (Combine transforms into a single transform)
- `transform3d *= transform3d` (in-place combination with another transform)

**Comment by SimonHeybrock** [comment]
Will write a full comment later, just briefly two questions:

1. Scaling: Why can we not just use a scalar variable (without unit)?
2. Translation: Why can we not use a vector with correct unit? This can simply be added. Would need to support `*` operator with `AffineTransformation` to combine this?

**Comment by Tom-Willemsen** [comment]
>     Scaling: Why can we not just use a scalar variable (without unit) for scaling all axes? Can we use a vector for scaling each axis on its own? I suppose the latter would be ambiguous with a translation vector?
>     2. Translation: Why can we not use a vector with correct unit? This can simply be added. Would need to support `*` operator with `AffineTransformation` to combine this?

So I think what you're suggesting is that we should support the following operations:
- `transform3d + vector -> transform3d` (equivalent to `transform3d * translation.from_vec(vector)`
- `transform3d * scalar -> transform3d` (equivalent to `transform3d * scaling.from_const(scalar)`
- And presumably `+=` and `*=` variants of these
- Along the same lines we *could* choose to support `transform3d * matrix -> transform3d` for applying rotation matrices.

Are we worried about potential ambiguities with an expression like:

`transform + vector * scalar`

which has two potentially reasonable interpretations with different answers:
- translate by the vector and then scale by the scaling factor
- calculate `vector_for_translating * scalar` (which is a vector) and then translate by that amount

Whereas with the more explicit API, this type of ambiguity is removed

`transform * translation.from_vec(vector) * scaling.from_const(scalar)`.

---

In terms of 
> Can we use a vector for scaling each axis on its own? I suppose the latter would be ambiguous with a translation vector?

I think the operation you're suggesting is `transform3d * vector -> transform3d`, however I think this is ambiguous with the operation of applying a transformation to a vector `transform3d * vector -> vector`.

**Comment by SimonHeybrock** [comment]
> > ```
> > Scaling: Why can we not just use a scalar variable (without unit) for scaling all axes? Can we use a vector for scaling each axis on its own? I suppose the latter would be ambiguous with a translation vector?
> > 2. Translation: Why can we not use a vector with correct unit? This can simply be added. Would need to support `*` operator with `AffineTransformation` to combine this?
> > ```
> 
> So I think what you're suggesting is that we should support the following operations:
> 
>     * `transform3d + vector -> transform3d` (equivalent to `transform3d * translation.from_vec(vector)`

I don't think I am suggesting this, `Eigen` uses `*` to composite this. That is why it would be ambiguous with a scaling vector.

I think due to the ambiguity we may indeed need different dtypes `scaling` and `translation`.

**Comment by Tom-Willemsen** [comment]
I've edited my comment above to separate transformations into 5 separate dtypes, which can be combined with each other, following a discussion with @SimonHeybrock .

**Comment by SimonHeybrock** [comment]
I think you can move forward with step 1, adding things on the C++ side. You need to touch the following files:

- https://github.com/scipp/scipp/blob/main/lib/core/include/scipp/core/eigen.h
- https://github.com/scipp/scipp/blob/main/lib/variable/variable_instantiate_linalg.cpp
- https://github.com/scipp/scipp/blob/main/lib/core/include/scipp/core/element/arithmetic.h

I suggest you first try this with a single type, to see if there are unforeseen problems, and open a PR for review.

**Comment by SimonHeybrock** [comment]
There may be a fundamental problem or subtlety with affine transformations: While the rotation part does not have a unit, a translation does. Consider https://en.wikipedia.org/wiki/Affine_transformation#Augmented_matrix. The `b` part should possibly have the same unit is that vector the transformation is applied to? The other option would be to (conceptually) have the vector `(x_1 x_2 x_3 one)` where `one` has the same unit as the vector. That is, `b` would be dimensionless as well, and we would have the definition `y = Ax +b*one` (where `one` has a unit).

I think this is how it work automatically, but it would be slightly odd to have translations without units. The implication is also that we cannot create a translation from a "translation vector", since the latter would have the same unit is the vectors we want to translate. Example:

```python
# now
vec += offset  # unit='m'
# then
sc.translation(offset) * vec  # exception, since `offset` has a unit
```
So instead we would write:
```python
sc.translation(offset.values) * vec
```
But now the following is broken:
```python
sc.translation(offset.values) * vec.to_unit('mm')
```

Do we need to consider encoding a unit in a `translation`? It would not get multiplied with the vector, but compared?

**Comment by Tom-Willemsen** [comment]
> Do we need to consider encoding a unit in a `translation`? It would not get multiplied with the vector, but compared?

This seems like a reasonable approach to me. Just to be clear, we are suggesting something along the lines of:

```
sc.translation([1, 2, 3], units="m") * sc.vector([1, 2, 3], units="m") -> sc.vector([2, 4, 6], units="m")
sc.translation([1, 2, 3], units="m") * sc.vector([1, 2, 3], units="mm") -> UnitError("units don't match")
```

and similar for combining multiple translations together into one?

I think we can probably put this logic into `__mul__` (or one of the functions it calls at a lower level), but maybe it would be better to use explicit methods for applying and combining transformations? Something along the lines of

```
scipp.spatial.transform.apply(transform, vector) -> vector
scipp.spatial.transform.combine(transform, transform) -> transform
```

where this dtype/unit specific logic would make more sense than in the general multiplication function? It is a more verbose API for the users though.

**Comment by SimonHeybrock** [comment]
> > Do we need to consider encoding a unit in a `translation`? It would not get multiplied with the vector, but compared?
> 
> This seems like a reasonable approach to me. Just to be clear, we are suggesting something along the lines of:
> 
> ```
> sc.translation([1, 2, 3], units="m") * sc.vector([1, 2, 3], units="m") -> sc.vector([2, 4, 6], units="m")
> sc.translation([1, 2, 3], units="m") * sc.vector([1, 2, 3], units="mm") -> UnitError("units don't match")
> ```
> 
> and similar for combining multiple translations together into one?

Yes.

> I think we can probably put this logic into `__mul__` (or one of the functions it calls at a lower level), but maybe it would be better to use explicit methods for applying and combining transformations?

The problem with this is that the dtype checking logic would be messy and error prone, I fear?

> Something along the lines of
> 
> ```
> scipp.spatial.transform.apply(transform, vector) -> vector
> scipp.spatial.transform.combine(transform, transform) -> transform
> ```
> 
> where this dtype/unit specific logic would make more sense than in the general multiplication function? It is a more verbose API for the users though.

Maybe we could consider using the `@` operator, as numpy does for  matrix multiplication?

**Comment by Tom-Willemsen** [comment]
> The problem with this is that the dtype checking logic would be messy and error prone, I fear?

Potentially yes. Of course we can mitigate some of the "error-prone" component with tests, but I do agree that it's a bit messy and the logic feels like it's in the wrong place.

> Maybe we could consider using the `@` operator, as numpy does for matrix multiplication?

My feeling is that this transformation stuff may not be used frequently enough to justify a specific operator? We could start with an explicit function and introduce an operator shortcut for it later if it turns out to be used commonly?

**Comment by SimonHeybrock** [comment]
> > The problem with this is that the dtype checking logic would be messy and error prone, I fear?
> 
> Potentially yes. Of course we can mitigate some of the "error-prone" component with tests, but I do agree that it's a bit messy and the logic feels like it's in the wrong place.

There is a way to solve this on the C++ side, in the implementation of `operator*`: Instead of changing the kernel, add branching in `variable::operator*` (instead of generating it). Then we can handle the unit nicely in a specific operator.

**Comment by SimonHeybrock** [comment]
Regarding exposing access to, e.g., the `linear()` part of `Affine3d`: It turns out this it not really possible, at least not as `Matrix3d`: Since the underlying matrix is stored as a normal 4x4 matrix, the 3x3 "linear" part has padding between elements. We thus cannot access only that part (without making a copy).

We still have the option to return the *values* of the linear part as a `Nx3x3` numpy array (with strides), but it is not clear if that is useful, for now.

**Comment by SimonHeybrock** [comment]
One option to avoid this issue would be to use a custom type for `Affine3d`, storing the linear part and the translation part independently. This would imply that we could not expose a 4x4 matrix, but we could:

```python
transform.fields.linear  # Variable of dtype=Matrix3d
transform.fields.translation  # Variable of dtype=Vector3d
```

**Comment by SimonHeybrock** [comment]
Discussion results:

dtype \ input | float | [x,y,z] | [x,y,z,w] | 3x3 | 4x4 |
--- | --- | --- | --- | --- | --- |
scalar | sc.scalar | - | - | - | - |
vector | - | sc.vector | - | - | - |
translation | - | sc.translation | - | - | - |
rotation | - | from_rotvec | sc.rotation | *defer* | - |
linear_transform | *reject* | from_scaling | *reject* | sc.linear_transform | - |
affine_transform | *reject* | *ambiguous, reject* | *reject* | *reject* | sc.affine_transform |

Notes:
- Use `from` in function names if input "dtype" is not output dtype?
- `linear_transform_from_scaling` or in module name?
- Right now `from_rotvec` is creating matrix, should create quaternion instead?
- Implement operations with scalar scalings, e.g., scalar * quat -> linear_transform
- `sc.vector(value=[1,2,3]).astype('translation')` too inconvenient => support `sc.translation`
- Do not support `sc.affine_transform(rotation=3x3, translation=[1,2,3])` since it is undefined which order rot and trans are applied
- Rename quaternion dtype to `rotation`
- `sc.rotation` should throw user-friendly exception if called with 3x3 matrix, referring to alternative function (making linear_transform) instead
- Rename `vector_3_float64` -> `vector`
- Rename `matrix_3_float64` -> `matrix` or `linear_transform`?
  => survey

**Comment by SimonHeybrock** [comment]
I believe everything needed here has been merged now.
