### ISSUE TITLE
Plots not shown when using `nb_conda_kernels`

### ISSUE THREAD

**Issue by arm61** [scipp/scipp#2275]
Once `nb_conda_kernels` is installed scipp plots no longer show up in a Jupyter Lab. Instead given the following error messages 

```
Error displaying widget: model not found
```

Possibly linked to?
- https://github.com/Anaconda-Platform/nb_conda_kernels/issues/201
- https://github.com/Anaconda-Platform/nb_conda_kernels/issues/206

**Comment by SimonHeybrock** [comment]
If I understand the answer https://github.com/Anaconda-Platform/nb_conda_kernels/issues/201#issuecomment-901068937 correctly, if you ensure that you install the correct/same ipympl version in the envs it should work?

**Comment by nvaytet** [comment]
See also:
- https://github.com/matplotlib/ipympl/issues/328
- https://github.com/jupyter-widgets/ipywidgets/issues/2628

**Comment by SimonHeybrock** [comment]
As we now default to making static figures, part of this problem can be avoided. Is it worth keeping this open? I am not sure there is much we can do apart from this?
