### ISSUE TITLE
Unused reduction functions

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#2298]
`nanmean` and `nansum` in `dataset/dataset_operations_common.h` are unused. Is this intentional or are we missing functions that would use them?

**Comment by SimonHeybrock** [comment]
What leads you to conclude they are unused?

**Comment by jl-wynen** [comment]
They were flagged in CLion and I removed them and everything compiled.

**Comment by SimonHeybrock** [comment]
@jl-wynen Since I could not reproduce this, have you figured out what is going on?

**Comment by jl-wynen** [comment]
No, I haven't. I suggest removing the one function where we agree that it is unused and leaving the rest.
