### ISSUE TITLE
Use builtin `configparser` instead of `python-configuration`

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#2312]
For some reason we are using the non-standard [python-configuration](https://github.com/tr11/python-configuration) library for scipp's config files. It cannot even be googled properly and it is unclear how well maintained it is. I suggest to switch to using the built-in [configparser](https://docs.python.org/3/library/configparser.html) instead.

**Comment by jl-wynen** [comment]
We could also use YAML since we already use that. Or does the builtin package have additional features?

**Comment by SimonHeybrock** [comment]
I don't know. I don't mind which solution we choose, provided that it is concise code and only used builtins?

**Comment by SimonHeybrock** [comment]
Of course I overlooked the requirement to *write* to the config. YAML and `ConfigParser` would be fine for just reading. We may consider something like https://github.com/beetbox/confuse, which seems more supported and established that `python-configuration`?

**Comment by SimonHeybrock** [comment]
Note: Ensure that writing config values from script does *not* update config file.

**Comment by SimonHeybrock** [comment]
Related(?) packages used currently: appdirs, pyyaml.

What do we really need, what can be avoided?
