### ISSUE TITLE
NaN value(s) in Dataset coordinates break open_hdf5

### ISSUE THREAD

**Issue by g5t** [scipp/scipp#2327]
If a `Dataset` contains a coordinate with a `numpy.nan` then it can not be retrieved after storage in a HDF5 file.
Such a coordinate may be, e.g., the result of a center-of-mass calculation for a quantity which is all zeros.

```python
import scipp
import numpy
x = scipp.Variable(values=[0, 1, numpy.nan, 3], dims=['x'], unit='m')
y = scipp.Variable(values=[3, 2, numpy.nan, 2], dims=['x'], unit='counts')
i = scipp.Variable(values=[0.1, 0.2, 0.3, 0.4], dims=['x'], unit='amp')

ds = scipp.Dataset(data={'y': y, 'i': i}, coords={'x': x})
ds.to_hdf5('test_scipp_dataset_nan_coord.hdf5')

scipp.io.open_hdf5('test_scipp_dataset_nan_coord.hdf5')
```
throws a `VariableError` with message
```python
VariableError: Expected
<scipp.Variable> (x: 4)    float64              [m]  [0.000000, 1.000000, nan, 3.000000], got
<scipp.Variable> (x: 4)    float64              [m]  [0.000000, 1.000000, nan, 3.000000].
```

A `Dataset` with only one `data` entry (or a `DataArray`) and one or more NaN values in a coordinate can be saved and re-loaded.
The problem is apparently in a comparison between `DataArray` coordinates and may be accessible elsewhere.

I would have guessed that combining `DataArray`s with the same coordinates would raise the same error, but
```python
day = scipp.DataArray(y, coords={'x': x})
dai = scipp.DataArray(i, coords={'x': x})
scipp.Dataset(data={'y': day, 'i': dai})
```
does not.

I think this is a problem with comparing coordinates before combing the constituent `DataArray`s since `numpy.nan == numpy.nan` is always `False`. Would it be possible to change the coordinate-comparison to treat two NaN values as equal?

**Comment by g5t** [comment]
Another related(?) error pops up when attempting to filter-out the NaN coordinate values:
```python
ds.coords['bad'] = scipp.isnan(ds.coords['x'])
filtered_ds = scipp.groupby(ds, group='bad').copy(0)
```
with `ds.coords['bad']` equal to `<scipp.Variable> (x: 4)       bool  [dimensionless]  [False, False, True, False]` throws
```python
VariableError: Expected
<scipp.Variable> (x: 3)    float64              [m]  [0.000000, 1.000000, nan], got
<scipp.Variable> (x: 3)    float64              [m]  [0.000000, 1.000000, nan].
```
So the wrong values are grouped into the `ds.coods['bad'] == False` group *and* the NaN comparison issue is present.

**Comment by SimonHeybrock** [comment]
I believe this is just a generic error of how coords are handled in operations involving 2 data arrays (which includes insertion into a `Dataset`): Coords are compared using `operator==`. At first sight treating NAN==NAN for coord comparison could make sense, but we will need to have a closer look and discussion whether we could switch such a comparison.

**Comment by SimonHeybrock** [comment]
> I would have guessed that combining DataArrays with the same coordinates would raise the same error [...]

Note that is due to an "optimization": If the buffer pointers are equal, values are not compared. This inconsistency is a good indicator that the current approach is wrong: We should either always compare all values, or treat NAN as equal to NAN.
