### ISSUE TITLE
Add `rename` methods for `Variable`, `DataArray`, and `Dataset`

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#2338]
Our `rename_dims` method was added because that is the name in `xarray`.... or so I thought: Actually only `xarray.Dataset` has this method. Furthermore, it (now) only renames dims, not coords.

Add `Variable.rename`, `DataArray.rename`, and `Dataset.rename` methods that renamed coords as well as dims. See https://xarray.pydata.org/en/stable/generated/xarray.DataArray.rename.html for details, and follow the same pattern (support dict as well as keyword args).

Xarray's `DataArray.rename` also support renaming the array, which feels odd to have in the same method? Maybe we can skip that?

**Comment by nvaytet** [comment]
Should we keep the `rename_dims` method, or should `rename` replace it?
