### ISSUE TITLE
Rethinking tags and global structure of class Dataset

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#234]
### Current status and shortcomings

Triggered by our discussion yesterday, I started thinking more about how data is identified via tags in `Dataset`. Essentially the current situation is:

- Variables in a dataset are identified by a key composed of a tag and a name. The name can be empty, in which case it can be omitted.
- Tags come in three classes, `Coord`, `Data`, and `Attr`.

Initially in the design there used to be a variety of different data tags. However, due to recent changes, mainly the added support for sparse data (see #207), essentially all data tags but `Data.Value` and `Data.Variance` became superfluous. This would make a potentially more intuitive access as suggested by a reviewer in https://github.com/scipp/scipp/pull/4#issuecomment-445320309 feasible.

For coordinates the situation is more complicated. We have to distinguish between dimension coordinates and non-dimension coordinates.
- The former have a tag corresponding to a dimension name, e.g., `Coord.X` and `Dim.X` (similar to `xarray`, which accomplishes the same with string-based name matching).
- The latter are in principle arbitrary and should ideally be user-definable. With the existing tag system this is slightly cumbersome. We could for example use `{Coord.User, "sample temperature"}` as a key.

Sparse data complicates the situation further:
- Coordinates for sparse data are specific to their data, e.g., we have `{Coord.Tof, "sample"}` corresponding only to the data for `"sample"`, but none of the other data entries.
- There can also be non-dimension coordinates for sparse data, e.g., the pulse times for neutron event data. This is currently identified via `{Coord.PulseTimes, "sample"}`, i.e., relies on a hard-codes tag specific to the application.

Another aspect are "monitors" in the case of neutron data reduction. These can in principle be handled as coordinates, data, or attributes, depending on the application. If the monitors are "global" to a dataset this works quite well with the current tag+name mechanism. However, the mechanism falls apart as soon as we require data-specific monitors. We would need a three-part key such as `{Coord.Monitor, "sample", "transmission"}`.

### Potential solution

We propose a different solution for discussion, eliminating the need for tags, and fixing some (but not all) of the problems discussed above.

1. Global dimension coordinates are accessed via their dimension tag:
   ```python
   d.coord(Dim.X) # the X coordinate
   d.coord(Dim.Y) # the Y coordinate
   ```
2. Global non-dimension coordinates are accessed via a name (this eliminates the need for any tags that do not have a corresponding dimension):
   ```python
   d.coord("spectrumNumber") # the spectrum number coordinate
   d.coord("temperature") # a temperature coordinate; note that temperature could also be a dimension coordinate in other cases, if there is Dim.Temperature
   ```
3. Data-specific variables are accessed based on indexing into the dataset with the data name:
   ```python
   d["sample1"].data # the data values
   d["sample1"].variance # the variances for the data values
   d["sample1"].coord(Dim.Tof) # in case of sparse data: data-specific dimension coordinate
   d["sample1"].coord("pulse-time") # in case of sparse data: data-specific non-dimension coordinate
   ```

##### Pros
- No tags in API.
- More intuitive way to access data and variance.
- Custom coords are more naturally supported.
- No special tags for "user" coordinates of sparse data required.
- Looks more similar to `xarray.Dataset` API (but still has major differences).

##### Cons
- Maybe more complicated implementation? Might still need tags internally?
- Other?

##### Unsolved/unclear
- Data-specific monitors still do not appear to supported naturally. Would a special `monitor` section (similar to the `variance` or `coord` section) help?
- Should `d["sample1"]` provide access to global coordinates? This would be convenient in operations, similar to what we accomplish with `d.subset["sample1"]`. However, we need to find a clear definition of how data-specific coordinates override global coordinates.

**Comment by SimonHeybrock** [comment]
Looking at this section from above suggestion:
```python
d["sample1"].data # the data values
d["sample1"].variance # the variances for the data values
d["sample1"].coord(Dim.Tof) # in case of sparse data: data-specific dimension coordinate
d["sample1"].coord("pulse-time") # in case of sparse data: data-specific non-dimension coordinate
```
We could consider going even one step further: Values and their variances are not separate entities. Essentially it should always be true that:
- They have the same data type.
- They have the same unit (or rather, the variance has the square of the units).
- They have the same dimensions and dimension order.

From this point of view it would be sensible to move away from the current implementation which handles values and variances as two independent `Variable` instances. Rather, we would consider a new class that holds both values and variances (as two separate arrays).

On the other hand, such a change would make it harder to operate only with data or variances on their own. This is mainly of concern for implementing new built-in operations or custom operations that are not based on existing built-ins. Some concepts of the current implementation might need to be completely revised.

This is an unfinished consideration, I have not reached a conclusion on this one yet.

**Comment by SimonHeybrock** [comment]
Fleshing out some details for the previous comment:

1. It is probably better to *not* store coordinates in `Variable` itself. Just having them in `Dataset` simplifies the implementation. That is, above interface is indeed only valid for the proxy object returned by `d['sample1']`. `Variable` would be missing the `coords` property.

2. Storing values and variances in the same variable has pros and cons.
   - Pros:
     - Simplified implementation of operations for `Dataset`.
     - Can potentially support "automatic" propagation of uncertainties with lambdas passed to `transform` (first introduced in #205).
     - Simplified handling of units and dimensions in the proxy returned by `d['sample1']`.
     - Data layout (2 arrays, vs. array of structures) can probably be hidden from most parts of the high-level interface.
   - Cons:
     - Complicated implementation and not insignificant amount of extra code in `Variable`.

**Comment by OwenArnold** [comment]
Seems reasonable to me. There are few things about this I'd like to discuss, but better done in a real conversation.
