### ISSUE TITLE
`sc.bin` should look at attrs as well as coords

### ISSUE THREAD

**Issue by nvaytet** [scipp/scipp#2341]
Doing
```Py
wavelength_edges = sc.linspace(dim='wavelength', start=2.0, stop=16.0, num=11, unit='angstrom')
sc.bin(da, edges=[wavelength_edges])
```
fails when the event data of `da` has a `wavelength` attribute, but not a coordinate.
A workaround can be done with
```Py
da.bins.coords['wavelength'] = da.bins.attrs.pop('wavelength')
```

The `bin` operation should be looking in both `coords` and `attrs` when looking for the event coord.

**Comment by SimonHeybrock** [comment]
I suppose problems like this may be another indicator that we should try to move forward with what we started discussiing in https://github.com/scipp/scipp/issues/2213 --- remove 'attrs' as they are (to make room for non-variable-based attrs later) and just use coords/meta for aligned/unaligned coords?
