### ISSUE TITLE
Improve behavior of scipp's Python dtype class

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#2371]
Compare:

```python
import numpy as np
np.arange(5.0).dtype == 'float64'  # True
np.arange(5.0).dtype == float  # True
np.arange(5.0).dtype  # repr is dtype('float64')
```

```python
import scipp as sc
sc.scalar(5.0).dtype == 'float64'  # False
sc.scalar(5.0).dtype == float  # False
sc.scalar(5.0).dtype  # repr is float64
```

I think we should:

- Allow comparison with string and Python dtypes (and numpy dtypes).
- Add `__str__` to `__repr__` can be more precise instead of just printing a stirng representation.
- Consider changing `scipp.dtype` from a module to a class. Registered dtypes could be added as static properties.

#2369 is one of probably several examples where a better behavior would have been helpful.

**Comment by jl-wynen** [comment]
Do we actually need the predefined dtypes? Or would it be enough if comparison with float and classes is supported? In constructors, you can also use strings or classes. If one wants an actual dtype object, one can use (assuming corresponding udpates) `sc.DType('float64')`, just like in numpy.

**Comment by SimonHeybrock** [comment]
Not sure. I think a case can be made for either. I think this would be an independent decision?

I think we also should rename `DType` to `dtype`.

**Comment by jl-wynen** [comment]
> I think we also should rename DType to dtype.

It would then be the only class with a lowercase name

**Comment by SimonHeybrock** [comment]
I was thinking of consistency with numpy, but maybe that is not a good argument.

**Comment by jl-wynen** [comment]
Lowercase is nicer to type. But I would prefer a consistent naming scheme. Especially since people rarely need to type it anyway.

For context, tensorflow uses `DType` (https://www.tensorflow.org/api_docs/python/tf/dtypes/DType), PyTorch uses `dtype` (https://www.tensorflow.org/api_docs/python/tf/dtypes/DType). Both use PascalCase for class names elsewhere.
Not sure what xarray does, it does not seem to have a class for it?

**Comment by jl-wynen** [comment]
Comparing with numpy dtype is finicky. Making `sc.DType == np.dtype` work is easy, this calls our `__eq__`. But the other way round, `np.dtype == sc.DType` calls numpy's `__eq__`, which does not know how to handle `sc.DType`. I'm digging into the implementation a bit to see if there is a solution...

**Comment by jl-wynen** [comment]
There is also [NEP 42](https://numpy.org/neps/nep-0042-new-dtypes.html) which might be useful. But even though it has been accepted, it looks like it can't be used yet.
```.py
    class DType(np.dtype):
        type: int
```
Raises `/home/jl/Work/scipp-1/tests/dtype_test.py`

**Comment by jl-wynen** [comment]
For later reference: It is possible to make numpy kind of interoperate with our dtype using
```.py
class DType:
  @property
  def dtype(self) -> np.dtype:
     # convert to numpy dtype
```
But this would fail for types that cannot be represented by numpy (e.g. vector*).

I suggest we implement `sc.DType == np.dtype` but not the reverse for now. When the NEP42 API is stabilised, we should be able to make the comparisons work in general and maybe allow for even more interoperability.
