### ISSUE TITLE
Add more standard operations

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#2375]
Add methods to Variable, etc:
- `__abs__` calling `sc.abs`
- ~`__matmul__` calling `sc.dot`~ (see discussion below)

**Comment by SimonHeybrock** [comment]
Is `__matmul__` really what `sc.dot` does?

**Comment by jl-wynen** [comment]
Sorta. Our dot is a bit odd because it operates along an inner dimension. But Everywhere else, the two are synonymous. So I don't see why we wouldn't support it.

**Comment by SimonHeybrock** [comment]
> Our dot is a bit odd because it operates along an inner dimension.

That is what a dot-product does? What is odd about that? It is very different from matmul as far as I understand.

> But Everywhere else, the two are synonymous. So I don't see why we wouldn't support it.

`dot` only supports vectors. It is defines as `v^T w`, i.e., this is not matrix multiplication.

**Comment by jl-wynen** [comment]
> hat is what a dot-product does?

Other packages define dot as contracting the axes that meet in the middle. This works for matrices, vectors, and any mixture of higher rank tensors. And `matmul` is simply an alias for `dot`.

> What is odd about that?

In numpy, et al, `dot` acts on the dimensions of the arrays, not dtypes.

**Comment by SimonHeybrock** [comment]
Reading the [numpy docs](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html):

> If the second argument is 1-D, it is promoted to a matrix by appending a 1 to its dimensions. After matrix multiplication the appended 1 is removed.

This sounds a bit odd and hard to understand for me?

Given that we simply use `__mul__` for matrix products (scipp can, while numpy cannot), what would be the reason for using `@` for dot-product?

**Comment by jl-wynen** [comment]
> This sounds a bit odd and hard to understand for me?

Yes. I had actually misunderstood it all these years. And the distinction between matmul and dot is subtle.

I checked the definition of the inner / dot product for matrices and it differs from what I had always used and is in particular not the same as matrix multiplication. This means that we should not use the same operator for `sc.dot` and products of matrices.
But that brings up another question: Should we use `__matmul__` for (transformation) matrices instead of `__mul__`? Following my argument from earlier (which I think you told me a while ago) that this multiplication acts on the dtypes and not the dimensions of the variable, the current solution is the right choice.

**Comment by SimonHeybrock** [comment]
> Should we use __matmul__ for (transformation) matrices instead of __mul__? Following my argument from earlier (which I think you told me a while ago) that this multiplication acts on the dtypes and not the dimensions of the variable, the current solution is the right choice.

Not sure. For me using `__matmul__` would mean: "The operands are matrices", but in our case we have arrays of matrices. If we *did* use `__matmul__`, that might give the impression that the arrays should be treated as matrices (which we do not (and do not want to) support)?

**Comment by SimonHeybrock** [comment]
I feel the `__matmul__` thing is just an artifact from having no dimension labels in numpy, i.e., it cannot distinguish between array dims and matrix dims. We don't have that issue, so we can just use `__mul__` like in normal mathematical notation?

**Comment by jl-wynen** [comment]
> I feel the __matmul__ thing is just an artifact from having no dimension labels in numpy, i.e., it cannot distinguish between array dims and matrix dims. We don't have that issue, so we can just use __mul__ like in normal mathematical notation?

I don't know if you can sensibly name dimensions for matrices. Seen as a transformation, a matrix maps vectors from a vectorspace into that same space. So both dims would have the same name. And really, matrix operations deal with positional indices, i.e. `A` is different from `A^T`.

There used to be `np.matrix` whose `__mul__` was a matrix multiplication. But that caused problems because of Python's dynamic type system. So they added `__matmul__` into the language, this is similar to `__div__` and `__truediv__`.
For us, the situation is slightly different. We distinguish multiplication based on an 'inner type', not the type of the variables (lowercase) we are multiplying. So conceptually, at a high level, we always do an element-wise multiplication. (Even though we do distinguish between `__div__` and `__truediv__`...)
