### ISSUE TITLE
Use nb-clean

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#2376]
Following the discussions in the UX workshop, maybe we should start using https://github.com/srstevenson/nb-clean

It can remove outputs from notebooks automatically when committing them.

**Comment by SimonHeybrock** [comment]
Also consider adding this to https://github.com/scipp/scipp/blob/e7b7cce7499615994a177c2a622dc8514c9a2cbe/.github/workflows/pr_and_main.yml#L18-L28.
