### ISSUE TITLE
Misleading axis labels in plots of Variables

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#2394]
The plot below shows 'wavelength' on the x-axis and only the unit on the y-axis. This looks like we are plotting an unnamed variable with unit Å against a dimensionless wavelength.
I think the 'wavelength' label should be placed on the y-axis.

![misleading_plot](https://user-images.githubusercontent.com/11393224/150977310-571c84e8-f5eb-4251-80b9-718ce431b68d.png)

**Comment by SimonHeybrock** [comment]
> I think the 'wavelength' label should be placed on the y-axis.

Initially I thought I agree, the x-axis is just an integer index. But then I starting considering a `DataArray` without a coord:

<img width="734" alt="image" src="https://user-images.githubusercontent.com/12912489/151108154-20e7ab2a-81f9-41ab-9eea-4c2b07f45a76.png">

I think here it is correct? We *are* plotting a dimensionless quantity against an (x) index so the 'x' label should indeed be on the x-axis.

Now, the question is, what is our interpretation when plotting a `Variable`. I suppose there are two possibilities:

1. Treat a variable like a data array without coords. This is the choice the current implementation makes.
2. Treat a variable like an independent variable (see https://en.wikipedia.org/wiki/Dependent_and_independent_variables), in this case we should indeed place the `wavelength` (dim) label on the y-axis.

First of all, does the above make sense? If so, we can start a discussion about whether there is a "correct" interpretation (1. or 2.).

- Note that 2.) would imply that `da.plot()` and `da.data.plot()` would yield different results
- Note that 2.) is possible only for 1-D variables. For 2-D there is no choice. That is, results between say `var.plot()` and `var['x', 0].plot()` would be different.

**Comment by SimonHeybrock** [comment]
@jl-wynen Comments?

**Comment by jl-wynen** [comment]
I agree with your assessment, in particular about DataArrays.

> - Note that 2.) would imply that da.plot() and da.data.plot() would yield different results

I don't think this is a problem. The latter explicitly states that you don't want to see coords.

> - Note that 2.) is possible only for 1-D variables. For 2-D there is no choice. That is, results between say var.plot() and var['x', 0].plot() would be different.

This is a strong argument against changing it.

Maybe we have to interpret variables int he following way. A variable assigns a value to each point along its dimensions. THose dimensions can be, e.g. 'wavelength'. But that does not meant hat the variable encodes a wavelength but only a value that varies with wavelength. What the variable actually encodes depends on its name, or by extension, if it is used as a coord or data of a DataArray.

I think whether a variable is dependent or independent is determined by its usage.

So I would say, we keep the current behaviour.

**Comment by SimonHeybrock** [comment]
> I think whether a variable is dependent or independent is determined by its usage.

Indeed, unless we want to introduce a different class for the two uses there is not much we can do. Should we but a "won't fix" on this one?
