### ISSUE TITLE
Unit of comparison results

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#2396]
Currently element-wise comparison operators such as `==` or `<` return a variable with unit `dimensionless`. With the introduction of variables without unit (`var.unit == None`) in #2395 the question is whether this is still the right choice. Should we use `None` instead?

On the surface, one argument against the use of `None` would be that we may want to do arithmetic based on the result of a comparison operator. This would be prevented if `None` was use.
Historically this has however led to bugs such as those fixed in, e.g., https://github.com/scipp/scipp/pull/2133 (and if I remember correctly this was not the first such bug). If the bool-valued masks had had `unit == None` then multiplying the mask into the data to "apply" the mask would not have been possible, and the bug (treating NaN incorrectly) would have been prevented. It is likely that users may try the some faulty approach.

Another argument is that `True` or `False` are not quantities (except for very special cases when they may be used for a very small problem domain to save memory), i.e., saying "`True` is a dimensionless quantity" sounds quite odd.

Even just considering the implementation, using `None` would make more sense. For example, say we compare `5.0 kg == 6.0 kg`. `kg == kg` may be `True` but not `dimensionless`. That is, the result is not in the space of possible units. What justifies using `dimensionless`?

A related question is that of the (default) unit used for integers. Obviously `5 kg` *is* a sensible quantity, but the use of integers is a special case and in most cases integers appear to be used as "indices". Indices are not quantities. Similar to the bugs from arithmetic with bool-valued variables, we can imagine errors from using indices in arithmetic: `da.coords['detector_id'] * da.data` is currently valid, since the `detector_id` coord is a "dimensionless quantity". If we were to default to using `unit == None` for integer-valued variables then this operation (which is not sensible, since `detector_id` is an arbitrary ID with no physical meaning) would be prevented.

The above discussion would imply:

- Change default-unit of integer dtypes (including `bool`) to `None`. Note that without this default label-based indexing such as `da['detector_id', sc.scalar(2342)]` would not work (`unit-None` would have to be specified explicitly).
- Change unit returned by element-wise comparison operators to `None`
- Adapt logical operators to handle this.

**Comment by jl-wynen** [comment]
I looked online for material about this topic. But all I could find were papers about treating physical quantities as elements of a vector space. They didn't talk about objects outside of that space or how to connect them. Only that 'pure numbers' belong to the special basis element 'dimensionless'. But the discussions focused entirely on real numbers, I guess because nothing else seems to be physical. So I don't think there is a theoretical foundation for what we are doing. But this only matters for the interaction of quantities and values without a unit.

> On the surface, one argument against the use of None would be that we may want to do arithmetic based on the result of a comparison operator.  [...]

I am unsure whether units are the right tool for preventing arithmetic. Strictly speaking, within boolean arithmetic, these operations are perfectly fine. But if we want to prevent them for safety reasons, we should disable the operations directly (by way of the dtype selection in `transform`) and not through an auxiliary mechanism like units.

Concerning the default for integers, I am not sure what is more common or natural to think of, indices or counts. I would tend to to consider integers special cases of real numbers and treat them in the same way regarding units.
One could maybe consider indices to be quantities in a special array dimension. Since we don't have a dedicated unit for that, dimensionless should be fine. This would also be required to allow arithmetic with indices which is often needed when manipulating arrays.
So I would still use 'dimensionless' for all integers unless it is specifically set to 'none' by the user.

Concerning booleans, there are essentially two ways of viewing them. Either as integers in a very small domain, or as abstract truth values. If we disallow arithmetic with booleans (by whatever means we choose), only the second view makes sense. So we could then remove their unit.

**Comment by SimonHeybrock** [comment]
> But if we want to prevent them for safety reasons, we should disable the operations directly (by way of the dtype selection in transform) and not through an auxiliary mechanism like units.

Not sure I agree. Especially in the case of integers that are two perfectly valid uses: a) as an index and b) as a quantity, possibly to optimize for the domain of the application (e.g., avoid rounding errors), or time offsets.

> I am not sure what is more common or natural to think of, indices or counts.

Since we have a special unit for counts, we would rarely want to use a "default" of dimensionless to represent that (unless you meant "counts" in its more general meaning).

> One could maybe consider indices to be quantities in a special array dimension. Since we don't have a dedicated unit for that, dimensionless should be fine. This would also be required to allow arithmetic with indices which is often needed when manipulating arrays.

Is required though? As it is in the PR, we *do* support arithmetic (+-*/) between two `None` units.

> Concerning booleans, there are essentially two ways of viewing them. Either as integers in a very small domain, or as abstract truth values. If we disallow arithmetic with booleans (by whatever means we choose), only the second view makes sense. So we could then remove their unit.

I am not sure disabling arithmetic gives us anything? As you say there are two ways of viewing them (same as for integers), so why not allow arithmetic, if we can safely distinguish the cases based on the presence of a unit or not?

**Comment by jl-wynen** [comment]
> > But if we want to prevent them for safety reasons, we should disable the operations directly (by way of the dtype selection in transform) and not through an auxiliary mechanism like units.
> 
> Not sure I agree. Especially in the case of integers there are two perfectly valid uses: a) as an index and b) as a quantity, possibly to optimize for the domain of the application (e.g., avoid rounding errors), or time offsets.

I was only talking about booleans. We should definitely not remove the ability to do integer arithmetic.

> > I am not sure what is more common or natural to think of, indices or counts.
> 
> Since we have a special unit for counts, we would rarely want to use a "default" of dimensionless to represent that (unless you meant "counts" in its more general meaning).

I meant any kind of counts, like '3 apples'.

> > One could maybe consider indices to be quantities in a special array dimension. Since we don't have a dedicated unit for that, dimensionless should be fine. This would also be required to allow arithmetic with indices which is often needed when manipulating arrays.
> 
> Is required though? As it is in the PR, we _do_ support arithmetic (+-*/) between two `None` units.

I thought you disabled it (didn't read the PR yet). So can we arbitrarily combine variables with 'none' units but not with variables that have a unit including dimensionless?

> I am not sure disabling arithmetic gives us anything? As you say there are two ways of viewing them (same as for integers), so why not allow arithmetic, if we can safely distinguish the cases based on the presence of a unit or not?

Normally, one would (or should) think of booleans as truth values and not integers. From what I have heard, doing arithmetic with them is discouraged. But I kind of agree, limiting what is possible might not be the right way.

I just realised that a 'none' unit represents two different cases. Firstly, 'this value is not a physical quantity and cannot have a unit' and second, 'I don't currently know the unit but I will add it later'. Does it make sense to represent both in the same way? Or should a missing unit be reserved for the latter? The former could simply be dimensionless.

**Comment by SimonHeybrock** [comment]
> >  Is required though? As it is in the PR, we do support arithmetic (+-*/) between two None units.
>
> I thought you disabled it (didn't read the PR yet). So can we arbitrarily combine variables with 'none' units but not with variables that have a unit including dimensionless?

Correct. You can add, multiply, ... *indices* with each other, but you cannot add an index to a dimensionless quantity such as a friction coefficient.

**Comment by SimonHeybrock** [comment]
> I just realised that a 'none' unit represents two different cases. Firstly, 'this value is not a physical quantity and cannot have a unit' and second, 'I don't currently know the unit but I will add it later'. Does it make sense to represent both in the same way? Or should a missing unit be reserved for the latter? The former could simply be dimensionless.

You also refer to our discussion on Slack, concluding that units from files that cannot be parsed should be `None`? I think you may have a point, using `None` may be misleading for that. `llnl::units` does define an "invalid" unit (iirc), maybe that could be used?

**Comment by jl-wynen** [comment]
According to the docs, "invalid" can be produced by operations. I don't know how, so we have to ensure that we don't overlap with that case. Maybe a check like the overflow check would work, that is, throw an exception if an operation produces 'invalid'.

**Comment by SimonHeybrock** [comment]
> According to the docs, "invalid" can be produced by operations. 

We are catching this case and raise an exception. `llnl::units` does not use exceptions, so this is added in our wrapper.

**Comment by jl-wynen** [comment]
Ok. Then 'invalid' sounds like a good choice. But of course, we need to wrap it properly so as to not confuse users.

**Comment by nvaytet** [comment]
If you had `None` as a default unit for integers, it would mean that you could do
```Py
2 * sc.arange('x', 10, unit='m')
```
but not
```Py
sc.scalar(2) * sc.arange('x', 10, unit='m')
```
Wouldn't that be a bit strange?
I think `dimensionless` makes more sense for integers. They are numbers after all. It shouldn't matter whether you are using them as indices or something else.

**Comment by SimonHeybrock** [comment]
> Wouldn't that be a bit strange?

You could write `2.` instead of `2`, or use `step=2`.

**Comment by nvaytet** [comment]
```Py
sc.scalar(2.) * sc.arange('x', 10, unit='m')
```
would work, and
```Py
sc.scalar(2) * sc.arange('x', 10, unit='m')
```
would throw... this is also strange

**Comment by SimonHeybrock** [comment]
I think I see your point regarding `sc.scalar(2) * sc.arange('x', 10, unit='m')`. More importantly, since `int` and `float` is promoted to scalar variables in operations, the following would not work any more either:

```python
var *= 2  # exception, assuming var.unit is not None
```

Apart from that, I was reconsidering our discussion regarding loading, e.g., raw Nexus files. We had previously "decided" in a standup call that we should use the default unit if the HDF5 dataset has no `units` attribute. I now consider this problematic. In many cases such datasets are actually just indices. Furthermore, this would imply that we block/lose the ability to save data back to Nexus, since our construction/loading process would impose default units.

Therefore, based on the two items above, how about this modified proposal:

- Comparison results (`bool`) default to `None` unit.
- Construction of `bool` variables defaults to `None` unit.
- Default for `int` stays `dimensionless`.
- Nexus loading (in scippneutron) should treat missing `units` attributes as `None`, *not* as "default unit"
- Add one or a couple convenience functions for creating indices. I think the first is essential, the others not so much:
  ```python
  sc.index(5)  # returns 0-D variable with unit=None
  sc.index_array(...)  # like sc.array with unit=None
  sc.index_range(...)  # like sc.arange with unit=None
  ```
  Without `sc.index` we would make label-based indexing cumbersome. Compare:
  ```python
  da['spectrum', sc.scalar(14)]  # current, a bit weird since "scalar" sounds misleading
  da['spectrum', sc.scalar(14, unit=None)]  # Would be required if we load with None units, as proposed
  da['spectrum', sc.index(14)]  # same as previous, but even cleared than current?
  ```

**Comment by SimonHeybrock** [comment]
@jl-wynen @nvaytet Could I ask for your thoughts on my last suggestion? Cheers!

**Comment by jl-wynen** [comment]
Makes sense.

Given the discussion in #2413, 
> Construction of bool variables defaults to None unit.

sounds like a good idea as that would propagate the `None` unit and indicate that something is fishy.

I don't think that `index_array` and `index_range` are necessary. There are already quite a lot of creation functions. And we rarely construct indices by hand. This might change if we support #1815 with arrays in label based indexing.
