### ISSUE TITLE
Handle comparisons with numbers

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#2411]
Since we require units for basically every operation, comparing a scipp Variable and a builtin number is not supported. Still comparisons are possible, e.g. `sc.array(dims=['x'], values=[0.0, 1.0]) == 0.0` gives `False`.

Similarly, comparisons with numpy arrays always return False.

I am unsure what is the best behaviour here. But the current one seems dangerous. In numpy, such a comparison operates element-wise. So a user might expect the same from a Variable. We could
- raise `TypeError` and not allow that comparison at all. That seems bad because in principle, everything can be compared with everything else.
- raise `UnitError` because the unit of the RHS is not known. Again, it is not great that the comparison is not allowed.
- Actually allow comparisons and operate on the `.values`. 
- Only allow comparisons with scalar 0 as neither the dimension nor unit matters in that case.

**Comment by SimonHeybrock** [comment]
Since we support `var + 1.0` (by treating `1.0` as `sc.scalar(1.0)`) I think the consistent solution would be to do the same here.
