### ISSUE TITLE
Bool gets promoted in groupby ops

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#2413]
Given
```python
da = sc.DataArray(sc.array(dims=['x'], values=[True, False]),
                  coords={'x': sc.array(dims=['x'], values=[1, 2])})
```
this
```python
sc.groupby(da, group='x').sum('x')
```
returns the data as `int64`
and
```python
sc.groupby(da, group='x').mean('x')
```
returns the data as `float64`.

Is this intentional? I think it is strange to promote booleans in this way.

**Comment by SimonHeybrock** [comment]
Yes, this is intentional. `sum` and `mean` (without `groupby` in the loop) have the same behavior.

Would you raise an exception instead?

**Comment by jl-wynen** [comment]
Not sure. In the case where I encountered it, the bool Variable cannot be handled in this way because the average of `True` and `False` is not defined. So maybe an exception would be the right solution. But I don't know if this would prevent other operations.

**Comment by SimonHeybrock** [comment]
```python
import numpy as np
np.mean(np.array([True, False]))
```
works though.

You could possibly use a `None` unit to prevent taking the `mean` or `sum` in such cases, but I am not sure if that is useful.

Unless you have a better suggestion, I suggest to close.

**Comment by jl-wynen** [comment]
Ok. Let's not break with numpy compatibility.
