### ISSUE TITLE
Support datasets with more dimensions?

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#2415]
We are currently hard-coding the maximum number of dimensions. In the case of `Dataset`, it can be essential to support more. For example, consider the case of storing multiple independent time-series, i.e., a "time" dimension that is not aligned. While scipp does not support such "unaligned" dimensions/coords within a dataset, it can easily be emulated:

```python
import scipp as sc
ds = sc.Dataset()
ds['series1'] = sc.linspace(dim='time1', start=0.0, stop=0.4, num=10)
ds['series2'] = sc.linspace(dim='time2', start=0.1, stop=0.4, num=4)
```
There are multiple other applications to this, beyond time series. One notable one is storing detector banks of mismatching logical size, loaded from a Nexus file.

It is important to note that supporting more dimensions in `Dataset` does *not* imply that `transform` must support more. We should therefore move to two independent limits:

- Keep hard-coded maximum number of dimensions that `transform` can handle (note that this could in principle be the number *after* flattening dimensions, which is done internally in `transform`).
- Large (in principle unlimited) number of dimensions in `Dataset` (or possibly other objects).

The simplest way to achieve this without resulting in more memory allocations might be to change `class Sizes` (base of `class Dimensions`) to use `boost::container::small_vector` instead of fixed-sizes arrays. `MultiIndex` (used in `transform`) would be left untouched.

**Comment by jl-wynen** [comment]
What is the reason for combining such data in a single dataset? Do they have other coords in common and only one / some coords are unaligned?
I am wondering if this would actually be useful or if it would introduce a lot of complication from handling unaligned coords manually.

**Comment by SimonHeybrock** [comment]
> What is the reason for combining such data in a single dataset? Do they have other coords in common and only one / some coords are unaligned?

Yes there typically is a lot of common metadata.

Apart from that, you are certainly right that we could use a plain `dict` of `DataArray` instead. But you lose a lot of convenience. For example, you need to write a loop to save to HDF5, or write a loop to plot.

**Comment by nvaytet** [comment]
> For example, you need to write a loop to save to HDF5, or write a loop to plot.

I don't think you need a loop to plot, because you can send a dict to `sc.plot`
