### ISSUE TITLE
Release and packaging pipeline

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#2454]
We have a couple of "issues" with our current setup:

- #2452 had to introduce a hack to install a Sphinx plugin. This is an consequence of running docs build as part of `conda build`.
- `meta.yaml` defines a long list of "build" requirements that are actually requirements for the docs build.
- Wheel and conda package builds a 2 separate workflows. Should consider unifying this such that uploads happen only if all pass.
- Docs build could be done on packaged scipp, as a separate job.
- No one uses `scipp/label/dev` conda packages. This is a waste of resources.
- Docs get updated when a new "dev" package is made, i.e., does not reflect state the users sees when installing scipp

Incomplete suggestion:

- Do not make `scipp/label/dev` packages any more.
- Remove docs build from `meta.yaml`.
- Merge wheel and conda build workflow into a single workflow.
- Add a job to build the docs based on a package made in one of the previous jobs (conda or pip). Could consider publishing conda packages to a `staging`/`rc` label for this purpose, and relabel to `main` only if docs build passes.

**Comment by nvaytet** [comment]
> Docs get updated when a new "dev" package is made, i.e., does not reflect state the users sees when installing scipp

Should we stop updating the docs for the latest `main`?

**Comment by SimonHeybrock** [comment]
> > Docs get updated when a new "dev" package is made, i.e., does not reflect state the users sees when installing scipp
> 
> Should we stop updating the docs for the latest `main`?

We are not doing that right now either. This is only part of the `scipp/level/dev` build (once per week), so if we remove that build, it implies the docs will not update either.

**Comment by nvaytet** [comment]
yes, i guess it's fine it it's our responsibility to check the docs when we make PRs.
I just think in the past, it's been useful to have the latest docs online, because you happen to be browsing them and notice something is wrong, but you cannot browse all the docs every time there is a PR, there are just too many pages...

**Comment by nvaytet** [comment]
That said, it would be nice if the pages at the root level, were just a copy of the latest release, so that users would land on the released version, not the dev pages

**Comment by SimonHeybrock** [comment]
> yes, i guess it's fine it it's our responsibility to check the docs when we make PRs. I just think in the past, it's been useful to have the latest docs online, because you happen to be browsing them and notice something is wrong, but you cannot browse all the docs every time there is a PR, there are just too many pages...

Agreed, but docs are for users, not for us. We could push the dev docs to a subfolder, instead of root.
