### ISSUE TITLE
Consider dimension scales in HDF5

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#2472]
From https://github.com/scipp/scipp/pull/2463#discussion_r815724040:

> Somewhat related: I recently learned about [HDF5 Dimension Scales](https://docs.h5py.org/en/stable/high/dims.html) and wondered whether we should be using that?

Looks pretty interesting. But I think this cannot work for us because of binned coordinates. It looks like a dimension scale needs to be a HDF5 dataset. But we encode binned variables as groups.

**Comment by SimonHeybrock** [comment]
> But I think this cannot work for us because of binned coordinates. It looks like a dimension scale needs to be a HDF5 dataset. But we encode binned variables as groups.

Actually, all variables are encoded as groups, since there may be values in addition to variances.
