### ISSUE TITLE
Add docs page on reshaping data: fold, flatten, concat...

### ISSUE THREAD

**Issue by nvaytet** [scipp/scipp#2476]
It would be good to have a nice page explaining the behaviour of fold and flatten (also with bin edges), and how they can be used to reshape one's data.

For example, one of the very common (and most useful) tricks that new users miss is concatenating along a new dimension.

**Comment by jl-wynen** [comment]
This seems like a fairly specific page. Not sure we should add it and make the table of contents longer. My feeling is that the reference of those functions should be sufficient (it might need to be extended.) We could add some explanation in the free_functions/shape section.

**Comment by SimonHeybrock** [comment]
Isn't having the function reference in sections a basic way of doing this? See https://scipp.github.io/reference/free-functions.html#shape.

Regarding tricks: Have you considered adding something to https://scipp.github.io/user-guide/tips-tricks-and-anti-patterns.html, if you can think of a generic example?

**Comment by nvaytet** [comment]
Yes, the tips page is probably the right place for this
