### ISSUE TITLE
Should `groupby(...).copy()` shallow-copy rather than deep-copy untouched metadata?

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#2479]
Generally any scipp operation that affects a dimension X but not Y, will shallow-copy meta data (coords and attrs) that do not depend on X, including all scalar meta data.

The two variants of `copy()` supported by groupby deep copy *all* meta data. This should probably be changed?

**Comment by SimonHeybrock** [comment]
> It seems to me like we should stick with deep=True by default for all functions called copy

You mean *change to*, not *stick with*? That would make scipp inconsistent with Python and other Python libraries.

> But we can add this arg to the groupby copy to allow users to get a shallow copy.

I really do not think this is the same. For the majority of data (in terms of size) `groupby(...).copy()` cannot avoid making a copy. This affects only some meta data, similar to how other operations such as `da2 = da + 42` return new data but shallow-copy meta data.

**Comment by jl-wynen** [comment]
> You mean change to, not stick with? That would make scipp inconsistent with Python and other Python libraries.

`Variable.copy` is deep by default.

I am only concerned about the name of the method. If we have `copy` which is deep for some classes and shallow for others, it might cause confusion. If we called it `extract` or `get` or something along those lines, I would be fine with making shallow copies by default.

**Comment by SimonHeybrock** [comment]
> Variable.copy is deep by default.

`DataArray.copy` is not. And I do not think this is inconsistent or that it should be changed.

> If we have copy which is deep for some classes and shallow for others

So you are concerned that `groupby(...).copy()` should not be called `copy` because it has to make a deep copy out of necessity?

**Comment by jl-wynen** [comment]
> DataArray.copy is not. And I do not think this is inconsistent or that it should be changed.

Yes it is: https://scipp.github.io/generated/classes/scipp.DataArray.html#scipp.DataArray.copy

**Comment by SimonHeybrock** [comment]
Ok, I guess I did not sleep enough :(

**Comment by SimonHeybrock** [comment]
We may consider adding a `deep=False` option (or options that only influence behavior for meta data), but that is unrelated to what I posted here.
