### ISSUE TITLE
Print configuration error at the end of CMake output if external dependencies fail to install

### ISSUE THREAD

**Issue by nvaytet** [scipp/scipp#257]
Currently, if I don't have `mercurial` installed, when trying to clone `Eigen`, I get the following error in the middle of the `CMake` output:
```
CMake Error at /usr/share/cmake-3.10/Modules/ExternalProject.cmake:2335 (message):
  error: could not find hg for clone of Eigen
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/ExternalProject.cmake:3029 (_ep_add_download_command)
  CMakeLists.txt:6 (ExternalProject_Add)

-- Configuring incomplete, errors occurred!
See also "/home/nvaytet/work/code/scipp/source/build/Eigen-download/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.
```
However, I only see this if I scroll back up and carefully go through the output.
The end of the `CMake` output looks like
```
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK -- success
-- Found Threads: TRUE  
-- Boost version: 1.69.0
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- LTO enabled
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nvaytet/work/code/scipp/source/build
```
which leads me to believe that everything went well during the configuration process.
I think it would be useful to have a global message at the end to confirm that everything went ok or that there were some errors.

**Comment by SimonHeybrock** [comment]
Looks like some incomplete requirements/dependencies setup in our build script. Probably here: https://github.com/scipp/scipp/blob/master/CMake/Eigen.cmake?

Also, maybe we should download a archive/release version with cmake, so we avoid `hg`? Most people don't have it installed by default, so this issue keeps coming up.
