### ISSUE TITLE
Printing variable with `unit=None` shows `[None]`

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#2578]
Example:
```
{'module': <scipp.Variable> (module: 10)      int64           [None]  [1, 2, ..., 9, 10],
 'segment': <scipp.Variable> (segment: 6)      int64           [None]  [1, 2, ..., 5, 6],
 'counter': <scipp.Variable> (counter: 2)      int64           [None]  [1, 2],
 'wire': <scipp.Variable> (wire: 32)      int64           [None]  [1, 2, ..., 31, 32],
 'strip': <scipp.Variable> (strip: 256)      int64           [None]  [1, 2, ..., 255, 256]}
```
It should be `None` or nothing at all, not `[None]`.

**Comment by jl-wynen** [comment]
What about `[]`? In order to keep the general pattern of having square brackets.

**Comment by SimonHeybrock** [comment]
Possible, but does `[]` risk to be confused with dimensionless?

**Comment by jl-wynen** [comment]
What about `[/]`? I am asking because seeing `<scipp.Variable> (counter: 2)      int64           None  [1, 2]` might not make it clear what `None` refers to.

**Comment by SimonHeybrock** [comment]
Completely unclear? How about `<no unit>`?

**Comment by jl-wynen** [comment]
Could work
