### ISSUE TITLE
Bad handling of dtype argument for data array

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#2582]
This
```.py
sc.scalar(0, dtpye=sc.DataArray)
```
creates
```
<scipp.Variable> ()   PyObject           [None]  [0]
```
i.e. it stores a Python `int`, which is probably not what the user wanted. We should throw an error instead.

There are probably more cases like this.

**Comment by SimonHeybrock** [comment]
Any idea what is going on? We is it treating `sc.DataArray` as pyobject?

**Comment by SimonHeybrock** [comment]
Numpy exhibits the same behavior:
```python
import numpy as np
np.array([1], dtype=dict)
```
gives
```
array([1], dtype=object)
```

**Comment by jl-wynen** [comment]
So any type passed to `dtype` that numpy (or scipp) does not understand decays to `object`? And since everything in Python is an object, it does not matter which value you pass in? Seems to make sense.
But we do have a special dtype for `DataArray`. So we should not treat it as `object`.

**Comment by SimonHeybrock** [comment]
Conclusion:

`sc.scalar(0, dtype=int)` works, thus, as `sc.DataArray` is a valid element type `sc.scalar(0, dtype=sc.DataArray)` should not produce something else. However, as there is no valid constructor we should raise an exception instead.
