### ISSUE TITLE
Remove or replace assert_export

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#2594]
`testing.common.assert_export` is broken and hides errors. For example, 
```.py
def test_cumsum():
    var = 1 * sc.units.m
    assert_export(sc.cumsum, a=var)
    assert_export(sc.cumsum, a=var, dim='x')
    assert_export(sc.cumsum, a=var, inclusive=False)
    assert_export(sc.cumsum, a=var, dim='x', inclusive=False)
```
incorrectly uses `inclusive=False` instead of `mode='exclusive'`.
This is hidden by `assert_export` because of its filter: `if 'incompatible function arguments' in ex.args[0]:`. The error message is 'TypeError: cumsum() got an unexpected keyword argument 'inclusive''

Removing the filter on the message makes very few tests fail. And all have similar errors. So I propose to remove the filter and re-raise all `TypeErrors`.

I also checked other exceptions and there is again only a small number of tests that fail if we propagate all exceptions from `assert_export`. And those are easily fixed. (In `test_cumsum`, all that is needed is to turn `var` into an array with dim 'x'.) So I propose to also remove that filter.

This means that `assert_export` only calls the given function and does nothing else. So we can remove it altogether. Or we preserve it for documentation purposes. That is, test implementations contain the word 'assert' which might make them easier to understand. Also, this would allow us to add extra logic in the future if we need to.

**Comment by SimonHeybrock** [comment]
I believe `assert_export` predates the introduction of widespread Python wrappers of C++ functions. Back then it was really typically sufficient to test that the export existed. With the wrappers we have now, we should really be testing that the Python wrapper calls the correct C++ function (e.g., `sin` should not call `_scipp.core.cos`). So maybe an argument for removing `assert_export` entirely?

**Comment by SimonHeybrock** [comment]
Should this be closed now?

**Comment by jl-wynen** [comment]
Possibly. Unless we want to completely remove `assert_export`?

**Comment by SimonHeybrock** [comment]
Might be a good idea.
