### ISSUE TITLE
Promote warnings to errors in CMake compiler flags

### ISSUE THREAD

**Issue by nvaytet** [scipp/scipp#261]
Currently builds on Travis pass even if compiler warnings are present.
We could consider adding the `-Werror` compiler flag to catch them and cause builds to fail if new warnings have suddently appeared.
#168 might have to be fixed first though.

**Comment by SimonHeybrock** [comment]
https://embeddedartistry.com/blog/2017/5/3/-werror-is-not-your-friend

**Comment by SimonHeybrock** [comment]
Long discussion (with differing opinions) here: https://news.ycombinator.com/item?id=12155223

**Comment by SimonHeybrock** [comment]
-> Just enable locally or in CI, such as to not prevent people with different compilers from building the project.

**Comment by SimonHeybrock** [comment]
This has been done on the build servers, but is not enabled by default for developer builds.
