### ISSUE TITLE
Where to put counts-related functionality?

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#263]
Scipp is handling "counts" using the units of data. For example, we can have unit `units::counts` or `units::counts / units::us` for a density.

There are a couple of operations that require this:
- `histogram` generates data with unit "counts".
- `rebin` (and other similar algorithms) work differently (or not at all) depending on whether you pass counts, densities (or something else).

With recent changes, unit systems can be defined at compile time, so we may end up with systems that do not have "counts".
- Should we put `histogram` and `rebin` into `scipp::neutron` (which has a unit system with counts)? This would work, but is not ideal since in principle `histogram` and `rebin` are not neutron-specific.
- Enable compilation of `histogram` and `rebin` within `scipp::core` conditionally at compile time, depending on whether the unit system contains counts? This would require addition of a special mechanism to define/identify "counts" units in `scipp::units` in custom unit systems.
- Something else?

**Comment by nvaytet** [comment]
So i guess you will always have at least `dimensionless` in your units system, even if nothing else.
So you could say that if `counts` is found in the units system, then use that for `rebin` and `histogram`, and if it is not, you could use `dimensionless` instead?

**Comment by SimonHeybrock** [comment]
For now I have no restrictions for names or units contained in a system. So someone could have `units::none` instead of `units::dimensionless`, or not support it at all. Maybe we need to require defining which label refers to the dimensionless one (and optionally on refering to counts)?

**Comment by SimonHeybrock** [comment]
Actually, as long as `none` is just another name for `boost::units::is::dimensionless` what I said above is not relevant. And maybe we should just require having that.

**Comment by OwenArnold** [comment]
I agree that `rebin` and `histogram` are not neutron specific, so it would be nice to keep them in `scipp::core`. As a relatively minor point - counts itself is a term that may not be natural in other domains, particularly those that are not dealing with detectors.

**Comment by SimonHeybrock** [comment]
> As a relatively minor point - counts itself is a term that may not be natural in other domains, particularly those that are not dealing with detectors.

So what would you suggest instead?

**Comment by OwenArnold** [comment]
Occurances/Events/Observations.

**Comment by SimonHeybrock** [comment]
Events would make sense to me, but according to google and wikipedia "counts" is prevailing.
