### ISSUE TITLE
`arange` should use dtype of provided variables

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#2639]
```python
import scipp as sc
sc.arange('x', start=sc.scalar(2, dtype='int32'), stop=sc.scalar(4, dtype='int32'))
```
should yield dtype='int32', not 'int64'

**Comment by jl-wynen** [comment]
Numpy always converts to int64:
```.py
>>> np.arange(np.int32(3)).dtype
dtype('int64')
>>> np.arange(np.array(3, dtype='int32')).dtype
dtype('int64')
```
Should we deviate from this?

**Comment by SimonHeybrock** [comment]
> Should we deviate from this?

I don't think we should.... except when we have *variables* as input. The reason is that in this case the variables may typically originate from things such as the `min` and `max` of another variable, e.g., of a coord we want to bin or group. Having the same integer width would be useful then.

**Comment by jl-wynen** [comment]
But the same reasoning applies to numpy because
```.py
>>> type(np.max(np.array([1, 2], dtype='int32')))
<class 'numpy.int32'>
```

**Comment by SimonHeybrock** [comment]
Then deviate from that as well?

**Comment by jl-wynen** [comment]
The numpy implementation contains a comment that the dtype is 'intentionally at least NP_LONG'. But digging through the git history, I found that the comment appeared in an unrelated commit. So I don't know what the intention actually is.

**Comment by SimonHeybrock** [comment]
Is there anything that can break if we implement this? Otherwise I do not see a good argument against it?

**Comment by jl-wynen** [comment]
As long as `start` and `stop` are both int32 (or not given), it should be safe.
