### ISSUE TITLE
More convenient API for `transform_coords`

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#2660]
The current function signature is https://github.com/scipp/scipp/blob/284fb18871c7fa6c8a5501a0a415c9b13775e701/src/scipp/coords/transform_coords.py#L16-L24

We are starting to see more and more opportunities for using `transform_coords` (eleminating custom and error-prone code) where just a single new coord is computed. See for example scipp/scippneutron#237. The current syntax that required listing of targets and graph separately leads to duplication and is not very user friendly. For example, we may have:

```python
da.transform_coords('temperature', graph={'temperature':make_temperature})
```
which can feel intimidating to non-expert users. In the above example we could instead imagine writing:

```python
da.transform_coords(temperature=make_temperature)
```

Proposed new function signature for discussion (working dummy code so you can try it out):

```python
import scipp as sc
from typing import Union, Iterable, Optional, Callable, Dict

def transform_coords(x: Union[sc.DataArray, sc.Dataset],
                     targets: Optional[Union[str, Iterable[str]]] = None,
                     /,
                     graph: Optional[dict] = None,
                     *,
                     rename_dims: bool = True,
                     keep_aliases: bool = True,
                     keep_intermediate: bool = True,
                     keep_inputs: bool = True,
                     quiet: bool = False,
                     **kwargs: Dict[str, Callable]) -> Union[sc.DataArray, sc.Dataset]:
    print(x, targets, graph, kwargs)
```

- `targets` should be position-only, I think?
- Should `graph` be keyword-only? I think there is utility in supporting calls with *only* a dict, i.e, `targets` would double as graph: `da.transform_coords({'weird dim name':func})`

**Comment by nvaytet** [comment]
I think
```Py
da.transform_coords(temperature=make_temperature)
```
looks nice, but I am not so keen on the potential name clashes it introduces. There are quite a number of keyword args, although I agree that most of them don't sound like the name of a coord, but you never know?

I also don't really like the possible alternative of having a different function name for the convenience wrapper (e.g. `transform_single_coord`), because it would make two options for doing the same thing (and you'd have to remember which function does what).

You say that it's often for a single coord, but your syntax would support multiple coords: `da.transform_coords(temperature=make_temperature, pressure=make_pressure)`
Was that intentional? Or would the use case almost always be for a single coord? (not sure if that helps the discussion...)

**Comment by SimonHeybrock** [comment]
> There are quite a number of keyword args, although I agree that most of them don't sound like the name of a coord, but you never know?

Of course "you never know", but is this really an issue? In the rare case of a clash we still provide the option of doing the transform in a more verbose syntax. And I don't think there is a risk of doing the wrong thing either? So the only argument here is "there are edge cases where a different syntax has to be used" (but it is actually the same syntax used for multi-step transform, i.e., not really different at all).

**Comment by SimonHeybrock** [comment]
> I also don't really like the possible alternative of having a different function name for the convenience wrapper (e.g. transform_single_coord), because it would make two options for doing the same thing (and you'd have to remember which function does what).

I don't think I am suggesting it can *only* be used for a single coord... that is just the most common application I see so far.

> You say that it's often for a single coord, but your syntax would support multiple coords: da.transform_coords(temperature=make_temperature, pressure=make_pressure)
Was that intentional? Or would the use case almost always be for a single coord? (not sure if that helps the discussion...)

Yes, this is intentional, it would of course work for multiple coords. Consider this example:

```python
da.transform_coords(r=..., phi, ...) \
  .hist(r=100, phi=100) \
  .plot()
```
to transform to polar coordinates and make a plot.

**Comment by jl-wynen** [comment]
When given multiple coords, would those be allowed to depend on each other? That is, is
```.py
da.transform_coords(a=fa, b=fb)
```
equivalent to (allows interdependence)
```.py
da.transform_coords(['a', 'b'], {'a': fa, 'b': fb})
```
or (allows b to depend on a but not the other way around)
```.py
da.transform_coords(['a'], {'a': fa})
  .transform_coords(['b'], {'b': fb})
```
or would a and b be computed in isolation from each other?

**Comment by SimonHeybrock** [comment]
I think maybe the keyword args should simply "update" the `graph` dict, and the answers to your questions derive from that definition?

**Comment by nvaytet** [comment]
About the potential name clashes in the arguments, I guess if we really wanted to be safe, we could check the types of `rename_dims`, `keep_aliases`, `keep_intermediate`, `keep_inputs`, `quiet` and raise (or warn) if they are callable (or non-boolean)?

**Comment by SimonHeybrock** [comment]
Yes we can add such as check. I think otherwise we would get error messages that are too confusing.

**Comment by SimonHeybrock** [comment]
I suggest a make quick implementation so we can try it out ourselves, and have something concrete to discuss.
