### ISSUE TITLE
Unit conversions

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#267]
The basic unit conversions have to be refactored to work with the rewrite of `Dataset`. The multi-dimensional version ~is probably not worth the effort right now~ should be ignored/removed for now since it is badly written and probably completely wrong.

Should also think about how to generalize the code such that more conversions and conversion paths can be added more conveniently.

Note that with support for arithmetic operation between sparse and dense data we will get conversions for event data "for free" (that is, simply use the sparse coordinate in binary operations with the geometry-derived factors/offsets), we simply need to ensure that we process the sparse coordinates.

**Comment by SimonHeybrock** [comment]
Part 1 in #356.

**Comment by SimonHeybrock** [comment]
@DanNixon It would be worth considering adding conversion back to TOF, since this appears to be used in data reduction in several places. If it is not much extra code, you could add it now as well.

**Comment by DanNixon** [comment]
@SimonHeybrock One issue I keep facing is having to define intermediate units (i.e. those of factors, etc. that may not be sensible usually) in `supported_units`. Is there a better way to do this or is one planned?

**Comment by SimonHeybrock** [comment]
This is expected. Some intermediate units can maybe be avoided by using a better order of operations. We "plan" to find a better units library (ideally run-time), but as far as I am aware there is no real alternative to `boost-units` available right now.
