### ISSUE TITLE
Histogramming `data` (not along a coordinate)

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#2676]
Given an array of statistical samples, one might want to histogram them to estimate the distribution. E.g.
```.py
da = sc.DataArray(sc.array(dims=['sample'], values=...),
                  coords={'sample': sc.arange('sample', n_samples)})
np.histogram(da.data.values, bins=100, density=True)
```
It would be good if this could be done without resorting to numpy. One solution might be supporting `sc.Variable` in `sc.hist[ogram]`.

**Comment by SimonHeybrock** [comment]
Not sure where the data array in your code example comes in, but yes, histogramming a variable is something I ran into previously and I agree that we should probably support it. If ultimate performance is not critical we can simply make a fake data array with `ones` as values and forward to the existing implementation.

**Comment by SimonHeybrock** [comment]
It is easy to get this to work, but slightly odd:
```python
da.coords['x'].hist(abc=10)
```
will result in a histogram with dimension `abc`. While explicitly given it feels a bit surprising that this assign meaning to the variable in the first part of the expression.
