### ISSUE TITLE
Make size_of recursive

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#2677]
Currently, `size_of` does not recursively get the sizes of data arrays nested in variables in attributes. This means that the reported size can be greatly underestimated. In particular when there are high-resolution time-series logs in attributes.

Note that we cannot reliably get the size of variables with `dtype=object`. But we can recurse into scipp objects.

E.g. 
```.py
s = sc.scalar(sc.DataArray(sc.arange('x', 100)))
print(s.__sizeof__())
print(s.value.__sizeof__())
```

**Comment by SimonHeybrock** [comment]
This also affects `dtype=string`:
```python
s = 'abc' * 1000
sc.scalar(s)
```
reports 32 bytes.

**Comment by jl-wynen** [comment]
Producing a reliable size if quite difficult. We can double count arrays that appear multiple times. E.g. an attribute shared by multiple dataset entries. Dataset has special handling for coords. But doing this for attrs is very complicated and expensive.

Where do we draw the line? What is the purpose of `__sizeof__`?

**Comment by SimonHeybrock** [comment]
The purpose is the size display in the HTML repr. In particular also to identify objects that are a slice of something large (and may keep that alive).
