### ISSUE TITLE
Support `__bool__` in some cases?

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#2691]
This came up from a user question. Currently we cannot use `if sc.scalar(1, unit='m') < sc.scalar(2, unit='m')`.

#2529 implemented `__float__` and `__int__`. The conditions there are:

- Only supporting `Variable` (not `DataArray`).
- No variance.
- 0-D, `shape=(1, )` is *not* ok.
- `unit=1` or `unit=None`.

Are the same conditions sensible for `__bool__`? I am unsure about support for `unit=1`, but deviating may also add confusion?

**Comment by jl-wynen** [comment]
Sounds like a good idea.

Numpy also supports this:
```.py
>>> if np.array(1) < np.array(2): print('works')
...
works
```

> I am unsure about support for unit=1, but deviating may also add confusion?

Conceptually, I would say we only support `unit=None` as otherwise the variable might encode something different than a pure truth value. And the only way to construct a bool variable with `unit=1` is by doing it by hand. All builtin operations set the unit to None.

**Comment by nvaytet** [comment]
Agreed, this will be a good addition. It's been confusing to a number of users that the `.value` is always needed.
The set of rules above look good, and I also agree with supporting only `unit=None`, not `unit=1`.

**Comment by jl-wynen** [comment]
> Should we only support dtype=bool?

Not sure. `int` and `float` convert the type. So maybe it should be `bool(var) == bool(var.value)` (plus constraint checks). That would mean that `bool(sc.scalar([1, 2])) == True`

**Comment by g5t** [comment]
:+1: This would also support more-easily using reduction operators, e.g.

```python
import scipp as sc
a = sc.array(values=[1,2,3,4,5], dims=['x'], unit='m')

if sc.any(a == sc.scalar(3, unit='m')):
    print('Do something cool')
```

Which is nicer than the currently-valid equivalent `sc.any(...).value`
