### ISSUE TITLE
Deleting from Dict while iterating segfaults

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#2696]
This code segfaults:
```.py
import scipp as sc
da = sc.DataArray(sc.scalar(3),
                  attrs={'a': sc.scalar(1),
                         'b': sc.scalar(2),})
for k in da.attrs:
    del da.attrs[k]
```

The operation cannot really be allowed and using a Python dict instead is unreliable as well (might work or might raise an exception). But we should raise instead of crash.

Specifically, it looks like the iterator itself causes the segfault after the first deletion. It thinly wraps a `boost::transform_iterator` (observed the same with `da.attrs.items()` which uses `std::unordered_map::iterator`). So we are probably dealing with dangling pointer. Detecting / avoiding them could turn out very complicated.

**Comment by SimonHeybrock** [comment]
I am starting to wonder if this can be considered a bug in pybind11?

**Comment by jl-wynen** [comment]
As I understand it, pybind11's iterators are intended as thin wrappers around C++ iterators. Fixing this in pybind11 would require implementing a specialised iterator for `std::map`. I doubt that they will do that.

**Comment by SimonHeybrock** [comment]
Could an implementation of iteration on the Python side to avoid this problem?

**Comment by jl-wynen** [comment]
If we would copy the map into a dict, yes.

I don't even know how to detect whether it is safe to continue using an iterator. It depends on when the underlying (unordered) map moves its data.
