### ISSUE TITLE
Plotting data with coords with different units is broken

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#2724]
```.py
x = sc.linspace('x', 0, 1000, 100, unit='mm')
a = sc.DataArray(x, coords={'x': x})
b = a.copy()
b.coords['x'] = b.coords['x'].to(unit='m', copy=True)
sc.plot({'a': a, 'b': b})
```
Results in
![Figure 3](https://user-images.githubusercontent.com/11393224/181257085-f5e8137c-eeb7-4489-8200-c5cfecf101a7.png)

**Comment by SimonHeybrock** [comment]
Note that this also works with `seconds` and `meter`, i.e., it is not just the unit *scale* that is ignored.
