### ISSUE TITLE
IPython output history prevents objects from being deleted

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#2737]
We frequently use and recommend to use the "HTML" repr (`__repr_html__`) to inspect objects. However, this places the object in the IPython output history. This will keep temporaries alive, and named objects are *not* freed after `del myobj`, since there is another ref in the history. This is a major pitfall, and we should consider what we can do to ameliorate:

- Add FAQ entry (run `%reset out`)
- Explain how to set `c.InteractiveShell.cache_size = 0` in `ipython_kernel_config.py`
- Provide function to display HTML and recommend using that instead of relying on `__repr_html__`.
- Should we consider disabling `__repr_html__`? Or at least providing an option to alert the user?
- Other options?

Try in a Jupyter cell:
```python
import scipp as sc
sc.zeros(dims=['x'], shape=[1_000_000_000])
```
and run repeatedly. This eats more and more memory.

Now compare to:
```python
import scipp as sc
sc.zeros(dims=['x'], shape=[1_000_000_000])
1
```

This is of course not Scipp-specific, same with NumPy:
```python
import numpy as np
np.ones([1_000_000_000])
```

**Comment by jl-wynen** [comment]
Is there a way to detect how much memory ipython uses and show a warning in `__repr_html__` when memory is getting low?
