### ISSUE TITLE
Use official action to deploy GH pages

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#2747]
https://github.com/actions/deploy-pages

Might help fix deployment issues with benchmarks and coverage reports. But the action is still in beta.

**Comment by SimonHeybrock** [comment]
Looking at https://github.com/actions/starter-workflows/blob/main/pages/static.yml I don't think this is doing what you think it is: This is for *deploying* the pages (which currently happens automatically on push, without custom action). You still have to put the generated HTML into the docs repo (or the `gh_pages` branch).

Please have a look. If you come to the same conclusion I suggest to close?

**Comment by jl-wynen** [comment]
It looks to me like you can avoid uploading anything to a repo. You just need an artefact and that can be deployed. So it seems as though we could do away with the `gh-pages` branch or deicated repos?

**Comment by SimonHeybrock** [comment]
But where would we store the docs of previous releases? We cannot build them every time.

**Comment by jl-wynen** [comment]
Right. I guess we could download them from the website. But at that point we don't really gain anything. Closing
