### ISSUE TITLE
Handling customization keyword args in new plotting

### ISSUE THREAD

**Issue by nvaytet** [scipp/scipp#2749]
In the new plotting, we should try to think carefully about how we want to handle keyword arguments for plots, especially for the `plot` wrapper function.

The old plotting supported a limited set of arguments, that applied to either 1d, 2d, or 3d plots, or all of them.
Do we need a similar mechanism or can we do better?

I don't think we should forward the raw arguments to the plotting library, because this would be library specific, and if one day we decide to switch from matplotlib to something else, many notebooks would then be broken.

Can we come up with an exhaustive list of arguments that would be sufficient for all our needs?

The old plotting supported:

- aspect: Specify the aspect ratio for 2d images.
- ax: Attach returned plot to supplied Matplotlib axes [ignore for now?]
- labels: Dict specifying which coordinate should be used to label the tics for a dimension. [ignore for now?]
- camera: Dict configuring the camera for 3d plots [3d scatter plots will have dedicated function]
- cax: Attach colorbar to supplied Matplotlib axes. [ignore for now?]
- cmap: Matplotlib colormap (2d and 3d only).
- color: Matplotlib line color (1d only).
- errorbars: Show errorbars if `True`, hide them if `False` (1d only).
- figsize: The size of the figure in inches (1d and 2d only).
- filename: If specified, the figure will be saved to disk. Possible file extensions are `.jpg`, `.png` and `.pdf` (1d and 2d only)
- grid: Show grid on axes if `True`.
- linestyle: Matplotlib linestyle (1d only).
- linewidth: Matplotlib linewidth (1d only).
- marker: Matplotlib line marker (1d only).
- masks: A dict to hold display parameters for masks such as a `color` or a `cmap`. [ignore for now?]
- norm: Normalization of the data. Possible choices are `"linear"` and `"log"`.
- pax: Attach profile plot to supplied Matplotlib axes. [ignore for now?]
- pixel_size: Specify the size of the pixels to be used for the point cloud (3d only). [3d scatter plots will have dedicated function]
- positions: Specify an array of position vectors to be used as scatter points positions (3d only). [3d scatter plots will have dedicated function]
- projection: Specify the projection to be used. Possible choices are `"1d"`, `"2d"`, or `"3d"`. [3d scatter plots will have dedicated function]
- resampling_mode: Resampling mode. [goes away]
- scale: Specify the scale (`"linear"` or `"log"`) for a displayed dimension axis. E.g. `scale={"tof": "log"}`.
- vmin: Minimum value for the y-axis (1d) or colorscale (2d and 3d).
- vmax: Maximum value for the y-axis (1d) or colorscale (2d and 3d).

I feel that this list of options should be sufficient to start with.
If some users want to make heavily customized figures with matplotlib, they should probably make their figure by hand. It should not be the job of Scipp to handle all possible cases, but to make something that works in 90% of cases.

**Comment by nvaytet** [comment]
Additional considerations should be how do we handle arguments when multiple data arrays are passed as a dict (1d plots).
Say you want to set the line color and marker symbols for two data arrays. The current way of doing things is
```Py
sc.plot({'a': da_a, 'b': da_b}, color=['red', 'blue'], marker=['s', 'x'])
```
where the order of the elements in `color` and `marker` have to match the order in the dict.

Is this still the mechanism we want to use, or can we do better?
Grouping the data entry with its arguments could be nice, but might make it difficult to write generic code?
```Py
sc.plot({'a': {'data': da_a, 'color': 'red', 'marker':'s'},
         'b': {'data': da_b, 'color': 'blue', 'marker': 'x'})
```
It also makes code more lengthy as you need to write `color` and `marker` twice...

**Comment by jl-wynen** [comment]
When the user wants to customise per-line properties when plotting multiple lines, can they just call plot multiple times and pass in an axes object every time? I.e. we don't try to wrap everything in a single function with complex logic for every argument.

**Comment by nvaytet** [comment]
> can they just call plot multiple times and pass in an axes object every time?

I think the possibility to pass a dict to the plot function was a powerful and very much used feature of the plotting. I think it would be inconvenient to have to do
```Py
p = sc.plot(da_a)
sc.plot(da_b, ax=p.fig.ax)
```
even if you don't want to customize anything?

Or are you saying that if you pass a dict, the `color` and `marker` would apply to all entries, and then the only way to customize individual curves would be to call `plot` multiple times? (with the assumption that this doesn't happen too often?)

**Comment by jl-wynen** [comment]
> Or are you saying that if you pass a dict, the color and marker would apply to all entries, and then the only way to customize individual curves would be to call plot multiple times? (under the assumption that this doesn't happen too often?)

Yes

**Comment by arm61** [comment]
> I don't think we should forward the raw arguments to the plotting library, because this would be library specific, and if one day we decide to switch from matplotlib to something else, many notebooks would then be broken.

Would this not still be the case if the new library didn't support some of the features in `matplotlib`?

**Comment by nvaytet** [comment]
> Would this not still be the case if the new library didn't support some of the features in matplotlib?

The idea would be that we would act as a small transition layer between the arguments and the underlying plotting library. We are already doing this, for instance Matplotlib doesn't support the `norm='log'` argument, this is a scipp thing.

We would keep those, and then change what we do internally if we swap out the plotting library. Same thing with the `scale={'tof': 'log'}` if you want to have a logarithmic tof axis.

**Comment by wpotrzebowski** [comment]
Just thinking about how I use plotting in scipp. In 90% of cases I am using defaults parameters and don't really care about arguments like markers, figsize, etc and for the rest I read documention anyway. What I am trying to say I am fine with whatever syntax you choose as long as there are well documented examples.

**Comment by SimonHeybrock** [comment]
We could consider having custom arguments, but additionally provide a plotting-library-specific dict that is just forwarded?

```python
da.plot(norm='log', matplotlib_args={...})
```
```
