### ISSUE TITLE
Require unit in step in arange with datetimes?

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#2756]
```suggestion
    "          num=30, dtype='datetime64')"
```
more readable?

_Originally posted by @SimonHeybrock in https://github.com/scipp/scipp/pull/2725#discussion_r946329055_

**Comment by jl-wynen** [comment]
My latest concern: 

>>A datetime string is conceptually equal to a scalar variable with a time unit. I think we should therefore also require a unit in the step size?
>
> Your argument only holds if the dtype is specified in addition because that overrides the 'natural dtype' of the string.
So in this case, arange gives special meaning to its arguments because it knows that it is constructing datetimes. But I would not add more special cases to it to make step to deviate from its usual requirements.

**Comment by SimonHeybrock** [comment]
I do not understand your commenty/concern.

As far as I am aware `arange` supports two cases:

1. Plain values as input. If unit is not given as kwarg it defaults to `dimensionless`.
2. Inputs with units (variables). All inputs must have this unit.

Mixing the two is not allowed.

The issue in question is that in the case of datetime strings, the input (datetime string) implies a unit (it is not a scipp variable, but still). Therefore, also the `step` must have a unit, so we are in case 2.

The other solution would be to always require a kwarg unit when making a datetime range.

**Comment by jl-wynen** [comment]
It is more tricky than that. Passing strings with different precision works and converts to the higher precision and therefore unit:
```.py
In [8]: sc.arange('x', '2000-01-01T00:00', '2000-01-01T00:01', 1, dtype='datetime64')
Out[8]: <scipp.Variable> (x: 1)  datetime64            [min]  [2000-01-01T00:00:00]

In [9]: sc.arange('x', '2000-01-01T00:00', '2000-01-01T00:01:00', 1, dtype='datetime64')
Out[9]: <scipp.Variable> (x: 60)  datetime64              [s]  [2000-01-01T00:00:00, 2000-01-01T00:00:01, ..., 2000-01-01T00:00:58, 2000-01-01T00:00:59]

In [10]: sc.arange('x', '2000-01-01T00:00:00', '2000-01-01T00:01', 1, dtype='datetime64')
Out[10]: <scipp.Variable> (x: 60)  datetime64              [s]  [2000-01-01T00:00:00, 2000-01-01T00:00:01, ..., 2000-01-01T00:00:58, 2000-01-01T00:00:59]
```
(it works the same without passing `step`)

This means that if we consider a string convertable to datetime as equivalent to a scipp variable, we have to require that all string shave the same unit because that is what we do with variables.
Or we leave it and treat the strings like numbers, i.e. something that can be converted to a variable but isn't one itself with the added logic that we can derive a unit from the datetime precision.

**Comment by SimonHeybrock** [comment]
Your example is a strong argument for making the proposed change (as implemented in the PR). In the current state the outcome is completely unpredictable.

**Comment by jl-wynen** [comment]
I wouldn't call that unpredictable. It depends on the values you pass in in the same way as otherwise. This is not dissimilar from how dtypes are handled. They also default to the input with highest precision.

**Comment by SimonHeybrock** [comment]
> This is not dissimilar from how dtypes are handled.

How is that similar? A float32 converted to float64 has approximately the same value, but a 1 interpreted as seconds instead of minutes is different by a factor of 60.

**Comment by SimonHeybrock** [comment]
> I wouldn't call that unpredictable.

It is unpredictable because the meaning of the `step` argument depends on value the `start` and `stop` arguments. If `start` or `stop` change then the meaning of `step` changes (by a large factor). Can you think of any other example where `arange` behaves like this?

**Comment by nvaytet** [comment]
I agree that it would be much less confusing if you had `step=1.0 * second`.

**Comment by jl-wynen** [comment]
> It is unpredictable because the meaning of the step argument depends on value the start and stop arguments. If start or stop change then the meaning of step changes (by a large factor). Can you think of any other example where arange behaves like this?

This is a good argument. I withdraw my objection
