### ISSUE TITLE
Advanced indexing is extremely slow for long dimensions

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#2767]
Motivated by the findings in #2745

```.py
import scipp as sc
import numpy as np
da = sc.data.table_xyz(10_000_000)
```
```.py
%%time
da[da.coords['x'] >= 0.5 * sc.Unit('m')]
```
```
CPU times: user 1min 15s, sys: 1.66 s, total: 1min 16s
Wall time: 6.91 s
```
but with numpy:
```.py
a = da.values
x = da.coords['x'].values
```
```.py
%%time
a[x>=0.5]
```
```
CPU times: user 66.5 ms, sys: 0 ns, total: 66.5 ms
Wall time: 64.1 ms
```

Using index lists shows the same difference between scipp and numpy.

**Comment by SimonHeybrock** [comment]
I have some improvements based on #2759 in mind (avoiding the `groupby`, using `copy_impl` directly).

I doubt it will give the same performance as numpy though --- if we keep the current generic approach. We can do better by pre-counting, and using `transform` with `subspan_view`, but that is more complicated and tricky to get to work with strides.

**Comment by SimonHeybrock** [comment]
Actually this is already a lot better with #2759:

```
CPU times: user 1.4 s, sys: 670 ms, total: 2.07 s
Wall time: 525 ms
```

Avoiding the use of `groupby` altogether I get:

```
CPU times: user 1.53 s, sys: 521 ms, total: 2.05 s
Wall time: 326 ms
```

Worth making the additional change?

**Comment by SimonHeybrock** [comment]
I'll make the change, since I can then use the same code for slicing with index list.

**Comment by jl-wynen** [comment]
Note that numpy is single threaded. The new implementation is only approaching numpy's performance because of multi threading. We are still ~20x slower. And indexing by an index list is not improved. Are we doing something fundamentally bad?

**Comment by SimonHeybrock** [comment]
Well, two things:

1. We have multiple columns, NumPy only 1, so it is not quite as bad.
2. We use generic code based on `transform` for binned data to accomplish this. In particular, we are *setting up* bin indices for this. We should make a comparison with larger chunks. Scipp should do a bit better there.
