### ISSUE TITLE
Make scipp pip- and/or conda-installable

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#277]

**Comment by OwenArnold** [comment]
As a mixed c++, python project, i'm not sure that the pip route will work nicely. Regarding conda - Maybe this is something @DanNixon  and I can look at together.

**Comment by DanNixon** [comment]
After a bit of discussion the following package managers were considered:
- `pip` would be ideal given that more poeple likely already use `pip` compared to `conda` but binary distribution may be an issue.
- `conda` is a good choice as it also provides a nice way to distribute scipp-core for C++ projects (this may include Mantid in the future if we end up using Conan for dependency management)
- `conan` may be worth looking into (with less priority) given that the DMSC seem to have standardized on this for a lot of other C++ libraries, but if no one is obviously going to use it it should be skipped.

Conda will probably be the first thing to look at given that it also solves C++ library distribution.
