### ISSUE TITLE
Many autogenerated typehints fall back to object because true types are not visible

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#2778]
`core/cpp_classes.pyi` contains many functions with `object` as a return type or argument type. I think this is wrong in all cases. Some of them should be `typing.Any` instead. But most should be a concrete type.
Currently, some common operations don't typecheck correctly because of this. For instance the following expressions are annotated as returning `object` which makes any subsequent operations with the return values fail type checks.
```.py
var.values
1 * sc.Unit('m')
```

I think to solve this, we need to define classes first in the bindings before defining any operations that use them. This is tricky especially for the unit multiplication because it needs `Variable` defined but that in turn needs `Unit` to be defined.

**Comment by jl-wynen** [comment]
It is more complicated. The stubs are based on `core.cpp_classes.py`. But the multiplication of unit and number if defined in `extend_units.py` which is imported in the base package. For some reason, `__rmul__` and `__rtruediv__` are missing from the stub but `__array_ufunc__` is there (also defined in `extend_units.py`). I can't seem to figure out why.

**Comment by nvaytet** [comment]
@jl-wynen wasn't this fixed in #3005 ?

**Comment by jl-wynen** [comment]
Yes. Forgot to close. Thanks!
