### ISSUE TITLE
Shorten the job names on the CI?

### ISSUE THREAD

**Issue by nvaytet** [scipp/scipp#2806]
Just a suggestion, but we could consider shortening the job names for the building and testing, as this would allow us to see on the preview how long the builds took.

E.g. on this preview, we can see the runtime for the formatting but not the others:
![Screenshot at 2022-08-26 14-15-15](https://user-images.githubusercontent.com/39047984/186901546-93899bce-e28e-4d9e-8e2b-9c4dc69ed4e6.png)

The name "build and test" may not really be needed, instead we could name the steps `CI / ubuntu-20.04, py3.8` and `CI / macos-11, py3.8` ?

**Comment by SimonHeybrock** [comment]
I don't think you can have an empty job name?

**Comment by SimonHeybrock** [comment]
Feel free to change to something shorter, I'll close this since we don't need an issue for such things.
