### ISSUE TITLE
Inconsistent dtype from `values` and `value` property.

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#2815]
```python
import scipp as sc

var1 = sc.array(dims=['x'], values=[0], dtype='int32')
var2 = sc.scalar(0, dtype='int32')
print(type(var1.values[0]), type(var2.value))
print(sc.scalar(var1.values[0]).dtype, sc.scalar(var2.value).dtype)
```
yields
```
<class 'numpy.int32'> <class 'int'>
int32 int64
```
I think we should try and return a NumPy type in both cases?

Even more inconsistent: `var2.values` (which returns a 0-D Numpy array) yields `sc.scalar(var2.values).dtype == 'int32'`.

**Comment by SimonHeybrock** [comment]
I looked into this a bit: `py::cast` does not appear to have any arguments that help with this. One workaround might be to cast the array and then extract the element using Python functions/methods.

**Comment by jl-wynen** [comment]
What array do you want to cast?

Can't we just implement a cast for `.value` ourselves?
