### ISSUE TITLE
Runtime configuration with file in working directory does not work as documented

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#2840]
https://scipp.github.io/reference/runtime-configuration.html#Working-Directory does not work. I couldn't figure out why.

**Comment by jl-wynen** [comment]
I did some experiments and it seems like confuse does actually detect the file in the local directory. (Setting `optional=False` in `YAMLSource` leads to an exception if the file does not exist.) But it does not appear to read the file. Omitting a field in the default config file but adding it to the local one makes the loader fail.

I think this has to do with how we read the file, i.e. `Config.get`. But I couldn't find a solution yet.
