### ISSUE TITLE
Unexpected result when parsing "a.u." as unit

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#2841]
```python
import scipp as sc
sc.Unit('a.u.')
```
gives `250606894.465190649s*[h]`. Is `'a.u.'` a "standard" for "arbitrary units"? We should probably avoid messing this up?

I think what is happening is that LLNL/units interprets `.` as `*`, we get the same result with `sc.Unit('a*u')`. Maybe a fix would be to avoid doing this when there also is a final `.`, since this indicates an abbreviation?

**Comment by nvaytet** [comment]
What were you expecting to get for `a.u.`? For me it means 'astronomical unit'...

**Comment by SimonHeybrock** [comment]
https://en.wikipedia.org/wiki/Arbitrary_unit

**Comment by SimonHeybrock** [comment]
But the main point is that it is parsed as *neither*, but in a broken manner.

**Comment by jl-wynen** [comment]
The issue goes a bit deeper: https://github.com/LLNL/units/issues/246

**Comment by SimonHeybrock** [comment]
https://github.com/LLNL/units/releases/tag/v0.7.0 should include the necessary fixes. We should try if updating works for us.

**Comment by SimonHeybrock** [comment]
After the update to units-0.7.0 this is now parsed as astronomical unit, which is ok.
