### ISSUE TITLE
Add sizes argument to broadcast

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#2842]
As with the other shape related functions.

**Comment by jl-wynen** [comment]
It already has this argument. Not sure why it failed for me earlier :confused:

**Comment by SimonHeybrock** [comment]
I think I know why: When you call `da.broadcast(other.sizes)` you get an error from the C++ bindings, which only lists the `dims` and `shape` overload.

**Comment by jl-wynen** [comment]
That could be it
