### ISSUE TITLE
Setting the `variances` property ignores dimension labels

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#2856]
```python
import scipp as sc

var = sc.linspace('x', 0.0, 1.0, num=5, unit='kg')
var.variances = sc.array(dims=['y'], values=[1,2,3,4,5])
var
```
We would expect this to raise `DimensionError`. Apparently the dims are just ignored?

Note that if we pass a `unit=kg*kg` (or anything else) we get an exception... probably we should *check* the unit instead?

**Comment by jl-wynen** [comment]
I am surprised this works at all. `.variances` and `.values`  operate on numpy-array like objects. So it should ignore all scipp-specific attributes of the RHS. (It doesn't units and variances make the assignment fail.)

**Comment by SimonHeybrock** [comment]
> I am surprised this works at all. `.variances` and `.values` operate on numpy-array like objects. So it should ignore all scipp-specific attributes of the RHS. (It doesn't units and variances make the assignment fail.)

Maybe we should change that. Operating on NumPy arrays without units has the risk of people setting standard-deviations here, checking the unit would prevent that.

**Comment by jl-wynen** [comment]
But isn't the purpose of `values` and `variances` to access the underlying memory as a plain array? I think your use case (and maybe the recommended solution in most cases) is to use `sc.variances`.

**Comment by SimonHeybrock** [comment]
Then we should add a better mechanism for setting variances (with units and dims), and consider removing the `variances` setter?

**Comment by jokasimr** [comment]
Seems there are two important uses that are colliding here:
1. Being able to set the variances of a variable in a safe way.
2. Being able to access the underlying plain array representing the variances.

I think it makes sense to allow both. One way to deal with this is to treat the `.variances` property *as if* it was just another Variable.
To change values of a variable in a safe way we use a slice:
```python
import scipp as sc

var = sc.linspace('x', 0.0, 1.0, num=5, unit='kg')
var[:] = sc.array(dims=['x'], values=[1., 2., 3. ,4., 5.], unit='kg')
var
```
We could allow the same syntax for variances:
```python
import scipp as sc

var = sc.linspace('x', 0.0, 1.0, num=5, unit='kg')
var.variances[:] = sc.array(dims=['x'], values=[1., 2., 3. ,4., 5.], unit='kg**2')
var
```
To replace the variances completely we can allow
```python
import scipp as sc

var = sc.linspace('x', 0.0, 1.0, num=5, unit='kg')
var.variances = sc.array(dims=['x'], values=[1., 2., 3. ,4., 5.], unit='kg**2')
var
```
both of those operations would be safe in the sense of respecting units, dims, and dtypes.

Then we can allow 'unsafe' access by adding the `.values` property of the variances
```python
import scipp as sc

var = sc.linspace('x', 0.0, 1.0, num=5, unit='kg')
var.variances = sc.array(dims=['x'], values=[1., 2., 3. ,4., 5.], unit='kg**2')
var.variances.values # This is a numpy array
```

**Comment by jokasimr** [comment]
I guess we could also raise an error (like @jl-wynen expected it would) when someone tries to assign a variable to the variances property.
This would communicate that the `.variances` is strictly for accessing the underlying plain array, and at least make the user aware that they are potentially doing something that requires extra attention.

**Comment by SimonHeybrock** [comment]
Maybe we should consider removing the ability to add a variances array by setting `variances` if it was previously `None`? Instead, we could have a dedicated function that acts a bit like `zip`, taking two variables, or data arrays:


```python
def with_variances(values: sc.Variable, variances: sc.Variable) -> sc.Variable: ...
def with_variances(values: sc.DataArray, variances: sc.Variable) -> sc.DataArray: ...
def with_variances(values: sc.DataArray, variances: sc.DataArray) -> sc.DataArray: ...
```

**Comment by jl-wynen** [comment]
This wouldn't solve the issue. When setting values, it would still ignore dim labels (and units).

**Comment by nvaytet** [comment]
I see both sides of the argument. I think I agree with @jl-wynen that I believed the `.variances` was the analog to `.values`, and was basically representing the underlying raw numpy array.
So I would say that setting `.variances` with a Variable should fail.

But I can see that using the safety of dimension labels would be nice. I do wonder if it would be confusing to non-expert users to require the unit to be the square of the unit of the values?

Now should the setter for `.variances` be removed altogether, I don't know. It is good to try an prevent bad usage, so that non-expert users don't get nasty surprises. However, I am also aware of trying to add too much protection and making the library too rigid in the process. We might also make expert users unhappy.

That said, I have thought and looked quickly through our codebase for an example which could not be covered by a new `with_variances` function, or just creating a new variable instead of setting variances on an existing one, and I could not find much.

What about in-place operations, such as `.variances[0:10] = 0`, would they also be prevented?

**Comment by SimonHeybrock** [comment]
> What about in-place operations, such as `.variances[0:10] = 0`, would they also be prevented?

No, that is a different code path and not affected.

**Comment by nvaytet** [comment]
So can you still do `.variances[...] = np.ones(...)`?
If so, then I am not sure I really see the point in trying to have all the safety of dimension labels, units etc....

I would just have it so that setting `.values` and `.variances` with a Variable raises an exception.

**Comment by SimonHeybrock** [comment]
Yes, that is what I was trying to suggest:
- Raise when setting `values` or `variances` from `Variable`
- Do not support adding `variances` if it was previously `None`
- Add a helper to combine two variables (`values` and `variances`) into a single one.

**Comment by SimonHeybrock** [comment]
Based on discussion with @jokasimr, consider:

```python
import scipp as sc
import numpy as np

var = sc.arange('x', 5.0, unit='s')  # UnitError below
var = sc.array(dims=['x', 'y'], values=[[1.,2],[3,4]])  # DimensionError below
var = sc.arange('x', 5.0)
var2 = 0 * var
var2.unit = 'm'
var2.values = np.asarray(var)  # array with dtype object!
var2
```
Since any 1-D unit-less or dimensionless variable can be converted (somehow, by, e.g., pybind11 magic) to an array of, say, float64 the above is "well defined" and works. Our current feeling is that we should therefore probably also allow the cases discussed earlier?

**Comment by jokasimr** [comment]
Somewhat unrelated question. Consider the `Variable` interface, which of the following actions should be possible?

1.  Updating the values and the variances of a variable *in-place* in a *safe* way. By safe I mean respecting `dims` and `units`.
2. Updating the values and the variances of a variable *in-place* in an *unsafe* way. By unsafe I mean disregarding `dims` and `units`.

As far as I can tell: 1 is not possible for the variances, should it be?

**Comment by SimonHeybrock** [comment]
Not sure I understand your question: `variances` have not unit (it exposes the plain underlying array). From what I saw yesterday this is exactly what the setter supports: updating from a unit-less array-like.

**Comment by jokasimr** [comment]
Yes `variances` exposes the underlying array and it can be used to perform unsafe updates. The question was: should we support updating the variance in-place in a safe way?

**Comment by SimonHeybrock** [comment]
> The question was: should we support updating the variance in-place in a safe way?

We could, but this is done very rarely, so I'd not implement anything for now.

**Comment by SimonHeybrock** [comment]
Was the conclusion that there is nothing to do here? Or maybe we should add some unit tests with the concrete examples from above, to ensure that this and only this works?
