### ISSUE TITLE
Calendar-versioning?

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#2857]
Over the past year or so we have adopted a quite rapid release cycle, and it appears to work out quite well. This implies that version numbers may not be so useful any more (in combination with the limitations of semantic versioning). We should consider switching to calendar-versioning, i.e., 2022-10, 2022-12, etc.

**Comment by jl-wynen** [comment]
I am generally in favour of this. And I am even considering it for Scitacean. But 

- The version needs to be more fine grained, it should at least contain the day and the option for multiple releases a day (has already happened)
- Do we see ourselves ever patching an old release? Say some users are stuck with 1.14 and development has moved to 1.15. If we find a critical bug and need to fix it for users of the old version, we can release 1.14.1 and 1.15.1. But how would this work with calendar based versions?

**Comment by SimonHeybrock** [comment]
I do not think the day should be included, but we should have a "patch" part of the version:

`YYYY-MM-(patch)`

So we would release 2022.10.0, and any bugfix release would be 2022.10.1, not matter when. This should address both of your questions

**Comment by SimonHeybrock** [comment]
Unless there are more concerns, I will switch to `YYYY.0M.MICRO` version numbers with the next release, i.e., the month is zero-padded.

**Comment by jl-wynen** [comment]
How do we handle the micro version? Does it correspond to our current use of the patch version?
And how should scippneutron depend on scipp? Should it fix the year and month?

**Comment by SimonHeybrock** [comment]
> How do we handle the micro version? Does it correspond to our current use of the patch version?

Yes.

> And how should scippneutron depend on scipp? Should it fix the year and month?

Yes, i.e., there would be little change for now.
