### ISSUE TITLE
Deprecate scipp's built-in plotting in favor of plopp

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#2864]
I think we should add deprecation warnings now (with the next release), as we may need a relatively long deprecation period.

- [x] Make sure warnings are visible in Jupyter (`DeprecationWarning` is not).
- [x] Consider deciding on dates for change of scipp's default as well as final removal, so it can be added in the deprecation warning?
- [x] Document how to use plopp by default. Modifying every notebook may not be nice, as many people will just want to use plopp by default, and not change again once scipp makes it the default. Should we advertise the config option (which we are using for the scipp docs)?
- [x] Add deprecation notes in the plotting docs pages (which refer to scipp's plotting)
- [x] Refactor final uses of scipp plotting in docs (with exception of the plotting pages that will be removed).
- [x] Update the `pip` "extra" and the recommended conda env file to include `plopp`.
- [x] ~Consider adding forwards or special pages explaining the change to replace the current plotting details pages, in case people still use those links.~ moved to  #2879
- [x] Go through all open plotting (visualization) issues and either close them or migrate them to plopp (if they still apply). WIP @SimonHeybrock

**Comment by jl-wynen** [comment]
We also need to decide on when we switch to plopp as the default backend: https://github.com/scipp/scipp/issues/2880
