### ISSUE TITLE
Strange error in event slicing

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#2874]
Using data from WISH (`"WISH00043525.nxs"`) I get the following error. Don't know why.
![strangeerr](https://user-images.githubusercontent.com/11393224/200803073-b00a1517-9148-412e-953e-e839253b8327.png)

**Comment by SimonHeybrock** [comment]
Does this also happen when the 'stop' includes the lower limit of the data?

**Comment by SimonHeybrock** [comment]
Confirmed, this only happens when `stop` does not include any events:

```python
da = sc.data.table_xyz(100).bin(x=1)
da.bins['x', :0.5*sc.Unit('m')]  # exception
del da.coords['x']
da.bins['x', :0.5*sc.Unit('m')]  # exception
da.bins['x', :0.0*sc.Unit('m')]  # ok
```

**Comment by SimonHeybrock** [comment]
The solution is probably to adapt the logic in `Bins.__getitem__` to adapt `start` and `stop` such that we never get a negative range (but use an empty range instead).
