### ISSUE TITLE
Aliases can override regular units

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#2876]
E.g.
```python
sc.units.aliases['m'] = 's'
print(sc.Unit('m'))
print(repr(sc.Unit('m')))
```
prints
```
m
Unit(1*s**1)
```
which can be highly confusing.

We could prevent this by checking if an alias can be parsed as a a unit and if so, reject it. But I am unsure if this would be too restrictive in some cases. Is this simply something we have to live with?

**Comment by SimonHeybrock** [comment]
Didn't you just write documentation on how to override "angstrom" so it is favored in string formatting?

> We could prevent this by checking if an alias can be parsed as a a unit and if so, reject it. But I am unsure if this would be too restrictive in some cases. Is this simply something we have to live with?

How about preventing it only if inconsistent? So you cannot define `angstrom = 0.1 meter`? But LLNL/units supports so many units that nevertheless there may be many clashes, so maybe we should just live with it?

**Comment by jl-wynen** [comment]
> Didn't you just write documentation on how to override "angstrom" so it is favored in string formatting?

Good point. Let's just leave it. We might mess up too easily if we tried to come up with rules.
