### ISSUE TITLE
Remove old plotting backend from Scipp (August 2023)

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#2879]
Removal is scheduled for v23.08.0 or after.

- [ ] Remove code (`scipp.plotting`)
- [ ] Remove tests. Consider keeping a minimal test suite for the plot method.
- [ ] Remove migration guide after the backend was removed.
- [ ] Consider adding forwards or special pages explaining the change to replace the current plotting details pages, in case people still use those links.

**Comment by SimonHeybrock** [comment]
The migration guide should probably be kept for a while longer *after* removing the old backend. Maybe a year or so.
