### ISSUE TITLE
Make plopp the default (March 2023)

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#2880]
- [x] Decide on a timeline. See #2890 
- [ ] Make plopp the default backend.
- [ ] Amend migration guide.

**Comment by SimonHeybrock** [comment]
This switch will be a breaking change, does that mean we will have two (the other being the removal of the legacy plotting)? I guess so.

In any case, I think many of the "simple" plotting commands still work without change (just the result you see is different). That is, the "break" is not 100%, i.e., having a few months of deprecation period may be sufficient?

**Comment by SimonHeybrock** [comment]
Do we need a transition period where `plopp` is the default, but you get a warning from old syntax? If not, then we end up breaking user code *before* the announced removal of the old plotting (unless we make plopp the default only then).

**Comment by jl-wynen** [comment]
> Do we need a transition period where plopp is the default, but you get a warning from old syntax? If not, then we end up breaking user code before the announced removal of the old plotting (unless we make plopp the default only then).

I'd avoid supporting old syntax through plopp. This would only make the interface more complicated.
We should announce the transition of the default together with the removal. I.e. change the warning and migration guide to include both.

**Comment by SimonHeybrock** [comment]
> We should announce the transition of the default together with the removal. I.e. change the warning and migration guide to include both.

You mean something like "Plopp will become default in 23.03.0 and the legacy plotting will be removed in 23.08.0 or later"?

**Comment by jl-wynen** [comment]
Yes

**Comment by SimonHeybrock** [comment]
This was done.
