### ISSUE TITLE
Reenable "custom count units" that are in use?

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#2888]
In #2843 we disabled "custom count units". However, I notice now that some of this are in use (i.e., not entirely custom), in particular one of them for "arbitrary unit". See https://units.readthedocs.io/en/latest/user-guide/custom_count_units.html#custom-count-units-in-use.

I think we should consider reenabling these, at least for the pre-defined ones?

**Comment by jl-wynen** [comment]
Does it really make sense to use arbitrary units? Or should people just set `unit=None`? (This is not exactly the same but does it matter in practice?)

I don't know how easy it is to identify these units when used in combination with others. The encoding of custom units is more complicated than for other units.

**Comment by SimonHeybrock** [comment]
I think many people will read files that define such units. If this always requires manual intervention it becomes tedious?

**Comment by jl-wynen** [comment]
How does this relate to my questions?

**Comment by SimonHeybrock** [comment]
Can you reformulate your question?

**Comment by jl-wynen** [comment]
1. Why do we need to support arbitrary units? Would it not be enough to use `unit=None`?
2. About implementing this: I am not sure how complicated it is to recognize a unit that we support vs one that we don't. (From an `llnl::units::precise_unit` object, not from a string or other serialization)

**Comment by jl-wynen** [comment]
> You mean to intercept the string parsing and turn it in to None? 

No, just don't support arbitrary units in any way and require users to use `None`.

> Furthermore, I am not sure if this would then prevent a number of operations?

It would prevent all operations between those variables and variables with an actual unit. But how would arbitrary units behave? What is `a.u. * m`?

> You mean selecting which "custom count units" are applicable and supported by us

yes

**Comment by SimonHeybrock** [comment]
After the update to units 0.7.0 there is some odd behavior:

```python
>>> sc.scalar(1, unit='arb.unit')
<scipp.Variable> ()      int64  [1e-26m^4*counts]  [1]
```

Another broken case?

**Comment by SimonHeybrock** [comment]
@jl-wynen Wasn't this addressed in your PR?

**Comment by jl-wynen** [comment]
Only arbitrary unit. Other custom units and custom count units are still disabled.

**Comment by SimonHeybrock** [comment]
Are there any that we actually need, or should we just close this?

**Comment by jl-wynen** [comment]
I'm not aware of any. In particular because I don't know what they mean.
