### ISSUE TITLE
More static analysis

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#2906]
Note that I learned about most of these through https://scikit-hep.org/developer/reporeview?repo=ScicatProject%2Fscitacean&branch=main

## Tools

There are a bunch more tools we could, and I think should, be using. See, e.g., the setup in scitacean which works nicely for me: https://github.com/SciCatProject/scitacean/blob/main/.pre-commit-config.yaml

### What I think we should use in the scipp stack

  - check-added-large-files  # esp. in ess to stop people from adding data files
  - check-yaml
  - check-json
  - check-toml
  - detect-private-key
  - flake8-bugbear  # already in scippneutron
  - codespell  # specialised spellchecker, haven't had a single false positive in scitacean
  - rst-directive-colons
  - rst-inline-touching-normal  # we've had this mistake in our docs multiple times

### Other options that I don't think are so important

  - isort  # sorts import statements, not really sure why this matters but we mostly sort them anyway but a tad incosistently
  - bandit  # security scanner, shouldn't really matter in scipp (until we integrate scitacean, tiled, etc)
  - the other checks in scitacean are relevant but not super important, IMHO.
  - have a look at the rest of hooks in https://github.com/pre-commit/pre-commit-hooks and https://github.com/pre-commit/pygrep-hooks

## Config

Scitacean is a lot stricter. We might want to adopt this:
```toml
[tool.pytest.ini_options]
minversion = "7.0"
testpaths = "tests"
addopts = """
--strict-config
--strict-markers
-ra
-v
--hypothesis-profile=scitacean
"""
filterwarnings = [
    "error",
]
```

## CI

We should consider using pre-commit-ci to run analysis and auto formatting. It would eliminate the duplication between pre-commit and tox / requirements files.

**Comment by SimonHeybrock** [comment]
> We should consider using pre-commit-ci to run analysis and auto formatting. It would eliminate the duplication between pre-commit and tox / requirements files.

How would this work in practice?

**Comment by jl-wynen** [comment]
As I understand it, pre-commit-ci is triggered like an action and reads the pre-commit config. If any file is changed, it pushes the change to the same branch. I don't know if we can set the actions up to wait for pre-commit like we have it now with our formatting job. Or if the other actions start running and get cancelled by the pre-commit commit. Need to investigate if we are interested in this.

**Comment by jl-wynen** [comment]
I tested pre-commit-ci in https://github.com/scipp/scippnexus/pull/92

It seems to work fine as is very easy to set up.
But it takes a long time to start a job. And while a job is pending, GH actions start running. In one case, the actions finished completely before pre-commit even started. When it then made a fix and commited it, that started the whole GH actions workflow from scratch.

It does not looks like there is a way to make GH actions wait for pre-commit-ci. And the author does not appear interested in adding support for it.

So I would suggest sticking with GH actions. But we could run `pre-commit -a` manually instead of using tox. This would ensure that local hooks and CI are in sync. And it would make sure that all checks run.

**Comment by SimonHeybrock** [comment]
How about changing the tox `static` env to run `pre-commit -a` as you suggest?

**Comment by jl-wynen** [comment]
Why? This would create two environments, one for tox (which contains no packages) and one for pre-commit.

**Comment by jl-wynen** [comment]
Well, it would allow us to control the version of pre-commit. But is this important enough?

**Comment by SimonHeybrock** [comment]
The past couple of years have consistently proven that controlling the version of everything is very important?

**Comment by SimonHeybrock** [comment]
We could consider having the static job open a PR into the base PR, instead of committing to the branch? Does that some of the problems?

**Comment by jl-wynen** [comment]
I don't think so. It would mean that the rest of the CI needs to run twice

**Comment by jl-wynen** [comment]
All repos now have a new setup based on pre-commit + tox. This should do for now
