### ISSUE TITLE
Should `Unit.__repr__` includes scale factors that are 1?

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#2914]
Consider:
```python
>>> sc.Unit('m')
Unit(1*m**1)
>>> str(sc.Unit('m'))
'm'
>>> repr(sc.Unit('m'))
'Unit(1*m**1)'
```
I feel including the "1" is odd. Should we avoid that?

**Comment by jl-wynen** [comment]
Given that `repr` is supposed to be a full representation of an object, I would say it makes sense to always show the multiplier.

**Comment by SimonHeybrock** [comment]
Isn't it equally "full" if we omit it? It is not very user friendly to always list it.

**Comment by jl-wynen** [comment]
Not sure it matters. But I am fine with going with your suggestion.
