### ISSUE TITLE
Editable installs of downstream software depending on scipp?

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#2915]
This may be a problem for developers: Say you develop scipp and scippnexus, and install scippnexus with `pip install -e .` This will install `scipp` via `pip`. However, we may want to instead use our current scipp install (e.g., from `scipp/install`). We could probably force this using PYTHONPATH, but ultimately not being able to have an editable install of scipp causes headaches and surprising issues.

**Comment by jl-wynen** [comment]
Not sure if there is a clean solution. We would need an editable install of scipp itself. But that isn't feasible with pip, so we would have to use conda. And then for the case you describe, we would mix a pip and a conda package. This can lead to clashes in dependencies (in particular `h5py`)
