### ISSUE TITLE
Yapf doesn't like walrusses

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#2918]
yapf fails for files that contain the walrus operator `:=`. This is a known problem since 2020 but doesn't seem to have been addressed. I don't know how this slipped through our CI so far but it tripped up my pre-commit in scippneutron now.

I think we have two choices:
- never use the walrus operator and remove all usages until yapf is fixed
- switch to a different formatter, e.g. black

Thoughts?

**Comment by SimonHeybrock** [comment]
I consider `:=` useful, so switch to black, maybe?

**Comment by jl-wynen** [comment]
I tested black. It reformats on the order to 10k lines.

I personally prefer black's formatting with the exception of strings. It enforces double quotes.

**Comment by SimonHeybrock** [comment]
The double-quote thing can be configured, as we suggest here: https://scipp.github.io/reference/developer/notebook-style-guide.html#Code-cells

**Comment by jl-wynen** [comment]
Ok. But I would still prefer normalizing quotes. It is just that I would rather use single quotes. But it's not a strong preference...

**Comment by jl-wynen** [comment]
Can reproduce in scipp. Both with `yapf -i  src/scipp/io/hdf5.py` and `pre-commit run yapf -a`.
I have version 0.32.0

It is reported here https://github.com/google/yapf/issues/856 and here https://github.com/google/yapf/issues/894
It seems like this was fixed in the library they use for parsing. But according to the last comment in the 2nd issue, it depends on the Python version. I have 3.8. Using 3.10, yapf does indeed handle `:=` correctly.

What do we do? This means that we cannot add or touch code with `:=` when we have an env that contains mantid.

**Comment by SimonHeybrock** [comment]
Python 3.8 support will be removed sooner or later, so I would just stick with yapf.

**Comment by jl-wynen** [comment]
According to numpy's schedule in April. But I don't trust that Mantid will do it anytime soon.

**Comment by jl-wynen** [comment]
Seems to work in plopp for me even though it uses python 3.8. Maybe it doesn't fail in every case. So closing this issue and I'm going to work around the problem when it crops up again.
