### ISSUE TITLE
Add dev. docs page on how to contribute a PR

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#2936]
I think such a page is missing. Should briefly list such as:

- Mention issue to close.
- Update release notes.

We should also link to this new page from https://scipp.github.io/about/contributing.html.

**Comment by jl-wynen** [comment]
We could add a GH template. Though for us this would mean that we always do ctrl+a, delete for every PR

**Comment by SimonHeybrock** [comment]
Also add a CONTRIBUTING.md file.
