### ISSUE TITLE
'==' operator between DataArray objects error when a mask with non-boolean values or unit given

### ISSUE THREAD

**Issue by YooSunYoung** [scipp/scipp#2944]
When I tried to use '==' operator between DataArray object, it rasied an error in certain circumstances.

Here is the example code below. 

Given these context below,
```
import scipp as sc
import numpy as np

data = sc.array(dims=['x', 'y'], values = np.random.rand(4, 3))
```

This code works
```
mask0 = sc.array(dims=['x'], values=[False, True, True, False])
dummy_data_array = sc.DataArray(data, masks={'mask0': mask0})
dummy_data_array == dummy_data_array 
```

But these two below don't.
```
# When a mask has unit
mask0 = sc.array(dims=['x'], values=[False, True, True, False], unit='')
dummy_data_array = sc.DataArray(data, masks={'mask0': mask0})
dummy_data_array == dummy_data_array
```
```
# When a mask is non-boolean
mask0 = sc.array(dims=['x'], values=[1,2,3,4])
dummy_data_array = sc.DataArray(data, masks={'mask0': mask0})
dummy_data_array == dummy_data_array

```

These two cases raise an error like below.
```
---------------------------------------------------------------------------
UnitError                                 Traceback (most recent call last)
Cell In[24], line 3
      1 mask0 = sc.array(dims=['x'], values=[1,2,3,4])
      2 dummy_data_array = sc.DataArray(data, masks={'mask0': mask0})
----> 3 dummy_data_array == dummy_data_array

UnitError: Expected unit None, got dimensionless.
```

**Comment by SimonHeybrock** [comment]
I think this is probably intentional behavior: Element-wise binary operations such as `+`, `*`, or `==` try to "OR" the masks, which is not possibly unless it is a boolean. Likewise, we are not defining this operations when there is a unit

What where you actually trying to achieve? If you need comparison for a unit test, use `sc.identical`.

That being said, even if this is intentional, we may need to consider raising a clearer error.

**Comment by YooSunYoung** [comment]
> 

Ah ha... so masks should be boolean if you want to use binary operations with DataArray, understood.

Then should we raise an error something like this?
> Element-wise binary operations are not supported for DataArray with non-boolean masks.
