### ISSUE TITLE
[DataGroup] Add `_repr_html_`

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#2947]
We need to support nested cases, i.e., a tree-like structure with sections that can be expanded/collapsed.

Performance actually quickly becomes an issue here: I think we *cannot* afford to create the full `_repr_html_` of each contained `Variable` or `DataArray`, since `DataGroup` may be used, e.g., for NeXus files that contain hundreds of HDF5 groups and thousands of HDF5 datasets. We should restrict this to a simple 1-line preview. That is, descend into all nested `DataGroup` items, but each non-`DataGroup` child must be displayed as a single line without too much formatting overhead.

**Comment by SimonHeybrock** [comment]
- Scipp objects:
  - dim, shape
  - Variable, DataArray: unit, and dtype
  - 0-D Variable: value
  - Dataset, DataGroup: Number of items
  - Dataset: item names
- np.ndarray:
  - not `str`
  - shape, dtype: `name  ()  ()  np.ndarray(shape=(2,3), dtype='float32')` maybe?

**Comment by YooSunYoung** [comment]
@SimonHeybrock Just to update the status of the `DataGroup._repr_html_`

Now the lists are at least readable.




![Image](https://user-images.githubusercontent.com/17974113/213721314-f02af97d-7c95-4c46-8c12-aea2e2d0aee4.gif)

**Comment by SimonHeybrock** [comment]
Are you planning to keep the duplicate information (item type, item name)?

Not sure about those black frame on the left... is it not readable without?

**Comment by SimonHeybrock** [comment]
I like how the right side looks!

Is it not possible to just remove the left side? Then, on the right, add the ability to hide/unhide nested rows by clicking on the row (with some indent in the first (name) column to indicate the nesting?
