### ISSUE TITLE
Setting dense data for sparse item does not fail

### ISSUE THREAD

**Issue by OwenArnold** [scipp/scipp#295]
`Dataset` is sensitive in some cases (though better than previous revision) to the order in which variables are applied during construction. A recent example to illustrate.

```
auto sparse_var = makeVariable<double>({Dim::Y, Dim::X}, {2, Dimensions::Sparse});
auto dense_var = makeVariable<double>({Dim::Y, Dim::X}, {2, 2});

Dataset a;
a.setData("dense_var", dense_var);
a.setSparseCoord("sparse_coord", sparse_var); // This throws

// Changing order bypasses checks
Dataset b;
b.setSparseCoord("sparse_coord", sparse_var);
b.setData("dense_var", dense_var); 
```

There may be other cases where we get temporal coupling issues. Should we consider adding some kind of indirection so that we can check all variables before attempting to make the dataset. Some kind of `builder` could be a solution. This would split out the construction parts of dataset, though we could make it look very similar to the current API.

**Comment by SimonHeybrock** [comment]
> Should we consider adding some kind of indirection so that we can check all variables before attempting to make the dataset. Some kind of `builder` could be a solution. This would split out the construction parts of dataset, though we could make it look very similar to the current API.

I suggest to just make `setData` throw. I cannot think of a reason why this could not be done as a simple check.

**Comment by SimonHeybrock** [comment]
Regarding the "builder" you mention: A key advantage we have with `Dataset` comes from the flexibility we have with adding and removing arbitrary items and coordinates at any time. So I do not think this would add anything useful.

That being said, I do intend to make a C++ equivalent to the `Dataset` creation with keyword arguments we have in Python. But this does not imply that a dataset would be fixed after that, i.e., we still need the checks in place in the setters.
