### ISSUE TITLE
Referencing release for additions or deletions in documentation

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#2957]
Libraries like Numpy have a banner in their docs, indicating when, e.g., a function was added. This is useful and we have previously agreed that we should also do this more. Main question is how? We may not know yet which release a function will be added in when the PR is merged.

One option would be to use a placeholder that can then be replaced across the repo by the actual release number (using a script or CI job) when the release is made.

**Comment by SimonHeybrock** [comment]
:facepalm: We should just read the documentation: https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-versionadded

**Comment by jl-wynen** [comment]
From the PR (#2972):
> The main question is whether it is good enough to "guess" which will be the next release, or whether we should use a placeholder in PRs and a script run as part of the release process to substitute for the actual release?

This is the problem here. I don't think we should be adding the directive until we have a solution.
I doubt that we will guess right often enough. Our schedule is pretty unpredictable. Currently, I think that a placeholder would work best as it would only be processed once during release. And not every time the docs are built.

**Comment by SimonHeybrock** [comment]
I suggest developers use `.. added-after :: NEXT_RELEASE`. Things to implement here are then:

- Update `tox.ini` so we can run `tox -e prepare-release XX.YY.Z`, replacing the placeholder
  - In all `.py` files (docstrings)
  - In the release notes? Right now we depend on editing this manually.
- Update `release.yml` github workflow to run a pre-release check, such as `tox -e check-release`. For now this would mainly check if the are any placeholders left. This may be more in the future.

**Comment by jl-wynen** [comment]
Sounds good. But I would use `.. versionadded :: NEXT_RELEASE`, `added-after` would take the current release as parameter.
