### ISSUE TITLE
[DataGroup] Detect and prevent cycles in

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#2980]
It is possible to create cycles in data groups:
```python
a = sc.DataGroup({'x': sc.scalar(2)})
b = sc.DataGroup({'a': a})
a['b'] = b
print(a)  # RecursionError: maximum recursion depth exceeded
```
This affects pretty much all operations.
We catch this type of error in other places.

We cannot feasibly prevent all cycles during creation / item insertion because we support arbitrary item types. So, e.g., a `list` might cause a cycle. But we can and should detect cycles in operations.

I don't know if we should add a check to `__getitem__`.

**Comment by SimonHeybrock** [comment]
I am not sure how much we would gain from that. It is not something we want to support, and the `memo` approach would be quite invasive (and costly, I suspect). What is wrong with users seeing `RecursionError`?

**Comment by jl-wynen** [comment]
It's not as clear as a dedicated error message. But you are right, implementing this is non trivial.
One more problem, though, this means that the memory will only be released in the garbage collector can figure out that there is a cycle.

How about we only check in `__setitem__` as that is likely the most common way of introducing a cycle?

**Comment by SimonHeybrock** [comment]
> One more problem, though, this means that the memory will only be released in the garbage collector can figure out that there is a cycle.

What means that? I don't think this can be fixed in either case.

> How about we only check in __setitem__ as that is likely the most common way of introducing a cycle?

You mean check if `self` is inserted?

**Comment by jl-wynen** [comment]
> You mean check if self is inserted?

Yes

> What means that? I don't think this can be fixed in either case.

In can be 'fixed' by not allowing people to make such an object. Then they have to use weakrefs or some other solution. But since `dict` has the same issue, we should not worry about it too much, I think. However, note that `dict.__str__` does detect cycles.

**Comment by SimonHeybrock** [comment]
Since adding the check in `__setitem__` would only guard against 1 in a million ways of breaking it, is it really worth it?

**Comment by jl-wynen** [comment]
Maybe not

**Comment by SimonHeybrock** [comment]
I'll close this then. We can revisit if we encounter problems in practice.
