### ISSUE TITLE
[DataGroup] Missing features

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#2990]
# Pretty sure these should be done

- [ ] More functional operations. 
  - [ ] adding / removing items
  - [ ] `apply_with_key` that takes a callable of the form `def callback(key, value) -> (key, value)`
- [x] `merge` should work with the data group instead of being mapped to the items
- [x] `hist`, `bin`, `nanhist`, etc. should all be supported as free functions and, where supported by DataArray, as methods.
- [x] Reductions (`all`, `sum`, etc) should be supported as free functions and, where supported by DataArray, as methods.

# Up for debate

- ~[ ] apply by name. E.g. `dg.apply_member('mean')` instead of `dg.apply(operator.methodcaller('mean'))` (it would be nice to use `dg.apply(sc.Variable.mean)` but that only works if all items are variables). This should also work for properties, i.e. `dg.apply_member('shape')` instead of `dg.apply(operator.attrgetter('shape'))`.~  Not for now
- [ ] `variances`, `stddevs` should drop items without variances and return a result for the other items. Right now, they raise if any item has no variances.
- [ ] Data frame like query:
  - [ ] get a coord, attr, mask by name
  - [ ] get only items with a given dim / dim length / shape
  - [ ] General filter, i.e. method like `apply` but it drops items where the callback returns `False`.

**Comment by nvaytet** [comment]
> apply by name

Is it possible to have a mechanism where if you supply a string (e.g. 'mean') to `apply` it internally does the `operator.methodcaller`, and if you supply a Callable, it does what the current `apply` does?

**Comment by jl-wynen** [comment]
It's definitely possible. But is this the API we want or could it be confusing?

**Comment by SimonHeybrock** [comment]
Pandas does something similar... but ?I don't see that as a good reason.  What is wrong with just using `operator.methodcaller`, so we keep `DataGroup` simple?

**Comment by jl-wynen** [comment]
> What is wrong with just using operator.methodcaller, so we keep DataGroup simple?

Nothing for now. We can stick with what we have and see how it works. If it gets too cumbersome, we can still add more features to `apply`.

**Comment by SimonHeybrock** [comment]
> `merge` should work with the data group instead of being mapped to the items

What would this do?

**Comment by jl-wynen** [comment]
> > `merge` should work with the data group instead of being mapped to the items
> 
> What would this do?

```python
def merge(a, b):
  return DataGroup({**a, **b})
```
maybe with conflict handling if the `merge` for datasets does that.

**Comment by SimonHeybrock** [comment]
I'll close this, as the list and discussion is not specific enough and we do not have concrete plans to work on this. Please open a new issue for individual features, if required.
