### ISSUE TITLE
DataGroup `_repr_html_` improvement

### ISSUE THREAD

**Issue by YooSunYoung** [scipp/scipp#3018]
This issue is for listing a potential or observed problems or improvement point of `DataGroup._repr_html_`.

- [ ] In case any string of table item is too big, wrap it into `<detail>` so that we can expand the information.
      - e.g. 
      - Instead of 
            <span>(very_long_name_dimension: 10, another_very_long_name_dimension: 20)</span>
      - Something like this below, but no arrow or no line-break,   also, `...` can be the button to trigger expanding 
            <details><summary>(very_long_name ...</summary>_dimension: 10, another_very_long_name_dimension: 20)</details>

- [ ] After 7-8 depth, the `name` column layout is broken and after 10th depth, it disappears when you hover it.
      - Solution will be to fix the `datagroup.css` not to break the line with the label of the checkbox.
      - Another solution might be adding a button to copy a hint of the index of each row. e.g. `['a']['b']['c']['d']['e']['f']['g']` Then you can easily see the object with the broken display.

- [ ] Different background color for parents rows.
- [ ] Better line break. https://github.com/scipp/scipp/issues/3018#issuecomment-1422094269
- [ ] Make the formatter configurable (?)
      - In case it becomes configurable, allow `json`-like printing option or plain text printing option (?)
- [x] Prioritize line break at `,` instead of blank space in the `shape` column. https://github.com/scipp/scipp/issues/3018#issuecomment-1424180313
- [x] Splitting `html-templates` into multiple files.

**Comment by SimonHeybrock** [comment]
I get a very wide `dims` column, but nevertheless it is rapping in some lines:
![image](https://user-images.githubusercontent.com/12912489/216267054-2a7f45be-614f-4174-b521-855bb5d06b87.png)

**Comment by SimonHeybrock** [comment]
Bug or feature? Should we escape strings?
![image](https://user-images.githubusercontent.com/12912489/216311960-6f1b0ba3-3c41-42b2-8cbb-c49ee0d2569c.png)

**Comment by jl-wynen** [comment]
> Bug or feature? Should we escape strings?

We escape them in dim labels.
I think we should do that everywhere. Note that this is needs to be done for the other html reprs, too.

**Comment by SimonHeybrock** [comment]
Weird linebreak position before closing `)`: 
![image](https://user-images.githubusercontent.com/12912489/217454820-4a74d840-1b24-4d6f-ac83-6431c1e15258.png)

**Comment by YooSunYoung** [comment]
> I get a very wide `dims` column, but nevertheless it is rapping in some lines: ![image](https://user-images.githubusercontent.com/12912489/216267054-2a7f45be-614f-4174-b521-855bb5d06b87.png)
> 
> Edit: Scratch that, it is space for the `dtype` column.

The column size is just decided by the maximum length of the content that exists in the column, even though it's not expanded....
Unfortunately there is not an easy way to dynamically change the column size without using php or javascript.

**Comment by YooSunYoung** [comment]
> Weird linebreak position before closing `)`: ![image](https://user-images.githubusercontent.com/12912489/217454820-4a74d840-1b24-4d6f-ac83-6431c1e15

![Screenshot from 2023-02-09 14-10-01](https://user-images.githubusercontent.com/17974113/217821901-073a2d7d-d503-4a95-a4bc-aab13798246c.png)
258.png)

It was the best I could do. I wrote it down in one of the bullet points.

**Comment by SimonHeybrock** [comment]
Is there a way to break more similar to how Python would break tuples, e.g.,
```
(x: 4, y: 3,
 z: 2)
```
That is:
- break (manually) after comma, but nowhere else
- at whitespace so new lines have same indent as first line (for the `(`)

**Comment by SimonHeybrock** [comment]
The preview is also quite broken for binned data (here the `mcstas_detector`): 
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/12912489/218658129-9c968796-82d3-49f8-9032-046d19f942ca.png">

**Comment by SimonHeybrock** [comment]
Closing for now, concrete ideas and problems will be addressed when they become relevant.
