### ISSUE TITLE
A case of very slow `DataGroup` HTML repr

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#3041]
This takes several seconds, this is the first time I observe such as case:

<img width="914" alt="image" src="https://user-images.githubusercontent.com/12912489/218665203-62d22425-6d12-48dc-a114-f0e84e90fea7.png">

**Comment by jl-wynen** [comment]
How long does it take to show `dg['events']`?

**Comment by SimonHeybrock** [comment]
> How long does it take to show `dg['events']`?

Much shorter.

**Comment by SimonHeybrock** [comment]
The bug is here: https://github.com/scipp/scipp/blob/bc08cac4f2a464e30e1239d67b08542011304d34/src/scipp/html/formatting_datagroup_html.py#L48 (and other places).

**Comment by SimonHeybrock** [comment]
I think it is what may cause the lag... but maybe it is not if it can avoid a copy?

**Comment by SimonHeybrock** [comment]
But the bug is definitely related to the size of the array.

Slow:

```python
import scipp as sc

var = sc.ones(dims=['x', 'y'], shape=[19453467, 6])
dg = sc.DataGroup(a=var)
dg
```

**Comment by SimonHeybrock** [comment]
If I make it 10x larger it takes *ages*.

**Comment by YooSunYoung** [comment]
Right... the document says it creates a copy only if needed though...? I'll update this part to avoid the lag.

**Comment by YooSunYoung** [comment]
It was because of `deque`...! Sorry, I'll remove that part.
