### ISSUE TITLE
Error for bins having units when they don't

### ISSUE THREAD

**Issue by arm61** [scipp/scipp#3047]
I am getting the following error:

```
UnitError: Bins cannot have a unit. Did you mean to set the unit of the bin elements? This can be set with `array.bins.unit = 'm'`.
```

When I try and histogram a binned object that has a mask. Not quite clear the cause as the object has no units itself. 

*Minimal example*

```
import scipp as sc

top = sc.array(dims=['a'], values=[1, 2, 3, 4, 5, 6])
top_bin = top.bin(a=2)

bottom = sc.array(dims=['a'], values=[4, 5, 6, 7, 8, 9])
bottom_bin = bottom.bin(a=top_bin.coords['a'])

div = top_bin / sc.values(bottom_bin).hist(a=top_bin.coords['a'])

div.masks['zeros'] = (bottom_bin == sc.scalar(0, unit='counts')).data

div.hist(a=200)
```

Will throw the error, but 

```
div.unit == None
```

is true.

**Comment by SimonHeybrock** [comment]
There are a couple of problems here. First, the error message is unclear, we can fix that. The rest are:

1. You are setting a "binned" mask on `div`. If you need to mask individual events, you should use `div.bins.masks['zeros'] = ...`
2. The number of events in`bottom_bin` are different, so you cannot use that to mask events in the top bin.
 
Did you mean to mask all the bins that have events with zero weights? Or all the bins that contain an event with a zero?

You can modify your example to mask bins, and this works:

```python
import scipp as sc

top = sc.array(dims=['a'], values=[1, 2, 3, 4, 5, 6])
top_bin = top.bin(a=2)

bottom = sc.array(dims=['a'], values=[4, 5, 6, 7, 8, 9])
bottom_bin = bottom.bin(a=top_bin.coords['a'])

div = top_bin / bottom_bin.hist()

div.masks['zeros'] = (bottom_bin.hist() == sc.scalar(0, unit='counts')).data

div.hist(a=200)
```

**Comment by arm61** [comment]
Cool, that works. Feel free to close unless you want to improve the error message first.

**Comment by jokasimr** [comment]
```python
import scipp as sc

top = sc.array(dims=['a'], values=[2, 3, 4, 5, 6, 7])
top_bin = top.bin(a=2)

bottom = sc.array(dims=['a'], values=[4, 5, 6, 7, 8, 9])
bottom_bin = bottom.bin(a=top_bin.coords['a'])

div = top_bin / sc.values(bottom_bin).hist(a=top_bin.coords['a'])

div.masks['zeros'] = (bottom_bin == sc.scalar(0, unit='counts')).data
```
In the above example we have a mask that is binned where every bin contains a `DataArrayView`
```python
div.masks['zeros']
```
![Image](https://github.com/scipp/scipp/assets/20954731/f77ac4f1-549a-4924-8107-3d1e22322f89)

Is that a "valid" kind of mask? My assumption was that a mask should always be 'boolean valued' and not '`DataArray` valued'.
If the mask is not valid then we could perhaps catch this error already when the mask is being set.

**Comment by SimonHeybrock** [comment]
You can have masked bin-elements (instead of masked bins). See example here: https://scipp.github.io/user-guide/binned-data/binned-data.html#Masking. Yes this is valid and it is handled in operations.

**Comment by jokasimr** [comment]
Sure, as it says in the docs: "Masks can be defined **for the scattered data array**, as well as **for the bin wrapper**."

But isn't this is a third case? The mask is defined on the bin wrapper but the shape is the same as the underlying scatter data.

This example constructs a mask of each of the three types:
```python
import numpy as np
N = 50
values = 10*np.random.rand(N)
table = sc.DataArray(
    data=sc.array(dims=['row'], unit=sc.units.counts, values=values, variances=values),
    coords={
        'position':sc.array(dims=['row'], values=['site-{}'.format(i) for i in range(N)]),
        'x':sc.array(dims=['row'], unit='m', values=np.random.rand(N)),
        'y':sc.array(dims=['row'], unit='m', values=np.random.rand(N))})
table
binned = table.bin(y=4, x=2)
binned = binned.bin(y=10, x=10)
x_y_mask = (binned.coords['x'][1:] < 0.5 * sc.Unit('m')) & (
    binned.coords['y'][1:] < 0.5 * sc.Unit('m')
)
binned.masks['mask_on_binned'] = x_y_mask
binned.bins.masks['mask_on_scattered'] = binned.bins.coords['y'] > 0.6 * sc.Unit('m')
binned.masks['wrong?'] = binned.bins.coords['y'] > 0.6 * sc.Unit('m')
```

Is that a correct way to define a mask? Should `mask_on_scattered` and `wrong?` be considered equivalent?

**Comment by SimonHeybrock** [comment]
Don't you get a `DimensionError` when trying to insert your `'wrong?` mask?

**Comment by SimonHeybrock** [comment]
The third case is not prevented, but it is meaningless: You could have completely different bin sizes on a mask stored like that, and only in the special case where it matches the bin sizes of the data one could *guess* that the are associated. This makes little sense in practice.

**Comment by jokasimr** [comment]
Okay, because I think a similar case is the root cause of the confusing error message.
So if we start raising `DimensionError` in this case perhaps that would solve this issue?

**Comment by SimonHeybrock** [comment]
> So if we start raising DimensionError in this case perhaps that would solve this issue?

You mean when inserting the mask? I don't think we want to do that. Scipp only handles masks with `dtype=bool`, but we allow storing mask with other types (such as `int`). This may be useful for users, and it is fine as long as no operations are applied that touch the mask.

We should rather raise a cleared `TypeError` when trying to *handle* such a mask.

**Comment by jokasimr** [comment]
> You mean when inserting the mask? 

Yes that's what I meant.

> Scipp only handles masks with dtype=bool, but we allow storing mask with other types (such as int). This may be useful for users, and it is fine as long as no operations are applied that touch the mask.

Seems odd to allow any datatype if we can only deal with bool valued masks. What are the use-cases for that? If the user wants to store arbitrary data they should probably do that directly using a datarray or a dataset, no?

**Comment by SimonHeybrock** [comment]
> > Scipp only handles masks with dtype=bool, but we allow storing mask with other types (such as int). This may be useful for users, and it is fine as long as no operations are applied that touch the mask.
> 
> Seems odd to allow any datatype in the `masks` field if we can only deal with bool valued masks. What are the use-cases for that? If the user wants to store arbitrary data they should probably do that directly using a datarray or a dataset, no?

Aside from the longer explanation on Slack: As a very concrete example, Mantid supports fractional masks (float ranging from 0 to 1). Our *operations* cannot handle this, but aside from that there is no reason to prevent this in our data structures.

**Comment by SimonHeybrock** [comment]
See #3279
