### ISSUE TITLE
Option to have normalisation by bin widths in histogramming

### ISSUE THREAD

**Issue by arm61** [scipp/scipp#3053]
Currently, if I have reflectometry data, the intensity is dependent on the number of bins, i.e. 

![Screenshot 2023-02-15 at 16 13 47](https://user-images.githubusercontent.com/15774281/219068293-a2baa92e-e420-4ea4-aa9e-6a979270b31c.png)

versus

![Screenshot 2023-02-15 at 16 14 03](https://user-images.githubusercontent.com/15774281/219068388-0aa11369-5d15-4918-bbb9-54425c3404f1.png)

Correctly normalised reflectometry data is definitionally the ratio between incident and reflected neutrons as a function of $Q$ so to have reflectometry data, it should be possible normalise the data by number of bins.

**Comment by arm61** [comment]
Closed cause I realised I want to multiply by bin number not divide by bin widths. [PBKAC](https://www.acronymfinder.com/Problem-Between-Keyboard-And-Chair-(PBKAC).html)

**Comment by SimonHeybrock** [comment]
You may also be interested in https://scipp.github.io/generated/classes/scipp.Bins.html#scipp.Bins.mean, I don't know if that solves your problem?

**Comment by arm61** [comment]
Mean also changes the scaling with different numbers of bins.
