### ISSUE TITLE
Test assertion helper

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#3055]
We currently use `sc.identical` for comparing Scipp objects in unit tests. This leads to unreadable assertion error messages. Pytest has [pytest_assertrepr_compare](https://docs.pytest.org/en/6.2.x/assert.html#defining-your-own-explanation-for-failed-assertions), but that only works for operations. See also https://github.com/pytest-dev/pytest/issues/5535.

As a workaround, we could implement a helper function that calls `sc.identical` but results in a better error message.

We may even consider not calling `sc.identical`, but instead (or maybe in the `except` case), asserting on the individual pieces of the inputs, so a more fine-grained error can be generated. Otherwise we frequently run into identical "print" outputs, e.g., because some element in the middle is different, or elements only differ before rounding for printing.

**Comment by jl-wynen** [comment]
A function that asserts on individual pieces could use assertions from `np.testing` which provide good error messages for the data.

**Comment by jl-wynen** [comment]
Going to implement `assert_identical`. Do we also need `assert_not_identical`? Numpy does not have any equivalent of this. But doing such an assertion requires
```python
try:
    assert_identical(x, x)
except AssertionError:
    raised = True
else:
    raised = False
assert raised
```
which isn't very nice.
