### ISSUE TITLE
Explicitly reexport public symbols

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#3065]
Currently, mypy with `--strict` complains about code like the following:

```python
import scipp as sc
sc.arange('x', 1)
```
with
```
error: "Module scipp" does not explicitly export attribute "arange"  [attr-defined]
```

This is because the top level `__init__.py` does not reexport its imported symbols. See https://mypy.readthedocs.io/en/stable/command_line.html?highlight=strict#cmdoption-mypy-no-implicit-reexport for an explanation.

So I see 2 solutions:
- Define `__all__` in all relevant modules in Scipp. (This would be cleanest but also a bunch of work to keep up to date. Although we don't add a lot of things any more.)
- Tell users not to use `--strict` or `--no-implicit-reexport` with mypy. (This doesn't really work in general, but we can adopt this internally.)

**Comment by SimonHeybrock** [comment]
Is this by any chance related to the issues with have with Sphinx automodule, not listing things imported in `__init__` in various (non-top-level) places?

**Comment by jl-wynen** [comment]
I don't know.

**Comment by jl-wynen** [comment]
> Is this by any chance related to the issues with have with Sphinx automodule, not listing things imported in __init__ in various (non-top-level) places?

Doesn't look like it is related. #3066 import `assert_identical` into `scipp.testing` and adds it to `__all__`. But autosummary still doesn't show it in the docs of `scipp.testing`.
