### ISSUE TITLE
Switch to pydate theme (was: Update to sphinx-book-theme 1.0)

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#3072]
1.0 has just been released yesterday. It supports the latest version of Sphinx and a dark mode.

But it breaks our header template and launch buttons. I am not sure how to even add buttons now. They don't seem to support the customisation options of the underlying pydata-theme. It is possible to add content to the navbar but that is placed above regular header and just looks wrong. 

Maybe we can find a different place for the 'related projects' menu.
And the version selection is hopefully supported by the theme natively. pydata supports it but books may disable it. If it does, we should consider switching to pydata. This would allow us to get rid of the double build at release.

Anyway, I made a start on the `update-sphinx` branch.

**Comment by SimonHeybrock** [comment]
Conclusion from discussion: We are strongly considering using the pydata theme (see https://scicatproject.github.io/scitacean/index.html for an example).

**Comment by nvaytet** [comment]
Done in #3362
