### ISSUE TITLE
Rename `to_hdf5` and `open_hdf5`

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#3075]
The current names are not ideal because 'to' and 'open' are not natural pairs.
- 'open' pairs with 'close', so this name doesn't fit.
- 'to' pairs with 'from'. I would not expect those functions to reach out to disk but operate on in-memory structures.

So I suggest to rename them to `save_hdf5` and `load_hdf5` in order to match the scheme in ScippNeutron and NumPy.

`write_hdf5` and `read_hdf5` would also be an option. But as I say above, ScippNeutron uses a the 'load'/'save' scheme.

**Comment by SimonHeybrock** [comment]
I think the current naming was from Pandas/Xarray. Most importantly however, I think that `open` is actually misleading, since it does not just "open" the file, but also read it (maybe it made more sense in Xarray, since it could use dask to lazy-load?). So :+1: on renaming. Not sure yet which version I prefer.

**Comment by SimonHeybrock** [comment]
Let us compare, which feels better when combined with suffixes?

```
load
load_hdf5
load_csv
save_hdf5
save_csv
```
```
read
read_hdf5
read_csv
write_hdf5
write_csv
```

**Comment by SimonHeybrock** [comment]
> We can discuss the pairing of load but at the least, `to` pairs with `from` and doesn't really work.

Why does it not work? If it is a static method?

```python
sc.DataArray.from_hdf5(name)
```

**Comment by jl-wynen** [comment]
> Why does it not work? If it is a static method?
> 
> ```python
> sc.DataArray.from_hdf5(name)
> ```

I might be biased because of Rust and Scitacean. But in those cases, `from` would be some more direct conversion. E.g. `sc.DataArray.from_hdf5(h5group)` would be fine. Because the argument has a 'hdf5-type'.

But also, we don't only have methods. In particular, when reading a HDF5 file, you don't necessarily know what type it contains.

**Comment by nvaytet** [comment]
`sc.DataArray.from_hdf5(name)` would mean that you know in advance that you will be reading a `DataArray`? But maybe the file contains a `DataGroup`?

So I would day `sc.io.load_hdf5(name)` makes more sense, as it can return either a `DataArray` or a DataGroup`?
