### ISSUE TITLE
Plotting documentation

### ISSUE THREAD

**Issue by nvaytet** [scipp/scipp#308]
Help documentation should be added to the `plot` function, which can take in many different arguments:
- `waterfall=Dim.X`
- `collapse=Dim.Y`
- `axes=[Dim.X, Dim.Z]`
etc...

**Comment by SimonHeybrock** [comment]
https://github.com/scipp/scipp/pull/305#issue-291980635 contains a number of nice basic plotting examples. I suggest to convert the PR message including examples into a sphinx page so these examples can be seen on RTD.

**Comment by SimonHeybrock** [comment]
See also https://github.com/readthedocs/sphinx_rtd_theme/issues/788, plotly currently not working with RTD theme.
