### ISSUE TITLE
`sc.sort` has strange behaviour with bin edge coordinates

### ISSUE THREAD

**Issue by nvaytet** [scipp/scipp#3086]
Sorting a data array with a midpoints coord works as expected.
However, making the same data array with a bin edge coord has a strange behaviour.
```Py
a = sc.DataArray(data=sc.array(dims=['x'], values=np.random.random(20)),
                 coords={'x': sc.linspace('x', 80, 33, 21, unit='m')})
sc.sort(a, key='x')
```
`sc.sort` drops the coord, probably because in principle there is no way to keep the bin edge coordinate if the edges are not monotonous.
However, if they are monotonous, the coord could be kept in the result.

In addition, the above returns a data array with data than now has shape 21 instead of 20, and the first value in the array is garbage (e.g. 1.0e-300).

**Comment by SimonHeybrock** [comment]
> However, if they are monotonous, the coord could be kept in the result.

I don't feel this is useful, sorting by bin edges just does not make sense conceptually. We should just raise an exception when attempting to sort by bin edges.

**Comment by nvaytet** [comment]
Yeah, maybe we should just throw. However, Drew came across this when trying to rebin a data array that had a Q coordinate that had been obtained from doing a transform coords from wavelength, so the Q axis is reversed in the result.
He then could not use `rebin` because it said the edges were not sorted.

I guess the best would probably be to just support negative strides in slicing to reverse the array.

**Comment by SimonHeybrock** [comment]
We should not abuse `sort` for reversing. Either we implement negative strides as you suggest, or implement something like `reverse`.
