### ISSUE TITLE
Replace `coords/attrs` mechanism by `coords` with `aligned` flag

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#3109]
Part of #2675. See in particular https://github.com/scipp/scipp/issues/2675#issuecomment-1337336190.

There are two reasons for this:

1. The `coords`/`attrs` mechanism is cumbersome for users (including, to a large extend, ourselves, when developing downstream code). In particular after calls to `transform_coords` it is unclear where to find a coord. We provide `meta`, but it does not support writing.
2. `attrs` would be useful for non-array "attributes", for example as supported by HDF5. Currently there is no way to support this. We would therefore like the free the `attrs` name so we can add this in the future.

The proposed solution is as follows:

1. Remove `attrs` and `meta` (after deprecation period).
2. Add `aligned` flag.
3. Adding a coord sets the `aligned` flag to a default value (probably `aligned=True`).
4. All mechanisms that currently change coords to attrs (or vice versa) are changed to toggle the `aligned` flag.

Consequences (apart from the obvious ones):

- Adding a new coord that is unaligned may become a two-step process. If this is a problem, a special helper can be added.

Implementation options:

- Add flag in the `coords` mapping implementation (`SizedDict`). While this seems sensible, it looks like a quite involved change.
- Add a flag in `Variable`. This may seem weird at first, since conceptually "alignment" does not make sense conceptually for anything but coords. However:
  - It is simple (simpler changes in the `SizedDict`).
  - It will incur no size overhead (we already have a single `bool` field, so according to C++ structure rules a second one will not make any difference).
  - May offer benefits since we could (if desired) preserve alignment flags when moving coords between data arrays.
  - Nicer API for users: `da.coords['x'].aligned = True` instead of `da.coords.set_aligned('x', True)`
  
  The downside is that a user can call `da.masks['mask'].aligned = False` or `da.data.aligned = False`, which makes no sense (but has no negative consequences either). Is there a significant risk that this would hide bugs?

**Comment by jl-wynen** [comment]
We should have a simple way to extract and set coords. A two step process will be cumbersome. So I suggest for getting coords: `coords` gives all coords, `aligned_coords` and `unaligned_coords` only give aligned/unaligned coords.
(In don't like the names, they are too long)

Another downside with an alignment flag in Variable: We need to be clear about the semantics of adding coords. E.g. `a.coords['x'] = b.unaligned_coords['x']` would create an unaligned coord. If `a.coords['x']` was aligned before, the assignment would make it unaligned.

So a potential specification could be, `coords` preserves whatever alignment the RHS has. `aligned_coords` and `unaligned_coords` would always set the flag to True/False on assignment.

**Comment by SimonHeybrock** [comment]
> We should have a simple way to extract and set coords. A two step process will be cumbersome. So I suggest for getting coords: `coords` gives all coords, `aligned_coords` and `unaligned_coords` only give aligned/unaligned coords. (In don't like the names, they are too long)


Can you list some cases where this is relevant and saves significant amount of code?

> Another downside with an alignment flag in Variable: We need to be clear about the semantics of adding coords. E.g. `a.coords['x'] = b.unaligned_coords['x']` would create an unaligned coord. If `a.coords['x']` was aligned before, the assignment would make it unaligned.

I suppose we just need to be clear that "alignment" is a property of a coord, not a separate flag in the coords dict? If we set the alignment using a flag on the variable then this should be quite clear? What `__setitem__` does is obvious, since as always, it completely replaces potential existing items.

**Comment by jl-wynen** [comment]
> Can you list some cases where this is relevant and saves significant amount of code?

I guess many places internally like `hist` and friends or plotting. This doesn't save a significant amount of code per usage but improves readability. Otherwise we always have to do things like
```python
c = da.coords[n]
if c.aligned:
  # do thing
```
or
```python
for n, c in da.coords.items():
  if not c.aligned:
    continue
```

How should alignment be handled in operations? What if you add an aligned and unaligned variable? (Or more advanced: what about coord transforms?)
What if you add two data arrays, one with aligned 'x' and one with unaligned 'x'?
Should hist and friends work on unaligned coords?

**Comment by SimonHeybrock** [comment]
> I guess many places internally like hist and friends or plotting

Can you actually find any concrete examples? As far as I remember it is often the opposite: The distinction between aligned and unaligned is irrelevant in many places (such as plotting), so this change would simplify the code rather than complicate it.

**Comment by jl-wynen** [comment]
> Can you actually find any concrete examples?

I guess if we make all or most operations work with both aligned and unaligned, the only place where we need to make a distinction is in binary operations. And those are handled in C++ anyway.

> Not sure I get the question. The behavior for coord transforms should be unchanged.

It was about promotion to aligned coords if all inputs to one coord are unaligned. But I agree that we should keep the current behaviour.

**Comment by jl-wynen** [comment]
I tried to implement the flag in variable. This doesn't work with the current interface of `SizedDict` (C++ class for `coords`) because its `operator[]` returns by value. I.e. it makes a copy of the variable. So `da.coords['x'].aligned = False` sets the flag on a temporary variable, not in the actual `coords` dict.

`SizedDict` was implemented this way to enforce the constrained that all items must have a size that is consistent with the data array. Returning a mutable-ref from `operator[]` would allow users to break this. But only in C++, there is no way to do this in Python. So we might consider removing this protection and returning by reference.

For now, I'm looking into implementing the flag in `SizedDict`.

**Comment by SimonHeybrock** [comment]
Is there more to do here @jl-wynen?

**Comment by jl-wynen** [comment]
Deprecation and removal of attrs

**Comment by SimonHeybrock** [comment]
That is unrelated, isn't it?

**Comment by jl-wynen** [comment]
The issue is called *replace* `coords/attrs` mechanism ...
We need to track the removal as well.

**Comment by SimonHeybrock** [comment]
This thread was about the `aligned` flag. `attrs` removal is tracked in #3166.
