### ISSUE TITLE
Replace predefined units with dynamic attr lookup

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#3127]
From a discussion on Slack:

We have moved away from using the limited set of predefined units and use, e.g., `sc.Unit('s')` instead. This is a little tedious because it needs more keystrokes than `sc.units.s`.

We can make this more convenient by adding the following to the units module (potentially with try-except to provide a better error message):

```python
def __getattr__(name: str) -> Unit:
    return Unit(name)
```

This would allow people to use `sc.units.s`, `sc.units.km`, etc. to *construct* units.

Note that `sc.units` currently contains two public members that are not predefined units: `aliases` and `UnitAliases`. Is it too confusing that those two are regular attributes but `sc.units.anything_else` constructs a new unit?
We might also add more functions / types to this module in the future. But a clash with any unit name seems unlikely.

**Comment by jl-wynen** [comment]
Duplicate of #3128

**Comment by nvaytet** [comment]
Judging from the issue number, yours was first ;-)
