### ISSUE TITLE
Make `sc.units` callable and remove the need for using `sc.Unit('m')`

### ISSUE THREAD

**Issue by nvaytet** [scipp/scipp#3128]
From Slack discussion

When using units in scipp, we have both `sc.units.s` (where `sc.units` has a set of predefined units) and `sc.Unit('s')`.
We, as developers, know that when it is not found in `sc.units`, we can use the other syntax, but I think it's confusing for users.
Would it be possible/desirable to have it so that you can do `sc.units.s` or `sc.units('s')`, to reduce the learning curve for users?

Simon Heybrock:
    We have been gradually removing the use of the predefined units, using strings everywhere.

Simon Heybrock:
    I wonder if one get define a `__getattr__` such that it just calls` sc.Unit` with the attr name. Then we would not be limited to pre-defined aliases. But I am not sure we want to go that path.

Neil Vaytet:
    I think it sounds like a useful way of doing things, but I probably don't understand the possible security implications

Jan-Lukas Wynen:

> possible security implications

Why would there be security implications?
This would require a class. So either we use `sc.Unit` for this, e.g. `sc.Unit.s` , or we turn units into a class, or we add a new one. But what about the other attributes in `sc.units`?

Simon Heybrock:
    :man-shrugging:

Sunyoung Yoo:
    But what about the other attributes in `sc.units`? Maybe we can wrap it in the try-except...?

Jan-Lukas Wynen:
    Actually, it is possible to define `_getattr_` for a module. So we could use the existing `sc.units` for this.

Neil Vaytet:
    I thought `__getattr__` is only called for attributes that don't exist? (edited) 

Jan-Lukas Wynen:
    correct

Neil Vaytet:
    so existing attributes should be fine, as long as they are not called `s` or something :wink:

Jan-Lukas Wynen:
    Yes. I'm not a huge fan of mixing dynamic attributes and static ones in this way. Though the risk of a clash should be small.
(Currently, `sc.units` only has `aliases` and `UnitAliases` members in addition to predefined units.)

Simon Heybrock:
    Why would we keep that static ones? Performance?

Jan-Lukas Wynen:
    No. I'm talking about aliases

Jan-Lukas Wynen:
    `sc.units.aliases` is a `dict` but `sc.unit.anything-else` is `sc.Unit('anything-else')`. Which might be suprising

**Comment by SimonHeybrock** [comment]
Have any users actually complained about the `sc.Unit('m')` syntax? I feel in practice many users don't create "simple" (without * or /) units very often? This reminds me partly of the discussions in the dim and distant past about long variable names (which or more typing... but how much of you dev time to you actually spend typing?).

UX wise, I feel something like `sc.quantity(1.2, 'm/s')` would be more beneficial. We could remove the need for the `unit` kwarg from `sc.scalar`, or add a new `sc.quantity`.

**Comment by nvaytet** [comment]
I am not sure `sc.quantity(1.2, 'm/s')` helps much? Are you saying we would then remove `sc.scalar()`? Otherwise, there would be two different ways of doing the same thing, which I think is even more confusing?

**Comment by SimonHeybrock** [comment]
Helps much with what?

**Comment by nvaytet** [comment]
Usability, reducing confusion. All variables in Scipp have units. If you have `sc.quantity` and `sc.scalar`, for a new user this may look like `quantity` has units and `scalar` does not?

**Comment by YooSunYoung** [comment]
> I think the word "quantity" has a pretty clear meaning? Which part is not usable?

`quantity` sounds like a function call that should return the size of the contents or sth...?

**Comment by SimonHeybrock** [comment]
Let us leave `scalar` out of the discussion for now: My question is: What would justify the proposed `__call__` function, compared to having something named `sc.quantity`?

**Comment by SimonHeybrock** [comment]
> > I think the word "quantity" has a pretty clear meaning? Which part is not usable?
> 
> `quantity` sounds like a function call that should return the size of the contents or sth...?

Every units library I have seen uses the term "quantity". I think it is much clearer than the `scalar` we have now. But this is not the main discussion here.

**Comment by nvaytet** [comment]
> What would justify the proposed __call__ function, compared to having something named sc.quantity?

Can you illustrate how `quantity` would be used?

What I would like is to remove the need for knowing that sometimes you have to use `sc.units.s` and sometimes you have to do `sc.Unit('Hz')`.

That is the only thing I am after. Either we remove `sc.units.s` and only use the `sc.Unit()` syntax, or we have a `units` thing that can be used as `sc.units.s` and `sc.units('s')`.

Having `sc.units.s` would be needed for backwards compatibility. I would also be happy with just `sc.units('s')` but I think it would break too many notebooks.

**Comment by nvaytet** [comment]
I am not saying we would remove `sc.Unit('m')` because that would also break notebooks, but gradually phase its use out of our docs ntoebooks.

**Comment by SimonHeybrock** [comment]
> What I would like is to remove the need for knowing that sometimes you have to use sc.units.s and sometimes you have to do sc.Unit('Hz').

You never have to use use `sc.units.s`. In fact we have pretty much phased-out its use (including removing uses in the docs). That is, we could consider removing the pre-defined aliases now.

**Comment by SimonHeybrock** [comment]
> I am not saying we would remove `sc.Unit('m')` because that would also break notebooks, but gradually phase its use out of our docs ntoebooks.

I don't understand. What did you suggest to replace it with?

**Comment by nvaytet** [comment]
> I don't understand. What did you suggest to replace it with?

I suggested `sc.units('m')` would return the same as `sc.Unit('m')`.
Both would still work, but users don't have to learn about both, they can just use `sc.units` to do either `sc.units('m')` or `sc.units.m`, whichever they prefer.

However, if you say that `sc.units.m` is not used much in the docs or the code, I am happy with just keeping `sc.Unit('m')`.

**Comment by SimonHeybrock** [comment]
I think when we are dealing with constructing classes we prefer CamelCase. On top of that, given the very widespread use of `Unit` I do not see a case for renaming it to `units`.

So back to the (I think) original question: What was the case for the `__getattr__` we discussed initially, to provide support for arbitrary things such as `sc.units.kilometer` (by forwarding to the string-based constructor)?

**Comment by nvaytet** [comment]
A quick survey: number of occurrences of `sc.units.*`
- `scipp`: 503 (i searched `src`, `tests`, `docs`)
- `scippneutron`: 155
- `plopp`: 1
- `scippnexus`: 3

**Comment by SimonHeybrock** [comment]
> > I think when we are dealing with constructing classes we prefer CamelCase. On top of that, given the very widespread use of Unit I do not see a case for renaming it to units.
> 
> We have plenty of functions that return classes, e.g. `sc.array()`. Why is it not an issue there?

We can argue about that. But what is the case for renaming? Not pressing the Shift key?

**Comment by nvaytet** [comment]
> So back to the (I think) original question: What was the case for the __getattr__ we discussed initially, to provide support for arbitrary things such as sc.units.kilometer (by forwarding to the string-based constructor)?

> We can argue about that. But what is the case for renaming? Not pressing the Shift key?

I don't mind if users have to use `sc.units.kilometer` or can only use `sc.units('kilometer')`, what I mind is that currently you can do both `sc.units.s` and `sc.Unit('s')`, but you can only do `sc.Unit('Hz')`, because `sc.units.Hz` fails.

I don't really know how else to write it to make it clearer?

**Comment by nvaytet** [comment]
I am saying we either have `sc.units` or `sc.Unit`, not both.

**Comment by SimonHeybrock** [comment]
I don't mind removing the aliases, as I said we have in fact already refactored most of the docs to that end. It was just very confusing in how the issues was formulated.

**Comment by nvaytet** [comment]
> It was just very confusing in how the issues was formulated.

Not sure why you are saying that, my first suggestion was to make `units` callable, so you could use both `sc.units('m')` and `sc.units.m`, which you understood perfectly as you suggested to use the dynamic `__getattr__`.

It then diverged towards discussing why it should be `sc.units()` instead of `sc.Unit()`, and as I explained, I thought we needed to keep `sc.units.m` for backwards compatibility.

You then said we don't need to because we have been phasing it out anyway, and we can just use `sc.Unit()` everywhere.

I am not sure why you say it's confusing.

**Comment by SimonHeybrock** [comment]
> > It was just very confusing in how the issues was formulated.
> 
> Not sure why you are saying that, my first suggestion was to make `units` callable, so you could use both `sc.units('m')` and `sc.units.m`, which you understood perfectly as you suggested to use the dynamic `__getattr__`.

It is confusing, because on Slack (as you copied into the first message), we were talking about `__getattr__`, but you then seemed to have moved into discussing `__call__`. `__getattr__` does not give you `sc.units('m')`.

**Comment by nvaytet** [comment]
The first message copied above is about `sc.units('s')`, i.e. the `__call__`.
You brought in the `__getattr__`.
I just copied from slack.

**Comment by SimonHeybrock** [comment]
I apologize for misunderstanding then.

In the follow-up discussion above discussion we seem to agree that (effectively) renaming `Unit` -> `units` is not useful. I'll therefore close this.

If you would like to remove the pre-defined aliases, please open a new issue.
