### ISSUE TITLE
Investigate `sc.group` baseline cost scaling with the number of groups

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#3130]
<img width="616" alt="image" src="https://user-images.githubusercontent.com/12912489/233621281-4559d944-40af-448b-b288-acab7e14a07b.png">

We expect the term that is "constant" in `nevent`, but it is not clear why it is quite so high. Check if all suboperations are multi-threaded, etc.

```python
import scipp as sc

def make_events(ndet, nevent):
    table = sc.data.table_xyz(nevent)
    table.coords['pix'] = (table.coords.pop('z') * ndet).to(dtype='int64')
    table.coords['pix'].unit = None
    return table

pix = sc.arange('pix', ndet, unit=None)
events = make_events(ndet=ndet, nevent=nevent)
events.group(pix)
```

**Comment by SimonHeybrock** [comment]
A quick experiment shows that a significant contribution to the baseline cost is a per-thread cost. The original plot above is for 24 threads. We can reduce it to 12 to obtain:


![Image](https://user-images.githubusercontent.com/12912489/233904728-bbaa4fc4-e990-4690-bff3-957e092e8da2.png)


Or further to 6:


![Image](https://user-images.githubusercontent.com/12912489/233904772-5ded8381-372c-4d33-aa3e-79e4c0925ae5.png)

Two observations:

- When we approach 1e8 events then fewer threads would be a pessimization. Therefore, we should check the size of the input buffer to set the number of threads dynamically.
- There appears to be yet another large contribution (of the order of 1 second for 4 Mbins) independent of the thread count. This needs to be investigated further.

The code controlling the thread count for this part of `bin` is https://github.com/scipp/scipp/blob/606af7647f7dcb08535de0c4844c15e4243e888e/lib/dataset/bins.cpp#L215-L225. Note that there are other suboperations which are not affected by this.

**Comment by YooSunYoung** [comment]
Sorry for being late...! Here is the benchmark from beamlime with this change...!
`er` refers to `event_rate`, wihch is number of events and `np` refers to number of pixels, which is size of bins.
The dummy workflow for benchmark is here: https://github.com/scipp/beamlime/blob/main/tests/prototypes/workflows.py

![performance](https://github.com/scipp/scipp/assets/17974113/edb683d7-dd5f-4df3-b000-38d08cfaa390)

**Comment by YooSunYoung** [comment]
> Can't see anything on this plot for the relevant values. Can you plot the relative change, for example?

like this...? @SimonHeybrock 

![performance_improvement](https://github.com/scipp/scipp/assets/17974113/7eaa04dd-5bef-4089-996c-6a3daffb02bd)

**Comment by SimonHeybrock** [comment]
I still can't see anything, as the datapoints look exactly zero. Can you plot the relative change such as 23.11/23.08?

**Comment by YooSunYoung** [comment]
> I still can't see anything, as the datapoints look exactly zero. Can you plot the relative change such as 23.11/23.08?

Ah ha...! I see. Like this...? 

![relative_improvement_plot](https://github.com/scipp/scipp/assets/17974113/bf2fe29f-d45c-43a1-9c16-ca7bc8fa5636)

**Comment by SimonHeybrock** [comment]
Is that time or rate? That is, is a positive value and improvement or a regression?

**Comment by YooSunYoung** [comment]
> Is that time or rate? That is, is a positive value and improvement or a regression?

It's still comparison between process rates, frame per second.
I put how they are derived in the legend, and each one refers to the original plot.
Maybe I should have put them in one plot...

Here is the all in one plot. The equation to derive the difference is included in the legend.

![performance_improvement](https://github.com/scipp/scipp/assets/17974113/17e2068d-bc8c-473a-bbfc-2fad8ae60890)
