### ISSUE TITLE
DataGroup shape operations should not be applied to non-scipp items

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#3135]
Example:

```python
import scipp as sc
import numpy as np

dg = sc.DataGroup(a=sc.ones(dims=['x','y'], shape=(2,3)), b=np.ones(shape=(10,2)))
dg.transpose()
```
This transposes the NumPy array, which is inconsistent, since it is considered a scalar 0-D object for operations such as slicing. Aside from NumPy arrays, we get exceptions if we have, e.g., a Python `str` item.

We should change all "shape" operations of `DataGroup` to ignore non-scipp items, with the same logic as applied in `__getitem__`.

Methods/functions to change (may be incomplete, please double check):
- `broadcast`
- `fold`
- `flatten`
- `squeeze`
- `transpose`

**Comment by SimonHeybrock** [comment]
There is a problem defining a consistent behavior:
```python
dg = sc.DataGroup(a=sc.scalar(1))
dg.broadcast(sizes={'x': 2})  # expect broadcast?
```

```python
dg = sc.DataGroup(a=1)
dg.broadcast(sizes={'x': 2})  # expect no broadcast?
```
Compare this also with `DataArray.broadcast`, which keeps scalar coord untouched, but always broadcasts data. `DataGroup` cannot make this distinction, so what should it do? Do we always have to broadcast (or flatten, ...)?

**Comment by jl-wynen** [comment]
Doesn't this argument also apply to the other shape functions? They too always modify the data of a data array. Why are broadcast and flatten (as singled out in the PR) special?

**Comment by SimonHeybrock** [comment]
Consider what, e.g., `squeeze` does: If something is 0-D it keeps it 0-D.

**Comment by jl-wynen** [comment]
Ok. But this is unique to squeeze. broadcast doesn't leave scalars as scalars. It always changes the data (like fold and flatten)

**Comment by SimonHeybrock** [comment]
Exactly, that is why I did not change broadcast.

**Comment by SimonHeybrock** [comment]
Not unique to `squeeze`, but also to `transpose` and `fold`: They do nothing to items that do not have the dims (or any dims).

**Comment by jl-wynen** [comment]
But fold and flatten raise an exception if the input dim does not exist which is different from squeeze.

**Comment by SimonHeybrock** [comment]
That is probably a wider discussion than this issue. Consider

```python
import scipp as sc
import numpy as np

dg = sc.DataGroup(a=sc.ones(dims=['x','y'], shape=(2,3)), b=sc.arange('y', 5))
dg.fold(dim='x', sizes={'x1':1, 'x2':-1})
```
You are saying that this must raise an exception?

**Comment by jl-wynen** [comment]
I think so. `dg.sum('x')` raises, so why wouldn't `fold`?

Maybe neither should raise. But then we should think about a proper definition for how dimensions are handled instead of singling out a couple of functions now.

**Comment by SimonHeybrock** [comment]
> I think so. `dg.sum('x')` raises, so why wouldn't `fold`?
> 
> Maybe neither should raise. But then we should think about a proper definition for how dimensions are handled instead of singling out a couple of functions now.

I think you make a fair point, but nevertheless I see some significant difference. First consider reduction operations:

```python
dg.sum()  # could apply to all items
dg.sum('x')  # if this skips x-independent, the result is bad if there are masks
```
This leads me to two possible conclusions:

1. `sum(dim)` should raise, unless *all* items have the requested dims, or
2. `sum(dim)` should *preserve all but the given dim*.

Now, for `squeeze` and `transpose` I feel the answer is simple &mdash; I cannot think of a good reason why we should not simply skip items that have nothing to squeeze or transpose.

For `fold` I would argue that this is similar: If I have a `DataGroup` holding a detector panel as well as other metadata, what is wrong with folding `pixel -> (xpix, ypix)`?
