### ISSUE TITLE
Scippy naming

### ISSUE THREAD

**Issue by OwenArnold** [scipp/scipp#314]
Python scipp packages now called `scipp` i.e. [here](https://pypi.org/project/scipp/)

Our python package is generated as `scippy` this will cause annoyance/confusion for example:
```
pip install scipp
python -c"from scippy import Dataset"
```
We should agree how to handle this before spending too much time documenting and creating notebooks against scippy

**Comment by OwenArnold** [comment]
Would appreciate thoughts from @nvaytet

**Comment by nvaytet** [comment]
We have decided with Simon to rename it as `scipp`, and there is to be no more `scippy` which is why Simon registered the `pipy` and anaconda domains as `scipp`.
It’s just a matter or renaming it all now. Probably the `scippy` directory should just be renamed `python`
