### ISSUE TITLE
Length-2 bin-edges in dataset

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#3148]
With the change to unaligned coords, there are some conceptual issues with bin-edges and datasets.

Given a dataset
```python
ds = sc.Dataset({'a': sc.scalar(0), 'b': sc.arange('x', 2)},
                coords={'x': sc.arange('x', 2)})
```
we treat `x` as a coord for `b` but not for `a` because otherwise, it would be
both a bin-edge and regular coordinate. So we have
```python
ds['a'] == sc.DataArray(scalar(0), coords={})
```
This means that for some datasets `d['x', 0]['a'] != d['a']['x', 0]` as the latter may have additional coordinates.

Also, the following does not hold if `ds` has a bin-edge coordinate in `x`:
```python
sc.concat([ds['x', 0], ds['x', 1], 'x') == ds['x', 0:2]
```
because `concat` loops over the constituent data arrays. And point slices turn the `x` coord into a length-2 bin-edge coord which is dropped from the constituent data arrays. But the range slice preserves the coord.

For the time being, old tests that check this kind of behaviour have been disabled (search for the number of this issue in the code).

**Comment by SimonHeybrock** [comment]
Will this be obsolete after #3199?

**Comment by jl-wynen** [comment]
Yes, this is obsolete now.
