### ISSUE TITLE
`DataGroup.__setitem__` fails to prevent non-string keys

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#3182]
```python
import scipp as sc

ds = sc.DataGroup(a=sc.arange('x', 4))
ds[1] = sc.scalar(666)  # User expects to set a slice
ds._items  # Item with int key was added
```
Note that things such as `DataGroup._repr_html_` raise a weird error with such a `DataGroup`.

**Comment by jl-wynen** [comment]
Is this required? I don't see a technical reason for not allowing non-str keys. Instead, we should make sure that things like `_repr_html_` work with any type.

**Comment by SimonHeybrock** [comment]
Yes, this is required, unless we want to make a U-turn on slicing syntax &mdash; integers and related things are interpreted as slicing *dimensions*, so a a lot of confusion will ensue unless we restrict item access to `str` only.

**Comment by SimonHeybrock** [comment]
Compare
```python
import scipp as sc

ds = sc.DataGroup(a=sc.arange('x', 4))
ds[1]  # returns a DataGroup with scalar 'a'
```

**Comment by SimonHeybrock** [comment]
> Yes, this is required, unless we want to make a U-turn on slicing syntax — integers and related things are interpreted as slicing _dimensions_, so a a lot of confusion will ensue unless we restrict item access to `str` only.

Note that this is of course a valid discussion to be had. For example, we might want to support mapping dimensions of a `DataArray` to items of a `Dataset` or `DataGroup`. We would then ideally want to use the coord values of that dimension as item keys, which is currently not possible.
