### ISSUE TITLE
Concatenating datasets in new dimension does not work

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#3191]
```python
import scipp as sc
da = sc.DataArray(sc.arange('x', 2))
ds = sc.Dataset({'a': da})
sc.concat([ds, ds], 'y')
```
gives
```
<scipp.Dataset>
Dimensions: Sizes[x:2, ]
Data:
  a                           int64  [dimensionless]  (x)  [0, 1]
```
which is the input dataset.

`concat` works when concatenating in an existing dimension. And it works for data arrays.

**Comment by jl-wynen** [comment]
This only happens when concatenating items with the same data. E.g. this works:
```python
sc.concat([ds, ds+ds], 'y')
```
```
<scipp.Dataset>
Dimensions: Sizes[y:2, x:2, ]
Data:
  a                           int64  [dimensionless]  (y, x)  [0, 1, 0, 2]
```

**Comment by jl-wynen** [comment]
There is actually a test that requires this behaviour:
```cpp

TEST(ConcatenateTest, identical_non_dependant_data_is_copied) {
  const auto axis = makeVariable<int>(Dims{Dim::X}, Shape{3}, Values{1, 2, 3});
  const auto data =
      makeVariable<int>(Dims{Dim::X}, Shape{3}, Values{11, 12, 13});

  Dataset a;
  a.setCoord(Dim::X, axis);
  a.setData("data_1", data);

  Dataset b;
  b.setCoord(Dim::X, axis);
  b.setData("data_1", data);

  const auto d = concat2(a, b, Dim::Y);

  EXPECT_EQ(d.coords()[Dim::X], axis);
  EXPECT_EQ(d["data_1"].data(), data);
}
```

@SimonHeybrock is this intentional? It seems very risky and confusing to me.

**Comment by SimonHeybrock** [comment]
Yes, this was intentional, ensuring that items with lower dimensionality are not duplicated. Is it still relevant after #3189?

**Comment by jl-wynen** [comment]
I don't think so. Now, either everything or nothing would be duplicated. Since DataArray doesn't have a special case, neither should Dataset.

**Comment by jl-wynen** [comment]
So I'm changing / fixing this as part of the update to Dataset (it breaks at least one test now)

**Comment by jl-wynen** [comment]
This was done in #3199
