### ISSUE TITLE
Environment file provided in installation guide fails

### ISSUE THREAD

**Issue by MridulS** [scipp/scipp#3196]
The `scipp.yml` linked from https://scipp.github.io/getting-started/installation.html#with-the-provided-environment-file fails to resolve a conda environment. `jupyter_nbextensions_configurator` is currently broken for newer releases of jupyter notebook (https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator/issues/165)

Maybe there should be an upper pin in the `scipp.yml` file for jupyter notebook for now? Something like:

``` diff
--- a/docs/environments/scipp.yml
+++ b/docs/environments/scipp.yml
@@ -13,6 +13,7 @@ dependencies:
   - jupyter_nbextensions_configurator
   - matplotlib-base
   - nodejs
+  - notebook<7
   - pythreejs
   - scipp::scipp
   - scipy
```

**Comment by SimonHeybrock** [comment]
Thanks for reporting this!

As far as I can tell, we don't need `jupyter_nbextensions_configurator` any more, it is probably a relic from the past of Scipp. I will provide a cleanup-up env file shortly.
