### ISSUE TITLE
Confusing error message from binning empty data

### ISSUE THREAD

**Issue by YooSunYoung** [scipp/scipp#3209]
When binning is attempted on an empty data, it's throwing `BinEdgeError` with  the error message `Bin edges in dim {coord-name} must be sorted.`.

Maybe it should catch the error earlier and throw a more specific error.

Code snippet to reproduce this error is below the image.

![image](https://github.com/scipp/scipp/assets/17974113/d25e7055-3cd2-4a66-8b84-0c94a020d933)

## Code snippet to reproduce the issue
```
import scipp as sc
import numpy as np
rng = np.random.default_rng(123)
da = sc.DataArray(data=sc.ones(sizes={"row": 1000}, unit="counts"),
                  coords={'longi': sc.array(dims=['row'], values=rng.random(1000)),
                          'lati': sc.array(dims=['row'], values=rng.random(1000)),
                          'time': sc.array(dims=['row'], values=rng.random(1000))})
empty_b = da.bin(lati=sc.array(dims=['lati'], values=[0.0, 1.2, 2.0]))['lati', 1]
empty_b.bin(longi=10)
```

**Comment by SimonHeybrock** [comment]
I suggest we catch this when determining bin edges and raise something like:

 > Empty data range, cannot automatically determine bounds. Must provide concrete bin edges.

**Comment by SimonHeybrock** [comment]
Yes, makes sense! 👍
