### ISSUE TITLE
Archive/collect old version documentations

### ISSUE THREAD

**Issue by YooSunYoung** [scipp/scipp#3210]

**Comment by SimonHeybrock** [comment]
See also scipp/copier_template#21

**Comment by jokasimr** [comment]
What's the difference between this issue and [scipp/copier_template/issues/21](https://github.com/scipp/copier_template/issues/21)?

The documentation is already archived with releases right?

**Comment by nvaytet** [comment]
It's not just that Scipp doesn't use the copier template, it's that currently Scipp does not upload old docs as assets of releases.
We have all the old versions stored in [this folder](https://github.com/scipp/scipp.github.io/tree/master/release), which is where the dropdown menu in the docs pages linsk to.

When we switch to the new theme, the drop down will be gone.
We need to somehow preserve the old docs. Either store them on a storage space available online, or try to us ethe github API to upload them as assets of the old releases.
This would probably be a manual process.

I suggest to try out the gh api thing on a dummy repo, to see if it is possible to attach assets to old releases.

**Comment by SimonHeybrock** [comment]
The first step should be to simply enable this for all future releases (as in the copier template). We can then also try to add attachments to old releases, as Neil suggests.

**Comment by nvaytet** [comment]
Maybe we should keep this open until we have decided what to do with the old documentation pages?

**Comment by jokasimr** [comment]
Yes let's keep it open.

**Comment by SimonHeybrock** [comment]
Looks good. I suggest you first try and run it for, e.g., two old versions of Scipp, check if it worked, and only then run again with the remaining list of releases.

**Comment by jokasimr** [comment]
:ballot_box_with_check: [scipp/releases](https://github.com/scipp/scipp/releases)
