### ISSUE TITLE
Remove "What's New" page?

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#3228]
Our [What's New](https://scipp.github.io/about/whats-new.html) page has been appreciated by users during early development when we added many new features with each release. Now we seem to have reached a more steady-state development phase, and we are not updating it anymore. It is therefore outdated and not very useful.

- Consider removing the page
  - If not, come up with an idea how to maintain it with updates
- For all content, check if it is documented elsewhere.
  - Can the examples be moved into examples in the docstrings?
- Remove reference to the page from the Docs front page.

**Comment by nvaytet** [comment]
I would say we can remove it? Can we transfer the version numbers into the docstrings of functions?
E.g. "New in version 23.05.0"

**Comment by SimonHeybrock** [comment]
I think it has been so long that the page was updated that we can even omit such additions. No one is using such old Scipp any more.
