### ISSUE TITLE
Hide attrs deprecation warning in visualizations

### ISSUE THREAD

**Issue by nvaytet** [scipp/scipp#3233]
Since #3227 we get the following warning in the various data visualizations:

VisibleDeprecationWarning: sc.DataArray.attrs has been deprecated and will be removed in Scipp v24.12.0. The deprecation includes sc.DataArray.meta and sc.DataArray.drop_attrs. For unaligned coords, use sc.DataArray.coords and unset the alignment flag. For other attributes, use a higher-level data structure.

We should hide this in:
- html_repr
- `sc.table`
- `sc.show`
- `identical`?
- `assert_identical`?

**Comment by SimonHeybrock** [comment]
One option for doing this is to call the methods/attrs by their `deprecated_` prefixed version, e.g., internally replace `da.attrs` with `da.deprecated_attrs` in the functions listed in the above post.

This will avoid triggering the warnings at all in these cases, i.e., there is no need to setup a filter or anything like that.

**Comment by SimonHeybrock** [comment]
It is undesired but not an oversight (see https://github.com/scipp/scipp/pull/3227). We wanted to avoid wrapping the constructor, or making calls to Python from the C++ side.

**Comment by SimonHeybrock** [comment]
@nvaytet But if you have a simple solution, that would be appreciated...
