### ISSUE TITLE
Negative variance in result of division by int32

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#3236]
```python
import scipp as sc

a = sc.scalar(419.0, variance=419.0)
b = sc.scalar(1615722, dtype='int32')
a/b  # variance = -5.35439526e-07
```

A brief look shows that we are computing `b * b` as an intermediate steps, which overflows in `int32`.

**Comment by jokasimr** [comment]
In practice we only allow variance to be a floating type. Would it make sense to make this more explicit in the code and in all variance computations cast all involved values to floating type before doing the operation?

As a side note I don't think we should disallow integer values from having variances.
But the variances should always be floating even if the dtype of `values` is integer.

**Comment by nvaytet** [comment]
> But the variances should always be floating even if the dtype of values is integer.

I don't think mixing dtypes for values and variances is (currently) possible.
