### ISSUE TITLE
Cannot compare object with variances with broadcast

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#3266]
E.g. this
```python
a = sc.array(dims=['x'], values=[1.0, 1.0], variances=[0.1, 0.1])
b = sc.scalar(1.0, variance=0.1)
a == b
```
raises 
```
scipp._scipp.core.VariancesError: Cannot broadcast object with variances as this would introduce unhandled correlations
```

It would be ok to broadcast in this type of operation. But is it important enough to warrant an exception in the implementation?

**Comment by SimonHeybrock** [comment]
I also think broadcasting would be ok. Is any operation that does not produce an *output* with variances allowed to broadcast input variances?

**Comment by jl-wynen** [comment]
Not sure. One such 'operation' is `sc.variances` which does work with broadcast arrays. Seems a bit odd, but since it makes a copy, I guess it is fine.
