### ISSUE TITLE
Operations on transposed (or similar) binned data return incorrect values in bin-element coords/masks/attrs

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#3277]
Consider https://github.com/scipp/scipp/blob/5b12dc349fe8f2086cd1e237f5bb4a04dd2f6a62/lib/dataset/variable_instantiate_bin_elements.cpp#L90-L109
Note in particular the first TODO. This means
1. We cannot apply operations to a slice of binned data (without copying first), instead we get an exception since the buffer length is not matching up. This is not nice, but at least correct.
2. If indices are not in order, coords (and masks) are copied directly into the output buffer *without* reordering. The implicit length check is not a sufficient safe guard here. This is a bad bug.

Example:

```python
import scipp as sc

table = sc.data.table_xyz(10)
da = table.bin(x=2, y=2)
print('data:')
print(da['x', 1]['y', 0].bins.data.value.values)
print((da.transpose() * 1)['x', 1]['y', 0].bins.data.value.values)
print((da.transpose().copy())['x', 1]['y', 0].bins.data.value.values)
print('coords:')
print(da['x', 1]['y', 0].bins.coords['x'].value.values)
print((da.transpose() * 1)['x', 1]['y', 0].bins.coords['x'].value.values)
print((da.transpose().copy())['x', 1]['y', 0].bins.coords['x'].value.values)
```
Output:
```
data (correct):
[1.08584904 1.00868831]
[1.08584904 1.00868831]
[1.08584904 1.00868831]
coords (broken!):
[0.97669977 0.96407925]
[0.38019574 0.26169242]
[0.97669977 0.96407925]
```

Note the `copy()` uses a different code path and is thus correct.

**Comment by nvaytet** [comment]
Why do you need the `* 1` in `da.transpose() * 1`?

**Comment by SimonHeybrock** [comment]
> Why do you need the `* 1` in `da.transpose() * 1`?

It is the simplest operation I could think of. The same problem should occur with any other operation.

**Comment by nvaytet** [comment]
Ah, so you don't see the problem with `(da.transpose())['x', 1]['y', 0].bins.coords['x'].value.values`?

**Comment by SimonHeybrock** [comment]
No, as the title says, this is about *operations* on transposed data. The linked code snippet is used for creating the output variable (holding binned data). The data values are filled in by the operations, but coords and masks are simply copied from the input. This happens, e.g., when you scale event data with a global or bin-specific factor.
