### ISSUE TITLE
Prevent insertion of binned variables as coords or masks?

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#3279]
In recent discussions with @jokasimr, in particular also in #3047, the question was raised whether Scipp and in particular `DataArray` should put more restrictions on the contents of variables when used within a `DataArray`. The current approach is to allow anything that has compatible `dims` and `shape`. Based on this, data arrays with arbitrary coords or masks:

- *can* be sliced, concatenated, transposed, ...
- *cannot* be used in arbitrary arithmetic (or other) operations. For example, the dtype or the ordering of a coord may conflict, or a mask may have the wrong dtype.

So far we have taken the approach that this is always good: Data structures are self-consistent, but this does not imply that we can apply arbitrary operations to them. **Generally, I still believe that this is the correct choice.** For example, a non-boolean mask will make operations like `+` fail (if the masks is present in both operands). However, a non-number data dtype will also make the operation fail, so that in itself is not a sufficient argument in my opinion &mdash; there is benefit to being able to store data in a way that assigns meaning to it (like: "this is a mask"), even if built-in Scipp ops cannot handle it.

**There is one special case however, which is a trap for users** (see linked issue, and I have also run into this myself): Having binned variables as coords or masks. These binned variables have no relation to the potential binned data variable, i.e., the lists for each bin may have unrelated lengths. I cannot think of any remotely valid application for this, it is most likely almost always a code/user error. Example:

```python
# user error
da.masks['wrong'] = da.bins.coords['time'] > 0.6 * sc.Unit('s')
# should have been
da.bins.masks['ok'] = da.bins.coords['time'] > 0.6 * sc.Unit('s')
```

Based on this, I therefore suggest we consider checking on insertion into `coords` and `masks` that the variable is not binned (i.e., `var.bins is None`), and otherwise raise an exception like

```
Insertion of binned variables as coord or mask is not possible. Did you mean to insert
it as a coord or mask of the bin contents? Instead of
    da.coords['x'] = var
use
    da.bins.coords['x'] = var
```

**Comment by SimonHeybrock** [comment]
Shortly after writing the above, I of course came up with a counterexample:

In operations such as `groupby` one might store the list of input coord values that contribute to a group. Scipp's `groupby` does not do this. However, we have one example in practice: In Mantid, detector pixels may be grouped into "spectra". Each spectrum is then associated with a (usually small) list of detector IDs. Individual detectors contributing to a spectrum may be masked. Mantid does store all this information.

Now, is this counterexample a good enough reason to support this? I am not so sure. Maybe not?

**Comment by jokasimr** [comment]
> Based on this, I therefore suggest we consider checking on insertion into coords and masks that the variable is not binned (i.e., var.bins is None), and otherwise raise an exception like

I think this is a good idea. And if we later come up with semantics for handling binned masks in operations we can just remove the check.

The other (in my opinion worse) options are:
1. Do nothing, this is a user error, perhaps document it as a sharp edge. I don't see what the advantage of doing that would be except to allow users the "freedom" to put binned data in the masks field.
2. Catch this in the functions where masks are used and raise an error there explaining the issue. This would require more work to implement and would be more error prone.
3. Define consistent semantics for how to treat binned masks, for example, treat nonempty bins as true etc. I think this would be a lot of work and hard to get right, and in the end it would be a lot of special cases to document and teach users about just to support something that doesn't really have a function (right now).

> In operations such as groupby one might store the list of input coord values that contribute to a group. ... Individual detectors contributing to a spectrum may be masked. Mantid does store all this information.

I don't understand the example. Masking individual detectors is already supported by placing a mask on the underlying event data right?

**Comment by SimonHeybrock** [comment]
> > In operations such as groupby one might store the list of input coord values that contribute to a group. ... Individual detectors contributing to a spectrum may be masked. Mantid does store all this information.
> 
> I don't understand the example. Masking individual detectors is already supported by placing a mask on the underlying event data right?

Look at `groupby`: The replaces a dimension A with a dimension B. The unique values of a B coord make up the new coord for this dim. However, the coord A is simply dropped and lost. If we would allow binned coords then we could store the list of coord-A values contributing to every B. This would allow for checking which A's contribute to any given B.

**Comment by jokasimr** [comment]
> If we would allow binned coords then we could store the list of coord-A values contributing to every B. This would allow for checking which A's contribute to any given B.

Hm I still don't understand what this has to do with masking.

> Individual detectors contributing to a spectrum may be masked. Mantid does store all this information.

Is this different from a mask on events based on the detector id?

**Comment by jokasimr** [comment]
> There may be an A-dependent mask as well.

A is a coordinate on the non-binned data right?
If that is the case, should not an A-dependent mask be defined on the non-binned data?

**Comment by SimonHeybrock** [comment]
> > There may be an A-dependent mask as well.
> 
> A is a coordinate on the non-binned data right? If that is the case, should not an A-dependent mask be defined on the non-binned data?

When you then call `da.groupby('B')` your mask (and your A coord) is gone.

**Comment by SimonHeybrock** [comment]
> Aha okay I'm not so familiar with `da.groupby`, but in this situation it is a quite different from `da.bin`?
> What I mean is that when you bin some data the masks on the underlying data are still considered in operations (as you know).

Not so different: If you bin something that has been binned already you may end up in the same situtation (masks are dropped). Also, this is not really the point of the discussion: The question here was whether allowing binned coords or masks is useful, and it would be for operations such as `groupby` (or some cases of `bin`).

**Comment by jokasimr** [comment]
I understood this to be relevant to the question at hand because if the use case you mentioned can be accomplished using boolean valued masks on either the binned data array or on the underlying data array then we don't need binned masks.

**Comment by SimonHeybrock** [comment]
`groupby` does not result in binned data, so what you suggest is not an option.

**Comment by SimonHeybrock** [comment]
Conclusion:
- Cater for 99% of users, i.e., flag a likely unintentional use.
- Can later (or now) add special setter, if we really see the use.
