### ISSUE TITLE
Switch to payed plan on Anaconda.org

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#3293]
This might be urgent! We have run out of space on anaconda.org and I suspect that we will soon be unable to upload new packages. We can get some breathing room by deleting old packages. In particular mantid-framework. But ultimately, we need to pay to get more storage. 
I could not yet find clear information on how expensive that would be.

**Comment by SimonHeybrock** [comment]
Would it make sense to remove old versions?

**Comment by MridulS** [comment]
>  I could not yet find clear information on how expensive that would be.

There isn't really a proper pricing plan for this. You could request anaconda to bump up the storage for free too btw.

**Comment by jl-wynen** [comment]
Hm, interesting. I would have thought they had a plan. But let's ask them! Thanks for the info!

**Comment by MridulS** [comment]
Is there a blocker for https://github.com/scipp/scipp/issues/2907 ? `scipp` wouldn't need to worry about storage then.

**Comment by jl-wynen** [comment]
Not a blocker. We just never spend the time to figure out how to set up the recipe for building C++. But yes, we should actually do that
