### ISSUE TITLE
We set the package version in 2 places and inconsistently

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#3302]
The package version is set in 2 places in CMake. In the root `CMakeLists.txt` (https://github.com/scipp/scipp/blob/80a8997fb61879b6ba5df658617c9e1e5aef14d0/CMakeLists.txt#L9-L14) and in `lib/CMakeLists.txt` (https://github.com/scipp/scipp/blob/80a8997fb61879b6ba5df658617c9e1e5aef14d0/lib/CMakeLists.txt#L92-L102).
The first filters out nightly tags and abbreviates. But the second does not. The second is what how we define `scipp.__version__` in Python.

Why are there 2 separate commands? Should we remove one? In any case, we should probably filter out nightly in both.

**Comment by SimonHeybrock** [comment]
The reason why they are different is that ones has `--abbrev=0` while the other does not. Cmake does not like the full Python version string.
