### ISSUE TITLE
Broken conda build

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#3309]
I ran the release build on GH actions: https://github.com/scipp/scipp/actions/runs/6744287487
And the conda build is broken with
```
=============== 5108 passed, 25 skipped, 171 warnings in 41.70s ================
-- The C compiler identification is GNU 12.3.0
-- The CXX compiler identification is GNU 12.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: $PREFIX/bin/x86_64-conda-linux-gnu-cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: $PREFIX/bin/x86_64-conda-linux-gnu-c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:27 (find_package):
  find_package called with invalid argument "nightly"


CMake Error at CMakeLists.txt:28 (find_package):
  find_package called with invalid argument "nightly"
```
Looks like this comes from the package test, not the build of scipp itself.

**Comment by jl-wynen** [comment]
@SimonHeybrock Didn't you fix this already?

**Comment by SimonHeybrock** [comment]
Looked into this 10 days ago and decided to not fix it. This issue should go away when we make the next release.

**Comment by jl-wynen** [comment]
How so. I get that the release should work. But wouldn't all builds that are started a day after the last release still pick up the nightly tag?

**Comment by jl-wynen** [comment]
Ok. Keeping this issue open to remind us to check after the release.

**Comment by SimonHeybrock** [comment]
I get an email every time it fails 😬
