### ISSUE TITLE
Nightly build on different version.

### ISSUE THREAD

**Issue by YooSunYoung** [scipp/scipp#3313]
Currently [.github/workflows/release-nightly.yml](https://github.com/scipp/scipp/blob/main/.github/workflows/release-nightly.yml) is using `cp38` only and [`make_base.py`](https://github.com/scipp/copier_template/blob/main/requirements/make_base.py) is using minimum version of python, which is not necessarily `3.8`.

Can we add more versions in `.github/workflows/release-nightly.yml` 
or should I use the same minimum version of python as ``scipp`` since it is depending on it...?

**Comment by SimonHeybrock** [comment]
We should add more versions (as needed, not all at the same time). We cannot guarantee that all projects will always be on the same minimum.
