### ISSUE TITLE
Support complex numbers

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#3319]
I haven't encountered a concrete need for this in practice. But I have a CIF file for a magnetic experiment which contains complex number for the susceptibility.

We will likely need complex numbers eventually.

They may be easy to add. But they could double the number of overloads for many operations. We may need to find a better solution.

**Comment by SimonHeybrock** [comment]
Closing as there is no useful info here. We are open to add this in the future, if needed.

**Comment by arm61** [comment]
I am working with a student on uncertainty propagation through a discrete Fourier transform (with applications in relating simulations and scattering data). I wantd to use scipp arrays to store the data, but have realised that scipp does not support complex number (necessary for FFT). Are there future plans to include this?

**Comment by jl-wynen** [comment]
No plans. We could try adding them and see what the impact on compile time and binary size is. (Probably large.)

Do you think there is any need for single precision complex numbers? Or is double precision good enough?

**Comment by arm61** [comment]
I imagine double precision would be fine. My current solution is to return a `sc.Dataset` with `real` and `imag` data but native compatibility would be nice.

**Comment by arm61** [comment]
Still causing problems for the scipp team ❤️

**Comment by jl-wynen** [comment]
I gave this a quick try but hit a tricky problem. C++'s `std::complex<double>` does not support arithmetic with other types. So, e.g., our addition kernel
```cpp
[](auto a, auto b) {
    return a + b;
}
```
fails to compile if it is instantiated with, e.g., `double` and `std::complex<double>`. So if we want to support combining different types like NumPy, then we need a new solution for converting types along the lines of
```cpp
overloaded{
    [](std::complex<double> a, auto b) {
        return a + std::complex<double>{b};
    },
    [](auto a, std::complex<double> b) {
        return std::complex<double>{a} + b;
    },
    [](auto a, auto b) {
        return a + b;
    },
}
```
We would need this for all arithmetic (and potentially more) operations. So this is quite a lot and makes currently simple code more complex.

**Comment by arm61** [comment]
Hmm, that's annoying. It might be better to just stick with my hack for now...

**Comment by jl-wynen** [comment]
There is an alternative:
```cpp

#include <complex>
#include <type_traits>

template <typename T>
concept NotDouble = std::negation_v<std::is_same<T, double>>;

template <class A, NotDouble B>
requires requires(A a, B b) { a + b; }
std::complex<A> operator+(const std::complex<A> &a, const B b) {
  return {a.real() + b, a.imag()};
}

template <NotDouble A, class B>
requires requires(A a, B b) { a + b; }
std::complex<B> operator+(const A a, const std::complex<B> &b) {
  return {a + b.real(), b.imag()};
}
```

This would allow us to keep the actual transform kernels simple. But we would still have to overload all operators.

**Comment by SimonHeybrock** [comment]
As an alternative to `std::complex`, it should be possible to add support for `complex` in a similar manner as `vector3` and other spatial types (the underlying mechanism in Scipp is generic enough, I think). This would allow for exposing `real`/`image` as variables (views without copying), and give more control over what is possible.
