### ISSUE TITLE
Python 3.12 status and blockers

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#3322]
# Status of 3.12 support

## pip -> done in #3321 

- Building wheels works with `conan==1.62`. ~Note that this is not released yet (2023-11-09), but we can install from the `develop` branch.~ This has been released now. See #3321
- Numba does not support 3.12 yet, this is an optional dependency. If we avoid installing it in the wheel tests those will be skipped.
- ~h5py does not support 3.12 yet, this is an optional Scipp dependency, but our tests are currently not configured to be skipped.~ has been released now.

## conda

- On `conda-forge`, there latest conan is 1.59, i.e., there will likely never be a 1.62 version.
- We would need to move to conan 2. This is currently blocked by [cmake-conan](https://github.com/conan-io/cmake-conan) not fully supporting it. There is a `develop2` branch which we could try.
- `conda-forge-pinning` supports only up to 3.11. We could make packages without pinning, but the setup would become more complicated.

**Comment by jl-wynen** [comment]
> conda-forge-pinning supports only up to 3.11. We could make packages without pinning, but the setup would become more complicated.

There is a way to add 3.12 to the pinning: #3353
This isn't ideal but it should not cause any problems. The 3.12 packages would be incompatible with the pinning but can be installed along with other compatible packages.

**Comment by SimonHeybrock** [comment]
`cmake-conan` not describes experimental Conan 2 support: https://github.com/conan-io/cmake-conan.

**Comment by MridulS** [comment]
`mamba create -n scipp3.12 scipp python=3.12 -c scipp` works just fine now :)
