### ISSUE TITLE
Remove `__init__.py` files from `tests/` folder tree

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#3344]
This seems error prone when forgotten in a folder since it may lead to tests not being run.

As far as I can tell there are only 3 places where we use relative imports:
```bash
$ grep -r import | grep from\ \\.
compat/xarray_compat_test.py:from ..factory import (  # NOQA
html/html_repr_test.py:from ..factory import (
html/table_test.py:from ..factory import (
```

Should we try and avoid this and remove all `__init__.py` files from `tests/`?

**Comment by jl-wynen** [comment]
Looking at this: https://docs.pytest.org/en/7.1.x/explanation/goodpractices.html#choosing-an-import-mode it seems that `__init__.py` also serves as a workaround for having multiple test modules with the same name. I don't know if we have that. But in any case, we should probably switch to the importlib mode. (In all projects.)

**Comment by jl-wynen** [comment]
Actually, the `importlib` import mode makes it difficult to import other modules in the test directory. But if we remove the `__init__.py` files, this becomes more difficult anyway.
Can we define the factory differently? E.g. provide as a fixture via `conftest.py`.

**Comment by jl-wynen** [comment]
See also https://docs.pytest.org/en/7.1.x/explanation/pythonpath.html

**Comment by jl-wynen** [comment]
I think all packages that used this are updated
