### ISSUE TITLE
Add `std` and `var` reductions 

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#3357]
We have `mean` but nothing to compute standard deviation or variances like `np.std`, `np.var`.

**Comment by SimonHeybrock** [comment]
`median` would also be useful.

**Comment by jl-wynen** [comment]
Implementing `var` is not straight forward. See, e.g., https://github.com/scipp/scippuncertainty/blob/ee64e9a28f20197bd70047cabe4b50c392a7b6bf/src/scippuncertainty/mc/accumulator.py#L42 for an efficient, numerically stable, parallel implementation (and algorithm ref). Not sure if this is doable with our transform mechanism, though.

Concerning `median`, yes, it would be useful and mathematically is similar to the others but implementation wise, it would be very different.

**Comment by SimonHeybrock** [comment]
Maybe we should simply make NumPy more usable with Scipp variables and data arrays? My guess is that it is relatively unlikely that performance would see a relevant benefit from Scipp's multi-threading in this case.

**Comment by SimonHeybrock** [comment]
I think we can or should to both. NEP18 and NEP35 are something we should consider again.

**Comment by jl-wynen** [comment]
[numpy.var](https://numpy.org/doc/stable/reference/generated/numpy.var.html#numpy.var) implements this equation: $$\mathsf{var} = \frac1{N-\mathsf{ddof}} \sum_{i=1}^{N} {(x_i - \bar{x})}^2$$ and [numpy.std](https://numpy.org/doc/stable/reference/generated/numpy.std.html#numpy.std) the square root of the above.
The `ddof` parameter defaults to 0. This means that the estimator is typically biased by default. The NumPy docs explain the meaning of the parameter superficially.

For me personally, this has caused problems in the past because I expected it to be the sample variance, meaning `ddof = 1` by default. This lead to subtly wrong results.
I think we should have such a parameter, but IMHO, it should default to 1. But this would be the wrong choice in some other situations.

What do you think?

**Comment by jl-wynen** [comment]
Given that there are good arguments for not using different default than numpy, as well as that any default for `ddof` can lead to problems, I'm going to make it a mandatory parameter. We can always make it optional in the future if that turns out to be better.
