### ISSUE TITLE
Segfault in arithmetic with high-dim binned variable

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#3365]
I found what looks like an array of uninitialised elements. It occurs in an operation between a dense and a binned variable:
```python
import scipp as sc
from ess import dream

da = dream.io.load_geant4_csv(dream.data.get_path('data_dream_with_sectors.csv.zip'))['instrument']['high_resolution']
print(da.bins.coords['position'].sizes)

# da = da.flatten(to='spectrum')

da.coords['sample_position'] = sc.vector([0, 0, 0], unit='m').to(unit='mm')
res = da.bins.coords['position'] - da.coords['sample_position']
print(res.bins.constituents['data'].values[0])
```
output
```python
{'sector': 4, 'module': 9, 'segment': 8, 'counter': 2, 'wire': 16, 'strip': 32}
[-1.23971686e+224  9.86707000e+001 -1.17365078e+214]
```
The large floats in the output are incorrect. But sometimes, it prints the correct numbers.

I could not reduce the example further yet. But uncommenting the `flatten` call makes the problem go away. So I suspect it has to do with the high number of dims. It is above the number of dims supported by `MultiIndex`. So the fact that we get a result at all means that we hitting the flattening optimisation. Maybe there is a bug for binned data.

**Comment by jl-wynen** [comment]
To reproduce:
```.cpp
DataArray events(
    makeVariable<int>(Dims{Dim::Event}, Shape{1}, Values{1}),
    {
        {Dim{"a"}, makeVariable<int>(Dims{Dim::Event}, Shape{1}, Values{1})},
        {Dim{"b"}, makeVariable<int>(Dims{Dim::Event}, Shape{1}, Values{1})},
        {Dim{"c"}, makeVariable<int>(Dims{Dim::Event}, Shape{1}, Values{1})},
        {Dim{"d"}, makeVariable<int>(Dims{Dim::Event}, Shape{1}, Values{1})},
        {Dim{"e"}, makeVariable<int>(Dims{Dim::Event}, Shape{1}, Values{1})},
        {Dim{"f"}, makeVariable<int>(Dims{Dim::Event}, Shape{1}, Values{1})},
    });
DataArray da =
    bin(events,
        {
            makeVariable<int>(Dims{Dim{"a"}}, Shape{2}, Values{0, 2}),
            makeVariable<int>(Dims{Dim{"b"}}, Shape{2}, Values{0, 2}),
            makeVariable<int>(Dims{Dim{"c"}}, Shape{2}, Values{0, 2}),
            makeVariable<int>(Dims{Dim{"d"}}, Shape{2}, Values{0, 2}),
            makeVariable<int>(Dims{Dim{"e"}}, Shape{2}, Values{0, 2}),
            makeVariable<int>(Dims{Dim{"f"}}, Shape{2}, Values{0, 2}),
        },
        {}, {});
auto x = dataset::bins_view<DataArray>(da.data()).data();
auto y = makeVariable<int>(Dims{}, Values{0});
auto res = x - y;
```
This is caused by an incorrect check in this line: https://github.com/scipp/scipp/blob/06ea6c618fe8428152ce541c86b718c0ae484f9e/lib/core/multi_index.cpp#L103
Replacing `NDIM_OP_MAX` with `out_shape.size()` fixes the immediate issue. This triggers an exception in MultiIndex instead of a segfault (in a release build, in debug builds, `span` catches the problem.)

What do we do? I will open a PR with this fix. But this came up in the data reduction for DREAM where we have 7 dims (6 outer and one event dim) for the high resolution detector. Do we need to investigate flattening with binned data? Or can we live with flattening the detector first?

**Comment by SimonHeybrock** [comment]
> Do we need to investigate flattening with binned data? Or can we live with flattening the detector first?

We definitely need to investigate what is going wrong. Not sure I understand exactly what you are asking.

**Comment by jl-wynen** [comment]
I don't understand what you mean. What was wrong is that there was a wrong condition. But I don't think we implemented support for flattening dims in this case. Not because of the binned data but because we have an operation with a scalar.

**Comment by SimonHeybrock** [comment]
Then you need to clarify the question in your final paragraph, I do not understand the question you pose there.
