### ISSUE TITLE
Flatten dims in operations with scalars

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#3367]
Continuation of #3365

Given, e.g.,
```python
sc.ones(sizes={'x': 2, 'y': 3}) + sc.scalar(1)
```
should we flatten the dims to effectively compute the following?
```python
sc.fold(sc.ones(sizes={'x': 2, 'y': 3}).flatten(to='aux') + sc.scalar(1), sizes={'x': 2, 'y': 3})
```
This should be possible in `MultiIndex`. And similarly for length 0 dims in any operand.

It would extend the usability of arrays with more than 6 dims.

**Comment by jl-wynen** [comment]
No. I'm suggesting to extend the logic in `MultiIndex` to work with dims where stride=0. I'm *not* suggesting to actually flatten variables.

**Comment by SimonHeybrock** [comment]
> No. I'm suggesting to extend the logic in `MultiIndex` to work with dims where stride=0. I'm _not_ suggesting to actually flatten variables.

Can you elaborate how that is related to what you describe in the original post?
