### ISSUE TITLE
Relax restrictions for `DataGroup` positional indexing?

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#3371]
Current behavior:
```python
import scipp as sc

dg = sc.DataGroup(a=sc.arange('x', 0, 10), b=sc.arange('x', 0, 5))
dg['x', 3:]  # DimensionError: Positional indexing dim 'x' not possible as the length is not unique.
```
The reason for this was to avoid ambiguities, or catch programming errors. However, Python *does* support this (as does NumPy), and right now I think I do not anymore see the point of forbidding this. Conceptually the above says "remove the first 3 elements", which makes sense.

There are probably some arguments relating to slicing from the back and order of slicing operations where one can claim an ambiguity/inconsistency, but I feel the loss in usability and break with standard Python behavior is more relevant.

**Comment by nvaytet** [comment]
I agree that we should allow this.
