### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by jokasimr** [scipp/scipp#3373]
In the [documentation of `sc.plot`](https://scipp.github.io/generated/functions/scipp.plot.html?highlight=plot) the url [https://scipp.github.io/plopp/reference/generated/plopp.plot.html](https://scipp.github.io/plopp/reference/generated/plopp.plot.html) is mentioned, but seems to be dead.

**Comment by jl-wynen** [comment]
Already done in  #3370
