### ISSUE TITLE
Inplace op with binned var on RHS does a reduction operation

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#3389]
```python
import scipp as sc

da = sc.data.table_xyz(1000).bin(x=4)
x = da.bins.coords['x']
var = sc.arange('x', 4, dtype='float')
var *= x  # This should raise `DimensionError`
```
`var` has its values overwritten with uninitialized values. This in-place op should raise!

**Comment by jokasimr** [comment]
Interestingly I don't think the values are uninitialized.
They are the result of multiplying each element of `var` with all the values in the corresponding bin.

```python
import scipp as sc

da = sc.data.table_xyz(10).bin(x=5)
x = da.bins.coords['x']
var = sc.arange('x', 5, dtype='float')
varcopy = var.copy()

var *= x

all_values_multiplied_in_each_bin = sc.array(
    dims='x',
    unit=var.unit,
    values=[np.prod(v.coords['x'].values) for v in da.values]
) 

var - all_values_multiplied_in_each_bin * varcopy # -> (x: 5) float64 m 0.0, 0.0, 0.0, 0.0, 0.0
```

Should probably still raise `DimensionError`. But at least this might help figuring out what's going on.

**Comment by SimonHeybrock** [comment]
Try using more events in sc.data.table_xyz`, then I see some non-zero values showing up.

**Comment by jokasimr** [comment]
When you multiply lots of events together you get cancellation errors.

**Comment by jokasimr** [comment]
Would it be a sufficient solution to raise if the LHS is not binned when the RHS is binned?

**Comment by SimonHeybrock** [comment]
Yes, probably.
