### ISSUE TITLE
Dimension order in bins.concat matters for high-dim arrays

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#3408]
For high-dimensional arrays (<6), we rely on the flattening optimisation in `MultiIndex`. In `bins.concat`, this can lead to surprising behaviour:
```python
import scipp as sc
buffer = sc.DataArray(sc.zeros(dims=['event'], shape=[10]))
var = sc.bins(dim='event', data=buffer, begin=sc.arange('0', 10, unit=None), end=sc.arange('0', 1, 11, unit=None))
var = var.broadcast(sizes={str(i): i+10 for i in range(6)}).copy()
print(var.bins.concat(('0', '2', '4', '1', '3')))
```
This raises
```
RuntimeError: Operations with more than 6 dimensions are not supported. For binned data, the combined bin+event dimensions count
```
because the total ndim is 7 (6 outer + 1 event) and the dim order given in `concat` does not allow any dims to be flattened.

I find this surprising because the order of dims in `concat` is irrelevant for the result when we don't need the flattening optimisation.

**Comment by SimonHeybrock** [comment]
> I find this surprising because the order of dims in concat is irrelevant for the result when we don't need the flattening optimisation.

Can you clarify why you consider it irrelevant? Wouldn't you to expect to handle the dims in the specified order?

**Comment by jl-wynen** [comment]
Why would I expect that? I only care about the input and the final result. Conceptually, it makes no difference whether we remove the dims all at once or one by one and in what order.

**Comment by SimonHeybrock** [comment]
In what order matters, because we must have a consistent order of the bin contents.

**Comment by jl-wynen** [comment]
Ok, the argument order matters because it determines the order of events in the result. Is this what you meant?

**Comment by SimonHeybrock** [comment]
Yes.
