### ISSUE TITLE
Remove deprecated binning functions / arguments

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#3409]
There are a number of deprecated functions and arguments for binning/histogramming. We did not set a removal date. But since it has been 2 years, I think we are good to remove them.

In `src/core/binning.py`.
- Remove `deprecated` arg in `rebin`
- Remove `histogram` function

In `src/core/bins.py`:
- `GroupbyBins.concat`; it looks like we can remove `GroupbyBins` entirely.

**Comment by nvaytet** [comment]
Can add in the description which ones should be removed or where to find them? So that someone new to the project can attempt this? Thanks!
