### ISSUE TITLE
Grouping by string-type coordinate with its name.

### ISSUE THREAD

**Issue by YooSunYoung** [scipp/scipp#3425]
Currently `sc.group` fails if we select a coordinate name to group.

```python
import scipp as sc
from scipp.data import table_xyz

da = table_xyz(100)
da.coords["str_coord"] = sc.array(dims=["row"], values=['a', 'b', 'c', 'd']*25)
da.group('str_coord') # AttributeError: 'scipp._scipp.core.ElementArrayView_string' object has no attribute 'size'

```

But it works when the group-coordinate is given,
```python
import scipp as sc
from scipp.data import table_xyz

da = table_xyz(100)
da.coords["str_coord"] = sc.array(dims=["row"], values=['a', 'b', 'c', 'd']*25)
da.group(sc.array(dims=['str_coord'], values=['a', 'b', 'c', 'd']))  # works
```

We should also support selecting the coordinate name of string type coordinate for grouping.

Related to #290

**Comment by YooSunYoung** [comment]
Should we just try-catch the exception or check the dtype ...?

**Comment by SimonHeybrock** [comment]
I think we should try and see if the code triggering the exception can be rewritten in a way that avoid accessing properties of `Variable.values` that do not exist for strings (or those properties can be added, if feasible).
