### ISSUE TITLE
Is the mechanism for controlling whether `hist` replaces dimensions too indirect?

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#3435]
According to the docstring:
> When histogramming a dimension with an existing dimension-coord, the binning for
> the dimension is modified, i.e., the input and the output will have the same
> dimension labels.
>
> When histogramming by non-dimension-coords, the output will have new dimensions
> given by the names of these coordinates. These new dimensions replace the
> dimensions the input coordinates depend on.

In practice this means that:

- A prior use of `transform_coords` with or without the `rename_dims` option affects the outcome of a subsequent `hist`.
- It is possible to indirectly control which dimensions are to be removed, as shown in the example below, by renaming and/or flattening dimensions:

```python
import scipp as sc

table = sc.data.table_xyz(1000)
binned = table.bin(x=3, y=4)  # sizes {'x': 3, 'y': 4}
binned.rename_dims(y='z').hist(z=5)  # sizes {'x': 3, 'z': 5}
binned.flatten(to='z').hist(z=5)  # sizes {'z': 5}
```

The mechanism was introduced since it allows the algorithm to either add a new dimension, or replace an existing dimension. But is it too confusing when working with multi-dimensional data?

Would it suffice to improve the docstring (I am thinking of adding concrete examples on how to control the behavior), or do we need to think of something else?

Note that related functions such as `bin` are also affected.

**Comment by nvaytet** [comment]
I do find it a little unpredictable sometimes.

Would it be less confusing if the dims you specified inside `hist(...)` would always be what you get as an output?
e.g. the output of `table.bin(x=3, z=4).hist(z=5)` would have `sizes {'z': 5}`.
If you want to keep the `x` dim, you'd have to do `table.bin(x=3, z=4).hist(x=3, z=5)` -> `sizes {'x': 3, 'z': 5}`.

It could check if the dims requested for `x` are the same and not re-do the binning in `x`?

However, that wouldn't really work if you've manually specified bins in x, because you'd have to specify them again, which would be annoying...

**Comment by SimonHeybrock** [comment]
That would not work, since you would always have to look up existing binning if you want to keep it, and we would need to add code that detects if the user-specified binning is the same as the existing one (to avoid re-doing the work), which is likely going to break all the time.

**Comment by SimonHeybrock** [comment]
Prioritizing this now since I believe a solution to scipp/essreduce#47 is linked to this.

**Comment by SimonHeybrock** [comment]
Current idea is as follows: Make this explicit, in the same way reduction ops such as sum do it:

```python
da.sum()  # dim=None means all dims
da.sum('x')  # sum only along x dim
da.sum(('x', 'y'))  # sum along x and y dims 
da.sum(())  # do nothing
```

We can think of hist and bin as a kind of reduction operation that can at the same time add new dims:

```python
da.hist(z=5)  # dim=None means z replaces all dims of the z coord (preserve unrelated)
da.hist(z=5, dim=da.dims)  # replace also z-independent dims
da.hist(z=5, dim=())  # keep all existing dims, add z
da.hist(z=5, dim='x')  # z dim will replace x dim
da.hist(z=5, dim=('x', 'y'))  # replace x,y with z
```
Note that by defining `dim=None` to replace all dims of *the coord* we will likely rarely need `dim='x'` or `dim=('x', 'y').

**Comment by SimonHeybrock** [comment]
See #3498 .

**Comment by nvaytet** [comment]
```Py
da.hist(z=5)  # dim=None means z replaces all dims of the z coord (preserve unrelated)
da.hist(z=5, dim=da.dims)  # replace also z-independent dims
da.hist(z=5, dim=())  # keep all existing dims, add z
da.hist(z=5, dim='x')  # z dim will replace x dim
da.hist(z=5, dim=('x', 'y'))  # replace x,y with z
```

Not sure I follow: would `dim` now be a special argument, meaning that you cannot hist using a dimension that has name `dim`?

**Comment by SimonHeybrock** [comment]
> Not sure I follow: would dim now be a special argument, meaning that you cannot hist using a dimension that has name dim?

You cannot use it as a dimension name via a keyword-arg, but you can still via the dict arg.
