### ISSUE TITLE
Unusual indexing behaviour

### ISSUE THREAD

**Issue by arm61** [scipp/scipp#3438]
I was trying to get the length of a single dimension of an array. I expected the following to return this: 

```
a = sc.array(dims=['x', 'y'], values=[[1, 2], [3, 4], [5, 6]])
a['x', :].shape
```

However, the return is the `(3, 2)` which is the shape of the whole of `a`. This made me realise that the following 

```
a['x', :]
```

Also returns the whole array, which seems like strange behaviour. 

Thoughts?

**Comment by nvaytet** [comment]
Not sure what you expected it to return.
When you want a single row in `y`, you have to give an index `a['x', 0]`.
If you say "I'm going to slice in the `x` dimension, but give me all of the indices (with `:`)", then it will return you the entire array. Seems to make sense?

You get the same with `numpy`:
![Screenshot at 2024-05-04 22-49-53](https://github.com/scipp/scipp/assets/39047984/1ccb9e96-0b0a-4896-9c4b-c420430b7fb3)

**Comment by SimonHeybrock** [comment]
> I was trying to get the length of a single dimension of an array. I expected the following to return this:

use `a.sizes['x']`

The indexing works as it should, as in NumPy. Maybe the confusing bit is that `,` in Scipp separates the dim label and the indices, not the axes?

**Comment by arm61** [comment]
I think that @SimonHeybrock has hit the nail on the head. I am mentally treating the `,` as the same between Scipp and NumPy.
