### ISSUE TITLE
Make `.hist()` without binning default

### ISSUE THREAD

**Issue by jokasimr** [scipp/scipp#3439]
The current default behavior of `scipp.hist` or `DataArray.hist` is to bin the array before computing the histogram.
This is usually more costly than directly computing the histogram using the deprecated `sc.histogram`.

In a small benchmark this boils down to a factor ~2x:

```
da = sc.data.table_xyz(1000_000)
%time da.hist(x=1000)
3.52 ms ± 300 µs
```
compared to
```
da = sc.data.table_xyz(1000_000)
%timeit sc.histogram(da, bins=sc.linspace('x', 0, 1, 1001, unit='m'))
2.09 ms ± 55.5 µs
```

**Comment by SimonHeybrock** [comment]
It should *not* do that. `hist` should fall back to `bin` only when there is more than one dimension:

https://github.com/scipp/scipp/blob/7e22a5b2858739b49d85a02ba8a4be54ae37b832/src/scipp/core/binning.py#L394-L396

Have you discovered a code path where this does not happen?

**Comment by jokasimr** [comment]
It could very well just be the `min`/`max` that's consistent with the 2X.

**Comment by SimonHeybrock** [comment]
I'll close for now then, but please check to confirm the hypothesis.

**Comment by jokasimr** [comment]
I looked into this because I was profiling part of the reflectometry workflow. In that case the histogram is 2D. Does that make a difference here?

**Comment by SimonHeybrock** [comment]
If there is no prior binning, then Scipp cannot histogram into 2-D directly, currently. It falls back to using `bin` first.

**Comment by jokasimr** [comment]
Okay I think it would be a good to be able to histogram in 2D without binning.

I don't know about the other workflows, but the runtime of the reflectometry data reduction consists mainly of the 2D histogrammings.

**Comment by SimonHeybrock** [comment]
> Okay I think it would be a good to be able to histogram in 2D without binning.
> 
> I don't know about the other workflows, but the runtime of the reflectometry data reduction consists mainly of the 2D histogrammings.

My guess is that the problem lies elsewhere, namely in *changing*/removing some existing binning (during `hist`). There are some pitfalls to avoid. I think it is unlikely that 2-D binning/hist on its own is the performance issue. We can look into your case together.
