### ISSUE TITLE
Inplace operation between dense and binned data accidentally allowed

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#3453]
This
```python
import scipp as sc

binned = sc.data.binned_x(10, 3).bins.data
dense = sc.arange('x', 3.)
dense *= binned
print(dense)
```
prints
```
<scipp.Variable> (x: 3)    float64              [K]  [0, 1, 2.35175]
```

To me this seems like a bug. The inplace multiplication should not be allowed here and the result makes no sense.

Am I missing something or is this a bug?

**Comment by jokasimr** [comment]
Looks similar to this: https://github.com/scipp/scipp/issues/3389

But I thought this was fixed and should raise dimension error?

**Comment by jokasimr** [comment]
Aha, we haven't released since this was fixed. Did you run this example using the latest release or on the main branch?

**Comment by jl-wynen** [comment]
> Did you run this example using the latest release or on the main branch?

I did not. And it indeed looks like the same issue. Thanks!
