### ISSUE TITLE
How to handle default arguments in fit function in `curve_fit`?

### ISSUE THREAD

**Issue by jokasimr** [scipp/scipp#3463]
Currently `scipp.curve_fit` ignores if an argument to the model function has a default value or not:
```python
from functools import partial

import scipp as sc


def model(x, a, b=2):
    return a * x + b


x = sc.linspace('x', 0, 10, 100)
y = model(x, a=0.5, b=2)
da = sc.DataArray(y, coords={'x': x})

popt, _ = sc.curve_fit(['x'], model, da, p0={'a': 1.0})
# Both a and b are among the parameters
#DataGroup(sizes={}, keys=[
#    b: DataArray({}),
#   a: DataArray({}),
#])
```
This is different from the `scipy.optimize.curve_fit` implementation where default arguments are ignored.

It would be good to do the same thing everywhere. I don't really see strong reasons for doing it either way. It's conceptually simpler (imo) to just say that the function doesn't care about if an argument has a default value or not. But it can also lead to surprises, for example when using `partial` since keyword arguments set by partial can still be overridden, and thus using `partial` with `scipp.curve_fit` does nothing.

**Comment by jl-wynen** [comment]
Why does it need to inspect the model signature anyway? Isn't it enough to rely on `p0`?

**Comment by jokasimr** [comment]
It's a convenience. If we don't inspect the signature the user has to define default values for all parameters.
`scipy.optimize.curve_fit` also does something similar, I think that's why it was done this way to begin with.

**Comment by jl-wynen** [comment]
But this only applies if `p0 is None`. We seem to be inspecting the signature even when `p0` is specified. Why?

**Comment by jokasimr** [comment]
Because in `scipy` you can only provide initial values for all parameters or none.
In our wrappers you can provide initial values for only some parameters and letting the others default to `1`.

**Comment by jl-wynen** [comment]
How valuable is this in practice? This only makes sense if 1 is a reasonable starting guess and the param is dimensionless.
Can we avoid this complication by removing this special feature?
