### ISSUE TITLE
Take old docs versions offline

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#3464]
The old versions of our documentation are still online (in the `release` folder). This can lead to people finding pages in those versions instead of the latest pages and that can lead to confusion (just happened to a new user).

We should take those old versions offline since we no longer maintain all versions anyway. Either remove them completely or move them somewhere where they are not published to the static web server.

**Comment by SimonHeybrock** [comment]
> Do we not maintain a version switcher? We can always have a banner on top of old docs to point towards latest release and a developer build.

We did:

<img width="1383" alt="image" src="https://github.com/scipp/scipp/assets/12912489/dcea2f98-563e-492f-9a57-dd2d9b608836">

But since recently we to not keep old pages around (I think the reason was space, remind me?).

**Comment by nvaytet** [comment]
> I think the reason was space, remind me?

I think it was both space (some of the repo sizes started to get very large) and making the docs build config and CI workflows more complicated/brittle. It messed things up multiple times.
Instead, we are now uploading the built docs as an Asset (`documentation-24.05.zip`) for each github release, where one can download and view them: https://github.com/scipp/scipp/releases
This has made things quite a bit simpler.
