### ISSUE TITLE
`replaced-docs` step in release action doesn't run, should it be removed?

### ISSUE THREAD

**Issue by jokasimr** [scipp/scipp#3467]
The `replaced-docs` step in the release action does not run.
See [the latest release run](https://github.com/scipp/scipp/actions/runs/9314468842), and [older release run](https://github.com/scipp/scipp/actions/runs/7955172534).

@jl-wynen mentioned that it might be something that isn't used any more.

Should it be removed?

**Comment by SimonHeybrock** [comment]
I think this is a leftover from when we used to keep old docs version, so it should be safe to remove.
