### ISSUE TITLE
Stubgen is broken for staticmethods

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#3469]
I think currently the only case is `Unit.from_dict`. The stubgen produces
```python
def from_dict(self) -> Unit:
    ...
```
but it should be (`Any` because the C++ function is not properly annotated)
```python
def from_dict(d: dict[Any, Any]) -> Unit:
    ...
```

Step one to detect static methods is to replace `def` with `def_static` in the bindings. Then I think fixing this needs some change to properly handle static methods. In particular, `_classify` is broken because it incorrectly classifies static methods as builtin. Properly generating the stub requires unwrapping the `staticmethod` decorator to get the underlying docstring, and alter re-adding the decorator in the stub.

**Comment by SimonHeybrock** [comment]
Removed in #3497, I think?
