### ISSUE TITLE
Scipp Coverage builds failing

### ISSUE THREAD

**Issue by jokasimr** [scipp/scipp#3488]
See https://github.com/scipp/scipp/actions/workflows/coverage.yml.

**Comment by jokasimr** [comment]
The coverage build ran successfully on April 28 and failed on May 5.

Here's the activity that happened that week: https://github.com/scipp/scipp/commits/main/?after=30d653365627d1d763201082d06bc6b6089b85ac+104

Changes that seem like they might have something to do with this:

* [Bump hendrikmuhs/ccache-action from 1.2.12 to 1.2.13](https://github.com/scipp/scipp/commit/e40f236d17d6cf76b7e173f1a8d68cd149024511)?
* [https://github.com/scipp/scipp/commit/7e22a5b2858739b49d85a02ba8a4be54ae37b832](https://github.com/scipp/scipp/pull/3428)

**Comment by jokasimr** [comment]
Maybe related to https://github.com/pybind/pybind11/issues/4748

**Comment by SimonHeybrock** [comment]
This seems to affect debug builds in general.

**Comment by SimonHeybrock** [comment]
Wondering if this is actually not a false positive and we are releasing the GIL on a too large scope here: https://github.com/scipp/scipp/blob/4e54974c75e3cf0da075e82b6995d080125be4bc/lib/python/bind_operators.h#L157-L163

Should it be released only for the actual `+=`? Or is only the return type the culprit, and changing it to return by reference would be enough?
