### ISSUE TITLE
`drop_coords` and `drop_masks` for binned data?

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#3496]
Currently these methods to not effect coord/masks of the bins content, and, e.g., `da.bins` lacks a `drop_coords` method. This is very inconvenient, since the only other way to solve this is using the low-level "expert" `da.bins.constituents` interface. I think there are two options:

- Modify outer methods to drop from `da.coords` *and* `da.bins.coords`.
- Add `da.bins.drop_coords`

I am not sure yet which is better.

**Comment by jokasimr** [comment]
Isn't there the possibility that there are two coordinates with the same name, one on the top level and one in `bins`. In that case the user might want to drop one but not the other. That seems to me like it excludes the option of having one method dropping from both `coords` and `bins.coords`?

**Comment by SimonHeybrock** [comment]
Yes, the same coord can be top level and in the bins. I think most of the time one would want to drop both. So maybe having a single function with a keyword-arg to prevent dropping the one of the bins content would be an option.

**Comment by jokasimr** [comment]
> having a single function with a keyword-arg to prevent dropping the one of the bins content would be an option.

Yeah that could work. But did you mean the keyword argument should prevent dropping the outer coord, or prevent dropping the inner coord?

Do we need to support all three cases (drop outer, drop inner, drop both)?

**Comment by jokasimr** [comment]
How can this actually be done manually through the python interface? :sweat_smile: 
```python
from scipp.data import binned_xy
da = binned_xy(100, 10, 10)
da.bins.constituents['data'].drop_coords('x')
# Above line actually doesn't drop the 'x' coord from the underlying data
# neither does
da.bins.constituents['data'].coords.pop('x')
```

**Comment by SimonHeybrock** [comment]
https://github.com/scipp/scipp/blob/5c70baba5dca9df4648d1e161ce26643a152ec5a/src/scipp/core/binning.py#L421-L427
