### ISSUE TITLE
Fix automatic bin-edge finding when coord has `nan` value

### ISSUE THREAD

**Issue by jokasimr** [scipp/scipp#3506]
If no explicit bin-edges are passed to the `.bin` method scipp tries to determine suitable bin-edges based on the values of the coordinate.

If the coordinate has `nan` values this fails
```python
import scipp as sc
data = sc.data.table_xyz(10)
data.coords['x'][0] = sc.scalar(float('nan'), unit=data.coords['x'].unit)
data.bin(x=4, y=2)
```
with error `BinEdgeError: Bin edges in dim x must be sorted`.

The error here is reasonable, we can't construct a binning without dropping the events associated with the `nan` coord values, and we don't want to do that automatically.
But the error message is not very clear. If we catch this issue before the faulty bin-edges are passed to `_cpp.bin` we could provide the user with a better error message like: `ValueError: coordinate contains nan, could not determine bin edges automatically`.

**Comment by jokasimr** [comment]
> we can't construct a binning without dropping the events associated with the nan coord values, and we don't want to do that automatically

After thinking about this a bit more, I think we do want to drop the events automatically. That is, we should probably just ignore `nan` values when determining the bin range automatically, that is, using `nanmin` and `nanmax` instead of `min` and `max`.

The reason is, a histogram will *always* drop `nan` valued events regardless what the binning is. So it should not be unexpected for the user that those events are dropped also in the case when the bins are determined automatically.

**Comment by SimonHeybrock** [comment]
Yes, I think what you say makes sense:.There is no way to preserve `NaN` in `bin`, since it does not work with `<` operators. It is supported in `group` as far as I can remember, but that is unrelated to the bin-edge setup.
