### ISSUE TITLE
Sorting and similar operations for sparse data?

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#351]
I would like to start a discussion on an important technical problem:

Our sparse-data implementation is based on potentially multiple vectors holding related data. The most relevant example would be the equivalent to a Mantid `EventList`, which would translate to a sparse coord (TOF), a sparse label (pulse-times), and optionally sparse data with values and variances (weights and errors), i.e., in total 4 vectors per "spectrum".

Having these separate has a number of advantages:

- Matches the data layout used for dense data.
- Data without weights or without pulse times does not require special handling via a separate type (or a wrapper like `EventList` in Mantid, which actually supports several (but not all) cases internally).
- Potentially large performance benefits for operations that do not need all fields, e.g., `histogram` could ignore pulse times, whereas they are always loaded in the Mantid-style array-of-structures approach.
- Maximum flexibility, can e.g., use single precision for certain fields, again with performance benefits. With an array-of-structures approach there would be too many cases (would require hard-coding or compile-time choice).

The "structure-of-array" approach comes with a problem though: Operations that require access to multiple fields must either handle this explicitly or a proxy iterator must be available. The most important example is sorting, but there will be others.

Here are a couple of solutions I can think of:

- Use a permutation vector, see https://stackoverflow.com/a/17074810.
  - Specific to sorting, would need other similar solutions for other operations.
  - Requires more operations and memory allocations (decreased performance).
- Use proxy iterators, such as https://github.com/ericniebler/range-v3.
  - Relatively general, though `std` algorithms cannot always be used.
  - No performance loss, provided that the compiler manages to deal well with the proxies.
  - `range-v3` is not (and to my understanding never will be) a production-quality library.
  - Implementing proxy iterators ourselves is quite advanced.
- Copy data to vector of tuples, sort, copy back.
  - Specific to sorting.
  - Inefficient, requires copies and allocation.
- Implement our own `sort`.
  - Specific to sorting.
  - "Local" solution, does not complicate other parts of the code.
- Switch to a array-of-structures layout.
  - Cannot imagine how this could work with the current codebase. This would be a step back towards not supporting generic sparse data.
- Switch underlying data layout to array-of-structures, but keep interface to pretend it is a structure-of-array. More specifically, the sparse coord, sparse labels, and sparse values/variances could be shared owners of a buffer that is internally an array of structs.
  - Loses performance advantages, e.g., access to sparse coord is always with a stride != 1 in the underlying buffer.
  - Performance penalty when adding or removing fields (requires reallocating buffer).
  - Probably relatively complicated.

What is your opinion? Are there other solutions? Is anything missing in my short analysis?  

Related issues:
- https://github.com/scipp/scipp/issues/279
- https://github.com/scipp/scipp/issues/221

**Comment by OwenArnold** [comment]
I think the SOA approach for the event data nice and It would be a shame to have to revert back to a AOS approach (even temporarily) to achieve sorting. 

> Use a permutation vector, see https://stackoverflow.com/a/17074810.

I find this suggestion to be the most natural, though as you say requires memory allocation and operations (at least 2-step). I also think this would be the fastest to develop given that it looks like it needs the fewest changes. Presumably this could be hidden (as with the other sort options) such that the user could apply a comparator and a field to sort on (TOF, PulseTime) - i mention this because if we can hide this, we can also easily change the internal sort methodology in future.

Note that for sorting events, it is also necessary to consider sorting on BOTH TOF and PulseTime, for example sorting by T at detector (PulseTime + TOF) such as is used in fast event filtering.

**Comment by SimonHeybrock** [comment]
See also #358.

**Comment by SimonHeybrock** [comment]
Outdated after event-data rewrite.
