### ISSUE TITLE
We have broken links

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#3513]
Linkcheck flags these as broken:
- Was moved to `https://jupyterlab-code-formatter.readthedocs.io/`
```
(development/notebook-style-guide: line   65) broken    https://ryantam626.github.io/jupyterlab_code_formatter/index.html - 404 Client Error: Not Found for url: https://ryantam626.github.io/jupyterlab_code_formatter/index.html
```

- Don't know what this was supposed to link to how how the URL was originally found:
```
(development/dependencies: line   77) broken    https://azure.archive.ubuntu.com - HTTPSConnectionPool(host='azure.archive.ubuntu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ff5a2e65e10>, 'Connection to azure.archive.ubuntu.com timed out. (connect timeout=30)'))
```

**Comment by jokasimr** [comment]
Seems the `azure.archive.ubuntu.com` url comes from here:

https://github.com/scipp/scipp/blob/8926f17e545fac331c475c1b80cfc3a901a8f2eb/docs/development/dependencies.rst#services--servers-we-depend-on

Don't know where exactly our `ccache-action` gets `ccache` from nowadays: https://github.com/hendrikmuhs/ccache-action/blob/main/src/restore.ts
Do we need to document that or can we just remove that entry from the table?
