### ISSUE TITLE
Support for unit roots

### ISSUE THREAD

**Issue by pordyna** [scipp/scipp#3534]
Hi! I get the following error message :`Unsupported unit as result of sqrt: sqrt(eV).`. It looks like roots of units are not supported, is this on purpose? I can go around it by multiplying the expression by 1eV before taking the root, but this is just a workaround.

**Comment by SimonHeybrock** [comment]
Hi @pordyna, wondering what the meaning of $\sqrt(eV)$ is?

Aside from that, Scipp uses https://github.com/LLNL/units, so you may inquire there.

**Comment by pordyna** [comment]
Hi @SimonHeybrock, thanks for answering so fast! It looks like it is a known limitation in LLNL/units, and you can't probably do much about it. So you can close the issue if you want.

> Fractional unit powers are not supported in general. While some mathematical operations on units are supported any root operations sqrt or cbrt will only produce valid results if the result is integral powers of the base units. One exception is limited support for √Hz operations in measurements of Amplitude spectral density. A specific definition of a unit representing square root of Hz is available and will work in combination with other units.

I was just working with a distribution that has eV^(0.5) in its unit. I guess it does not have any physical meaning per se. It was a 1D Maxwell–Boltzmann distribution for the kinetic energy multiplied by the sqrt(E) so that it becomes purely exponential. It has the dimensionality of Energy^(-0.5).
