### ISSUE TITLE
Possible `CreateRule` creation error for `transform_coords` graph

### ISSUE THREAD

**Issue by g5t** [scipp/scipp#3539]
## Description
As part of a utility to split time-dependent data into constant parameter-set-point periods, I tried my hand at writing a somewhat-generic function to group event data by any number of time-dependent variables wrapped by `scipp.lookup`.
That function takes the lookup tables as collected keyword arguments, and has an implementation like

```python
def group(data_array: DataArray, coord: str, **lookup_tables):
    targets = tuple(lookup_tables.keys())
    graph = {'new_variable_name': coord}
    graph.update({k: lambda new_variable_name: v[new_variable_name] for k, v in lookup_tables.items()})
    return data_array.transform_coords(targets, graph=graph, keep_aliases=False).group(*targets)
```

which somehow causes a failure in `transform_coords`, seemingly due to the use of the dictionary comprehension in building the graph.

## Minimal example
The aliasing for `coord` above is not necessary to exhibit the error, and using string-variables in the graph definition is insufficient to cause the error. The follow will fail at the last `assert` statement:

```python
import scipp as sc

d = sc.data.binned_xy(nevent=1000, nx=10, ny=100)

three_elements = sc.DataArray(
  data=sc.linspace(dim='angle_dimension', start=10., stop=20., num=3, unit='deg'), 
  coords={'angle_dimension': sc.linspace(dim='angle_dimension', start=0., stop=1., num=3, unit='m')}
)

five_elements = sc.DataArray(
  data=sc.array(dims=['temperature_dimension'], values=[1,10,100,1000,10000], unit='K'), 
  coords={'temperature_dimension': sc.linspace(dim='temperature_dimension', start=0., stop=1., num=5, unit='m')}
)

l_three_elements = sc.lookup(three_elements, 'angle_dimension')
l_five_elements = sc.lookup(five_elements, 'temperature_dimension')

temperature = 'temperature'
angle = 'angle'

graph = {angle: lambda z: l_three_elements[z], temperature: lambda z: l_five_elements[z]}
dat = d.transform_coords([temperature, angle], graph=graph, keep_aliases=False).group(temperature, angle)

assert dat.sizes[temperature] == 5
assert dat.sizes[angle] == 3

tables = {angle: l_three_elements, temperature: l_five_elements}
targets = tuple(tables.keys())
graph = {k: lambda z: v[z] for k, v in tables.items()}
dat = d.transform_coords(targets, graph=graph, keep_aliases=False, rename_dims=False).group(*targets)

assert dat.sizes[temperature] == 5
assert dat.sizes[angle] == 3, f'{angle} dimension is {dat.sizes[angle]} not 3'

```

## Conclusion
I suspect a graph constructed from dictionary comprehension was not an intended use case for `transform_coords`, but if you think this _should_ be possible I would greatly appreciate advice on how it can be achieved.

**Comment by g5t** [comment]
Thanks to helpful feedback from @jl-wynen I now see that this is a result of how Python lambda functions work.
Namely that in `graph = {k: lambda z: v[z] for k, v in tables.items()}`, the variable _name_ `v` is bound not the object it refers to, and since each lambda is defined in the same context the name refers to its last definition in the dictionary comprehension.

In case someone else encounters the same problem, a solution is to define the lambda functions in a separate function context, e.g.,
```python
def make_lookup_function(table):
    return lambda z: table[z]

graph = {k: make_lookup_function(v) for k, v in tables.items()}
```

**Comment by jl-wynen** [comment]
For more context: https://docs.astral.sh/ruff/rules/function-uses-loop-variable/ (Also, use static analysers! :wink: )
