### ISSUE TITLE
curve_fit does not respect masks

### ISSUE THREAD

**Issue by TheFermiSea** [scipp/scipp#3557]
Hello,

It appears that scipp.curve_fit attempts to perform a fit even if a large section of data has been masked.  Certainly, this has some benefit in certain circumstances, but I would suspect that in most cases, masked data (meeting certain conditions) should be ignored when curve_fit is broadcast.  Here is an anecdotal example.  Imagine a DataArray that consists of a stack of images (dims = ['x', 'y']), stacked across a different independent variable (let's call it 'theta').  Now, consider that only certain regions of the image stack carry useful information.  For example, let's define a mask as follows:

da.masks['mask'] = da.mean('theta') < da.mean('theta').mean('x').mean('y')/2

If I then run scipp.curve_fit on this masked DataArray, the fit is broadcast to *all* pixels, not just the unmasked ones, which may lead to convergence issues.  Would it be possible to have a kwarg that allows a user to choose whether masks should be respected?

**Comment by SimonHeybrock** [comment]
Hi!
I think I need some clarification to understand your question. First of all, `scipp.curve_fit` respects masks by treating masked data points as if they were not there. Example from the docs (with added mask):

```python
import scipp as sc
import numpy as np


def func(x, a, b):
    return a * sc.exp(-b * x)


rng = np.random.default_rng(1234)
x = sc.linspace(dim='x', start=0.1, stop=0.4, num=50, unit='m')
y = func(x, a=5, b=17 / sc.Unit('m'))
y.values += 0.01 * rng.normal(size=50)
da = sc.DataArray(y, coords={'x': x})
da.masks['mask'] = da.coords['x'] < sc.scalar(0.2, unit='m')

popt, _ = sc.curve_fit(['x'], func, da, p0={'b': 1.0 / sc.Unit('m')})

a = sc.values(popt['a']).data
b = sc.values(popt['b']).data
x = sc.linspace(dim='x', start=0.1, stop=0.4, num=1000, unit='m')
sc.DataGroup(data=da, fitted=sc.DataArray(func(x, a, b), coords={'x': x})).plot(
    marker={'fitted': None}, linestyle='solid'
)
```
Result (observe how fit result is not constrained by masked points):
<img width="509" alt="image" src="https://github.com/user-attachments/assets/376b0f84-bf80-4117-b67f-f9582faab0a4">

So I wonder what you are reporting. Is it
1. A multi-dimensional case where this is broken?
2. Something else?

**Comment by jokasimr** [comment]
1. For masks that share dimensions with the dimensions fitted over (like the example @SimonHeybrock gave above) the curve fit routine should ignore masked points. If it doesn't do that in some case that's a bug. We would be grateful for a reproducible example.

2. For masks that don't share dimensions with the dimensions fitted over, for example, fitting over `theta` and having a mask over `x` and `y`, the curve fit routine makes a fit for every `(x, y)`, even if that point is masked. In that case the parameters returned will have the mask applied. This is inefficient if a large fraction of the points are masked. See example below:

```python
import scipp as sc
import numpy as np


def func(theta, a, b):
    return a * sc.exp(b * theta)


rng = np.random.default_rng(1234)
x = sc.linspace(dim='x', start=0.1, stop=0.4, num=50)
y = sc.linspace(dim='y', start=0.1, stop=0.4, num=50)
theta = sc.linspace(dim='theta', start=0.1, stop=3, num=20)

z = func(theta, a=x, b=y)
z.values += 0.01 * rng.normal(size=z.values.shape)
da = sc.DataArray(z, coords={'x': x, 'y': y, 'theta': theta})
da.masks['mask'] = (da.mean('theta') < da.mean('theta').mean('x').mean('y')).data

popt, _ = sc.curve_fit(['theta'], func, da)
popt['b'].plot()
```

![curve_fit_example](https://github.com/user-attachments/assets/4b8dbe4b-3320-4621-933c-63ac1784b99c)

**Comment by TheFermiSea** [comment]
I am referring to case (2) described by @jokasimr.  It is not entirely clear to me how _curve_fit (line 174 of curve_fit.py) is being mapped, nor is it clear how this is parallelized (it certainly is because it runs across all cores on my machine).  But, in the case that scipy.optimize.curve_fit is simply called in a nested for loop, it may be sufficient to check if that point is masked and, if so, assign the value as nan *before* calling scipy.optimize.curve_fit.  (I think this amounts to wrapping lines 242:257 in if __: __ else: continue).  This does not seem very efficient, but is better than attempting to fit data that has already been deemed ineligible for fitting.

**Comment by SimonHeybrock** [comment]
I think setting those to `NaN` would make sense, we should consider doing that. But also note that the current behavior is also consistent with other operations. For example `masked_da1 + masked_da2` will operate normally on all elements, including the masked ones, but the output will have those masked as well.

**Comment by jokasimr** [comment]
Setting `NaN` makes sense to me too. We could make that the default behavior, or we can hide it behind a keyword argument, something like `set_nan_in_masked_regions`. If we make it the default that's a breaking change. Hiding it behind a keyword leaves it up to the user to decide, but also makes an already complicated interface more complicated. Not sure what's best.

**Comment by SimonHeybrock** [comment]
I think a breaking change is fine here, as very few (other) users will have run into this.
