### ISSUE TITLE
Problems accessing `scipp.constants`

### ISSUE THREAD

**Issue by arm61** [scipp/scipp#3560]
The following raises an error for me: 

```
import scipp as sc
sc.constants
```

But works if I do

```
from scipp import constants
```

Scipp version: 24.9.1

**Comment by SimonHeybrock** [comment]
Hi! This is by design. Similar to, say SciPy submodules, it is a submodule that needs to be imported explicitly. One reason for this is that it relies on Scipy, which is an optional dependency of Scipp.

If you would like to use `sc.constants` in code, you can

```python
import scipp as sc
import scipp.constants

sc.constants.h  # works now
```
