### ISSUE TITLE
Should `flatten` allow out-of-order dims?

### ISSUE THREAD

**Issue by nvaytet** [scipp/scipp#3570]
Currently, doing
```Py
import scipp as sc
sc.data.binned_xy(1000, 10, 10).hist().flatten(dims=['y', 'x'], to='z')
```
raises `DimensionError: Can only flatten a contiguous set of dimensions in the correct order`
while
```Py
sc.data.binned_xy(1000, 10, 10).hist().flatten(dims=['x', 'y'], to='z')
```
works.
Should we also allow the first one? It seems rather unambiguous what the result should be?

**Comment by SimonHeybrock** [comment]
If I remember correctly tit was actually you and I who discussed this originally. We decided to not support this as it is ambiguous. Is the user expecting to flatten the specified dims in the given order, or in the order they appear in the input data?

**Comment by nvaytet** [comment]
Yes, I remember I was involed in the design and implementation of `fold` and `flatten`. Sometimes I disagree with my past self, but in this case, I see that it is somewhat ambiguous. Closing this issue.
