### ISSUE TITLE
Add `standard_deviation` property

### ISSUE THREAD

**Issue by arm61** [scipp/scipp#3614]
Currently, it is a bit annoying to have, the following, for example when plotting some data.

```
np.sqrt(da.data.variances)
```

In particular, as I am trying to minimise the amount of `numpy` being used where `scipp` can be used instead. 
Would it be possible to add a `da.data.standard_deviations` or similar?

**Comment by jl-wynen** [comment]
There is `sc.stddevs(da)` which returns a new variable / data array (https://scipp.github.io/generated/functions/scipp.stddevs.html). Does this do what you need?

Note that a property like you suggest would be a bit odd because it wouldn't return a stored quantity but compute and return a new numpy array.

**Comment by arm61** [comment]
Ideally, I hoped for something that looked and acted (to the user) like the variances property. 

Currently in scipp, there are two ways I can achieve what I am trying to get:

```
import numpy as np

plt.errorbar(da.coords['x'], da.data.values, np.sqrt(da.data.variances))
```

or

```
plt.errorbar(da.coords['x'], da.data.values, sc.stddevs(da.data).values)
```

Ideally, I would like:

```
plt.errorbar(da.coords['x'], da.data.values, da.data.stddevs)
```

**Comment by jl-wynen** [comment]
I'm not sure this is a good idea. As I said, it would produce a new array and return that. This means that:
1. It's not cheap but an O(1) operation.
2. Modifications to the array don't affect the Scipp variable. I.e., `da.data.stddevs[0] = 1` does not change `da.data.variances`.

**Comment by arm61** [comment]
Hmm, I might do `variances ** 0.5` instead then.
