### ISSUE TITLE
Forward kwargs to pandas in `load_csv`?

### ISSUE THREAD

**Issue by nvaytet** [scipp/scipp#3621]
Right now, we only support 3 args in `load_csv`: `sep`, `data_columns`, `header_parser`.
But Pandas's `read_csv` supports many more.

Can we forward the kwargs to Pandas?

**Comment by jl-wynen** [comment]
We can. The reason for not doing that from the beginning is that I didn't want to couple the function to closely to pandas. As it stands, we could replace the implementation to get rid of the dependency on pandas.

**Comment by nvaytet** [comment]
I guess if we swap it out for another library, we could then just forward the kwargs to the new library.
All we need to say is something like "see pandas for other kwargs"?

Right now, I cannot skip e.g. 10 rows in the header (I want to use `header=10`)

**Comment by jl-wynen** [comment]
> I guess if we swap it out for another library, we could then just forward the kwargs to the new library.
> All we need to say is something like "see pandas for other kwargs"?

We can, but that is a breaking change which is not feasible once we have users.

**Comment by nvaytet** [comment]
Sure, but is the big downside of not being able to utilize the many options in the pandas loader worth a hypothetical library change (maybe far) in the future?

I think users may also complain about the fact that there are hardly any options in the loader?
