### ISSUE TITLE
Dataset setData form the DataConstProxy 

### ISSUE THREAD

**Issue by igudich** [scipp/scipp#373]
Implement `void Dataset::setData(const DataConstProxy& data)`.
Checks: 
1. For dense coordinates checks all coordinates equality.
2. Names conflicts for sparse coordinates.
3. Names conflicts for data variables.

Actions:
1. Copy sparse coordinates and data only if all checks are passed.

**Comment by SimonHeybrock** [comment]
I think we should have to same behavior as other `setData` (or `setCoord`) methods. That is, silently replace existing items. So 2. and 3. in your list should not be necessary?

**Comment by SimonHeybrock** [comment]
Note the fix in the title. The description was correct however.
