### ISSUE TITLE
Update jupyter demo part 3

### ISSUE THREAD

**Issue by nvaytet** [scipp/scipp#379]
Parts 1 & 2 were updated in a separate PR. Part 3 still needs to be updated with the new python API.

**Comment by SimonHeybrock** [comment]
One thing where we can improve upon the old notebooks: Instead of exposing Mantid code and manual conversion, create a wrapper for it, something like:

```python
dataset = sc.compat.mantid.load(filename="abc.nxs")
```

This wrapper avoids mixing Mantid and scipp Python code, and reduces complexity for the user.
