### ISSUE TITLE
Dataset find related stuff.

### ISSUE THREAD

**Issue by igudich** [scipp/scipp#388]
Implement `find` and `contains`.

See https://github.com/scipp/scipp/tree/v0.0.1 and in particular dataset.h (before the refactor) for what was previously supported.

**Comment by DanNixon** [comment]
`contains()` seems to be already implemented for relevant classes (`Dataset` and `DataConstProxy`).

@SimonHeybrock Would you expect `find()` to do? Would it essentially be `operator[]` that does not throw?

**Comment by SimonHeybrock** [comment]
In general I am using `std::map` as a guideline for the API (unless it does not make sense or is ambiguous), so it would return an iterator: https://en.cppreference.com/w/cpp/container/map.
