### ISSUE TITLE
Dataset merge

### ISSUE THREAD

**Issue by igudich** [scipp/scipp#390]
Implement `merge`.
Inner, outer, left, right?

See https://github.com/scipp/scipp/tree/v0.0.1 and in particular dataset.h (before the refactor) for what was previously supported.

**Comment by SimonHeybrock** [comment]
I think the inner/outer/left/right is not relevant in this case, at least for now. We are *not* looking for merging datasets with mismatching dimensions or coordinates (as supported by pandas). Rather, we want the union of all items, see, e.g., http://xarray.pydata.org/en/stable/combining.html#merge and http://xarray.pydata.org/en/stable/generated/xarray.Dataset.merge.html#xarray-dataset-merge, which I think do the same.
