### ISSUE TITLE
Dataset sum related

### ISSUE THREAD

**Issue by igudich** [scipp/scipp#391]
Implement `sum`, `mean`.

See https://github.com/scipp/scipp/tree/v0.0.1 and in particular dataset.h (before the refactor) for what was previously supported.

**Comment by SimonHeybrock** [comment]
Exists for variable, just add it for `DataProxy` and `Dataset`.

**Comment by igudich** [comment]
@SimonHeybrock, why the `Variable::mean(...)` casts everything to double? Should we provide `dtype` optional argument? Until we haven't this I suggest keeping the type corresponding to the input argument, at least for floats/doubles, for integers default cast to double is consistent with numpy behaviour.

**Comment by SimonHeybrock** [comment]
> Until we haven't this I suggest keeping the type corresponding to the input argument

I agree. At the same time however, I *do* suggest we consider using `double` for intermediate values in `sum`? Our naive summation order can otherwise lead to a lot of precision loss (and major parts of our target audience is probably not aware of the issues with summing large numbers of `float`).

If it isn't simple to do, we can postpone this until after v0.1.

**Comment by igudich** [comment]
> > Until we haven't this I suggest keeping the type corresponding to the input argument
> 
> I agree. At the same time however, I _do_ suggest we consider using `double` for intermediate values in `sum`? Our naive summation order can otherwise lead to a lot of precision loss (and major parts of our target audience is probably not aware of the issues with summing large numbers of `float`).
> 
> If it isn't simple to do, we can postpone this until after v0.1.

Double buffer or some version of Kahan algorithm. But due to the realization of `Variable::sum()` through `accumulate_in_place` it is not trivial to make the buffer different from the variable type, as well as implement the algorithms. So, for now, I would just make the behaviour consistent with `numpy` and put the issue about accuracy.

**Comment by SimonHeybrock** [comment]
I think `accumulate_in_place` can already do it. We just need to adjust the template arguments (pass, e.g., `pair<double, float>` instead of `pair<float, float>`).
