### ISSUE TITLE
Python API manual testing

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#400]
We keep uncovering issues with our Python bindings, either missing features or crashes/segfaults. The most recent example:

```python
for dim, coord in dataset.coords:
   do_something(coord) # segfault
```

I suggest everyone spend at least 1 hour, randomly playing with `scipp` in Python, trying various things. Add comments to this issue if problems or API gaps are encountered (or directly create new issue if it is clearly a bug).

**Comment by OwenArnold** [comment]
I have not performed exhaustive testing, but I was unable to generate segfaults despite trying to remove base objects from scope etc. Here are some of the smaller issues I found:

* `ConstProxy` types need to provide a representation on the python side.
* `del` not supported via `Dataset` (for good reason), but generated `AttributeError` is a little unfriendly.
* Some unit operations are supported but others, not - not easy to establish what operations are allowed on which units based on python help etc. For example, `sp.units.m ** 2` is fine `sp.units.s ** 2` not supported. 
* Many unit tests for high level operations (for example `filter`) disabled. Though as far as I could test, `filter` worked as expected.
* A few operations need, `coord` variables on the dataset, but do not provide very helpful outputs if missing, for example `histogram` *Could not find data with name sparse*. Slicing without coords gives similar cryptic error *map:at IndexError*

**Comment by SimonHeybrock** [comment]
>     * `del` not supported via `Dataset` (for good reason), but generated `AttributeError` is a little unfriendly.

What reason? I think this should be implemented in #389?

**Comment by SimonHeybrock** [comment]
> I was unable to generate segfaults despite trying to remove base objects from scope etc

Can you tried chaining access? I tend to run into trouble with things like `data = dataset.coords[Dim.X].values`, then use `data` for something.

**Comment by OwenArnold** [comment]
> > ```
> > * `del` not supported via `Dataset` (for good reason), but generated `AttributeError` is a little unfriendly.
> > ```
> 
> What reason? I think this should be implemented in #389?

I did not intend to say that it shouldn't be implemented. My thoughts were more about the side effects, so undoing the actions make when variables are added. For example might mean reducing the global dimensionality or extent space, there are possibly complications around this with extent tracking etc. i.e it's probably not trivial.

**Comment by SimonHeybrock** [comment]
> > > ```
> > > * `del` not supported via `Dataset` (for good reason), but generated `AttributeError` is a little unfriendly.
> > > ```
> > 
> > 
> > What reason? I think this should be implemented in #389?
> 
> I did not intend to say that it shouldn't be implemented. My thoughts were more about the side effects, so undoing the actions make when variables are added. For example might mean reducing the global dimensionality or extent space, there are possibly complications around this with extent tracking etc. i.e it's probably not trivial.

We can probably just regenerate the dimensions from scratch.

**Comment by SimonHeybrock** [comment]
Coordinate checks in operations with datasets appear to be too restrictive, see #417.

**Comment by SimonHeybrock** [comment]
Another example:

```python
dataset -= dataset[Dim.X, 0] # works
dataset = dataset - dataset[Dim.X, 0] # throws
```
Again, see #417.

**Comment by OwenArnold** [comment]
Strange coordinate values 
```
In [311]: ds = Dataset()                                                                                                                                                                                       

In [312]: ds.set_coord(Dim.X, Variable([Dim.X], values=np.arange(4)))                                                                                                                                          

In [313]: data = ds.coords[Dim.X].values                                                                                                                                                                       

In [314]: data                                                                                                                                                                                                 
Out[314]: array([0, 1, 2, 3], dtype=int64)

In [315]: ds += ds                                                                                                                                                                                             

In [316]: data                                                                                                                                                                                                 
Out[316]: array([4, 1, 2, 3], dtype=int64)
```

**Comment by SimonHeybrock** [comment]
> Strange coordinate values
> 
> ```
> In [311]: ds = Dataset()                                                                                                                                                                                       
> 
> In [312]: ds.set_coord(Dim.X, Variable([Dim.X], values=np.arange(4)))                                                                                                                                          
> 
> In [313]: data = ds.coords[Dim.X].values                                                                                                                                                                       
> 
> In [314]: data                                                                                                                                                                                                 
> Out[314]: array([0, 1, 2, 3], dtype=int64)
> 
> In [315]: ds += ds                                                                                                                                                                                             
> 
> In [316]: data                                                                                                                                                                                                 
> Out[316]: array([4, 1, 2, 3], dtype=int64)
> ```

This appears to be working with the changes in #416. I have added this code snipped as another unit test.

**Comment by SimonHeybrock** [comment]
I consider this done for now. Of course more testing will follow.
