### ISSUE TITLE
Can no longer build scipp with clang on Linux

### ISSUE THREAD

**Issue by DanNixon** [scipp/scipp#414]
Seems to have started happening around the time #404 was merged.

Clang version:
```
clang version 7.0.0-3~ubuntu0.18.04.1 (tags/RELEASE_700/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

Last output of `make -j VERBOSE=1`:
```
[ 76%] Linking CXX executable scipp-core-test
cd /home/dan/git/scipp/build/core/test && /usr/bin/cmake -E cmake_link_script CMakeFiles/scipp-core-test.dir/link.txt --verbose=1
ccache /usr/bin/clang++-7   -fno-omit-frame-pointer -fsized-deallocation -O3 -DNDEBUG   CMakeFiles/scipp-core-test.dir/bool_test.cpp.o CMakeFiles/scipp-core-test.dir/counts_test.cpp.o CMakeFiles/scipp-core-test.dir/dataset_test.cpp.o CMakeFiles/scipp-core-test.dir/dataset_test_common.cpp.o CMakeFiles/scipp-core-test.dir/dataset_operations_test.cpp.o CMakeFiles/scipp-core-test.dir/dimensions_test.cpp.o CMakeFiles/scipp-core-test.dir/except_test.cpp.o CMakeFiles/scipp-core-test.dir/transform_test.cpp.o CMakeFiles/scipp-core-test.dir/value_and_variance_test.cpp.o CMakeFiles/scipp-core-test.dir/variable_test.cpp.o CMakeFiles/scipp-core-test.dir/variable_custom_type_test.cpp.o CMakeFiles/scipp-core-test.dir/variable_operations_test.cpp.o CMakeFiles/scipp-core-test.dir/variable_view_test.cpp.o CMakeFiles/scipp-core-test.dir/view_index_test.cpp.o  -o scipp-core-test ../libscipp-core.a ../../googletest/lib/libgtest_main.a ../../googletest/lib/libgtest.a ../../units/libscipp-units.a ../../googletest/lib/libgtest.a -lpthread
../libscipp-core.a: error adding symbols: File format not recognised
clang: error: linker command failed with exit code 1 (use -v to see invocation)
core/test/CMakeFiles/scipp-core-test.dir/build.make:437: recipe for target 'core/test/scipp-core-test' failed
make[2]: *** [core/test/scipp-core-test] Error 1
make[2]: Leaving directory '/home/dan/git/scipp/build'
CMakeFiles/Makefile2:608: recipe for target 'core/test/CMakeFiles/scipp-core-test.dir/all' failed
make[1]: *** [core/test/CMakeFiles/scipp-core-test.dir/all] Error 2
make[1]: Leaving directory '/home/dan/git/scipp/build'
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by SimonHeybrock** [comment]
Could this be a ccache issue?

**Comment by DanNixon** [comment]
> Could this be a ccache issue?

Doesn't look like it.

**Comment by igudich** [comment]
It seems that clang can't treat the case then  `INTERPROCEDURAL_OPTIMIZATION` has different values for libraries and tests. So my suggestion would be either remove the explicit setting this in tests or disable for clang:
https://github.com/scipp/scipp/blob/80fa8e453b014e773526510f44954e504ce32b17/core/test/CMakeLists.txt#L30

@SimonHeybrock, @DanNixon, @OwenArnold, any comments?

**Comment by SimonHeybrock** [comment]
Maybe:
1. Disable it for PR builds.
2.Enable it for building conda packages (affects only OSX not since Linux used gcc), excluding build of tests from conda jobs (not needed anyway).

?

**Comment by igudich** [comment]
> Maybe:
> 
> 1. Disable it for PR builds.
> 2. Enable it for building conda packages (affects only OSX not since Linux used gcc), excluding build of tests from conda jobs (not needed anyway).
> 
> ?

Add another flag for this and manage in Travis scripts?

**Comment by SimonHeybrock** [comment]
Yes. Maybe building tests should not be included in the `all` target?

**Comment by DanNixon** [comment]
> Yes. Maybe building tests should not be included in the `all` target?

I think including tests in `all` is OK. The Conda config uses `install` which should not include tests (but actually does unless you set `WITH_CTEST=OFF`).
