### ISSUE TITLE
Nested Slice Issue

### ISSUE THREAD

**Issue by OwenArnold** [scipp/scipp#425]
Problem illustrated in following test.

```cpp
TEST(DatasetTest, slice_problems) {

  Dataset ds;
  auto var1 = makeVariable<double>({Dim::X, 3}, {1, 2, 3});
  ds.setCoord(Dim::X, var1);
  auto var2 = makeVariable<double>({Dim::Y, 3}, {1, 2, 3});
  ds.setCoord(Dim::Y, var2);

  // Here slicing goes from 0 - var length.
  auto sliced1 = ds.slice(Slice{Dim::Y, 1, 2}, Slice{Dim::X, 1, 2});
  CoordsProxy proxy = sliced1.coords();
  // Get the variable const proxy. Looks correct.
  auto ext1 = proxy[Dim::X].dims()[Dim::X];
  EXPECT_EQ(ext1, 1);
  auto ext2 = proxy[Dim::Y].dims()[Dim::Y];
  EXPECT_EQ(ext2, 1);

  // Same as above, but no end, defaults to -1. Note that begin is non-zero.
  auto sliced2 = ds.slice(Slice{Dim::Y, 1}, Slice{Dim::X, 1});
  proxy = sliced2.coords();
  ext1 = proxy[Dim::X].dims()[Dim::X]; // Throws key not found because item
                                       // removed in ConstProxy constructor.
                                       // Should check begin of slice before
                                       // disposing.
}

```

Offender is likely the logic here. https://github.com/scipp/scipp/blob/36b7fb9bd5c7ea8a119d4e4ae7d3cf9a9b4e5e29/core/include/scipp/core/dataset.h#L378

[patch file for test](https://github.com/scipp/scipp/files/3496005/problem.txt)

**Comment by OwenArnold** [comment]
@SimonHeybrock above details the problems noted earlier this morning.

**Comment by SimonHeybrock** [comment]
The default `-1` used in the C++ implementation is *not* a Python-style "before end" index. It indicates that the slice is not a range, but a single index. Therefore, the coord/dim is removed, just like when slicing, e.g., a `numpy` array `a` with `a[1, 1]`. There is currently not C++ equivalent to the `a[1:-1]` that is available in Python.

**Comment by SimonHeybrock** [comment]
See also https://scipp.readthedocs.io/en/latest/user-guide/slicing.html.

**Comment by OwenArnold** [comment]
Ok. that makes sense from your description. I think the only action is then to add code comments to this effect for the `Slice` type.

**Comment by SimonHeybrock** [comment]
I will close this then since there is no actual bug.
