### ISSUE TITLE
Code rules and style guide

### ISSUE THREAD

**Issue by OwenArnold** [scipp/scipp#43]
We should create a clang-format file in the directory root.

Also, at present we do not have a large number of contributors (external or otherwise), but I still think it would be a good idea to create a `CONTRIBUTING.md` an to adopt an existing coding convention i.e http://developer.mantidproject.org/Standards/CPPStandards.html LLVM, etc.

**Comment by SimonHeybrock** [comment]
https://scipp.github.io/developer/coding-conventions.html
