### ISSUE TITLE
__setitem__ for arrays of types not supported by numpy

### ISSUE THREAD

**Issue by igudich** [scipp/scipp#442]
Make this work.
```python
var = sc.Variable(dims=[Dim.Row], values=['a', 'bb'], unit=sc.units.m)
var.values = ["cc", "d"]
```

**Comment by SimonHeybrock** [comment]
Solution: Do something like here: https://github.com/scipp/scipp/blob/master/python/variable.cpp#L161 also for `set_values` (etc.) in https://github.com/scipp/scipp/blob/master/python/bind_data_access.h#L328.
