### ISSUE TITLE
Adding variances for event-data

### ISSUE THREAD

**Issue by igudich** [scipp/scipp#443]
Somehow set the variances for aparse data.
```python
var1 = sc.Variable(dims=[Dim.X, Dim.Y], shape=[2, sc.Dimensions.Sparse])
var1.variances = ...
```

**Comment by SimonHeybrock** [comment]
If I remember correctly it is currently not possible to set variances back to `None`.

**Comment by SimonHeybrock** [comment]
Outdated after event-data rewrite.
