### ISSUE TITLE
size() method in Variable

### ISSUE THREAD

**Issue by igudich** [scipp/scipp#448]
It was deliberate to not add `size()`, since it may be misleading. Think for example of what `len(numpy.ndarray)` gives --- it is the size of the outer dimension, not the element count. Can you avoid adding this method?

_Originally posted by @SimonHeybrock in https://github.com/scipp/scipp/pull/441_

**Comment by SimonHeybrock** [comment]
Also:

> [...] what do you do for sparse data? And why is it returning 0 if there is no data pointer? Unless you need it here and want to deal with the subtleties of defining what exactly this should do in such cases, I suggest you remove it.
