### ISSUE TITLE
Layout considerations

### ISSUE THREAD

**Issue by OwenArnold** [scipp/scipp#462]
Consider layout and standardisation of data in scipp. As raised by Jon Taylor Wed 14th Aug 2019. 

**I do not see this as actionable at present**, scipp will need to be more mature to do this, but do not want to loose the fact that this will need to be considered. 

I believe Jon's point was essentially that there are many ways that information could be stored in a dataset, but probably a few consistent patterns based on the technique area/experiment type that it would be nice to converge upon. There are considerations here too for function authors - how do I know if input dataset contains a normalisation variable for run 'x', based on naming convention? based on sub-dataset?.

**Comment by SimonHeybrock** [comment]
We should discuss this elsewhere since this is not strictly related to (and definitely not limited to) the scipp core libraries.
