### ISSUE TITLE
Functions for DataArray should copy coords, labels, and attrs from input

### ISSUE THREAD

**Issue by nvaytet** [scipp/scipp#495]
Should we also include all other coords and labels from the input(except for the sparse ones)? I am not sure what would be the most consistent / expected way? I think we should?

_Originally posted by @SimonHeybrock in https://github.com/scipp/scipp/pull/479_

**Comment by nvaytet** [comment]
And also preserve the name? See #479

**Comment by SimonHeybrock** [comment]
As far as I can tell the only missing things is to add this for `histogram`.
