### ISSUE TITLE
_repr_html_ for improved rendering in Jupyter notebooks

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#496]
The current text output from `__repr__` is too messy due to the inclusion of arrays of values and variances. This will only get worse when we have larger datasets with more items.

A quick solution would be to show values and variances only on hover, using some css.

It turns out that xarray is working on something much better: https://github.com/pydata/xarray/pull/1820. See https://jsfiddle.net/tay08cn9/4/ for a preview. Can we benefit from this development and reuse/adapt it, or have some common code?

**Comment by DanNixon** [comment]
@SimonHeybrock Do you see an approach similar to xarray potentially replacing `sc.table()`?

**Comment by SimonHeybrock** [comment]
I don't think I would replace `sc.table()`. The html representation is still just a "fancy" version of `__repr__` which does not include all data. Rendering tables will still be useful for some applications, I think.

**Comment by SimonHeybrock** [comment]
https://github.com/pydata/xarray/pull/3425
