### ISSUE TITLE
Variable with variances `mean` - what does it mean?

### ISSUE THREAD

**Issue by igudich** [scipp/scipp#499]
It looks like something crucial got lost here in the `Dataset` rewrite a couple of months ago:

https://github.com/scipp/scipp/blob/ca957f2beeb492778028a79d1f56cc332d82e835/src/dataset.cpp#L1112-L1119

We need to scale the variance, so we get the *standard deviation of the mean*! Could you add that back in here, now that the variances are inside `Variable`. Previously this was handled on the dataset level, but this is not possible/sufficient anymore, of course.

If this takes too long before you go an vacation, I can implement it in a separate issue.

_Originally posted by @SimonHeybrock in https://github.com/scipp/scipp/pull/492_

**Comment by igudich** [comment]
It is not clear what is the correct procedure (or name)  for this operation. For detector data, we normally have in variable values for the mean of Poisson distribution variable - for variance (`\sigma`) of this distribution,  which actually equals mean, but we store it because of its changing during the operations with the variable. The current procedure of `mean` calculation for variances : ` variance = sum(variances)/N^2'.

**Comment by SimonHeybrock** [comment]
There was an option issue for this already, see #494.
