### ISSUE TITLE
Owning proxies

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#503]
The current separate implementation of data containers and their proxies leads to lengthy code and also inefficiencies in some case. Consider for example a function operating on a variable:

```cpp
Variable func(const VariableConstProxy &var) { ...}
```

- In some cases we may want to return the input unchanged, so we would like to simply return the `VariableConstProxy`.
- If a modification is necessary we need to create a new variable. We therefore cannot return a `VariableConstProxy`, since it has no means of keeping a new `Variable` instance alive.

Consider changing `VariableConstProxy` to optionally own a variable. The signature could then be:

```cpp
VariableConstProxy func(const VariableConstProxy &var) { ...}
```

Potentially *all* interaction could be done using the proxies.

**Comment by OwenArnold** [comment]
Interesting discussion point. 

Presumably `VariableConstProxy func(const VariableConstProxy &var) { ...}` would be required as some client function where a side effect would take place? Where else might you want this?

**Comment by SimonHeybrock** [comment]
I am not sure I understand your question?

**Comment by OwenArnold** [comment]
What is the specific benefit of moving to owning proxies? I agree from the side of code length and maintainability, but you mention inefficiencies - Are you concerned that the Variable wrapping is expensive?

**Comment by SimonHeybrock** [comment]
Well, consider for example getting spectrum positions from dataset. If they are stored directly, we can return a proxy, referencing existing data. If they need to be computed, e.g., from underlying detector positions we need to create a new variable. So when we write the function `scipp.neutron.positions`, we have 3 options:

1. Always return `Variable`. This is inefficient since it allocated memory even if there is no need.
2. Have two functions, and let the client code figure out which one has to be used. This is creating horrible client code.
3. Always return a proxy as proposed here, which could internally either own the data, or reference existing data. This makes this efficient, while at the same time keeping client code clean.

Maybe one extra open thing to think about here is how to handle const-ness. In the example I just gave we would need to return a `VariableConstProxy`, so even if new data is returned it cannot be changed.

**Comment by OwenArnold** [comment]
So along the lines of point 3, above the (either owning, or a proxy), it perhaps make sense to drop `Proxy` from the naming convention - it becomes an implementation detail.

**Comment by SimonHeybrock** [comment]
Correct. :)
