### ISSUE TITLE
More systematic and maintainable testing

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#513]
## Partial solution to be implemented

- Extract lambda implementing element-wise operations from implementation.
- Test lambda separately (applied to `Unit` as well as elements of different types).
- Test of, e.g., `Variable::sqrt` can then rely on correctness of underlying components, and just need to test that components are combined in the correct way:
  - `Unit::sqrt`
  - `ValueAndVariance::sqrt`
  - `transform` and `transform_in_place`
  - `element_wise::sqrt`

To do:

- [x] @SimonHeybrock Implement first example (sqrt).
- [x] Implement for other transform-based functionality.

## Original discussion

We support a big variety of possible containers in scipp. For example, just considering `Variable`, we have:

- Data types.
- Units.
- Variances or not.
- Dimensionality, transposed dimensions, broadcasting, ...
- Sparse data or dense.

This leads to a large number of possible "variables" and it has proven difficult to tests all operations for all cases. A big part of the problem is that it it hard to get an overview of what is tested and what not. **It is essential that we improve this**.

I have a couple of suggestions, but not complete solution yet:

1. We have already worked on improving things, e.g., being more systematic in relying on tests of lower-level functionality, such as relying on `operator==` in all but the most basic tests, instead of checking all output properties by hand. This approach needs to be extended and consolidated.

2. Define a set of test data (variables, data arrays, dataset). Require that all operations are tested with all elements of the test data set.
   - Not sure how to do this in practice. Can we avoid hand writing the individual tests? It is not clear how this could be parametrized, since the behavior of a function will vary wildly depending on the input.
   - How would this be combined with other function parameters, or functions that take, e.g., two variables as input? How can we define sensible combinations?

3. Reflect test modularity in file structure? Currently things tend to gravitate to "spaghetti" test files, with dozens or hundreds of tests one after another. It is impossible to quickly figure out what is tested and what is not.

**Comment by DanNixon** [comment]
>     2. Define a set of test data (variables, data arrays, dataset). Require that all operations are tested with all elements of the test data set.

At least a good start here would be moving all test data generation to a common place, this should help with reuse and reduce cognitive load when writing tests (in determining why test data is structured in a certain way and what structure new test data must take).

>     1. Reflect test modularity in file structure? Currently things tend to gravitate to "spaghetti" test files, with dozens or hundreds of tests one after another. It is impossible to quickly figure out what is tested and what is not.

A method I like is a directory structure that mimics the namespace structure then test filenames with the format `class_function.cpp` or `function.cpp`, this makes it very easy to find where a particular piece of functionality is tested and keeps test cases/files small and easier to manage (e.g. ordering of things in files).
To be clear, in this case each test file would test a single function, entire classes are tested by multiple test files.

I'm not sure how well this would integrate with type and value parameterised tests. Particularly when tests can be type parameterised on containers (e.g. `DataArray`, `DataProxy`) or stored dtype.

**Comment by SimonHeybrock** [comment]
> > Define a set of test data (variables, data arrays, dataset). Require that all operations are tested with all elements of the test data set.
> 
> At least a good start here would be moving all test data generation to a common place, this should help with reuse and reduce cognitive load when writing tests (in determining why test data is structured in a certain way and what structure new test data must take).

You think so? I feel this will lead to the same situation we have in Mantid with `WorkspaceCreationHelpers`, which is hard to use and has not significantly improved tests, as far as I can tell.

**Comment by DanNixon** [comment]
> > > Define a set of test data (variables, data arrays, dataset). Require that all operations are tested with all elements of the test data set.
> > 
> > 
> > At least a good start here would be moving all test data generation to a common place, this should help with reuse and reduce cognitive load when writing tests (in determining why test data is structured in a certain way and what structure new test data must take).
> 
> You think so? I feel this will lead to the same situation we have in Mantid with `WorkspaceCreationHelpers`, which is hard to use and has not significantly improved tests, as far as I can tell.

I think the difference is `WorkspaceCreationHelpers` is code that tries to make generating data easy, whereas what I suggested is just moving generation of common test data into one place.

There are probably cases you need a specific test data configuration, but most of the time you can probably operate with some standard test data that contains the various representations (0D, 1D, 2D, ..., sparse, dense, counts, dtypes, etc.).

**Comment by OwenArnold** [comment]
I also think it's important that we spend time ensuring that the test quality is good, and that the tests are easy to understand, use and maintain. I think we ought to be more picky about test quality as part of our review process, so they don't become a second-rate part of the codebase. Maybe we should establish as set of community guidelines for the tests that might lay-out how your test suites would be ordered. i.e 

```
# sematic operations
1. Test construction logic, copy, copy assignment, clone, move ...
2. Test simple operator override behaviour if any `==`, `[]`
3. Test implicit conversions
....
```
Would help with navigation and readability for later tests which I think was one of the issues Simon specified in point 3 above.

I like @DanNixon idea about having common test data in one place, however if prematurely put there, it can just create noise (I think this happened in Mantid). Maybe we need some period sweep-up were we look at common test data and try to refactor to a common location.

I certainly agree with @SimonHeybrock point 1. I'm not sure about point 2, even if there was a feasible way to do this, it might be problematic that the "standard test data" did not properly reflect the situations that really highlighted the problems for each set of operations. i.e could give false confidence and low ability to find bugs for the specific cases. Maybe @SimonHeybrock  was thinking more along the lines of having this standard test data as a separate set of acceptance testing in addition to what we might test otherwise?

**Comment by SimonHeybrock** [comment]
No, I as not thinking of separate acceptance testing, but yes, it can be in addition to other specific tests.

I feel that "guidelines" do not really solve the maintenance problem. Let me give a concrete example:

Before summer we refactored `Dataset` to not store variances in separate variables, instead `Variable` now contains the variances. Unit tests for `Variable` with variances were added. The problem however was: Not all free functions/algorithms that were implemented have been rigorously updated to include tests with variances. The addition of sparse data may be a similar case.

That is, while we may have had a reasonable and (actually not very) structured set of unit tests, a conceptual change in an object (`Variable`) suddenly made 20+ functions badly tested. It is hard to know which changes "break" which test suites (in the sense of create hole in the test suite). In this sense this is not maintainable. We will get to the point where we have 100+ functions/algorithms for variable. If we make an addition to `Variable` I think it is unrealistic to expect that we can confidently say "we updated all affected test", *unless we have a mechanism that* **automatically** *causes test failures.*

One such mechanism could be a base test fixture defining a set of data to be tested on. All functions are to be tested with everything in the base test fixture. If we add a new element to the set of data, all functions will automatically run tests on it. This should fail if a new feature is added that is not supported.

**Comment by DanNixon** [comment]
> One such mechanism could be a base test fixture defining a set of data to be tested on. All functions are to be tested with everything in the base test fixture. If we add a new element to the set of data, all functions will automatically run tests on it. This should fail if a new feature is added that is not supported.

Maybe I worded it badly originally but that is essentially what I meant in https://github.com/scipp/scipp/issues/513#issuecomment-532159901.

**Comment by OwenArnold** [comment]
This sounds like a reasonable suggestion,  I think this would do be a good way of catching errors like you and Dan suggest. I think there are a number of practices that could be adopted to improve maintainable testing.

* Standard Test Data in a base fixture, with the expectation that developers write tests against all of these.
* I think my suggestion earlier with layout would help with maintainability.
* Another suggestion that might be considered in evaluating holes in the test suites and the quality of the test suites themselves is mutation testing. I have not done this in c++ myself, but there are a number of projects to facilitate this [example](https://github.com/nlohmann/mutate_cpp)

**Comment by SimonHeybrock** [comment]
>     * Standard Test Data in a base fixture, with the expectation that developers write tests against all of these.

I think I would try to use a parametrized test with the base fixture. That way we avoid reliance on an "expectation".

The problem to solve is how we can then write a tests with reasonable assertions that work for the full range of inputs. One option I can think of is to just branch in the test, depending on properties of the input, e.g., `if (input.unit() != units::dimensionless) ASSERT_THROW(tested_function(input), ...)`

**Comment by OwenArnold** [comment]
> > ```
> > * Standard Test Data in a base fixture, with the expectation that developers write tests against all of these.
> > ```
> 
> I think I would try to use a parametrized test with the base fixture. That way we avoid reliance on an "expectation".

Yes, this was also my intention.

**Comment by SimonHeybrock** [comment]
A had tried to make a start in https://github.com/scipp/scipp/tree/testing, but got quickly stuck. I did not see a good way to get/create expected outputs. One option I considered was to define some sort of graph connecting a number of variables (or datasets), where the graph edges are function/algorithm calls. This could also work with multiple inputs. Essentially, a continuation of the round trip testing approach: `((a + b) * c - bc) / c == a`.
