### ISSUE TITLE
Attribute handling

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#514]
In binary operations (arithmetic or other) it is not clear how to handle attributes. It would be desireable to preserve all attributes, but in general they may be incompatible. A good example of this is the behavior that Mantid is implementing for merging the experiment logs, which contains some very complex logic and special case handling. See for example https://github.com/mantidproject/mantid/blob/8f04b4496d524b49de6ad995687ee768898b0562/Framework/API/src/Run.cpp#L29-L42:
```cpp
/// The number of log entries summed when adding a run
const int ADDABLES = 12;
/// The names of the log entries summed when adding two runs together
const std::string ADDABLE[ADDABLES] = {
    "tot_prtn_chrg",   "rawfrm",          "goodfrm",         "dur",
    "gd_prtn_chrg",    "uA.hour",         "monitor0_counts", "monitor1_counts",
    "monitor2_counts", "monitor3_counts", "monitor4_counts", "monitor5_counts"};
```
 This situation has to be avoided. It is not clear how, but the solution will likely include:

- Clear definition of the default behavior, followed by all functions in scipp.
  - This includes defining whether comparison should fail on mismatching attributes.
- User-control to override the default behavior.

An additional option may be to leverage the power of nested datasets. This option has been explored in https://github.com/scipp/scipp/blob/v0.0.1/test/Run_test.cpp. In principle this gave enough control to obtain all desired behavior, without bespoke code. Note that this depended on the removed behavior of concatenating iterables when adding the containing container, so this is not applicable 1:1 any more. Furthermore, this solution only worked for addition, but not for other operations.

**Comment by OwenArnold** [comment]
You raise a good point, and the Run/MergeRuns is a good example of trying to after-the-fact define behaviour for the logs.

I think that providing a classifier for the behaviour of the attribute at the point of definition would be good. That way we do NOT need to make downstream client-code aware of how the handling should happen - [bad example](https://github.com/mantidproject/mantid/blob/8f04b4496d524b49de6ad995687ee768898b0562/Framework/API/src/Run.cpp#L107) it could happen internally. 

I would rather that whatever mechanism was adopted for this was simple at the point of use from both the c++ side and python side, so declaring that an attribute was "addable".  Maybe of policy-based-class design would fit here. be possible to specify the behaviour. I get the impression that the actual range of behaviour that we would want would be limited based on [MergeRuns] (https://github.com/mantidproject/mantid/blob/master/docs/source/algorithms/MergeRuns-v1.rst) which would make this approach feasible.

**Comment by SimonHeybrock** [comment]
> I think that providing a classifier for the behaviour of the attribute at the point of definition would be good. That way we do NOT need to make downstream client-code aware of how the handling should happen - [bad example](https://github.com/mantidproject/mantid/blob/8f04b4496d524b49de6ad995687ee768898b0562/Framework/API/src/Run.cpp#L107) it could happen internally.

I am not so sure a generic definition of behavior is sufficient.
- Should every addition add "addable" attributes (I guess no?)?
- Should subtraction subtract "addable" attributes (Mantid does not do this, but isn't this inconsistent? Should it drop the attributes)?
- Similar questions for other operations.
- Similar problems for other attribute categories (e.g., time-series, which are not added but appended/concatenated, but again only if it makes sense)

> I would rather that whatever mechanism was adopted for this was simple at the point of use from both the c++ side and python side, so declaring that an attribute was "addable".

That would be nice, but I feel the situation is to complex for such a solution. One could argue that making things "simple at the point of use" the part of the problem of many things implemented in Mantid --- an attempt to "automatically" do the correct thing. This had led to a lot of special-case handling being added. Isn't it worth considering the opposite approach: Make things *explicit* at the point of use.

**Comment by OwenArnold** [comment]
Yes, there is some befit to pushing the handling right down to the point of use, I think this is quite a complex problem, and it might therefore be worth doing a detailed survey of what is handled in Mantid, and therefore how we would prefer to handle each use-case in scipp.

One additional problem is that NXLogs resulting in names for logs/attributes are created by the ECP and written to file/streamed - they can potentially change or be absent in the naming, or in the case of mantid might change type while keeping the same name. Therefore writing reliable functions "algorithms" that use these always has the potential to break due to upstream changes - infact some of the problems Neil and I had at V20 were related to exactly this in the LoadEventNexus code.

**Comment by SimonHeybrock** [comment]
Maybe a related decision (not part of `scipp` itself, but affecting what we will implement in `scipp`) is then whether we want to initially just store Mantid's `Run` in a dataset, or if we directly switch over to storing everything natively. If we do it natively we should be completely flexible in terms of naming and types. The problem of how algorithms can find specific logs with unknown name remains, of course.

**Comment by OwenArnold** [comment]
> Maybe a related decision (not part of `scipp` itself, but affecting what we will implement in `scipp`) is then whether we want to initially just store Mantid's `Run` in a dataset, or if we directly switch over to storing everything natively. If we do it natively we should be completely flexible in terms of naming and types. The problem of how algorithms can find specific logs with unknown name remains, of course.

In both cases we would have to go via Run given that we will still use the compatibility `load` from Mantid to create attributes. Whether there are other things from `Run` that are needed, i'm not sure, but we should also survey that.

**Comment by SimonHeybrock** [comment]
> In both cases we would have to go via Run given that we will still use the compatibility load from Mantid to create attributes.

Would it be hard to make a meta-data loader using `h5py` directly into `scipp`, avoiding some of the trouble you had recently with very strict naming requirements that Mantid imposes?

**Comment by OwenArnold** [comment]
> Would it be hard to make a meta-data loader using h5py directly into scipp, avoiding some of the trouble you had recently with very strict naming requirements that Mantid imposes?

I am coming to the conclusion that eventually scipp would need it's own loaders (much further down the line), or there should be some shared project to develop new ones, which properly follow the nexus format, don't have the facility fudges, and use modern h5 or NAPI libraries (which don't yet exist). I think the SNS computing group are considering this, I'll follow up with Pete on that.

Yes, it would in theory be simple to write a h5py script to create the attributes directly from `NXlogs`, but it's hard to see this part of the reading of the file in isolation. You would also want to read the data, geometry etc from the file.

**Comment by SimonHeybrock** [comment]
:+1: 

> Yes, it would in theory be simple to write a h5py script to create the attributes directly from NXlogs, but it's hard to see this part of the reading of the file in isolation. You would also want to read the data, geometry etc from the file.

Well, it can be loaded separately, then combined. `LoadEventNexus` does the same thing, calling child algorithms for loading the instrument, monitors, ...

**Comment by OwenArnold** [comment]
> Make things explicit at the point of use

I wonder if the correct thing to do is the push the decision of what to do with meta-data right down to the point of use. One option would be to keep separate attributes from each contributing operand unless the attributes matched exactly. This of course has a memory overhead, and it might not be possible to trace which input the attribute came from, but does allow the user/client code to have the full information to decide exactly what to do with the attributes/logs. 

I think this is somewhat half-baked, but I don't think we have considered this as an option.

**Comment by SimonHeybrock** [comment]
Well, it would involve renaming attributes if there are clashes, which does not sound like a good solution. Furthermore, it would not do things like accumulating monitor counts.

Maybe monitors should not be attributes if they are expected to be added, but normal data instead.

**Comment by OwenArnold** [comment]
> Well, it would involve renaming attributes if there are clashes, which does not sound like a good solution. Furthermore, it would not do things like accumulating monitor counts.

You don't necessarily need to rename. You could represent the attributes along an additional dimension. There would be additional complexity if the log entries were not the same length, but we can store sparse data.

> Maybe monitors should not be attributes if they are expected to be added, but normal data instead.

I think so, but I also see why they were originally considered as attributes. I think that could be partially a question that needs to be fed into Jon's standard layout question. For example if you had an experiment involving polarised neutrons, giving you (or the ability to) derive a variables for up and down state `A`, `B`, but the monitors counts were not filtered  `A` + `B` would give 2x monitor counts.

**Comment by OwenArnold** [comment]
I believe that the current implementation in scipp demonstrates our understanding of how this should work, namely attributes are dropped owing to the complexity of fully defining an automatic set of operations.

**Comment by SimonHeybrock** [comment]
Closing, since no generic solution was found. Plan for next steps in #1014.
