### ISSUE TITLE
Generic inexact comparisons

### ISSUE THREAD

**Issue by DanNixon** [scipp/scipp#519]
From https://github.com/scipp/scipp/pull/517#issuecomment-529470900:

> I was thinking of a generic implementation that would just let you do similar(dataset1, dataset2, tolerance=1e-12, allow_transpose=True, allow_broadcast=True), or something like that.

**Comment by SimonHeybrock** [comment]
Also for `Variable` and `DataArray`.

**Comment by SimonHeybrock** [comment]
Regarding implementation, I suggest to use `transform` to implement inexact comparison of variables.
- I suppose this only makes sense for floating-point types, other types can fall back to exact comparison, but with broadcast/transpose, which needs to be added by hand.
  - For "built-in" types we can still use `transform` to get an exact comparison but with broadcast/transpose.
  - Other types have low relevance for now, so just doing a normal `==` (ignoring broadcast/transpose) could be good enough for now.
- When using `transform` we automatically support broadcast and transpose. I think this is a good default, maybe we can ignore the other cases for now, until we have specific additional requirements.

**Comment by OwenArnold** [comment]
@DanNixon @SimonHeybrock I would be happy to pick this up unless either of you had a preference for this?

**Comment by SimonHeybrock** [comment]
Note that probably you don't need `transform`, but `accumulate_in_place`. There may be different ways to do this.
