### ISSUE TITLE
Operations between Variable/DataArray/Dataset and scalars

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#551]
We have a number of operators like `Variable &operator+=(const double value);`

- This should be templated, instead of just accepting double.
- Should be supported also for `DataArray` and `Dataset`
- ... and all relevant proxies.
- Python bindings.
- Can `template <class T>Variable &operator*=(const boost::units::quantity<T> &quantity)` be removed? If we have a more generic template that accepts any `T` this could become possible. Potentially the only thing to be done is to add `makeVariable` that accepts `boost::units::quantity` and splits it into value/unit parts to create the variable.
- The reverse operations `scalar <op> variable/dataset` should also be added.

**Comment by DanNixon** [comment]
I think this is pretty much done now. https://github.com/scipp/scipp/issues/585 describes the last requirement.
