### ISSUE TITLE
Operations between Dataset and Variable

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#552]
We have `DataArray &operator+=(const VariableConstProxy &other);` but the equivalents for `Dataset` (and its proxies) are missing.

- Add those.
- Same goes for non-in-place operators like `+` between `VariableConstProxy` and `DatasetConstProxy`/`Dataset`.
- Python bindings.

**Comment by DanNixon** [comment]
For in place operations with `Dataset` and `VariableConstProxy` I assume some variant of `apply_with_delay` would be needed (e.g. if for whatever reason you did `a += a["item"].data()`). Is there a sensible way to actually detect this?

**Comment by SimonHeybrock** [comment]
Correct. `VariableConstProxy` holds a pointer to the underlying variable (it is currently not accessible in the public API, but we could add a method `underlying()`, just as in `DataConstProxy`). Then just compare those, as in `apply_with_delay`.
