### ISSUE TITLE
Incorrect dtype with numpy floats

### ISSUE THREAD

**Issue by igudich** [scipp/scipp#571]
```python
import scipp as sp
import numpy as np

x = np.float32(0)
sp.Variable(x) 
```
gives
```
<scipp.Variable>          int64      [dimensionless]  ()  [0]
```

According the documentation python searches for the overload without conversion, the picks up the first for convertible type. As far as numpy types might be not the same as C++ types the overload for `double` or `float` is chosen dependently on the order of definition. @SimonHeybrock , any comments?

**Comment by SimonHeybrock** [comment]
I think we should support this correctly. Should also check for other, similar, cases in our python bindings.
