### ISSUE TITLE
`makeVariable` from a `boost::units::quantity`

### ISSUE THREAD

**Issue by DanNixon** [scipp/scipp#585]
See https://github.com/scipp/scipp/pull/576#discussion_r330522824

**Comment by SimonHeybrock** [comment]
It is not clear to me how this should work with the new "keyword argument" constructor/factory. I'll push it to the next release, which should give us time to develop a better understanding of how it would be used.

Maybe we need to add another keyword, `Quantity`? But actually this should be obvious from the type? Just add a normal constructor for `Variable`?

**Comment by igudich** [comment]
> It is not clear to me how this should work with the new "keyword argument" constructor/factory. I'll push it to the next release, which should give us time to develop a better understanding of how it would be used.
> 
> Maybe we need to add another keyword, `Quantity`? But actually this should be obvious from the type? Just add a normal constructor for `Variable`?

This is the special case and it seems not to be used frequently, also due to the very special argument type there shouldn't be any clashes with other constructors, so I would Just add the constructor.

**Comment by SimonHeybrock** [comment]
Will implement constructor (not `makeVariable`), needed for other cleanup.
