### ISSUE TITLE
Issues with variables containing PyObject

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#604]
#605 supports storing arbitrary Python object in a `Variable`. The consequence is that `__copy__` causes a shallow copy (contrary to all other dtypes scipp supports). Furthermore, we do not have `__deepcopy__`.

- Should we always make a deep copy, even if `__copy__` is called? This would be consistent with existing behavior.
- If not, we have to add `__deepcopy__` properly.

**Comment by nvaytet** [comment]
I can see that it would be a little strange if we only had shallow copies for the python objects, and deep copies for everything else. So in that sense I would intuitively think deep copies for python objects would be the way to go.
However, as you pointed out, it seems `__copy__` is commonly used for shallow copies (https://docs.python.org/2/library/copy.html) and we should be using `__deepcopy__`.
I guess the proper way of doing things would be to have `__deepcopy__` everywhere.

**Comment by SimonHeybrock** [comment]
For this and support of other operations like `operator==` I think we may want to wrap `pybind11::object` in a `scipp::object`. This would handle proper (deep) copies and provide (deep) comparison.

**Comment by SimonHeybrock** [comment]
More urgent issue: Apparently the missing comparison prevents insertion with "matching" attributes, so currently https://scipp.readthedocs.io/en/latest/tutorials/neutron-data.html#Loading-Nexus-files does not work anymore.
