### ISSUE TITLE
Python dependency management

### ISSUE THREAD

**Issue by DanNixon** [scipp/scipp#611]
Remove the duplication of Python requirements.

**Comment by SimonHeybrock** [comment]
@DanNixon You said this is not relevant anymore for this milestone, should we keep this open, or close entirely?

**Comment by DanNixon** [comment]
It would be nice to improve this but we're not at the point of what we already do being a significant problem. So probably keep it open for now.

**Comment by DanNixon** [comment]
Has been done by moving to Conda as main means of distribution and CI.
