### ISSUE TITLE
Make plotly plotting work with xarray

### ISSUE THREAD

**Issue by nvaytet** [scipp/scipp#630]
One way we could kick-start a collaboration with the `xarray` guys would be to extend our plotly plotting to work with `xarray` `Dataset`s, as they currently only have `matplotlib` plotting.
This might boost interest for `scipp` if they find it useful.

As an aside, should the plotting then become a separate project in the `scipp` organisation? So that one can use the plotting without installing the whole `scipp` library?

**Comment by SimonHeybrock** [comment]
plotly support has been dropped.
