### ISSUE TITLE
Add keyword arguments and docstrings for free functions

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#652]
Documentation here: https://scipp.readthedocs.io/en/latest/python-reference/api.html#free-functions is not really useful, since it is unclear what functions parameters mean. This has caused confusion with early users.

Better way, see https://scipp.readthedocs.io/en/latest/generated/scipp.neutron.diffraction.convert_with_calibration.html#scipp.neutron.diffraction.convert_with_calibration.

Part of the task is to find out why overloaded functions render badly: https://scipp.readthedocs.io/en/latest/generated/scipp.neutron.convert.html#scipp.neutron.convert. Sphinx does not produce proper headings for parameters, etc.

**Comment by DanNixon** [comment]
> Documentation here: scipp.readthedocs.io/en/latest/python-reference/api.html#free-functions is not really useful, since it is unclear what functions parameters mean. This has caused confusion with early users.

What would be an improvement here?
If you click on a function you do get a full description complete with parameters (e.g. https://scipp.readthedocs.io/en/latest/generated/scipp.abs.html#scipp.abs).
Is it not clear this can be clicked?
Should the complete function descriptions all be on a single page?

**Comment by SimonHeybrock** [comment]
Several:
- Overloaded functions render badly as you say. I tried to fix it, but could not find what the issue was. Is it maybe the template of our sphinx plugin? Would I would prefer is to just have a single documentation for all overloads (the user does not need to know there are overloads, as long as all the keyword args are documented?).
- Function parameters are not documented and named in many cases (they just show `arg0`, `arg1`, ...). We should give named params everywhere and document them, as in the example.

**Comment by DanNixon** [comment]
>     * Overloaded functions render badly as you say. I tried to fix it, but could not find what the issue was. Is it maybe the template of our sphinx plugin? Would I would prefer is to just have a single documentation for all overloads (the user does not need to know there are overloads, as long as all the keyword args are documented?).

I tried to look into this but can't even find the templates that are in use when rendering functions (the files that the [documentation](https://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html#customizing-templates) mentions do not exist on my installation).

Perhaps having a Python function to wrap the exported overloads would allow this to work, but this feels like a hacky solution.

I think as long as the missing argument documentation is added it may not be worth spending too much time on this.

**Comment by DanNixon** [comment]
In fact I'm not even sure how to document the arguments, `py::arg()` does not seem to work with overloaded functions.

**Comment by SimonHeybrock** [comment]
Are you saying that sphinx does not pick up the keyword arguments when overloaded? I have previously used `py::arg` with overloaded functions and had no trouble with compilation.

**Comment by DanNixon** [comment]
It compiles fine, but the documentation still lists them as "arg0", "arg1", etc.

**Comment by SimonHeybrock** [comment]
You also need to add the `param` to the docstring.

**Comment by DanNixon** [comment]
Is it expected that I have to remove `docs/generated` every time I change the Python exports? Because that's what the issue was.

**Comment by SimonHeybrock** [comment]
I had trouble with that as well. There are some sphinx flags to rebuild more, but in the end I still had to remove some things by hand. I have also found that `.buildinfo` `.doctrees` in the sphinx build folder can make trouble, but that may just be my misunderstanding of how sphinx works.
