### ISSUE TITLE
Consider making LTO configuration dependent

### ISSUE THREAD

**Issue by OwenArnold** [scipp/scipp#654]
Limited symbol information for debugging purposes with LTO enabled. Consider using CMAKE property https://cmake.org/cmake/help/v3.6/prop_tgt/INTERPROCEDURAL_OPTIMIZATION_CONFIG.html instead.

Also i've read reports LTO in debug mode is reportedly slow (though I haven't measured)

**Comment by SimonHeybrock** [comment]
https://scipp.github.io/developer/getting-started.html
