### ISSUE TITLE
Bring back the waterfall plots?

### ISSUE THREAD

**Issue by nvaytet** [scipp/scipp#683]
This version of waterfall plots, where the lines are filled with white underneath looks quite nice.
![Screenshot at 2019-11-14 15-06-00](https://user-images.githubusercontent.com/39047984/68864037-bbbf1000-06f0-11ea-806c-61fa25bc722e.png)

From: https://dawnsci.org/using-dawn/videos/

**Comment by SimonHeybrock** [comment]
If you don't mind, I'll close this until we have concrete requirements, to avoid having too many open tasks that are unlikely to be implemented (without concrete requirements).
