### ISSUE TITLE
Missing support for plotting x error bars

### ISSUE THREAD

**Issue by nvaytet** [scipp/scipp#734]
Currently, only variances along the y direction are plotted for 1D data.
![Screenshot at 2019-12-10 11-53-57](https://user-images.githubusercontent.com/39047984/70523653-cf209800-1b43-11ea-8f24-7b2eca8bef9a.png)

We also need to show error bars in the x direction if the coordinate has variances.

**Comment by SimonHeybrock** [comment]
Are X errors conceptually the same as errors on the coordinate?

**Comment by SimonHeybrock** [comment]
Closing until we have a concrete requirement.
