### ISSUE TITLE
to_html fails for sparse items without data

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#745]
Sparse data can be "coord-only". `to_html` causes a `RuntimeError` in this case.

Maybe a good way to display sparse coords and labels would be in the same way as attributes, i.e., a button to extend the subsection?

**Comment by dtasev** [comment]
> Maybe a good way to display sparse coords and labels would be in the same way as attributes, i.e., a button to extend the subsection?

I agree, currently the attribute subsection doesn't have any styling, and we might want some for coords/labels, but that can be a follow-up issue
