### ISSUE TITLE
Python testing during conda packaging

### ISSUE THREAD

**Issue by OwenArnold** [scipp/scipp#756]
During conda packaging, we do not build `all-tests` targets to save on build time. We should easily be able to execute the python tests though as they should not require the generation of any new targets.

I think this could simply be done [here](https://github.com/scipp/scipp/blob/master/conda/build.sh#L23) and would also need to be done in the `bld.bat` file between `cmake --build` and the `move`.

I think this would be a good sanity check that the master branch is not somehow carrying broken runtime prior to anaconda deployment.

**Comment by OwenArnold** [comment]
@DanNixon

**Comment by DanNixon** [comment]
Sounds like a good idea.

I believe Coda has a separate test stage/target that should ideally be sued for this.
I haven't done this before so an not sure of the specifics though (i.e. can we still use the same build artifacts? if not we just end up increasing package build time).

**Comment by OwenArnold** [comment]
@DanNixon I think we would need to check:

* Can we still use the same build artefacts
* Can we ensure that deployment fails if testing fails
* Can we see proper test outputs so that fixes can easily be identified and made

I think the python test times should be quick enough not to be of any concern.
