### ISSUE TITLE
Config / settings file

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#758]
Scipp has some options for customization. Currently this is mainly plotting styles. To make this persistent we need some sort of (cross platform) config-file mechanism, e.g., for storing things in `~/.scipp/` on Linux.

Probably this is only required on the Python side?

**Comment by DanNixon** [comment]
> Probably this is only required on the Python side?

I agree. I can't think of a valid use case for such persistent storage outside of plotting defaults.

Rather having core functionality depend on local configuration would be a reproducibility problem in my opinion.

**Comment by nvaytet** [comment]
A default file, e.g. `~/.scipp/config` could be created when the `scipp` module is first imported.

For instance, in `scipp`'s `__init__`, you could check if a `~/.scipp/config` file exists. If it does, load the parameters from it, if it doesn't, create one with the defaults.
When parameters are loaded from the config files, if a particular parameter is not found in the config file (the used might have deleted it), then fall back to the defaults.

The default file would be https://github.com/scipp/scipp/blob/master/python/src/scipp/config.py
