### ISSUE TITLE
Units to LaTeX string

### ISSUE THREAD

**Issue by dtasev** [scipp/scipp#784]
Units like `m / s` are currently displayed in plaintext `m s^-1`. It would be nice if they were instead formatted as LaTeX, this can then be used in the `_repr_html_` for the unit representation.

To achieve this the string returned from the unit string representation (or a new method, `to_latex`?) needs to format the fractions in one of the following ways:
- wrap exponent in `{}`: `m s^-1` should become `m s^{-1}`
- wrap in a `\frac`: `m s^-1` should become `\frac{m}{s}`

**Comment by nvaytet** [comment]
It seems that unfortunately, `boost` units does not support LaTeX output.
We may be able to have this if we eventually move to another (runtime) units library.
For instance, `pint` (https://pint.readthedocs.io/en/stable/) supports LaTeX output.

**Comment by SimonHeybrock** [comment]
I would really like to move to another unit package. There seems to be very little on the C++ side. `pint` looks good. What would need to change in scipp to be able to use it?

1. Make `Unit` an abstract class that can be implemented based on libraries other than `boost::units`. This will add some most likely irrelevant overhead from virtual function calls, and also increase the memory footprint of variables (in a probably minor way).
2. Add `PyObjectUnit` inheriting `Unit`. This would hold a `PyObject` and forward all the operators to the Python methods of these objects. This part brings a major cost: Every call to Python needs to happen under the GIL, so *every* operation scipp does with variables would temporarily re-acquire the GIL.

**Comment by SimonHeybrock** [comment]
For trying this out, it might be even better to do this without the runtime-polymorphism. We can just switch out `Unit` at compile time, i.e., we can still chose the `boost::units`-based `Unit` without the extra overhead.

**Comment by SimonHeybrock** [comment]
Actually, there are quite a few more problems:
- We are using boost quantities in some places for physical constants. We would need a way of converting those.
- We have `constexpr` units such as `scipp::units::m`, which would need to work in a different way.

**Comment by jl-wynen** [comment]
Tried a basic implementation. The following gets Jupyter to format the unit using LaTeX:
```python
def repr_latex(u):
    s = str(u)
    s = s.replace('*', r' \cdot ')
    s = re.compile(r'(\w+)/(\w+)').sub(r'\\frac{\1}{\2}', s)
    # more replacements can be added
    return rf'$\displaystyle {s}$'

sc.Unit._repr_latex_ = repr_latex
sc.Unit._repr_html_ = None
```
- It works well for a number of basic units like `m`, `m/s`, `m^2/s`. 
- It fails and produces the same as `str(u)` for more complex cases like `eV/[c]` (could be done by improving the regex.
- It produces ugly results for units that are words like `counts` or `CXCUN[1]` (arbitrary unit).
- It produces **incorrect** results if the bracketing is more complicated as in `m/s^2` or `K/m/s`.

Especially the last point indicates that a proper implementation would require parsing or at least tokenising the unit string to properly group pieces and put braces around them.

While I don't think this is particularly complicated to do (the syntax of units that LLNL/Units produces is pretty simple), it is a bunch of extra code with, IMHO, little added value.

Opinions?

**Comment by SimonHeybrock** [comment]
Not sure how heavy this is, but could `sympy` help with this?

**Comment by jl-wynen** [comment]
Probably, if it can format as LaTeX. But I would add it as a dependency just for this purpose.
