### ISSUE TITLE
Test _repr_html_

### ISSUE THREAD

**Issue by dtasev** [scipp/scipp#787]
Add tests for `_repr_html_` that check it executes correctly for all inputs and data combinations. 

Investigate if it's possible to test the presentation without being overly sensitive to changes. 
- Use BeautifulSoup to parse the HTML and find the relevant tags - this will make it easy to test if e.g. `"[bin-edges]"` is present in the right tag, and check the local structure, but not care about if we move the columns of dimensions from 2nd to 5th.

**Comment by SimonHeybrock** [comment]
This has been done already.
