### ISSUE TITLE
Imaging Workflow with Scipp

### ISSUE THREAD

**Issue by OwenArnold** [scipp/scipp#788]
Use scipp to do [this](https://git.esss.dk/testbeamline/gp2/blob/master/reduce.py) and store as jupyter notebook.

The work for this, and indeed this issue and other outputs (with the exception of WFM, which might well live in scipp.neutron) should be done in the neutron repository.

* This can largely be done now with recent additions such as groupby
* Has current equivalent in Mantid, so verification easy.
* Allows us to compare scipp syntactically to Mantid equivalent 
* This may serve as a useful benchmark for future performance optimisations
* Relates to ESS instruments that are in the first cohort

**Comment by SimonHeybrock** [comment]
I believe a lot of this has been completed. Also, it is not part of scipp right now, closing.
