### ISSUE TITLE
Detector IDs have inconsistent dtype

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#801]
Apparently detector IDs created using the normal converters (stored in the `detector_info` labels) have a different dtype than those created in `neutron.diffraction.load_calibration`. Both should be `int32`, since this is what Mantid uses.

**Comment by OwenArnold** [comment]
I suspect the difference comes in here https://github.com/mantidproject/mantid/blob/master/Framework/PythonInterface/mantid/geometry/src/Exports/DetectorInfo.cpp#L117 (int64_t) as then called in `make_detector_info` and https://github.com/scipp/scipp/blob/master/python/src/scipp/neutron/diffraction/load.py#L69-L71 so fix should be easy. Note that https://github.com/scipp/scipp/blob/master/python/src/scipp/neutron/diffraction/load.py#L12-L85 could use some minor refactoring too.

**Comment by celinedurniak** [comment]
Please see below an example reproducing the error (the input files are ORNL SampleData from Mantid example)
![Screen Shot 2020-01-09 at 18 22 15](https://user-images.githubusercontent.com/7889724/72089798-fd44f380-330c-11ea-8692-640e49ea9d3c.png)
