### ISSUE TITLE
Optimized histogram implementation for logarithmic bins

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#813]
`histogram` has previously been "optimized" using a special branch for constant-sized bins, which gave a huge performance boost over the default implementation. This was possible since we can directly *compute* the target bin without iteration over bin edges.

Implement a similar branch for logarithmic bins, e.g., as created by `numpy.geomspace`.

**Comment by nvaytet** [comment]
Optimization for arbitrary (=non-regularly spaced) bins could also be achieved by overlaying a set of high-resolution regularly spaced bins that represent a mapping from input value to arbitrary bin number. Storing this mapping should not take too much memory.

Some special handling will probabably be needed when arbitrary bin boundaries fall in the middle of a regular bin.

**Comment by SimonHeybrock** [comment]
@nvaytet Should we close this for now, given that it proved to be more difficult than expected?

**Comment by nvaytet** [comment]
I don't mind just leaving it open, so that we don't forget about it.
See initial work done in https://github.com/scipp/scipp/tree/log_histogram

**Comment by SimonHeybrock** [comment]
:+1: I'll just remove it from the milestone then.

**Comment by SimonHeybrock** [comment]
Note that `sc.bin` would benefit from the same optimization.
