### ISSUE TITLE
Improved multiplication/division of sparse data with histogram

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#816]
- Support for non-constant bin widths (currently only constant-width bins are implemented).
- ~Optimization for logarithmic bins (see also #813).~ (proven to be too difficult in #813).

**Comment by nvaytet** [comment]
@SimonHeybrock will the implementation for this depend on what happens with #949 ?

**Comment by SimonHeybrock** [comment]
No, this should be largely unaffected.

**Comment by SimonHeybrock** [comment]
Need this for event filtering support, will solve two applications at once.

**Comment by SimonHeybrock** [comment]
Fixed in #1048.
