### ISSUE TITLE
`groupby` with Variable as group

### ISSUE THREAD

**Issue by dtasev** [scipp/scipp#823]
Currently `groupby` only takes in a string and looks up the grouping variable from a dataset's labels. 

A solution is adding `groupby` overload that takes in a `Variable` as the grouping and produces a `Variable`.

------------

Operation on dataset proxies is cumbersome, as it needs to be worked around:
```
# makes the position a DataConstProxy otherwise groupby won't take it
stitched["position"] = stitched.labels["position"]
dm1d = sc.groupby(stitched["position"], "detector_mapping", Dim.Row)
position = dm1d.mean(Dim.Spectrum)

# can't do stitched.labels["position"] = position because Labels won't take a DataArray
# also can't do stitched.labels["position"] = sc.Variable(position) because then sc.convert 
# thinks stitched.labels["position"] is dimensionless (as it's actually still a DataArray)
pos = np.zeros((position.shape[0], 3))
for i, val in enumerate(position .values):
    pos[i, :] = val

# finally add it back!
stitched.labels["position"] = sc.Variable(position .dims, pos, unit=sc.units.m, dtype=position.dtype)
```
(Example from docs/tutorials/scipp-imaging-2D.ipynb)

should just be 
```
det_map = stitched.labels["detector_mapping"]
dm1d = sc.groupby(stitched.labels["position"], det_map, Dim.Row)
stitched.labels["position"] = dm1d.mean(Dim.Spectrum)
```

**Comment by SimonHeybrock** [comment]
The actual task is to add overloads that accepts a `VariableConstProxy` as `group` parameter, essentially splitting the existing overloads on the C++ side into a wrapper function and one calling the actual code.

**Comment by rozyczko** [comment]
This has been merged so probably needs closing?

**Comment by SimonHeybrock** [comment]
Yes, see #1117
