### ISSUE TITLE
Implement transpose

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#847]
In most cases there is little need for an explicit `transpose` call in scipp, since dimension label matching is sufficient.

There are two cases where explicit transpose is useful:

1. Users want to access data as a `numpy` array and need a specific order from `var.values`.
2. For performance reasons, if subsequent operations run much faster on transposed data.

The implementation should return a *view* (matching the numpy and xarray behavior). If an actual transpose of the underlying array of elements is required, users should call `copy` on the returned view.

- [x] Transpose for variables.
- [ ] Transpose for data arrays.

See also http://xarray.pydata.org/en/stable/generated/xarray.DataArray.transpose.html and http://xarray.pydata.org/en/stable/generated/xarray.Dataset.transpose.html.

**Comment by SimonHeybrock** [comment]
Transpose for variables in #886. It is not clear how to handle data arrays yet.

**Comment by SimonHeybrock** [comment]
Data arrays can be handled based on #905.

**Comment by SimonHeybrock** [comment]
This should be really easy based on the new buffer sharing approach.

**Comment by jl-wynen** [comment]
Tried it and the implementation would be simple. But there are conceptual problems.

What do we do with multi dimensional metadata? Do we transpose it as well?
What if the metadata has fewer dims than the data, e.g. a data Variable with dims x, y, z and a coord with dims x, y?

The problem with coords is that in contrast to the rest of scipp, the storage order matters:
```.py
a = sc.DataArray(sc.fold(sc.arange('x', 6), 'x', {'x':2, 'y':3}), 
                            coords={'x': sc.fold(sc.arange('x', 6), 'x', {'x': 2, 'y': 3}),
                                          'y': sc.arange('y', 3)})
b = a.copy(deep=True)
b.coords['x'] = sc.transpose(b.coords['x'], ['y', 'x'])
a + b
```
->
```
scipp._scipp.core.CoordError: Mismatch in coordinate 'x', expected
(x: 2, y: 3)      int64  [dimensionless]  [0, 1, ..., 4, 5], got
(y: 3, x: 2)      int64  [dimensionless]  [0, 3, ..., 2, 5]
```

**Comment by jl-wynen** [comment]
This was my first thought, too. In principle, this makes sense if we regard it as operating on the primary data like transforms. And one likely needs fine control over the components in cases where transposition matters. So operating on just the data would make sense. But does that cover typical use cases? Or would it make more sense to not provide a function at all as that communicates that the individual components need to be handled separately.

**Comment by SimonHeybrock** [comment]
I feel 2d coords are kind of a special case and we can worry about it later. Ater least in the neutron context I cannot think of a reason to transpose in this case.
