### ISSUE TITLE
Enable yapf on Travis

### ISSUE THREAD

**Issue by DanNixon** [scipp/scipp#848]
I'd like to suggest we move to YAPF instead of flake8 for Python formatting.

YAPF is much closer to cmake-format so can be used to format code as it is being written rather than having to manually fix issues when the CI fails.

Both can use a pep8-ish format so no large scale changes would be needed (@OwenArnold did notice YAPF formats things flake8 didn't care about, but I'm not sure how much was actually changed).

**Comment by SimonHeybrock** [comment]
I think several of us are already using `yapf` for formatting. Does it support the same level of checks as `flake8`, i.e., is it equivalent in use of CI?

**Comment by DanNixon** [comment]
> Does it support the same level of checks as flake8, i.e., is it equivalent in use for CI?

Actually, no. It is only concerned with formatting.
In that case I suggest we run both on CI, otherwise we end up with those that do format including changes that are unrelated in their commits when others do not format.

**Comment by OwenArnold** [comment]
We now have a yapf settings file too. I have noticed that it seemed to make format changes to areas I don't think were necessary, though I haven't performed any investigation on this.

**Comment by nvaytet** [comment]
> > Does it support the same level of checks as flake8, i.e., is it equivalent in use for CI?
> 
> Actually, no. It is only concerned with formatting.
> In that case I suggest we run both on CI, otherwise we end up with those that do format including changes that are unrelated in their commits when others do not format.

So you'd run `yapf` for the formatting and `flake8` to check for syntax errors, unused variables etc?

**Comment by DanNixon** [comment]
> So you'd run `yapf` for the formatting and `flake8` to check for syntax errors, unused variables etc?

Yes.
