### ISSUE TITLE
Stride support for positional indexing

### ISSUE THREAD

**Issue by nvaytet** [scipp/scipp#860]
It is currnetly not possible to slice with steps, like in numpy, e.g. `var[Dim.Tof, 0:50:2]`
This fails with "Step must be 1".

@SimonHeybrock says:

Implementing this should be possible by adding a fake dimension, reshaping to a 2d array and then slice according to the starting point of the range.

`VariableView` knows the dims of the parent, and the "target" iteration dims. For example parent may be `(Dim.X, 10)`. To introduce stride support, pretend the parent is `([Dim.X, Dim.Dummy], [10/stride, stride]` and iterate as if slicing in `Dim.Dummy`.

We may need to add some helper methods to actually be able to support setup of the VariableView in the way we need it.

**Comment by SimonHeybrock** [comment]
After #1844 is done this can be implemented easily.
