### ISSUE TITLE
Add `astype` for data arrays

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#910]
This was previously added for variables. How should this behave for data arrays --- convert also coords, or keep them? Maybe worth checking what http://xarray.pydata.org/en/stable/generated/xarray.DataArray.astype.html does.

I suppose keeping coords untouched is maybe the best and most obvious choice, and keeps things simple (separation of concerns)?

For now this will be required in particular for benchmarking purposes, i.e., for running workflows in different precision.

**Comment by DanNixon** [comment]
> convert also coords, or keep them? Maybe worth checking what http://xarray.pydata.org/en/stable/generated/xarray.DataArray.astype.html does.

xarray seems to preserve coords, from what I can tell only the data itself is touched.
