### ISSUE TITLE
Proposal: Natural API for event data

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#949]
## Introduction

This is a proposal, or rather a partially incomplete collection of thoughts for a better API for event data (aka sparse data). As most developers of scipp are aware, handling sparse data can be cumbersome. That alone may be reason to consider improvements. It was however the realization that it is not just cumbersome but also unnatural, unintuitive, and forcing knowledge of and interaction with aspects of the underlying data representation that led to this new set of ideas.

In short, I propose to always couple event data to a dense axis (coord). The axis provides means of interacting with the event data in a way similar to how we deal with dense data. This is conceptually similar to the interface Mantid's `MDEventWorkspace` or rather the base class of `MatrixWorkspace` and MD-workspaces, `MDGeometry` (see also the delated `IMDDimension`).

Note that this is not proposing to use a similar data layout, but it may provide a pathway to also support the equivalent of `MDEventWorkspace` in scipp with a unified interface (`MDEventWorkspace` is the only major Mantid Workspace not support by scipp yet, see https://scipp.readthedocs.io/en/latest/scipp-neutron/from-mantid-to-scipp.html#Workspaces).

### Related issues and discussions:
- #424, an old attempt to come up with a better representation.
- #351, which discusses sorting. Just for illustrating potential boundary conditions, this proposal does not address the underlying problems.
- #935 (Event filtering based on groupby) can be considered a precursor to this, bringing some of the ideas but requiring extra steps due to lack of dense coord counterparts.
- #921 interface issues around `shape`.
- Alignment promise of `Dataset` vs. sparse data (which breaks the alignment guarantees of coords)
- Issues with `DataArray`, which cannot have dense coord together with sparse.
- Verbose and error-prone iteration of data items potential sparse coords and labels. Examples easily visible in several places, e.g., https://github.com/scipp/scipp/blob/bc2f7fc0fa93fdd8e97720fc20b733cb91674f7f/core/dataset.cpp#L557-L575.
- Separate error prone handling of dense coords and sparse coords for every item, e.g., https://github.com/scipp/scipp/blob/bc2f7fc0fa93fdd8e97720fc20b733cb91674f7f/neutron/convert.cpp#L38-L48 and related bugs #842 and #865.

## Proposal

The current API is dictated by the data layout and data content (primarily TOF and pulse-time). Most users (including myself) do not care (directly) about layout or content. Explaining a complicated API that gives access to something they do not care about just to control what they *do* care about is bound to run into problems. Even training experienced developers to deal with this kind of data tends to take longer than desirable.

To remedy this, I propose the following:
1. All coords of a data array or dataset have "dense" values. There are two cases:
   - Normal dense coords as we have them now.
   - New virtual coords, essentially a dense coord with an additional "event store". Example:
     ```python
     data.coords['tof'].values # TOF bins
     data.coords['tof'].events # sparse variable (or similar) containing TOFs
     ```
2. The dense component of virtual coords provides natural slicing functionality and can be used for filtering such as by `groupby`.
3. The *data* component of events has two levels:
   - `data['sample']` is the data overlayed with the virtual coords and dimensions.
   - `data['sample'].data` is the underlying event data
   ```python
   data['sample'].values # what is this? should not do automatic on-the-fly histogram?
   ```

## Examples of the possible new API

Details may vary, the gist of all the following examples is that the coords and slicing we know from dense data should be supported also when backed by event data.

#### Extract TOF range
```python
data = data['tof', 10:20].copy()
```

#### Filter by pulse time
```python
data = data['pulse_time', 10:20].copy()
```

#### Filter by sample environment parameter
```python
data.coords['temperature'] = sc.rebin(data.attrs['sample_temperature'], data.coords['pulse_time'])
data = data.groupby('temperature', bins=np.linspace(100, 200, num=10))
```

#### Histogram
```python
hist = sc.histogram(data) # all axes are known and histogrammed
hist = sc.histogram(data['tof', 10:20]) # only subrange
events = sc.histogram(data, 'pulse_time') # only histogram 'pulse_time', result is still event data but this dimension is now dense (internally, event lists are split, as for pixels)
```

#### Operations such as unit conversions
```python
data.coords['tof'] *= conversion_factor
```
If broadcast is needed (as for `neutron.convert`):
```cpp
data.setCoord('tof', data.extractCoord('tof') * conversion_factor)
```

#### Operations between event data and histograms
```python
events2 = events / normalization # compares dense part of the coords
```

## Details

- Probably "sparse dim" should no longer be known to scipp. This is not necessary, we just have a variable containing lists as elements.
- `d['a'].dims` and `d['a'].data.dims` are different entities now:
  - The latter is the variable containing the events. Its `dims` are just the dense dimensions.
  - The former is the variable containing the events, packaged and overlayed with coordinates. The dimensions are *virtual* and contain, e.g., `tof` and `pulse_times`.
- Operations using the new "high level" interface use `d['a']` and do not directly handle the events, this is all done internally. `d['a'].data` provides access to the event data.
- Event coords are accessed, e.g., as `d.coords['tof'].events['a']`. This is a variable containing event lists.
- Slicing coord should slice *bins*, not *edges* (unlike now). Could solve messy code in dataset shape logic.
  - Note implications: Modifying coord slices needs to be aware of overlap.

### Interfaces

```python
d.coords['tof'] # Coord
d.coords['tof'].data # Variable
d.coords['tof'].values # values of data
d.coords['tof'].is_edges
d.coords['tof'].events # Variable, or map of variables
d.coords['tof']['tof', 10:20] # slice bins, contains 11 edges
d.coords['tof'].data['tof', 10:20] # slice edges, contains 10 edges
```

## Implementation steps

- Implement `class Coord`, containing dense `Variable` and map of (or single, in case of `DataArray`) events variables.
- No slicing support, this keeps things simple.
- Map coords into dataset items (similar to current mechanism).
- Later: Slicing and groupby aka event-filtering.

## Open questions

- Implementation in general.
- Combining multiple variables with events in a dataset. Should the variable contain a dict mapping from item name to events, similar to dataset mapping from item name to data?
- Slicing in virtual dimensions. Can this be done without coping? If not, can we or do we need to support in-place operations?
- Slicing in virtual dimension: Slicing one dim affects the other, can this be handled on the variable level without linking to other coords?
- It may now be possible and advantageous to prevent coord modifications via dataset items.
- How to represent the "data" part of events? It feels like it must somehow be different from the coords, but it is not clear how. Can we avoid large data that is just "1", i.e., broadcast?

**Comment by OwenArnold** [comment]
Looks like a good proposal, I certainly like the simplicity of the API. We should probably discuss in person, but a few thoughts.

```
data.coords['tof'].values # TOF bins
data.coords['tof'].events # sparse variable (or similar) containing TOFs
```
* How do we deal with sorting events? API implies events are ready sorted by TOF, but I think you're already considering that problem in (3) above.
* Access is specific for coordinates, we therefore need to think about adding such sparse information.
* We associate counts with TOF, but we may want to do the same with pulse times etc for filtering. you could do this with an additional virtual dimension maybe? but you also have to consider not wanting pulse times, or only wanting pulse times.

**Comment by SimonHeybrock** [comment]
>     * How do we deal with sorting events? API implies events are ready sorted by TOF, but I think you're already considering that problem in (3) above.

No, events a priori are not sorted. This is impossible if there is more than one axis, such as `tof` and `pulse_time`.

>     * Access is specific for coordinates, we therefore need to think about adding such sparse information.

I am not sure I understand the question. I will later update the original proposal with some more details, I hope that will clarify.

>     * We associate counts with TOF, but we may want to do the same with pulse times etc for filtering. you could do this with an additional virtual dimension maybe? but you also have to consider not wanting pulse times, or only wanting pulse times.

Indeed, this is the plan, see above in particular the second example ("Filter by pulse time").

**Comment by SimonHeybrock** [comment]
Closing, since agreed to move forward. Subtasks tracked in other issues.
