### ISSUE TITLE
Azure pipeline migration

### ISSUE THREAD

**Issue by DanNixon** [scipp/scipp#952]
- [x] Add basic Azure pipelines to https://github.com/scipp/scipp
- [x] Docker image build and publish on `master`
- [x] cmake-format on `master` and `pull_requests`
- [x] Move static analysis to common location ([see docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#insert-a-template))
- [x] Documentation build on `master` and `pull_request` (publish on `master`)
- ~Caching~
- [x] Check Copyright year is up to date
- [x] Finalise documentation versioning strategy
- ~Restrict jobs based on paths changed?~ Can be done by developers using `[ci skip]` in commit messages as required, not worth the time to try and automate.
- [x] Deployment pipeline (#990)
- ~Sanitizer builds on `master`~ Too expensive for MS hosted CI.

**Comment by SimonHeybrock** [comment]
Should documentation builds also run on PRs? We have repeatedly run into trouble with broken docs due to the lack of that.

**Comment by DanNixon** [comment]
> Should documentation builds also run on PRs? We have repeatedly run into trouble with broken docs due to the lack of that.

Yes, good point.

**Comment by DanNixon** [comment]
Due to several Conda issues, it looks pretty much impossible to get `ccache` to work inside a Conda build.

**Comment by DanNixon** [comment]
@SimonHeybrock One other option to have sanitizers as part of the CI would be to host a on premise worker at the DMSC.
This has the advantage of being able to use as powerful machine as is needed, while keeping Azure orchestration and reporting.

**Comment by SimonHeybrock** [comment]
@DanNixon Is a "premise worker" something that get integrated into the Azure thing, similar to a Jenkins worker we have for Mantid?

**Comment by DanNixon** [comment]
> @DanNixon Is a "premise worker" something that get integrated into the Azure thing, similar to a Jenkins worker we have for Mantid?

Yes, exactly the same concept.

**Comment by SimonHeybrock** [comment]
I will talk to DST to figure out if that could be provided, based on their security guidelines.
