### ISSUE TITLE
Mark dimension and non-dimension coordinates differently in sc.show and sc.table

### ISSUE THREAD

**Issue by nvaytet** [scipp/scipp#980]
Currently, dimension and non-dimension coordinates show up the same in `show` and `table`:
![Screenshot at 2020-02-21 10-40-36](https://user-images.githubusercontent.com/39047984/75022983-51f49600-5497-11ea-9b5f-5be3a28f65c8.png)
![Screenshot at 2020-02-21 10-42-04](https://user-images.githubusercontent.com/39047984/75022997-55881d00-5497-11ea-9169-ed4379544b3e.png)

Non-dimension coordinates (formelly known as labels) used to show up in a different color:
![Screenshot at 2020-02-21 10-47-28](https://user-images.githubusercontent.com/39047984/75023124-92541400-5497-11ea-93f4-87a6721832cb.png)

We could either do the same again, or use bold type (as in the html `__repr__`) to make the dimension coordinates.

**Comment by SimonHeybrock** [comment]
Differences between dimension- and non-dimension coords are marginal. This is not a priority and probably has little utility.
