### ISSUE TITLE
Fix table_html tests

### ISSUE THREAD

**Issue by nvaytet** [scipp/scipp#993]
- The `test_sparse` in `test_to_html_dataarray.py` has been disabled because it will fail on Windows after #977 is merged.

- The `test_sparse_does_not_repeat_dense_coords` in `test_to_html_dataset.py` is also broken (on all platforms) after the change of API in #977 : it gives a `Length mismatch on insertion` error.

These issues needs to be resolved.

**Comment by SimonHeybrock** [comment]
Thoughts from dev meeting:

- Should we replace this by manual testing, e.g., loop through all docs pages before each release?
  - Need a reference (e.g., screenshots?) of what visualizations in docs should look like
- GUI tests always very brittle.

**Comment by OwenArnold** [comment]
@nvaytet is any of this still valid?

**Comment by OwenArnold** [comment]
I haven't noticed that these tests have been failing frequently recently, however I can see that this would be brittle following updates. Do we still wish to remove the `table_html` beautifulsoup based testing directory?
