### ISSUE TITLE
Setting parameters in `scipp.config` at runtime has no effect

### ISSUE THREAD

**Issue by nvaytet** [scipp/scipp#997]
Doing
```Py
import numpy as np
import scipp as sc
from scipp.plot import plot
sc.config.plot.width = 533

d = sc.Dataset()
N = 50
d.coords['tof'] = sc.Variable(['tof'], values=np.arange(N).astype(np.float64),
                                unit=sc.units.us)
d['Sample'] = sc.Variable(['tof'], values=10.0*np.random.rand(N),
                          unit=sc.units.counts)
plot(d)
```
does not change the width of the figure; it stays at 800.

In fact,
```Py
print(sc.config.plot.width)
```
then outputs `800`.

**Comment by DanNixon** [comment]
Yes, the syntax for setting a config option in this case is `sc.config.update({'plot.width': 300})`.
I'll update the docs to make this clear.

**Comment by nvaytet** [comment]
And does this update the config just temporarily or does it also update the config file?

**Comment by DanNixon** [comment]
> And does this update the config just temporarily or does it also update the config file?

No, it is just temporary.
